### ISSUE TITLE
Inconsistent example code and documentation

### ISSUE THREAD

**Issue by GiedriusM** [openthread/openthread#101]
POSIX example platform radio [implementation](https://github.com/openthread/openthread/blob/master/examples/posix/platform/radio.cpp) can return kThreadError_Busy in state change operations (_otPlatRadioEnable_, _otPlatRadioSleep_, _otPlatRadioIdle_, _otPlatRadioReceive_ and _otPlatRadioTransmit_), however the [documentation](https://github.com/openthread/openthread/blob/master/include/platform/radio.h#L171) does not allow such return.

**Comment by darconeous** [comment]
From my experience with the code base so far, `kThreadError_Busy` seems to be the go-to generic error, unfortunately. Should definately be cleaned up.

**Comment by jwhui** [comment]
Fixed in #138.
