### ISSUE TITLE
Fragile mbedtls configuration

### ISSUE THREAD

**Issue by gilles-peskine-arm** [openthread/openthread#10251]
[`third_party/mbedtls/mbedtls-config.h`](https://github.com/openthread/openthread/blob/main/third_party/mbedtls/mbedtls-config.h) has the following code:

```
#include "mbedtls/version.h"
// Include in the legacy config name adjustment file for mbedtls >= 3.5.0
#if (MBEDTLS_VERSION_NUMBER >= 0x03050000)
    #include "mbedtls/config_adjust_legacy_crypto.h"
#endif
```

This is an [unintended workaround and might not compile with Mbed TLS 3.6.1](https://github.com/Mbed-TLS/mbedtls/issues/9147). I think that the OpenThread configuration is simple enough that there's currently no problem with inconsistencies, but it's at least fragile.

The solution is to remove this block and also remove `#include "mbedtls/check_config.h"`, which since Mbed TLS 3.0 is done automatically at the right point.

**Comment by jwhui** [comment]
@gilles-peskine-arm , thanks for raising this issue.

I just submitted #10251 . Please review if you get a chance.
