### ISSUE TITLE
mDNS implementation questions.

### ISSUE THREAD

**Issue by Cristib05** [openthread/openthread#10273]
**Describe the bug** A clear and concise description of what the bug is.
Thread 1.3 Certification Test 2.15 is failing for the BR DUT on step 12 and all other steps related to a PTR query for a subtype.
It seems that the current native mDNS implementation is not adding any other RRs, except for subtype's specific PTR when answering for a subtype PTR query. Certification testing seems to be checking if the base service RR are present, a service name check seems to be performed.
![image](https://github.com/openthread/openthread/assets/127317648/c927dc58-80d2-45de-80ae-37c8e613d9c7)

A comparation has been done with **dns-sd** implementation:
![image](https://github.com/openthread/openthread/assets/127317648/69335267-05b7-45cf-91e1-e4509226a85a)

Found out that in ```Core::ServiceEntry::PrepareResponseRecords``` is determined which RR should be added to the message.
Would it be a bad idea that for a specific subtype PTR record that has to be added to an answer, the corresponding base SRV, TXT, AAAA records to be ```MarkToAppendInAdditionalData()```. In this way, an mDNS browse from AIL will generate the same output as a DNS browse from OT side.

Another issue that our team discoverd is that a service registration can be performed using an mDNS host that has not been previously verified unique on the network.

There was already an 'Ubuntu' host registered on the network in this case, but no error on registration.
![image](https://github.com/openthread/openthread/assets/127317648/cb4e29c8-5b33-4f05-bc3b-b6ee61f75cb2)
 
Comparing to dns-sd implementation, it seems that a service registration using ```dns-sd -R```, is adding the host to the Queries and also to the Authoritative section:
![image](https://github.com/openthread/openthread/assets/127317648/c1cc86f8-924c-4f3f-a54c-7857115a46ac)

In the current implementation, the service will be present when issuing ```mdns services```, but the host is not. A simple browse query will result in:
![image](https://github.com/openthread/openthread/assets/127317648/45fa8d66-e760-4f5a-82d3-f264e2575019)
but the target is not reachable, a NSEC record will be issued for an AAAA query.

Services remain also present when a host in unregistered. Should those be deleted in those scenarios? What do you think?

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by abtink** [comment]
Thanks, @Cristib05.

I'm surprised that cert tests mandate specific behaviors for additional record generation, as RFC 6763 frames these as recommendations.

We intentionally omitted additional records for sub-type PTR browse queries to reduce message size and traffic. These queries usually aim to identify devices with a particular function and are often accompanied by a base type browse (which would include those records).

We can modify the code to include additional records for sub-type PTR queries. I'll submit a PR for this shortly.

---

> Another issue that our team discoverd is that a service registration can be performed using an mDNS host that has not been previously verified unique on the network.

Regarding this,  the service and host registration APIs in native mDNS are intentionally independent of each other. This design choice aligns more closely with how they are used by Advertising Proxy.  Callers can first attempt to register the host before registering services under the same host name.

**Comment by abtink** [comment]
Submitted: 
- https://github.com/openthread/openthread/pull/10276

**Comment by jwhui** [comment]
>> It seems that the current native mDNS implementation is not adding any other RRs, except for subtype's specific PTR when answering for a subtype PTR query. Certification testing seems to be checking if the base service RR are present, a service name check seems to be performed.
>
> I'm surprised that cert tests mandate specific behaviors for additional record generation, as RFC 6763 frames these as recommendations.

@Abhayakara @EskoDijk , should we relax this check in the Thread Test Specification?

**Comment by radua-nxp** [comment]
But let me understand correctly: If we register a service:
```mdns register service my-service _http._tcp my-host 8333``` and my-host doesn't exist that it should be ok? I find that both un-intuitive and wrong. Shouldn't it be better to return an error code that would point to the fact that a user should first register the host and then the service?

**Comment by EskoDijk** [comment]
@jwhui @abtink The current 1.3 test plan does not mandate additional records to be generated (I checked R6). It may be that some of the test scripts aren't yet updated to R6 -> for that a TSTBED JIRA issue can be filed ; @radua-nxp can you do this?

**Comment by radua-nxp** [comment]
> @jwhui @abtink The current 1.3 test plan does not mandate additional records to be generated (I checked R6). It may be that some of the test scripts aren't yet updated to R6 -> for that a TSTBED JIRA issue can be filed ; @radua-nxp can you do this?

@Cristib05 is working on this!

**Comment by jwhui** [comment]
Closing stale issue.
