### ISSUE TITLE
mJoinerRouterChannel must have a value between kPhyMinChannel and kPhyMaxChannel

### ISSUE THREAD

**Issue by shahab5** [openthread/openthread#1028]
Hi,

If the Joiner discovery results are null, then the PHY channel is set to` mJoinerRouterChannel`, which is initialized to zero.

In joiner.cpp
`mNetif.GetMac().SetChannel(mJoinerRouterChannel);`

`mJoinerRouterChannel` should have a value between `kPhyMinChannel` and `kPhyMaxChannel`, shouldn't it?

Thanks,
Shahab

**Comment by chshu** [comment]
If discovery failed, the PHY channel shouldn't be set to `mJoinerRouterChannel`, please refer to the `mJoinerRouterPanId != Mac::kPanIdBroadcast` check before the channel set action.

**Comment by shahab5** [comment]
Thanks, I was using an earlier version which didn't have this fix.

Thanks,
Shahab
