### ISSUE TITLE
docs: improve build related documentation - how to run unit tests, pretty, code coverage, etc.

### ISSUE THREAD

**Issue by turon** [openthread/openthread#103]
The autotools build system can do a number of things.  This task would be to improve the documentation so it is easy to determine what can be done and how to do it:
- unit tests: how to build them; how to run them?
- pretty: how to verify coding convention conformance; what prerequisite tools are needed?
- code coverage: how to run analysis; how to view html output?
- doxygen: how to regenerate the docs?
- check: how to run certification tests; how to configure to run against hardware vs. simulator?
- tags: how to generate and use tags to browse the code via emacs or other tool?
- cross-compilation: how to compile the library for a different target architecture?

**Comment by jwhui** [comment]
FWIW, a lot your topics (e.g. check, unit tests, tags, cross-compilation) are covered in:
- [autoconf manual](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/)
- [automake manual](http://www.gnu.org/software/automake/manual/)

Uses of these mechanisms will become more clear as we build out examples.
