### ISSUE TITLE
[log] Spinel tx commands are no longer logged

### ISSUE THREAD

**Issue by no2chem** [openthread/openthread#10428]
**Describe the bug**

`SpinelDriver::SendCommand` no longer logs, while `SpinelDriver::HandleReceivedFrame` still does. It seems like at one point in time `SpinelDriver::SendCommand` did log. Either way, this asymmetry between send/receive can cause some confusion during debug.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: 89b54dca2b4b7f5da0f203eaac8a9e048738403f

**Expected behavior** A clear and concise description of what you expected to happen.

`SpinelDriver::SendCommand` should log (or SpinelDriver::HandleReceivedFrame should not log).

**Comment by zhanglongxia** [comment]
I have pushed the https://github.com/openthread/openthread/pull/10429 to fix this issue.
