### ISSUE TITLE
Prioritization of MLE messages over data and handling of child re-attach

### ISSUE THREAD

**Issue by abtink** [openthread/openthread#1047]
Summarizing two features: 

- Prioritize MLE traffic over data packet. This is particularly important for MLE "Child Id Response" message. 

- Current implementation removes the child/neighbor when we recive a "Parent Requst" from it (child tries to re-attahc). This in turn causes all queued data packets for the node to be cleared. It'd be better to keep all the data packets  but clear out the queued MLE packets.

**Comment by jwhui** [comment]
Resolved by #1106.
