### ISSUE TITLE
Diagnostic commands

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#1055]
Currently OpenThread supports some of diagnostic commands (DIAG_GET.req, DIAG_GET.rsp and DIAG_RST.nrf). CLI example exposes command `networkdiagnostic get`, however a response is not populated back (see `NetworkDiagnostic::HandleDiagnosticGetResponse`).

I would like to get those information on CLI at least in raw tlv ASCII format e.g.: 
`DIAG_GET.ans: 0102fc00`
So the Openthread public API callback could be like: `otSetDiagnosticGetCallback(otInstance, callback(otMessage))`

Other option could be to parse DIAG_GET.rsp in the `NetworkDiagnostic::HandleDiagnosticGetResponse` and return some kind of structure (but who should allocate the memory for it, since DIAG_GET.ans consists of different number of members e.g. could carry 4 IPv6 addresses and 3 child information etc.) - however it may be challenging taking to account the amount of possible Diagnostic TLVs.

So generally there are two questions:
1. How do you want to Diagnostic Get callback to look like in Openthread API (return only otMessage and otMessageInfo or parsed structure etc.)
2. How to show responses on the CLI? Is it acceptable to print only raw payload in ASCII?

Also as a side task it might be usuful to implement two left commands DIAG_GET.qry and DIAG_GET.ans which are almost the same as already implemented with a difference that they are better for multicast queries due to different transaction pattern.

**Comment by jwhui** [comment]
Resolved by #1099.
