### ISSUE TITLE
The example /examples/posix/app/cli/soc  CAN NOT Start .

### ISSUE THREAD

**Issue by ZetaChow** [openthread/openthread#106]
Build success,but run /examples/posix/app/cli/soc 1 , nothing happen
OS is OS X
I tried sudo , and no effect yet

**Comment by mszczodrak** [comment]
Hi,
After starting the soc app, one should be able to enter into the shell 'start', 'state', 'ipaddr'. Does any of those commands return any output in your case?

**Comment by ZetaChow** [comment]
@mszczodrak Thank you! I enter 'start' and output 'done'; 
I understand it correctly, before I wait for a prompt, in fact, it worked well

**Comment by darconeous** [comment]
An actual command prompt would really be helpful, as I ended up having the same reaction the first time I tried it. Something even as simple as a `>` would do the trick.

**Comment by jwhui** [comment]
Good idea.  Pull request coming soon.
