### ISSUE TITLE
[br] Use correct bit position 6 for RA stub router flag (SNAC router flag)

### ISSUE THREAD

**Issue by EskoDijk** [openthread/openthread#10691]
**Describe the bug** A clear and concise description of what the bug is.
Position of stub router flag was initially chosen in the RA flags extension option. Now IANA has allocated it as bit 6 in the regular flags byte, see https://www.iana.org/assignments/icmpv6-parameters/icmpv6-parameters.xhtml#icmpv6-parameters-11 

**To Reproduce** Information to reproduce the behavior, including:
See latest OT code

**Expected behavior** A clear and concise description of what you expected to happen.
"Stub router" flag bit set to flag position 6 and mention "SNAC router flag" as a name also.
Reference to spec in code can be updated to : https://datatracker.ietf.org/doc/html/draft-hui-stub-router-ra-flag-02 
which has the bit position that is now chosen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.
See [SPEC-1283](https://threadgroup.atlassian.net/browse/SPEC-1283)

**Comment by EskoDijk** [comment]
FYI @abtink @jwhui

**Comment by abtink** [comment]
Submitted: 
- https://github.com/openthread/openthread/pull/10695

**Comment by abtink** [comment]
Address by #10695
