### ISSUE TITLE
Two-hop loops detection

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#1086]
I have experimented with large Thread network with OpenThread's nodes that send quite a big amount of application packets. Once in a while i saw loops (A->B->C->B->C->B->C->... ended when mesh hop limit expired). I did some quick code analysis and it looks like there is no two-hop loops detection as per 5.9.6.

**Comment by jwhui** [comment]
Good catch!  Would you be willing to add that feature?

**Comment by LuDuda** [comment]
Sure, please go on with the fix then! Thanks :+1:
