### ISSUE TITLE
Thread Harness - 8.1.1(OMC Joining,no JR,any commissioner,single(correct)) failure issue with ARM mbed Golden device

### ISSUE THREAD

**Issue by charishmag** [openthread/openthread#1093]
Hi,
   Test 8.1.1(OMC Joining,no JR,any commissioner,single(correct)) is failing with ARM: NXP FRDM-K64F with Firefly as a Golden Device, whereas similar test is passing with openthread device taken as Golden device.
   ARM: NXP FRDM-K64F as a golden device is not responding for **Discovery request** from openthread device as a Router. 
   Please find the attached image with no response for Discovery Request.
![8 1 1_router_fail_log](https://cloud.githubusercontent.com/assets/24287473/21338480/94414968-c69c-11e6-847d-7f623d7f39bb.png)

**Comment by jwhui** [comment]
@charishmag, thanks for pointing this out.  We'll take a look.  Thanks.

**Comment by librasungirl** [comment]
Hi @charishmag, this issue should have been fixed recently. Will close it now.
Please retry with latest master branch code and feel free to reopen it if you still have the problem. Thanks.
