### ISSUE TITLE
The Timer logic can be improved to be more logical and deterministic.

### ISSUE THREAD

**Issue by pvanhorn** [openthread/openthread#11]
The Timer logic fails to execute expired timers in order of earliest expired to last expired. Instead the logic executes the first expired timer in the list.

**Comment by jwhui** [comment]
The current Timer logic is certainly simplistic.  It only seeks to execute any expired timer, regardless of when the timers actually expired.

**Comment by pvanhorn** [comment]
Agreed, this is correctly classified as an improvement/enhancement.  I think it is worth the effort as it should help to make execution more deterministic.

**Comment by jwhui** [comment]
I think that makes sense.  Feel free to submit a PR for review.

**Comment by jwhui** [comment]
Addressed in #96.
