### ISSUE TITLE
Question related to TREL and Thread 1.4 Certification in Thread Harness

### ISSUE THREAD

**Issue by Cristib05** [openthread/openthread#11002]
**Describe the bug** A clear and concise description of what the bug is.
Hi @abtink,
In Thread 1.4 certification tests, there is a test, TREL 8_4 Radio Link (Re)discovery through Receive, which fails.
After the topology is created as in the attached picture, ROUTER will begin sending ping packets to ED, this leading to increase of TREL radio link preference. After 10 pings are sent, TREL connectivity on ROUTER is disabled and another round of 10 pings is issued, from ROUTER to ED.
First ping request packet is not present on the Wireshark capture. Second ping request packet is present, but no reply is received on ROUTER side.
For first packet, in `radio_selector` module, `selectedRadio` will be set to `ot::Mac::kRadioTypeTrel` as `RadioTypeTrel` is the first item in radio type list and also has the highest preference. When in reaches `Interface::Send` in `trel_interface.cpp`, `mEnabled` is set to `false`, as `trel disable` has been previously issued, this leading to a `kErrorAbort` return of `Interface::Send`. Preference will then be decreased, and the next ping packet will be sent on 15.4; The reason that a reply is not present for the second request might be the same scenario described, but this time on DUT side.

On ROUTER side, before and after first ping packet is sent:
![image](https://github.com/user-attachments/assets/62dec785-f618-480c-b60e-d56480343a70)
On DUT side after second and third packets are sent:
![image](https://github.com/user-attachments/assets/06160b3e-dbb5-4b69-9102-39d7e1879576)

Based on what I've understand from the code, in this test scenario, there is no chance for a reply to be captured and validated for the first 2 ping request packets.
That being said, what is your thought on this? Is there something that can be improved, like when TREL module is disabled link preference to be decreased in order to avoid possible packet loss, or should the validation be modified to take into account packets only when TREL preference is lower than 15.4 one? (Issuing `multiradio neighbor list` and determine the preference)

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id : 4cc1ffd17439db6e0b97b010ad00043d7509f246
3. IEEE 802.15.4 hardware platform
4. Build steps
5. Network topology
![image](https://github.com/user-attachments/assets/9ead729b-2fc7-4c57-927d-cd9e47af71b9)

**Comment by abtink** [comment]
Thanks @Cristib05.

I think this certification test is validating the "multi-radio" behavior. I expect it to almost mirror (be very similar to) the [`cli/test-702-multi-radio-discovery-by-rx.py`](https://github.com/openthread/openthread/blob/881f55762938fe2eee79aa6262e1d098b010dbd8/tests/toranj/cli/test-702-multi-radio-discover-by-rx.py) test in OT.

The gist of the test is to check whether the "radio link" preference is correctly updated when we receive a message from a neighbor over that radio link.

Let me give a summary of the test steps. Here is the toplolgy

```
# -----------------------------------------------------------------------------------------------------------------------
# Test description: This test covers behavior of a device after the TREL network is temporarily disabled
# and rediscovery of TREL by receiving a message over that radio from the neighbor.
#
#     r1  ---------- r2
# (15.4+trel)     (15.4+trel)
#
#  On r2, we disable TREL temporarily.
```

*   We start by making sure `r1` and `r2` can talk to each other, and detect both 15.4 and TREL radio links, and prefer TREL.
*   Then we create a situation where `r1` assumes `r2` no longer supports TREL:
    *   We disable TREL on `r2` and send a bunch of message (ping or UDP) from `r1` to `r2` (which may fail).
    *   We expect `r1` to quickly detect that TREL is no longer supported by `r2` and prefer 15.4 for transmitting to `r2`.
*   So far, the above steps are to create the situation for the main test.
*   We re-enable TREL on `r2` and start sending messages from `r2` to `r1`.
    *   We expect `r2` to use probe mechanism and try TREL to talk to `r1`.
    *   `r1` should then notice new message received on TREL from `r2` and update its TREL preference for `r1`.
*   The main test is to validate that `r1` detected TREL radio link through rx.

There is also `cli/test-701-multi-radio-probe.py`, which does similar checks (detecting through probes, etc).

Generally, during these tests, if some of the messages or pings are dropped, it is okay and expected; I don't expect these to be the condition for the test to pass.

---------------------

> That being said, what is your thought on this? Is there something that can be improved, like when the TREL module is disabled, the link preference is decreased in order to avoid possible packet loss, or should the validation be modified to take into account packets only when the TREL preference is lower than the 15.4 one?

The `trel disable` command (and its related `otTrelSetEnabled()` function) was mainly intended for testing—for example, emulating behavior where the infrastructure interface or Wi-Fi is down or not working.

As you mentioned, it just disables the "TREL interface," causing transmissions on TREL to fail with an `ABORT` error. It is then used to validate that the "multi-radio" code correctly detects such a situation,  adjusting the "radio link preferences".

I understand your suggestion to clear TREL "radio link preferences" for all neighbors upon `trel disable`. Logically, if we want to fully disable TREL, it may make sense to do so, but I am not sure if changing this would be good, as it may impact existing tests and how this command is being used today.
