### ISSUE TITLE
test_router_multicast_link_request.py is flaky

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#11041]
**Describe the bug** A clear and concise description of what the bug is.

test_router_multicast_link_request.py often fails for expected link not established.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: fa9994a75303567fabf8109c3a7d8b56eb781edb
2. IEEE 802.15.4 hardware platform: simulation

**Comment by jwhui** [comment]
Closing stale issue.
