### ISSUE TITLE
[SED] Forwarding multicast messages

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#1131]
Currently when Router forwards MPL message to its SED children (destined to Realm-Local All Thread Nodes Address) it does it two times per one message, because MPL does retransmissions.

I don't see how current behaviour could violate Thread Specification, but what do you think about improving the process and forward such messages only once? Right now a second message will be discarded (due to MPL duplication) by SED anyway. Additionally, forwarding between Router and SED is ACKed on 15.4 layer, so its reliable.

If so, i have a simple fix by introducing a new subtype of Message object that indicates the next retransmission of MPL message, so MeshForwarder won't add message to the indirect queue.

**Comment by jwhui** [comment]
I agree that we should improve the multicast to sleepy behavior.  Please submit a PR, thanks!
