### ISSUE TITLE
Programming OpenMote

### ISSUE THREAD

**Issue by beriberikix** [openthread/openthread#1145]
For future earthlings trying to flash an OpenMote with OpenThread via the UART, the following worked for me:

* ground the CTS/DI07 pin (labeled on the OpenBase)
* run `~/bin/cc2538-bsl/cc2538-bsl.py -v -e -w -b 115200 -p /dev/tty.usbserial-A9040YSF arm-none-eabi-ot-cli-ftd.bin`. Update the [cc2538-bsl](https://github.com/JelmerT/cc2538-bsl) location and serial port
* try hitting reset once or twice if it doesn't work initially

More details on the [OpenMote site](http://www.openmote.com/blog/bootstrapping-the-openmote-platform.html).

**Comment by Gr3yh0und** [comment]
@beriberikix, Did you try to access the OpenMote via serial? I have got two OpenMotes based on the OpenUSB Board and Contiki is running fine with serial access. But I do not get any output with Openthread. As far as I've checked OT also uses the GPIO Pins 0/1 for TX/RX.
