### ISSUE TITLE
#include <new> is not available on all C++ platforms.

### ISSUE THREAD

**Issue by pvanhorn** [openthread/openthread#115]
#include <new> found in openthread.cpp is not available on all platforms.  A more portable way for initializing and assignment memory to the ThreadNetif needs to be provided to make Openthread more portable.

**Comment by pvanhorn** [comment]
The solution for this could be to create a platform API that returns a pointer to a allocated and initialized ThreadNetif object.  Something like;

ThreadNetif *otPlatAllocThreadNetif(void);

This would allow the platform to not only invoke the constructors on the ThreadNetif, but also to choose from which memory resource the ThreadNetif object will be allocated.

**Comment by jwhui** [comment]
Fixed in #118.
