### ISSUE TITLE
The radio API's are declared without the requisite void argument.

### ISSUE THREAD

**Issue by pvanhorn** [openthread/openthread#12]
Those platform radio API's which take no arguments, lack the requisite (void) declaration and instead appear as follows.

ThreadError otPlatRadioEnable();

**Comment by jwhui** [comment]
Thanks for pointing that out.  Are you willing to submit a PR?

**Comment by pvanhorn** [comment]
Yes.

**Comment by jwhui** [comment]
Fixed with #14
