### ISSUE TITLE
Security Policy B(value 0) doesn't take effect

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#1228]
Thread spec 8.4.4.2
When the Security Policy B bit is not set (has value 0), the Beacon payload MAY be elided or
have an application specific value.

**Comment by jwhui** [comment]
I agree that OpenThread does not currently change its IEEE 802.15.4 Beacon behavior based on the Security Policy B bit.  However, the specification indicates this is a MAY and not a MUST.  Does the harness require this?

**Comment by librasungirl** [comment]
No impact. Just noticed this during looking into the 5.8.4 traffic.
