### ISSUE TITLE
NCP: which side should response to the echo request

### ISSUE THREAD

**Issue by luwannest** [openthread/openthread#125]
The wpantund and the ncp app both response to the echo request from the soc app, if the soc app uses the mesh local address as the destination address.
Could I know which side should response to this echo request? The laptop running wpantund or the end node running ncp app?

**Comment by jwhui** [comment]
ICMPv6 Echo Request processing should be disabled in OpenThread when operating in NCP mode.  I can submit an update to address this.  Thanks.

**Comment by darconeous** [comment]
@jwhui, was this ever addressed?
