### ISSUE TITLE
POSIX example ignores FRAME_PENDING flag

### ISSUE THREAD

**Issue by GiedriusM** [openthread/openthread#126]
In POSIX platform example FRAME_PENDING flag is set to true if the local device just sent MAC command frame (before commit b865607619d06c1a10a231025ec48749fef80a19, it checked that it was DATA_REQUEST MAC command).  This creates few issues:

1. The requester (local) device decides whether the responder (remote) device has pending data frame.
2. The requester (local) device ignores responders FRAME_PENDING bit.
3. FRAME_PENDING bit is set to true for all MAC commands (not just DATA_REQUEST).

**Comment by GiedriusM** [comment]
Reference: https://groups.google.com/forum/#!topic/openthread-users/VQZARiTHlls

**Comment by jwhui** [comment]
Fixed in #139.
