### ISSUE TITLE
Inform radio layer about pending packets

### ISSUE THREAD

**Issue by GiedriusM** [openthread/openthread#127]
There is no functionality in which MAC layer would inform radio (implementation) layer about pending frames for a particular node. In this case implementation is forced to always set FRAME_PENDING bit in ACK frames. This is not ideal for sleepy devices, that will send DATA_REQUEST, receive an ACK with FRAME_PENDING bit set and wait for (probably) non-existent packet and waste battery life.

**Comment by GiedriusM** [comment]
Reference: https://groups.google.com/forum/#!topic/openthread-users/VQZARiTHlls

**Comment by jwhui** [comment]
Resolved by #562.
