### ISSUE TITLE
Data Request flooding when Operational Dataset changes.

### ISSUE THREAD

**Issue by hubertmis** [openthread/openthread#1316]
When Operational Dataset changes Leader sends unsolicited Data Response to all neighbor Routers containing new Timestamp value. Every Router in response sends Data Request to get new Dataset. The problem is that all Routers send Data Request at once that causes packet collisions.
I'm not sure if MLE_MAX_RESPONSE_DELAY jitter should be used in this case to prevent packet collissions.

**Comment by jwhui** [comment]
While the Thread spec does not clearly specify this behavior, I think it makes sense to apply `MLE_MAX_RESPONSE_DELAY` to MLE Data Requests sent in response to a multicast MLE Data Response.  Would you like to propose a change?

**Comment by hubertmis** [comment]
Yes. I'll do that.

**Comment by jwhui** [comment]
Thanks!
