### ISSUE TITLE
Examples should output to unique directory

### ISSUE THREAD

**Issue by beriberikix** [openthread/openthread#1346]
The posix example creates a unique folder in the `output` directory, like `x86_64-apple-darwin` on a mac. The other platforms examples dump their binaries into the `bin` folder, overriding previous builds from potentially different platforms. Can we move to unique platform-specific directories in `output`? Ex. `output/cc2538/bin.` It would be even better to have devkit-specific directories but that might not be needed at this time. Ex. `output/cc2538-cc2538dk` or `output/cc2538-firefly`.

**Comment by jwhui** [comment]
I'll take a look.
