### ISSUE TITLE
DNS support in OpenThread

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#1351]
From application point of view, one of the most important core module in IPv6 stack is `DNS`.
What do you think about providing a simple implementation of it that works on `AAAA `records (IPv6 only) to OpenThread? 

If so i am willing to implement it as an optional module (like we do with CoAP/DHCPv6 right now).

**Comment by jwhui** [comment]
Supporting DNS would be a great addition!  Looking forward to your contribution.

**Comment by jwhui** [comment]
Resolved with #1460.
