### ISSUE TITLE
Move updated wiki sitenav

### ISSUE THREAD

**Issue by beriberikix** [openthread/openthread#1366]
@betsyl-at-google has a draft of a [new sitenav](https://github.com/openthread/openthread/wiki/OpenThread-Docs) for the wiki that's more useful than we have now. Should we integrate it into the wiki home page?

**Comment by beriberikix** [comment]
On second thought, and probably the more obvious one, we could replace the existing sidenav.

**Comment by betsyl-at-google** [comment]
Let me know if you want my help with this.

**Comment by beriberikix** [comment]
@betsyl-at-google @jwhui can you review the proposed nav I just staged at the wiki?

**Comment by nibanks** [comment]
Would it be ok to add a link to [Building on Windows](https://github.com/openthread/openthread/wiki/Building-on-Windows) to either the [Getting Started](https://github.com/openthread/openthread/wiki/OpenThread-Docs#get-started) or [Build Tools](https://github.com/openthread/openthread/wiki/OpenThread-Docs#build-tools) sections? Also, I'm not sure where we should link in the [OpenThread on Windows](https://github.com/openthread/openthread/wiki/OpenThread-on%C2%A0Windows) installation instructions wiki page.

**Comment by beriberikix** [comment]
How about Building on Windows under Getting Started and OpenThread on Windows in the Platforms page?

**Comment by nibanks** [comment]
Works for me. Thanks.
