### ISSUE TITLE
Update makefile for cc2650 example to default to MTD

### ISSUE THREAD

**Issue by beriberikix** [openthread/openthread#1375]
@srickardti can we update the make file for the cc2650 to default to only building the cli-mtd? Currently running `make Makefile-cc2650` tries to also build the FTD build and blows up.

**Comment by srickardti** [comment]
I'll make MTD only builds the default and add a configuration option to build the ncp.

**Comment by chshu** [comment]
How about to add a new build option **--enable-ftd**, then platform without this build option will not build cli-ftd (including libopenthread-ftd.a), and the build option will also helps to exclude some unused features from MTD build (#1361). @jwhui , May I know your opinion?
