### ISSUE TITLE
Platform Tx Power API

### ISSUE THREAD

**Issue by pvanhorn** [openthread/openthread#1407]
There currently does not exist a mechanism by which Openthread can initialize the TxPower used by the platform for frames other than those that OpenThread transmits explicitly.  Consider ACK frames which are typically generated by either the hardware or radio driver in response to received frames.  The TX power used for these auto-generated frames must be configured.  

It is proposed that the otSetMaxTransmitPower API be extended to also call a new API otPlatRadioSetDefaultTxPower.  This call would be in addition to the existing behavior of otSetMaxTransmitPower which should remain unchanged.

**Comment by jwhui** [comment]
I agree that OpenThread needs to support configuring the "default" transmit power at the radio level.  Your proposal seems reasonable to me.

**Comment by hubertmis** [comment]
:+1:

**Comment by pvanhorn** [comment]
@jwhui This can be closed.

**Comment by jwhui** [comment]
Fixed by #1417.
