### ISSUE TITLE
Segmantation fault in network_data_leader_ftd.cpp

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#1411]
By accident I got `Segmentation fault` in network_data_leader_ftd.cpp.

How to reproduce:

Node 1 (Leader): 
```
> panid 0
Done
> ifconfig up
Done
> thread start
Done
```
Node 2 (Router):
```
> panid 0
Done
> ifconfig up
Done
> thread start
Done
> state router
Done
> prefix add 2001:db8::/64 paros med
Done
> netdataregister
Done
> prefix remove 2001:db8::/64
Done
> netdataregister
Done
> route add 2000::/3 s med
Done
> netdataregister
Done
> prefix add 2001:db8::/64 paros med
Done
> netdataregister
Done
```

When Leader gets Server Data it throws:
` Segmentation fault (core dumped)`

The reason is memcmp here: https://github.com/openthread/openthread/blob/master/src/core/thread/network_data_leader_ftd.cpp#L523

I did verifiy that both pointers (`hasRoute `and return value of `FindHasRoute`) are not null, but haven't got time to look deeper.

**Comment by jwhui** [comment]
Thanks for reporting this issue.  I'll take a look.
