### ISSUE TITLE
Build: Compiling openthread should not cause build machine to reboot.

### ISSUE THREAD

**Issue by turon** [openthread/openthread#1425]
I have a fairly stock Ubuntu 16.04 virtual machine that would reboot randomly whenever I would initiate the the stock make commands to build an OpenThread example platform, i.e. the `make -f examples/Makefile-posix` method.

I've isolated the root cause to the large default values for the number of build jobs (`BuildJobs ?= 99`).  I plan to submit a PR to resolve this.

We probably want the default value to be conservatively low so new developers don't have a bad out-of-box experience, and let Travis dial up the numbers within the Continuous Integration scripts.

**Comment by jwhui** [comment]
Are others experiencing this problem?

**Comment by jwhui** [comment]
FWIW, Travis uses Ubuntu Trusty VMs (which should be 16.04).

**Comment by wbober** [comment]
@jwhui @turon  I use Arch based VM exclusively. I don't have any issues with building for NRF52840 and I don't recall to have any with Posix builds (although I haven't tried for some time).

**Comment by Gr3yh0und** [comment]
Haven't seen this on Debian Stretch yet ...
