### ISSUE TITLE
OpenThread deinitialization

### ISSUE THREAD

**Issue by hubertmis** [openthread/openthread#1446]
When OpenThread is initialized it takes some peripherals. It is not possible to deinitialize the OpenThread stack and use taken peripherals by other modules. It seems to be a good idea to provide termination function that releases OpenThread resources if an application don't use Thread connectivity continuously.

**Comment by jwhui** [comment]
We have an [`otInstanceFinalize()`](https://github.com/openthread/openthread/blob/master/include/openthread/instance.h#L197) function that is intended to serve this purposes.  Maybe that implementation needs to be extended to support your use cases?

**Comment by hubertmis** [comment]
I meant something like `PlatformDeinit()`. Maybe I'll just implement it and create a PR. We'll discuss there.
