### ISSUE TITLE
Spinel: Separate Definition of Protocol Basis

### ISSUE THREAD

**Issue by jhwoodyatt** [openthread/openthread#1472]
Presentation of the Spinel protocol to IETF would likely find an easier path to publication as Request For Comment (RFC) if the general-purpose basis of the Spinel protocol were documented separately from the specialization of the Spinel protocol for Thread™ network control processors.

**Comment by darconeous** [comment]
This is basically addressed by #1912, right?

**Comment by darconeous** [comment]
Closing. See https://github.com/openthread/spinel-spec
