### ISSUE TITLE
spinel-cli: debug levels > 1 should display more output.

### ISSUE THREAD

**Issue by turon** [openthread/openthread#1479]
spinel-cli.py can be assigned a higher debug level by either invoking with the "-d <level>" flag, or passing the "debug <level>" command into the cli shell.

None of this more advanced output is displaying however.  It seems like the calls to logging.debug() are not getting routed to stdout properly.

**Comment by jwhui** [comment]
Thanks for reporting this issue.  Will you be submitting a PR to address this?

**Comment by turon** [comment]
I noticed the regression when working on #1478, but unfortunately won't be able to allocate time to look into the fix in the near future.

**Comment by jwhui** [comment]
Moved to https://github.com/openthread/pyspinel/issues/6.
