### ISSUE TITLE
External Route Config mPreference values should have an enumeration.

### ISSUE THREAD

**Issue by pvanhorn** [openthread/openthread#1487]
the mPreference value defined in otExternalRouteConfig should have an enumeration for what is otherwise a set of cryptic values.

-1 == low priority
 0 == medium priority
 1 == high priority

Currently, any code using this member must assign one of the numerical values as there is no enum available.

It is proposed that the following enum be created to satisfy this readability issue;

typedef enum otExternalRoutePreference
{
    kExternalRoutePreferenceLow        = -1,     
    kExternalRoutePreferenceMedium  = 0,
    kExternalRoutePreferenceHigh       = 1
} otExternalRoutePreference;

**Comment by jwhui** [comment]
Resolved by #1525.
