### ISSUE TITLE
Make variable ${CMP} is not defined

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/openthread#1512]
The included makefile fragment:  third_party/nlbuild-autotools/repo/automake/pre/macros.am

References the macro ${CMP} - however this macro is not defined.
The result is a strange message  like this during a build:

```
  STAGE    cortex-m3-arm-none-eabi
make -j10 -C build/cortex-m3-arm-none-eabi --no-print-directory DESTDIR=/vagrant/PUSH_openthread/output install
  CHECK    .local-version
/bin/bash: -s: command not found
  GEN      .local-version
```

Not sure if this should be defined in/via/by - the  auto-tools in third_party/nlbuild-autotools or elsewhere.

**Comment by jwhui** [comment]
@DuaneEllis-TI, thanks for raising this issue.  I just submitted #1537.  Please let me know if this addresses your issue.
