### ISSUE TITLE
TI chips do not report CRC

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/openthread#1513]
TI chips do not report the CRC, instead they report status bits in place of the crc.

In sniffer mode (ie: sniffer.py) Wireshark wants a CRC otherwise it reports a BAD FCS

A simple quick workaround is to have the sniffer.py recompute the CRC when given a command line option.

**Comment by jwhui** [comment]
I think that makes sense.  Will you submit a PR to implement this?

**Comment by jwhui** [comment]
Resolved by https://github.com/openthread/pyspinel/pull/5.
