### ISSUE TITLE
Deadlink in CLI documentation

### ISSUE THREAD

**Issue by GiedriusM** [openthread/openthread#152]
In section 4 of [app CLI readme](https://github.com/openthread/openthread/blob/master/examples/posix/app/cli/README.md), there is a link to more (core) CLI documentation. That link is dead (https://github.com/openthread/openthread/blob/master/examples/posix/src/cli/README.md) and [I think] it should point to https://github.com/openthread/openthread/blob/master/src/cli/README.md.

This probably happened after code rearrangement.

**Comment by jwhui** [comment]
Fixed in #153.
