### ISSUE TITLE
Usage of arrays with a size of 0

### ISSUE THREAD

**Issue by mstamer** [openthread/openthread#1564]
In the open thread code, there is usage in a few places of arrays of 0 size.  This feature (zero sized arrays) seems to be a specific feature enhancement to the gnu/gcc compiler.  Since I am tied to IAR, it would be nice to update the code to be more compiler independent...  I am also creating this ticket based on the info from the below user group thread...  

https://groups.google.com/forum/#!searchin/openthread-users/array%7Csort:relevance/openthread-users/kNBYtAVJfSc/svRVOPq-AQAJ

Places where arrays of size zero I found are at:
openthread\src\core\thread\network_diagnostic_tlvs.hpp

- class IPv6AddressListTlv: public NetworkDiagnosticTlv, its private data member Ip6::Address mIPv6AddressList[0]

- class ChildTableTlv: public NetworkDiagnosticTlv, its private data member ChildTableEntry mChildTableEntry[0]

**Comment by jwhui** [comment]
Thanks for submitting this issue!  I'll have a PR out soon that enforces C++03 and does not allow GNU extensions.
