### ISSUE TITLE
Rename the executable of the `cli` app to something other than `soc`

### ISSUE THREAD

**Issue by darconeous** [openthread/openthread#158]
It is rather confusing that the name of the executable for the `cli` app is `soc`. I think we should consider renaming it to something more clear.

**Comment by jwhui** [comment]
I agree they should at least be consistent.  Rename the executable to `cli`?  Or replace references to `cli` with `soc`?  Open to other suggestions.

**Comment by GiedriusM** [comment]
cli/soc/ncp are quite short names and with that comes a slight chance of clashing with system executables. Something like app_cli, ot_cli, openthread_cli would be a better name IMO.

**Comment by darconeous** [comment]
I recommend avoiding using `soc` at all. It's confusing. An SOC is what the code can run on.

**Comment by jwhui** [comment]
Fixed in #173.
