### ISSUE TITLE
examples/posix/flash.c problems with self-checks.

### ISSUE THREAD

**Issue by DuaneEllis-TI** [openthread/openthread#1599]
Technically there is nothing wrong with this, but depending upon the machine validation check-tests run on, the tests fail.  The current result, depending on the environment where the self-test operations are run they fail - randomly, but run perfectly when the next time.

The intent here is to fix/address the problem so that the validation tests work on more machines.

During the FLASH.C init() call, the simulated flash is erased - the current configuration is a simulated 256K byte flash chip (page size: 0x800(2K), npages=128 = 256K) 

Underlying problem:  The ${openthread}/tests/scripts/thread-cert directory - is run with numerous test scripts in parallel.  For example  Cert_5_2_06_RouterDowngrade.py - launches 26 instances of the CLI, Cert-5_2_03_LeaderReject2Hops.py launches 33 instances - the point here is there is a huge number of instances of the CLI application running in parallel.

The above to factors together cause the errors.

Solution/Option that is rejected:  Changing theses tests to run in *SEQUENCE* (not parallel) takes, means some tests take more then 3 hours to complete on the Travis-CI servers, well beyond a reasonable time limit. In fact, Travis dies with timeout errors.

Solution/Option that is rejected: Adjusting the total number of parallel jobs may solve the solution for one environment, but not all test environments, and extend test time on fast machines.

Solution/Option that is rejected: Just use a Bigger/Faster machines, this solution may work on sever class machine, but it is better if all developers can run the complete test suite on their assigned laptop, which may for example actually use a virtual machine. The developer tells the boss: I need a new laptop, the biggest, the baddest, the fastest thing on the planet.  The Boss says: What are you smoking?

Problem Detail 1 - The current implementation of page erase writes single bytes by calling pwrite()

Thus there are 50 instances of the CLI app - making 256K calls to the pwrite() function, each writing a single byte - depending upon the load on the machine running the test  (typically a VM of some sort) things timeout and fail for random reasons.

The solution is in this function *write* full pages in one operation, obviously (PAGE SIZE) 2048 times faster.

Problem Detail 2 - which is more of a comment of how *NOT* to fix this, and not cause other problems.  I learned this during my attempt to resolve the above issue.

To accomplish 1 (full page writes) - we need a PAGESIZE array of bytes, this could be: STATIC allocation,  MALLOC allocation, or on the runtime stack.

Static is not always a good solution.

The way to *NOT* solve this is to use MALLOC, meaning:  Allocate a page, initialize the page to 0xff, write the page, then free the page.

here's why:  Some (not all) of the tests make use of the address sanitizer  (aka: libasan, or just ASAN) the address sanitizer has a feature to detect  use-memory-after-free. To accomplish this, the function free() is changed to *NEVER* release the memory, instead free() "poisons" the freed memory in some form but does not release the memory. The net effect, the ASAN feature becomes a rather massively large memory leak.

Part 1: Thus any application that makes *MANY* malloc/free calls will cause a huge pseudo-memory leak. The CLI applications do exactly this as part of the flash page erase operation.

Part 2: Because the CERT tests execute well more then 50 tests in parallel, each with their own "pseudo-massive-memory-leak" means the test machine requires a HUGE amount of RAM (or swap space) this, coupled with virtual memory paging often results in either (a) timeout failures, (b) random strange crashes in Python due to out of memory errors, or (c) random failures in the ASAN enabled tests due to allocation failures.

On travis-ci, if you run the test second, or third time it sometimes passes, but another combination of tests fail, what is generally consistent is exactly an "out-of-memory" error/failure due to malloc/free + ASAN.

The simple solution is, in this case to place the dummy page on the runtime stack,  and not use malloc/free, and not use static memory allocation.

**Comment by jwhui** [comment]
Thanks for raising this issue and the thorough analysis.  I agree with the issue and the proposed resolution.  Would you be willing to submit a PR to address this?
