### ISSUE TITLE
Requesting new Network Data if Child Update Response contains new version

### ISSUE THREAD

**Issue by hubertmis** [openthread/openthread#1672]
Right now when a child handles Child Update Response message it calls `HandleLeaderData()`. Child Update Response does not contain Active or Pending Timestamps and because of that `HandleLeaderData()` does not send Data Request packet even if Network Data version in the message is greater than local value. It seems that Data Request should be sent in this case.

It is not a big problem because there is fallback procedure to check Network Data version in Advertisements transmitted by parent and this procedure works as expected.

**Comment by jwhui** [comment]
I agree that we should trigger an MLE Data Request message to be sent in this scenario.  Would you like to submit a PR that addresses this issue?
