### ISSUE TITLE
joiner does not reset Crc16 calculations after joining attempt

### ISSUE THREAD

**Issue by thcu-gp** [openthread/openthread#1710]
When the commissioner calculates the steeringdata, `Crc16::mCrc` is always `0` at the start of each calculation.
When the joiner calculates the steeringdata, `Crc16::mCrc` is only `0` at boot or after a reset, but not at each join attempt. Therefore if a joiner tries to join a second time (the first attempt might have failed), the steeringdata are calculated incorrectly and the joining fails.

`src/core/meshcop/joiner.cpp` on the lines `107-111` should start from `Crc16::mCrc=0` instead of from a previously calculated version

**Comment by chshu** [comment]
I think the issue will be fixed by #1706.

**Comment by jwhui** [comment]
@thcu-gp, does #1706 address your issue?

**Comment by thcu-gp** [comment]
yes, the fix in #1702 should do the trick

**Comment by jwhui** [comment]
Resolved by #1706.
