### ISSUE TITLE
ncp: some suggestions on PROTOCOL.md

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#179]
The encoding symbols, 'i', 'ii' or 'U' etc,  are used in Section 5, how about bringing Section 7.1 to front or adding one sentence in Section 5 illustrating that the meaning of the encoding symbols would be described in section 7.1?
It might be a little confusing when first met with the symbols in section 5 if without some explanations or any reference introduction in advance.

BTW, a minor typo in Section 4.6, the fifth line 'followed by the value to be inserted', 'inserted' should be 'removed'

**Comment by darconeous** [comment]
Thanks for the suggestions! Will review and reorganize to see how that reads (I suspect you are right).

**Comment by jwhui** [comment]
Fixed in #198.
