### ISSUE TITLE
Move vagrant, docker in /etc to "Script to rule them all"

### ISSUE THREAD

**Issue by beriberikix** [openthread/openthread#1860]
https://github.com/github/scripts-to-rule-them-all

`borderrouter` [moved](https://github.com/openthread/borderrouter/pull/7) to the [script-to-rule-them-all](https://github.com/github/scripts-to-rule-them-all) config boilerplate and I think it is a very clean pattern. I'm proposing we move the Vagrantfile, Dockerfile (when merged) and [codelab](https://codelabs.developers.google.com/codelabs/openthread-simulation/) to use the same pattern.

**Comment by jwhui** [comment]
Codelabs have also been updated (thanks to @Vyrastas)

- [Build a Thread network with nRF52840 boards and OpenThread](https://codelabs.developers.google.com/codelabs/openthread-hardware/index.html#0)
- [Simulating a Thread network with OpenThread](https://codelabs.developers.google.com/codelabs/openthread-simulation-posix/index.html#0)
