### ISSUE TITLE
ncp: sys/types.h not available in some embedded toolchains

### ISSUE THREAD

**Issue by turon** [openthread/openthread#191]
The IAR toolchain libc doesn't have sys/types.h included by spinel, and thus doesn't compile at this time.  It would be good if the spinel client code didn't have this dependency so it can easily be retargeted for a wide variety of MCUs and toolchains.

**Comment by darconeous** [comment]
I can't remember what I'm using `sys/types.h` for. I'm curious what breaks if you comment it out.

**Comment by turon** [comment]
Hi RQ, yes, deleting that line from spinel.h seems to build fine.

**Comment by turon** [comment]
Correction, these symbols seem to be missing without it:
EOVERFLOW
EINVAL
ssize_t

**Comment by jwhui** [comment]
Fixed in #193.

**Comment by darconeous** [comment]
`EOVERFLOW` and `EINVAL` should come from `errno.h`, included in `spinel.c`. Maybe IAR doesn't define these errors?

~~`ssize_t` should get pulled in by `stdio.h`, which needs it for the return value of `printf()`.~~ Er, nevermind, `printf()` returns `int`. >_<

I'll just get rid of the use of `ssize_t`. Will figure out what to do about `EOVERFLOW`...

**Comment by darconeous** [comment]
Reopening, based on @turon's comments.

**Comment by jwhui** [comment]
Fixed in #203.
