### ISSUE TITLE
NCP: Add support for Spinel's multiple-value get/set commands

### ISSUE THREAD

**Issue by darconeous** [openthread/openthread#1938]
Implement NCP support for `CMD_PROP_VALUE_MULTI_GET`, `CMD_PROP_VALUE_MULTI_SET`, and `CMD_PROP_VALUES_ARE`, as described by #1331 ([docs](https://rawgit.com/darconeous/openthread/feture/spinel-prop-multi/doc/draft-spinel-protocol.html#prop-value-multi-get)).

This was originally requested by @pvanhorn a while back but somehow fell off my plate, so I'm filing this issue to make sure we have something to keep track of it with.

**Comment by pvanhorn** [comment]
Ahh yes, I remember it well.

**Comment by jwhui** [comment]
No plan to implement. Closing.
