### ISSUE TITLE
bootstrap kw41z

### ISSUE THREAD

**Issue by khn123** [openthread/openthread#1939]
I just compiled the example and I got the following ...
`machine@ubuntu:~/openthread$ ./bootstrap 
./third_party/nlbuild-autotools/repo/scripts/bootstrap: 280: ./third_party/nlbuild-autotools/repo/scripts/bootstrap: --automake: not found
machine@ubuntu:~/openthread$ make -f examples/Makefile-kw41z 
  CONFIG   kw41z...
(cd build/kw41z && /home/machine/openthread/examples/../configure INSTALL="/usr/bin/install -p" CPP="arm-none-eabi-cpp" CC="arm-none-eabi-gcc" CXX="arm-none-eabi-g++" OBJC="cc" OBJCXX="" AR="arm-none-eabi-ar" RANLIB="arm-none-eabi-ranlib" NM="arm-none-eabi-nm" STRIP="arm-none-eabi-strip" CPPFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb " CFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb " CXXFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb -fno-exceptions -fno-rtti " LDFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb -specs=nano.specs -specs=nosys.specs -Wl,--gc-sections -Wl,-Map=map.map " --host=arm-none-eabi --prefix=/ --exec-prefix=/kw41z --enable-cli-app=all --enable-ncp-app=all --with-ncp-bus=uart --enable-diag --with-examples=kw41z --with-platform-info=KW41Z )
/bin/sh: 1: /home/machine/openthread/examples/../configure: not found
examples/Makefile-kw41z:226: recipe for target 'build/kw41z/config.status' failed
make: *** [build/kw41z/config.status] Error 127
`
can someone help me?

**Comment by khn123** [comment]
I just compiled the example and I got the following ...
[machine@ubuntu:~/openthread$ ./bootstrap 
./third_party/nlbuild-autotools/repo/scripts/bootstrap: 280: ./third_party/nlbuild-autotools/repo/scripts/bootstrap: --automake: not found
machine@ubuntu:~/openthread$ make -f examples/Makefile-kw41z 
  CONFIG   kw41z...
(cd build/kw41z && /home/machine/openthread/examples/../configure INSTALL="/usr/bin/install -p" CPP="arm-none-eabi-cpp" CC="arm-none-eabi-gcc" CXX="arm-none-eabi-g++" OBJC="cc" OBJCXX="" AR="arm-none-eabi-ar" RANLIB="arm-none-eabi-ranlib" NM="arm-none-eabi-nm" STRIP="arm-none-eabi-strip" CPPFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb " CFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb " CXXFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb -fno-exceptions -fno-rtti " LDFLAGS="-fdata-sections -ffunction-sections -Os -g -DOPENTHREAD_PROJECT_CORE_CONFIG_FILE='\"openthread-core-kw41z-config.h\"' -I/home/machine/openthread/examples/../examples/platforms/kw41z/  -mcpu=cortex-m0plus -mfloat-abi=soft -mthumb -specs=nano.specs -specs=nosys.specs -Wl,--gc-sections -Wl,-Map=map.map " --host=arm-none-eabi --prefix=/ --exec-prefix=/kw41z --enable-cli-app=all --enable-ncp-app=all --with-ncp-bus=uart --enable-diag --with-examples=kw41z --with-platform-info=KW41Z )
/bin/sh: 1: /home/machine/openthread/examples/../configure: not found
examples/Makefile-kw41z:226: recipe for target 'build/kw41z/config.status' failed
make: *** [build/kw41z/config.status] Error 127
](url)
Anyone can help me?

**Comment by hubertmis** [comment]
I had similar problem. I installed `libtoolize` to solve it.

**Comment by jwhui** [comment]
@khn123, did the suggestion @hubertmis help resolve your issue?

**Comment by bydottck13** [comment]
@jwhui, I had the similar problem, and this works for me:
# sudo apt-get install libtool

My OS is Ubuntu 14.04 32 bits.

**Comment by khn123** [comment]
@jwhui  this works for me. Thx @hubertmis .
