### ISSUE TITLE
Different .map files for different targets

### ISSUE THREAD

**Issue by Gr3yh0und** [openthread/openthread#1956]
Hey,
I am building my own `app` as an `ftd` and `mtd`. But the `Makefile-cc2538` only adds `-Map=map.map` as a `LDFLAG` which leads to the `map.map` file to get overwritten in the `build` directory. Would it be possible to get two map files like `app123-ftd.map` and `app123-mtd.map` automatically?

I'm currently changing the created `Makefile` which isn't a nice thing to do.

**Comment by jwhui** [comment]
@Gr3yh0und, thanks for reporting this issue.  I have submitted #1992 to help address this.  Please review.

**Comment by Gr3yh0und** [comment]
Looks good to me, thanks for adding this. Should've come up with that myself! 👍
