### ISSUE TITLE
uint8_t* vs otExtAddress

### ISSUE THREAD

**Issue by thcu-gp** [openthread/openthread#1979]
Sometimes the OpenThread api uses uint8_t* (of length 8) and sometimes it uses otExtAddress to represent an extended address.
*  `otLinkSetAssignLinkQuality` has argument `uint8_t* aExtAddr`
* `gpOpenThreadApi_ThreadSetSteeringData` has argument `otExtAddress_t aExtAddress`

I believe a unified approach would be better

**Comment by jwhui** [comment]
Thanks for flagging this issue.  I agree we should unify around `otExtAddress` rather than the generic `uint8_t*`.

Note that `otLinkSetAssignLinkQuality()` is being replaced as a part of #1967.  Are there other instances that need changing that you are aware of?

**Comment by thcu-gp** [comment]
| file | function |
|--|--|
| src/core/api/link_raw_api.cpp:202 | otError otLinkRawSrcMatchAddExtEntry(otInstance *aInstance, const uint8_t *aExtAddress) |
| src/core/api/link_raw_api.cpp:226 | otError otLinkRawSrcMatchClearExtEntry(otInstance *aInstance, const uint8_t *aExtAddress) |
| src/core/api/link_api.cpp:65 | const uint8_t *otLinkGetExtendedAddress(otInstance *aInstance)

**Comment by jwhui** [comment]
Thanks for identifying those other instances.  Are you planning to submit a PR for this?

**Comment by macysstorage** [comment]
thanks
