### ISSUE TITLE
NCP: get OpenThread stack counters

### ISSUE THREAD

**Issue by luwannest** [openthread/openthread#199]
Could we get the OT stack counters via wpanctl, though it only has MAC counters so far?
It will be really useful.

**Comment by darconeous** [comment]
Absolutely!

**Comment by darconeous** [comment]
I hope to get to this on monday.

**Comment by darconeous** [comment]
Will go ahead and map the counters to Spinel.

**Comment by darconeous** [comment]
Pull request #259 has the OpenThread-side of things. Will be throwing together the `wpantund` side of things shortly.

**Comment by darconeous** [comment]
Support for this in `wpantund` is being tracked by [issue 20](https://github.com/openthread/wpantund/pull/20).

**Comment by jwhui** [comment]
Resolved in #259.
