### ISSUE TITLE
./bootstrap fails with error "not found"

### ISSUE THREAD

**Issue by malexw** [openthread/openthread#2026]
Hi folks,

Following the instructions for building the CC2650 driver demo, I've installed autoconf, automake, and the gcc-arm toolchain. After running `./bootstrap` from the repo root, I get this error:

```
./third_party/nlbuild-autotools/repo/scripts/bootstrap: 280: ./third_party/nlbuild-autotools/repo/scripts/bootstrap: --automake: not found
```

Have I just missed a set-up step somewhere?

**Comment by bukepo** [comment]
Have you installed libtool?
```
sudo apt-get install libtool
```

**Comment by malexw** [comment]
That was the problem, thanks!
