### ISSUE TITLE
[MeshForwarder] Incorrect link-layer address selection

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#2046]
I found that there are couple violations to Thread Specification when it comes to link-layer address selection (in `MeshForwarder::UpdateIp6Route`).

Hightlights:
 - REED sends both link-local and real-local scope multicast message using IEEE 802.15.4 broadcast, however it must transmit message as IEEE 802.15.4 unicast to its parent.
 - When End Device sends realm-local scope multicast (e.g. from RLOC as a source) it uses extended mac addresses on IEEE 802.15.4 while short would be more efficient.
 - `UpdateIp6Route` performs link-layer address selection based on FTD or MTD type of the node, while in some situations this should be done based on current role (Router or End Device - root cause for 1).

I am going to propose some fixes for this issues.

**Comment by jwhui** [comment]
Sounds great.  Thanks for identifying and working to address these issues!
