### ISSUE TITLE
Application -- Network join status

### ISSUE THREAD

**Issue by pkanek** [openthread/openthread#2055]
What is the best way for the application (running on the device) to query the network join status of a thread device?
This will help the application to make a decision to start the join process or join with the available network data.

**Comment by jwhui** [comment]
A Thread device is commissioned when it has a valid Active Operational Dataset.  OpenThread provides the [otDatasetIsCommissioned()](https://github.com/openthread/openthread/blob/master/include/openthread/dataset.h#L59) API to indicate whether or not it has a valid Active Operational Dataset.  Does that help?

**Comment by pkanek** [comment]
@jwhui  Thanks
