### ISSUE TITLE
Create an otPlat API to handle vendor / platform specific Spinel properties.

### ISSUE THREAD

**Issue by pvanhorn** [openthread/openthread#2057]
Occasions exist where a host needs to send commands that are specific to its platform. Such commands should not be implemented by Openthread but should be handled by code that is technically separate from Openthread but still part of the NCP image.  Because Spinel and ncp_base get first opportunity to parse incoming frames from the host, it becomes necessary for ncp_base to have a way to route vendor specific requests to an appropriate handler.

For this reason it is proposed to create a new otPlat API that ncp_base will call for any Spinel property frames that it cannot handle internally.  Calls to this API shall be configured at build time via a core config variable that shall be disabled by default.

**Comment by jwhui** [comment]
Resolved by #2117.
