### ISSUE TITLE
cli: any plan to add children/routes/routers clis?

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#213]
are we going to add children/routes/routers clis to display current children set, routing table and router set?  might be useful for observing and evaluating the network status.

**Comment by jwhui** [comment]
Yup, I've been meaning to add these.  Watch for a PR soon.

**Comment by librasungirl** [comment]
Thanks @jwhui .  Looking forward to your PR.  Some more supplements here just as remind:
1) cache - show current EID-to-RLOC map 
2) whitelist - show current whitelist configuration

**Comment by librasungirl** [comment]
Thanks @jwhui  for these PRs. Supplement one more cli:
3) leaderdata - show current partition information (leaderid, partitionid, network data version, network data stable version etc)

**Comment by jwhui** [comment]
Resolved by #225, #226, $228, #229, and #231.
