### ISSUE TITLE
[netdata] issues when multiple BRs are configured the same prefixes (or routes) with different stable flag

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#2164]
Multiple BRs MAY be configured with the same prefixes (or routes) of different stable flags, different priorities etc. That is, in theory, one prefix may include both stable and unstable borderroutertlv, each of which may also include multiple borderrouterentries.

Current `GetNextOnMeshPrefix()` would always get the BRs in the first `BorderRouterTlv` of the Prefix.  Another impact  is on`IsOnMeshPrefixConsistent() ` evaluation and may cause repeating SRV_DATA.ntf. Similar impact on external routes.

**Comment by abtink** [comment]
With the change from https://github.com/openthread/openthread/pull/2073, the two methods `GetNextOnMeshPrefix()` and `GetNextExternalRoute()` should now iterate over all entries.

**Comment by librasungirl** [comment]
@abtink, I think #2073 could iterate all entries in the **first** `BorderRouterTlv` of one Prefix. However as stated above, one `PrefixTlv` may have two `BorderRouterTlv` (one stable, and one unstable).  Existing code does try to iterate the second `BorderRouterTlv`.

**Comment by abtink** [comment]
Ah, I see... Got it. Thank you.

**Comment by abtink** [comment]
PR: https://github.com/openthread/openthread/pull/2183
