### ISSUE TITLE
Running `./output/x86_64-unknown-linux-gnu/bin/ot-cli-ftd 0` should print a warning.

### ISSUE THREAD

**Issue by nutka7** [openthread/openthread#2178]
When you follow the Simulation Codelab but use node numbers 0 & 1 instead of 1 & 2 Thread doesn't work as expected (both clients transition to Leader). A warning explaining that 0 node number is special would save some time debugging.

**Comment by Vyrastas** [comment]
@nutka7 Thanks for the heads up... in the interim I'll update the Codelab to mention not to use 0.
