### ISSUE TITLE
Unable to see Zolertia Re-Mote Serial console output

### ISSUE THREAD

**Issue by akshaypm** [openthread/openthread#223]
As per given instruction on https://github.com/Zolertia/Resources/wiki/OpenThread#configure-the-devices-and-network-parameters I am unable to see serial output either putty/minicom/gtkterm/coolterm.

Kindly look into the issue.

**Comment by jwhui** [comment]
Thanks for catching this.  Looks #215 broke the examples for cc2538.  I just submitted #224 to fix this.
