### ISSUE TITLE
EUI64 ? SHA256 of EUI64 : while adding joiner

### ISSUE THREAD

**Issue by vinvinodk** [openthread/openthread#2254]
As per the section 8.10.1.9 of thread specification, User will feed the EUI64 of the device to the Commissioner for adding a thread product. But in native commissioner code of OT, we are mem-comparing the user's EUI64 address against SHA256 of EUI64. 

Code @ Commissioner::HandleRelayReceive API of commissioner.cpp file.

If my understanding is wrong, then user should feed SHA256 of Device's EUI64. What's the right one?

**Comment by jwhui** [comment]
At the user-interface level, the input should be the factory-assigned IEEE EUI-64.

I see that the `commissioner joiner add` CLI command does expect the Joiner ID (i.e. SHA-256 of the factory-assigned IEEE EUI-64).

I can look into changing the CLI to support the factory-assigned IEEE EUI-64 instead.

**Comment by jwhui** [comment]
@vinvinodk, submitted #2311.
