### ISSUE TITLE
Scan() function is called before initializing the mEnergyScanHandler 

### ISSUE THREAD

**Issue by pkanek** [openthread/openthread#2257]
https://github.com/openthread/openthread/blob/95f744fbb40fe5dbd69856820520b397fb372fad/src/core/mac/mac.cpp#L212

This can cause an exception, if the otPlatRadioEnergyScan() returns an error in Mac::StartEnergyScan() function.

The fix is to initialize the  mEnergyScanHandler before calling Scan() function in Mac::EnergyScan().

**Comment by abtink** [comment]
Good find! Thanks. Do you want to submit a PR for this (or let me know I can add it)....

**Comment by pkanek** [comment]
I will create a PR.

Thanks,
Parag

**Comment by jwhui** [comment]
Resolved by #2274.
