### ISSUE TITLE
ncp: openthread-config.h.in assumes autotools and isn't toolchain portable

### ISSUE THREAD

**Issue by turon** [openthread/openthread#230]
The iar port of the openthread apps isn't able to find openthread-config.h since it is assumed to be autogenerated by autotools.  This will be a roadblock for building NCP firmware on other toolchains as well.

**Comment by jwhui** [comment]
The only items used out of `openthread-config.h` is `PACKAGE_NAME` and `PACKAGE_VERSION`.  Those can easily be generated as necessary:
* `PACKAGE_NAME` is just `OPENTHREAD`
* `PACKAGE_VERSION` is generated with the bash script `third_party/nlbuild-autotools/repo/scripts/mkversion`

**Comment by turon** [comment]
Wouldn't it be simpler to just have a static .h for those then?  
It seems best to minimize the friction for folks trying to compile NCP with other toolchains.

**Comment by jwhui** [comment]
A static header file would not capture the actual state of your git tree, which is the purpose of the `mkversion` bash script.
