### ISSUE TITLE
README link to Qorvo does not work

### ISSUE THREAD

**Issue by wwhuang** [openthread/openthread#2312]
The link to Qorvo is for https://www.qorvo.com, which fails. The http version of quorvo works. I'm not sure if qorvo's https site is just down or does not exist.

**Comment by jwhui** [comment]
@wwhuang, thanks for reporting this.  We'll get this fixed.

**Comment by Vyrastas** [comment]
I think it was a mistake, as we have the http:// version on openthread.io

**Comment by jwhui** [comment]
Fixed by #2318.
