### ISSUE TITLE
script/bootstrap or instructions to install tools should be available for Mac

### ISSUE THREAD

**Issue by turon** [openthread/openthread#2331]
The openthread.io site mentions running `script/bootstrap` in order to automatically install required tools, but it doesn't work on Mac:

```
$ ./script/bootstrap 
./script/bootstrap: line 95: .: filename argument required
.: usage: . filename [arguments]
```

**Comment by bukepo** [comment]
I think we should remove from the main function the following lines:
```bash
    . $BEFORE_HOOK
    . $AFTER_HOOK
```

**Comment by jwhui** [comment]
Submitted #2332 to install basic tools for building.  Please review.
