### ISSUE TITLE
MLE: MTD's mode setting?

### ISSUE THREAD

**Issue by Hyungsin** [openthread/openthread#2357]
I tested MTD mode, which does not make a node sleep.
Why is "RxOnWhenIdle" turned on here? I think it is supposed to be disabled for MTD.
https://github.com/openthread/openthread/blob/master/src/core/thread/mle.cpp#L67

**Comment by jwhui** [comment]
The radio is always-on when attaching to a network, in order to receive MLE Parent Response messages.  A MTD only receives messages via IEEE 802.15.4 Indirect Transmissions after it has selected a Parent.

**Comment by Hyungsin** [comment]
Yes, but to make a node sleep, I think SetRxOnWhenIdle(false) should be executed as follows.
https://github.com/openthread/openthread/blob/master/src/core/thread/mle.cpp#L1680
https://github.com/openthread/openthread/blob/master/src/core/thread/mle.cpp#L1824
https://github.com/openthread/openthread/blob/master/src/core/thread/mle.cpp#L2900

When RxOnWhenIdle is on in mDeviceMode, the above lines are not executed.

**Comment by jwhui** [comment]
Minimal Thread Devices (MTDs) may operate as a Minimal End Device (MED) or Sleepy End Device (SED).  The former is the default configuration in OpenThread.  The latter may be configured by setting the rx-on-when-idle flag to false.

**Comment by Hyungsin** [comment]
Oh, I did not know that SED is not default. 
Then it's fine if the default setting is documented somewhere since SED is also working well with disabling rx-on-when-idle.

**Comment by jwhui** [comment]
See the [`otThreadSetLinkMode`](https://github.com/openthread/openthread/blob/master/include/openthread/thread.h#L211) API.
