### ISSUE TITLE
Routing: Handling the link with cost 4

### ISSUE THREAD

**Issue by Hyungsin** [openthread/openthread#2358]
I see the following note on the page 5-25 of Thread specification 1.1.1.
![image](https://user-images.githubusercontent.com/22308790/33049196-bc641e8c-ce13-11e7-82b0-64d0d83dbdd2.png)

In my understanding, Thread wants to select a neighbor with link cost 4 as the nexthop only if there is no other choices. But the following line makes me feel that OpenThread may prefer a direct transmission to the destination with link cost 4 when better multihop routes exist.
https://github.com/openthread/openthread/blob/master/src/core/thread/mesh_forwarder.cpp#L958

Also when determining multihop routes, I don't think OpenThread handles the cost-4 links differently. Is there any reason behind?

**Comment by jwhui** [comment]
General consensus is that Link Cost 4 links included in the route selection as other link metrics.  I can see how the specification text is confusing.  It may be worth filing an errata JIRA.  At the same time, the text does not contain normative keywords.

See [SPEC-218](https://threadgroup.atlassian.net/browse/SPEC-218) for more discussion around this topic.

**Comment by Hyungsin** [comment]
Thanks! But I cannot access SPEC-218.

**Comment by jwhui** [comment]
You need to be a Thread Group member.

**Comment by Hyungsin** [comment]
Ok. Is academic membership enough to see this?

Also regarding the following line, does OpenThread want to use direct route even though there are better multihop routes? For example, when the direct route has cost 4 and the two-hop route has cost 2 (1+1), OpenThread seems to select the direct route.
https://github.com/openthread/openthread/blob/master/src/core/thread/mesh_forwarder.cpp#L958

**Comment by Hyungsin** [comment]
I'm curious about the reason why link cost 4 is not handled differently. Avoiding using link cost 4 links may increase hop distance a little bit, but it would not be problematic since routers are plugged-in and always-on.

**Comment by jwhui** [comment]
Yes.  Academic and Affiliate membership have the same benefits: http://threadgroup.org/joinus#Membershipbenefits

In practical settings, going multiple hops incurs a lot more risk than the link/path cost may suggest.  In addition to link margin, there's buffering constraints, routing inconsistencies, etc.  If you can deliver directly to the destination, you avoid all of that uncertainty.

If the direct link turns out to be unusable, the direct link will be removed and the routed path will be used.

**Comment by Hyungsin** [comment]
I see, thanks!
Maybe UC Berkeley is not an academic member yet?

**Comment by jwhui** [comment]
I don't think so.  I reached out to you earlier in the year... :)

**Comment by Hyungsin** [comment]
and we answered "Yes"... :) So does it take a while?

**Comment by jwhui** [comment]
You have to apply: http://threadgroup.org/join/Becomemember

**Comment by Hyungsin** [comment]
Got it. Thanks!

**Comment by Hyungsin** [comment]
Assume that a neighbor has a weak link which becomes on and off.
Then, the current openthread tries to send packets directly to the neighbor whenever the link is on and experiences continuous failures when the link is off. Is this cycle repeated infinitely without giving any penalty to that neighbor node?
