### ISSUE TITLE
CoapBase::HandleRetransmissionTimer doesn't set the InterfaceID?

### ISSUE THREAD

**Issue by Rubeer** [openthread/openthread#2369]
On retransmit, the interfaceID is 0, causing OT_ERROR_DROP in Ip6::SendDatagram.
Am I doing something wrong? Adding
`                
messageInfo.mInterfaceId = OT_NETIF_INTERFACE_ID_THREAD;
` 
in Coap::HandleRetransmission solves the problem for me.

**Comment by jwhui** [comment]
@Rubeer, good catch.  Setting the interface id is necessary for link-local communication.  Would you like to submit a PR with the fix?  If not, I can submit the PR.

**Comment by Rubeer** [comment]
I have created a pull request: https://github.com/openthread/openthread/pull/2370

**Comment by jwhui** [comment]
Resolved by #2370.
