### ISSUE TITLE
[nrf52480] usb-cdc-uart: NCP locks up after receiving CMD_RESET

### ISSUE THREAD

**Issue by darconeous** [openthread/openthread#2383]
When built with `USB=1`, the resulting nRF52480 NCP image will lock up hard after receiving `CMD_RESET`.

Removing the call to `PlatformDeinit()` from `otPlatReset()` seems to correct the issue. Is the call to `PlatformDeinit()` really necessary before calling `NVIC_SystemReset()`?

**Comment by darconeous** [comment]
Proposed fix in #2383

**Comment by jwhui** [comment]
Resolved by #2388.
