### ISSUE TITLE
Let non-profit open source projects join the ThreadGroup for free?

### ISSUE THREAD

**Issue by Hedda** [openthread/openthread#24]
Please consider letting non-profit open source projects, such as example Domoticz and OpenHAB, join the ThreadGroup for free.

**Comment by gerickson** [comment]
On Fri, May 13, 2016 at 7:29 AM, Hedda <notifications@github.com> wrote:

> Please consider letting non-profit open source projects, such as example
> Domoticz and OpenHAB, join the ThreadGroup for free.
>
Please note that OpenThread Released by Nest is an independent effort
separate from and independent of the Thread Group.

**Comment by beriberikix** [comment]
Thanks @Hedda. I'd suggest contacting the Thread Group about non-profit membership at http://threadgroup.org/contact.
