### ISSUE TITLE
[ncp] Add a public method to ncp_base that allows vendor code to send Spinel messages to a host.

### ISSUE THREAD

**Issue by pvanhorn** [openthread/openthread#2410]
In order to allow vendor specific code to send Spinel packets to a host asynchronously, a new method must be added to the ncp_base class.  This method will be public and callable from vendor code. Like VendorCommandHandler this new method will be implemented by the vendor to perform vendor requirements with full access to the ncp public and private methods and members. 

This will allow vendor code to send spinel packets up to the host without having to implement new code to Openthread.

The new method will have to take a void* context as an input parameter which will represent the content that is understood by the vendor code calling the API and the vendor implemented API.

**Comment by jwhui** [comment]
Resolved by #2412.
