### ISSUE TITLE
Cannot open Visual Studio .sln project file

### ISSUE THREAD

**Issue by VictorAtPL** [openthread/openthread#2414]
Hello,

I cloned repository code of OpenThread and tried to open .sln project file located at etc/visual-studio as openthread.sln and I get following error:
![image](https://user-images.githubusercontent.com/1886347/33790573-9c00588c-dc81-11e7-9710-0483896bab2a.png)

Version of VS: 
![image](https://user-images.githubusercontent.com/1886347/33790585-ab0d2742-dc81-11e7-9cb0-86b15002b871.png)

I appreciate any help.

**Comment by jwhui** [comment]
Thanks for raising this issue.  I'm not sure why AppVeyor does not run into this specific error.

The solution file was last updated by #2329.  Can you try removing the commented-out lines completely to see if that helps?

**Comment by VictorAtPL** [comment]
Yes, it helped.

Could you tell me why did you comment those lines?

**Comment by jwhui** [comment]
@VictorAtPL, #2325 details why those lines were commented.  I can submit a PR that directly removes those lines.

**Comment by jwhui** [comment]
@VictorAtPL, submitted #2448.  Please review.
