### ISSUE TITLE
[nRF52840]: cannot build nrf_egu.c

### ISSUE THREAD

**Issue by retobkeller** [openthread/openthread#2424]
nRF52840 specific issue. I built commit 38b7d9e with this issue:
 
<assert.h> was not found in nrf_egu.h
I had to change <assert.h> into "nrf_assert.h" in the file nrf_egu.h

Best,
Reto

**Comment by jwhui** [comment]
FWIW, I just built 38b7d9e for nrf52840 without any issue.

Can you provide more information on your build environment?

**Comment by retobkeller** [comment]
Sorry, I am late.

I used:
- "SDK for Thread" from Nordic
- Eclipse
- GNU Tools ARM Embedded/5.4 2016q3

Thank you Jonathan and hubertmis for fixing it!!!

Best,
Reto
