### ISSUE TITLE
[tests] unstable tests collection

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#2425]
OT Contributors may have experienced travis tests failure which may be not relative to their PRs. Re-run travis build is current workaround. Now we have dedicated person who will 
help to improve this. If you have met or are experiencing travis tests failure and you think it should not be a problem caused by your PR, please help to list the unstable tests here. Thanks.

Sometimes it is hard to reproduce the unstable tests locally. Please help to update below summary along with the failing travis building log as well. Failing tests which occur more often would be prioritized.

Summary:
- [x] Cert_5_1_08_RouterAttachConnectivity (#2574)
- [x] Cert_5_1_09_REEDAttachConnectivity  (#2575)
- [x] Cert_5_2_01_REEDAttach (#2577)
- [x] Cert_5_2_04_REEDUpgrade (Occurrences: 1)
- [x] Cert_5_2_05_AddressQuery (Occurrences: 1)
- [x] Cert_5_2_07_REEDSynchronization (#2588)
- [x] Cert_5_3_05_RoutingLinkQuality (#2564)
- [x] Cert_5_5_08_SplitRoutersLostLeader (#2457)
- [x] Cert_6_1_03_RouterAttachConnectivity (#2580)
- [x] Cert_9_2_12_Announce (#2521)

**Comment by abtink** [comment]
Great to see this. Thanks.
I have seen the following tests failing for me on some travis runs: 
- FAIL: Cert_5_5_08_SplitRoutersLostLeader.py (example: [travis master build](https://travis-ci.org/abtink/openthread/jobs/318196314))
- FAIL: Cert_9_2_12_Announce.py

**Comment by LuDuda** [comment]
Adding logs to already reported test.

FAIL: Cert_9_2_12_Announce.py - [travis_9_2_12_announce.txt](https://github.com/openthread/openthread/files/1613163/travis_9_2_12_announce.txt)

**Comment by librasungirl** [comment]
FAIL:  Cert_5_1_09_REEDAttachConnectivity
https://travis-ci.org/openthread/openthread/jobs/326701681

**Comment by librasungirl** [comment]
FAIL: Cert_5_1_08_RouterAttachConnectivity
https://travis-ci.org/openthread/openthread/jobs/326715975

**Comment by librasungirl** [comment]
FAIL：Cert_5_2_5_AddressQuery
https://travis-ci.org/openthread/openthread/jobs/328382463
@hjian2017 , maybe you want to have a look as well as it is you who last updated it #2173

**Comment by librasungirl** [comment]
Another failing run of Cert_9_2_12_Announce in @jwhui 's #2472 , with the same error as the log @LuDuda attached above.

> FAIL: test (__main__.Cert_9_2_12_Announce)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "../../../../tests/scripts/thread-cert/Cert_9_2_12_Announce.py", line 124, in test
>     self.assertEqual(self.nodes[MED].get_state(), 'child')
> AssertionError: 'detached' != 'child'

**Comment by librasungirl** [comment]
FAIL: Cert_5_3_05_RoutingLinkQuality when building #2521
[travis_5_3_05_fail_2.txt](https://github.com/openthread/openthread/files/1687973/travis_5_3_05_fail_2.txt)
