### ISSUE TITLE
[mle] multicast address subscription by SEDs

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#2444]
As Thread specification says:

"_Thread devices MAY subscribe to additional realm-local multicast addresses. Rx-off-when-idle Children MUST register such IPv6 multicast addresses with their Parent to receive them via IEEE 802.15.4 indirect transmissions._"

Currently, OpenThread does not allow this operation (registration of multicast address as unicast does not work because of several reasons - e.g. wrong source address selection algorithm operation on SED, mesh forwarder actions on Parent etc..). So the only way to send MPL messages to the SEDs is to use the Realm-Local All Thread Nodes multicast address - which not always is the desirable solution.

I just want to emphasize the lack of this feature. We would be happy to implement this feature, but not in the short time, so please keep this issue open, or if anyone is interested to fill the gap, feel free to contribute.

**Comment by librasungirl** [comment]
Thanks for raising this. Agree that it is a missing feature. I'd like to implement this.

**Comment by librasungirl** [comment]
@LuDuda , #2474 is submitted to provide this feature. I have done some simple validation. Please help to have a review, and maybe further verification if you'd like. Thanks.

**Comment by LuDuda** [comment]
@librasungirl that is so awesome! ! Of course i will take a look on your contribution.
