### ISSUE TITLE
[efr32] add support for SPI Slave API

### ISSUE THREAD

**Issue by gemini-dakota** [openthread/openthread#2445]
It appears that support for using SPI (as opposed to UART) is not supported for the EFR32 platform. I am able to get UART compiling for using the EFR32 as either a CLI or NCP device. However, when I enable SPI, I receive the following linking error: "undefined reference to `otPlatSpiSlaveEnable'". I briefly looked into this error and openthread appears to be missing the implementation of this function. There is a spi-slave.h, but no spi-slave.c in the efr32 platform. 

Assuming I'm not missing something, I'd like to request the feature addition of SPI support for the EFR32 when used as a NCP (network co processor). 

Otherwise, if this should already be support, let me know as I must be doing something wrong.

**Comment by jwhui** [comment]
@gemini-dakota, the EFR32 example drivers do not currently include SPI support.  You are correct, that the platform APIs in`spi-slave.h` need to be implemented.  We welcome any contributions!

**Comment by gemini-dakota** [comment]
@jwhui Thanks for the response!

**Comment by unitrust1** [comment]
@jwhui you are very correct,the platform APIs in spi-slave.h need to be implemented.

**Comment by jwhui** [comment]
Closing stale issue. If this is still of interest to anyone, please open an issue in [openthread/ot-efr32](https://github.com/openthread/ot-efr32).
