### ISSUE TITLE
[DTLS] Cannot successfully join to Thread network thru own written code

### ISSUE THREAD

**Issue by VictorAtPL** [openthread/openthread#2501]
Hi,

I have two CC2538 modules. I have managed to successfully join to commissioner when both devices are configured by CLI. It weren't 100% rate success joins, but the trend was that I could join and ping the another device.

I started to write custom main.c files, first is for commissioner and second is for joiner.

Unfortunately when I start devices, the network is being formed, but the joiner couldn't join.

Even if I just form network with commissioner code and join to it by CLI on joiner - it doesn't work too.

The problem seems to be with MbedTls and/or my code. I see it hangs for some time on 

> generating new ecjpake parameters

and in that time it doens't send ACKs to other device (frame tx failed; failed to send ipv6; Dropping (reassembly queue) IPv6 UDP msg). Does CC2538 example have implemented SHA software generating? Because I suppose some kind of keys are being generated while establishing encrypted connection between devices?

I attach pcap file (wireshark-compatible) where all packets are sniffed. Also I attach pcap file from successful joining when I was doing it by CLI on both devices. Also I give you debug logs and main.c files, so please be so kind to check it (especially otJoinerCallback - is it implemented well?).
[commissioner_debug.log](https://github.com/openthread/openthread/files/1654359/commissioner_debug.log)
[joiner_debug.log](https://github.com/openthread/openthread/files/1654360/joiner_debug.log)
[main.c files](https://gist.github.com/VictorAtPL/7595ef2a2cd929696da22084aede39ac)
[pcap files for Wireshark](https://drive.google.com/open?id=182OD9r7EXY9ZX4Xm4eRwdR0rzBZ3gHZ-)

I would appreciate any help,
Piotr

*Update:* Same things happens if I just start commissioner node and join to it via CLI (ifconfig up; joiner start _PSK_). There is something like this:
> 201.599 | [INFO]-MESH-CP-: Dtls::HandleMbedtlsTransmit
> 201.604 | [INFO]-MESH-CP-: Sent joiner finalize
> ▒201.621 | [INFO]---------: execute command: ▒▒▒▒▒k▒▒W▒^▒▒▒▒▒▒▒▒>▒▒▒▒▒▒▒▒▒▒{▒v˿~▒▒▒▒▒m▒▒~▒▒}▒▒Y▒▒▒}▒▒▒▒▒▒▒R▒▒▒?▒▒▒▒▒w▒▒▒▒▒▒▒?w>▒▒▒▒▒▒▒▒
> 201.640 | [INFO]---------: execute command: ▒▒▒▒▒▒z_▒▒{u▒▒▒▒▒▒▒▒▒▒▒▒▒7▒▒▒▒_▒▒▒|▒w▒▒▒{▒▒n?▒▒▒▒▒▒▒}▒▒7▒▒M▒{f▒▒▒▒{▒W▒~▒▒_▒~▒▒▒▒▒▒▒▒▒▒

I think the execute command is thrown, because suddenly node breaks. Then it gets some kind of random bytes on Uart's RX. What does `Sent joiner finalize` mean and why the node breaks after that?

**Comment by VictorAtPL** [comment]
Any thoughts guys? Or suggests of ways how to debug it?

Need to make it work, because it's part of my thesis paper.

**Comment by jwhui** [comment]
@VictorAtPL, I did a quick review of your code and did not notice anything obvious.  I also tested your code with posix platform and it seemed to work fine.  I suspect that this is an issue specific to the CC2538 platform.

The Joiner Finalize message is used to trigger application and/or vendor-specific provisioning.  See Thread 1.1.1 Section 8.4.5 for more details.

The "hangs" you see during mbedtls crypto operations are expected.  The CC2538 example drivers do not implement platform-specific acceleration of elliptic curve crypto operations.

In your "update", you indicated that the same issue occurs with a CLI-based joiner built clean from GitHub master branch?

**Comment by jwhui** [comment]
@VictorAtPL, I just tried your main.c files on top of the latest master with two CLI nodes (https://github.com/openthread/openthread/commit/9190aa21c4b3983c05aad6be8fd5d62942b8cbd8) and everything worked as expected.

I built the images using: `COMMISSIONER=1 JOINER=1 make -f examples/Makefile-cc2538`

**Comment by jwhui** [comment]
Closing this issue.  Please reopen if you still have this issue.
