### ISSUE TITLE
sInstanceRaw

### ISSUE THREAD

**Issue by McMm77** [openthread/openthread#2503]
I have ported TI CC2538 to FreeRTOS and wanted to add openthread to my project.
But when everything compiles, I have a memory issue. In better words, lack of memory (RAM - .bss).

According to the generated memory map (generated by code composer), it seems that the following 
variable is taken the most memory.

openthread/src/core/api/instance_api.cpp
static otDEFINE_ALIGNED_VAR(sInstanceRaw, sizeof(otInstance), uint64_t);

Mem Size: 12824

Can someone explain to me, why such amount of memory needs to be allocated??

**Comment by jwhui** [comment]
`sInstanceRaw` is a memory buffer that contains _all_ statically allocated memory for a given OpenThread instance.  The memory size you quoted above is for an FTD and includes message buffers, router table, child table, address mapping table, among others.
