### ISSUE TITLE
Add support for SPI Slave API to CC2538 Platform

### ISSUE THREAD

**Issue by darconeous** [openthread/openthread#251]
Now that we have an API for a SPI slave interface, we should add support for it to the CC2538 platform.

**Comment by jwhui** [comment]
Closing this issue now that we have an example implementation (albeit for a different platform).  See [examples/platforms/nrf52840/spi-slave.c](https://github.com/openthread/openthread/blob/master/examples/platforms/nrf52840/spi-slave.c).
