### ISSUE TITLE
NRF52840 build fails on GCC 7.2 -Wexpansion-to-defined

### ISSUE THREAD

**Issue by nealjack** [openthread/openthread#2513]
On a clean git clone on a fresh install of Ubuntu 17.10, the build environment bootstrap script will install the latest arm-none-eabi-gcc, version 7.2.1. GCC version 7 includes `-Wexpansion-to-defined`, which causes multiple macros in the Nordic libraries to throw warnings, which are treated as errors. This can be fixed by adding `-Wno-expansion-to-defined` to the `COMMONCFLAGS` variable in `Makefile-nrf52840`. I am working on a pull request to add this flag conditionally based on installed GCC version.

**Comment by jwhui** [comment]
Resolved by #2514.
