### ISSUE TITLE
CC2538:  no ack for data request from SED

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#252]
One device as Leader, one as SED,  Leader would not ack the data request from SED

platform CC2538DK
firmware openthread master branch (commitid ef41589)

![cc2538dk_leader_sed no ack to data request](https://cloud.githubusercontent.com/assets/19217991/16641602/f67fc91e-4434-11e6-96a7-c8894c9d6e6b.png)

**Comment by jwhui** [comment]
@librasungirl, can you see if this was fixed by #247?

**Comment by librasungirl** [comment]
Thanks, will try out

**Comment by librasungirl** [comment]
hi @jwhui, here is the update for the try with the latest master branch(ab28c3a) - include #247
 
The first Data Request could be acked, but afterwards, SED would hang and trapped in below code,

`// in func ThreadError otPlatRadioTransmit(void) of cc2538 radio driver
while ((HWREG(RFCORE_XREG_FSMSTAT1) & 1) == 0);`

the traffic is as below
![sed hang after attach](https://cloud.githubusercontent.com/assets/19217991/16648341/21929d58-4466-11e6-920c-171cdb911c4c.png)

Will update if any new process.

**Comment by GiedriusM** [comment]
Offtopic:
@librasungirl Do you use any custom wireshark dissector for MLE (or maybe even for Thread?). If not, could you provide your wireshark version information. I'm having trouble getting MLE packets parsed in my pcaps.

**Comment by librasungirl** [comment]
hi @GiedriusM , the special wireshark comes along with GRL's Test Harness. You may need to download  and install Harness first from http://graniteriverlabs.com/thread/ and then configure wireshark according to the ‘Quick Start Guide' before you use it to dissect thread packets. 
Please have a try.

**Comment by librasungirl** [comment]
The root cause is explained as below, FYI.
After handled Child Id Response in upper layer, before go back to radio driver, NextOperation() in mac layer would call otPlatformSleep() and the typo ` VerifyOrExit(error = kStateIdle, error = kThreadError_Busy);` would force the status of the radio be kStateSleep, so when go down to radio driver,  disableReceiver() would not take effect; RX FIFO is not flushed, that is why  `(HWREG(RFCORE_XREG_FSMSTAT1)` is observed as 0x54 (overflow) when SED device is trying to send another packet but trapped in `while ((HWREG(RFCORE_XREG_FSMSTAT1) & 1) == 0);` 

PR#256 has beed created for this.

**Comment by jwhui** [comment]
Fixed in #256.
