### ISSUE TITLE
PlatformInit() namespacing

### ISSUE THREAD

**Issue by robertcragie** [openthread/openthread#2592]
PlatformInit() namespacing is a bit generic and has caused an issue in a porting exercise I am doing, Would it be possible to change it to otPlatInit() in line with the other platform files? The same would apply to PlatformProcessDrivers().

**Comment by jwhui** [comment]
@robertcragie, thanks for raising this issue.

We want to reserve the `otPlat*` prefix for platform functions that the OpenThread library actually uses.  Things like `PlatformInit()` and `PlatformProcessDrivers()` are specific to the particular examples that are using OpenThread.  Would something like `otExampleInit()` and `otExampleProcessDrivers()` help?

**Comment by turon** [comment]
I'd like to throw the proposed namespace of `otRuntime*` into the hat.  So `PlatformInit()` and `PlatformProcessDrivers ()` would become `otRuntimeInit()` and `otRuntimeProcessDrivers()`.

**Comment by jwhui** [comment]
@turon, not sure I see "runtime" as a good fit.  A "runtime" typically implements an execution model, or portions thereof.  In this case, `PlatformInit()` and `PlatformProcessDrivers()` have nothing to do with the execution model.

**Comment by robertcragie** [comment]
@jwhui I see your point as these are called by the example apps' `main()`, not the OpenThread library and are indeed specific to the way the examples are structured. The `otExample` prefix works for me but I would suggest making that distinction clear in the porting guide, i.e. separating what is actually platform abstraction from specific example implementation API.
