### ISSUE TITLE
DialogSDK cannot be compiled by gcc-6 because of 1 << 31

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#2661]
In some older compiler, 1 << 31 was undefined. Shall we change this to 1U << 31 at line https://github.com/openthread/openthread/blob/master/third_party/dialog/DialogSDK/bsp/peripherals/src/hw_otpc.c#L164

**Comment by jwhui** [comment]
@JakubBrachTieto, can you help take a look?
