### ISSUE TITLE
Add support for long routes

### ISSUE THREAD

**Issue by Nopik** [openthread/openthread#2758]
Currently OpenThread (and Thread itself) does perform very poorly when faced with network consisting of long line of devices - e.g. a street, where there is a device in each street lamp. So, each device sees few neighbours on each side only. If the radio reachability is relatively small (e.g. device can see 5 neighbours on each side), and we want to have lets say 150 devices in line, it is (sadly) simply impossible to have such stable mesh with Thread.

The reasons behind it are pretty related to Thread internals - specifically `kMaxRouteCost` (equal to 16 now), max router count to be 32 and Route64 TLV not allowing router-router paths to cost more than 16. Given that in the extreme configuration as described above, we'd need all 32 routers, and they will still barely see the next router -> i.e. using maximum cost.

Currently no more than 4-5 routers would work like this, as the route cost between them would quickly reach 16, so they would stop being able to communicate with each other. If one of the edge routers would happen to be the leader, the other edge will be too far away to contact leader within 16 cost and mesh would partition.

I will try to submit PR with some proposal how to solve this, but that obviously will hit a number of problems, so I'm opening this issue to host the discussion (which hopefully will unfold) until PR is ready.

One of the biggest obstacle is that the Thread specification itself (at least in version 1.1.1) basically limits this. Any modification will fail to comply with standard. It seems, that some trade-off can be made, to allow heterogenous meshes containing standard and non-standard devices working together as much as possible - but that is going to be extremely tricky.

We also need to be careful to not exceed certain MLE Advertisement size, to avoid unnecessary packet fragmenting. My tests show that we can add up to 27 bytes to the advertisement packets safely.

Another quirk is that, I feel that introducing brand new TLV would be a better (or more elegant) idea, yet it would add 2 bytes to the advertisement packet, and the current OpenThread implementation seem to rely heavily on `Route64TLV::GetCost()`, so when cost would depend on different TLV, code refactoring would be significantly bigger. For both those reasons, I think I will try to add some bytes at the end of existing Route64 TLV instead of adding new TLV. Especially that later it should be relatively simple to split that out to new TLV (apart of the refactoring of the today's code).

My biggest question is: if this PR will materialize, and will go through your review process, are there chances to merge it to the master? Or I shouldn't bother, since the change will deviate from standard?

For the reference, there was a very short discussion on this on openthread-users: https://groups.google.com/forum/#!topic/openthread-users/F6YY_lQiTZg

So, my plan is to:
- add some #define / configure switch (e.g. `LONG_ROUTE_SUPPORT`) to have this fully optional
- increase `kMaxRouteCost` to something like `127` (to keep `aRouteCost1 + aRouteCost2` within `uint8_t` range) - `31*4=124` might be enough, actually (I'm not 100% sure here)
- or maybe keep `kMaxRouteCost` at `16` but add `kMaxLongRouteCost` - for easier handling fallback scenarios to cooperate with vanilla 1.1.1 devices
- extend the `Route64` TLV with 7 bits for each router-router path with cost higher than current maximum
- trace down all route cost calculations and update them to use new max values and making sure they won't overflow `uint8_t`

What do you think?

**Comment by jwhui** [comment]
Thanks for continuing to drive this proposal (and apologies for not responding to your mail earlier).

While a primary goal of OpenThread is to be a leading reference implementation of Thread, I would also like to see OpenThread support development of forward-looking features that may eventually land in a future version of the Thread specification.  Allowing a Thread network to expand beyond several hops certainly seems like a feature worth exploring.  As long as the new feature places (ideally) no burden (e.g. can be compiled out, limited hooks in the base code, etc.) on the core Thread 1.1 implementation, then I think there is a path forward.

While supporting a single Thread mesh composed of Thread 1.1 routers and "long-route" routers is desirable, I'm not sure this is achievable.  For example, in Thread 1.1, the Leader allocates and maintains the set of active router ids.  The Leader determines if a router is present within its partition by monitoring the route cost to that router.  If the route cost is "infinite" for some continuous time period, the Leader will reclaim the router id and begin advertising that the given router id is no longer a part of the partition.

An alternative approach is to configure the network such that only "long-route" devices are able to become routers.  As part of Thread Commissioning, the Security Policy TLV may be used to restrict Thread 1.1 devices from becoming routers.

Thoughts?

**Comment by Nopik** [comment]
I'm glad to hear that this work have a chance to be merged, encouraging ;) Indeed, the plan is for it to be completely compiled out by default, with no cost.

As for the old & new mixing, I don't have a solid plan yet - I'm also afraid that it won't be possible, at least in some edge cases. I wasn't aware of the Security Policy TLV details, it's R bit seem indeed very interesting solution.

Since many internal details of Thread working are still unknown to me, I'm not sure how much we will gain by that. Like, I'm not sure how much Route64 TLV processing is done on children / REED. It seems that almost none, but the spec also says that child need to check cost to leader from its parent Route64 TLV. If that is the case, even the Security Policy TLV won't help, we will have to transmit values in some backward compatible format (which will be extremely annoying). 

However, Security Policy TLV is probably the most elegant solution (if it will work) - and it feels like designed for case like that, actually. It would allow introducing new version of Route64 TLV without any tricks to maintain compatibility with 1.1 - therefore saving some bytes.

**Comment by jwhui** [comment]
Router-Eligible End Devices (REEDs) are required to process Route64 TLVs because they are capable of becoming a router if needed.  If an end device never intends to become a router, there is no reason for it to process Route64 TLVs.  That said, I believe we need to add code to properly honor the Security Policy TLV R bit.

**Comment by Nopik** [comment]
Yeah, the change seems so incompatible, that it warrants the R bit usage. I will go for it.

My only concern is that we have only 1 R bit for whole Thread 1.x stuff. By using it, this feature will eye forward Thread 2.x. Which probably is a proper thing to do... Also, Thread 2.x should probably define more bits like this (only 3 left without extending the TLV) to block all Thread 2.x REEDs from becoming routers - for 3.x compatibility..

**Comment by Nopik** [comment]
@jwhui it seems that the R bit in Security Policy TLV is currently ignored in OpenThread. This is a bug, actually. In order to fix it, should I just add proper `&& (aDataset.mSecurityPolicy.mFlags & OT_SECURITY_POLICY_ROUTERS)` to https://github.com/openthread/openthread/blob/master/src/core/thread/mle_router.cpp#L104 and https://github.com/openthread/openthread/blob/master/src/core/thread/mle_router.cpp#L109 ? What about https://github.com/openthread/openthread/blob/master/src/core/thread/mle_router.cpp#L75 - the TLV value might not be known at the moment of initialization, right?

Or the actual fix should be more sophisticated?

**Comment by jwhui** [comment]
@Nopik, as you noted, the R bit is currently ignored.  I’ll have a PR up soon to address this.  You can see a preview here: https://github.com/openthread/openthread/compare/master...jwhui:security-policy

**Comment by Nopik** [comment]
Thanks. I started to implement this on my PR, but I'll revert, as your implementation seems to be better.

**Comment by jwhui** [comment]
@Nopik, I just submitted #2778.  Please review.

**Comment by jwhui** [comment]
Resolved by #2775.

**Comment by abtink** [comment]
@Nopik do you still use the `OPENTHREAD_CONFIG_MLE_LONG_ROUTES_ENABLE` feature? 

Working on something related, I noticed OT stack may not compile ok if thire feature enabled (couple of build errors - mostly seem to be trivial type mismatch issues). We can fix them but may be good to not keep code around if it is not being used and/or tested (by CI)?

**Comment by Nopik** [comment]
@abtink Unfortunately I no longer with that company and currently I'm not in position to submit any fixes for this ;( I tried to look up any github nickname from my old team, but didn't found any, either. (Quite surprisingly, because *I know* that some of them were active in this repo, apparently Github is making search not perfect). Anyway, I eventually pinged one mate on LinkedIn, so hopefully he'll pick it up..

**Comment by abtink** [comment]
Thanks @Nopik . No worries. I can fix the build issues in an upcoming PR. 😃 (I guess it may be toolchain dependent).
