### ISSUE TITLE
Border Router (Prepare Joiner Device) - Building Makefile-cc2650 fails

### ISSUE THREAD

**Issue by centrexsolutions-admin** [openthread/openthread#2767]
Hi,

I'm trying to make a build of the cc2650 with a switch of JOINER=1 for my OpenThread Border Router. 

I am using the following command 
$ sudo make -f examples/Makefile-cc2650 JOINER=1

I get the following output (Provided just the error. If you need more I can paste the full logs). 
/usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/bin/ld: ot-cli-mtd section `.text' will not fit in region `FLASH'
/usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/bin/ld: section .ccfg LMA [0001ffa8,0001ffff] overlaps section .text LMA [00000000,00024273]
/usr/lib/gcc/arm-none-eabi/5.4.1/../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 17504 bytes
collect2: error: ld returned 1 exit status
Makefile:1115: recipe for target 'ot-cli-mtd' failed
make[5]: *** [ot-cli-mtd] Error 1
Makefile:479: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
Makefile:485: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
Makefile:646: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
Makefile:572: recipe for target 'all' failed
make[1]: *** [all] Error 2
examples/Makefile-cc2650:231: recipe for target 'do-build-cortex-m3' failed
make: *** [do-build-cortex-m3] Error 2

Any ideas on how to resolve? 

Thanks,
James

**Comment by jwhui** [comment]
The CC2650 only has 128 KB flash.  As noted by the linker error `region 'FLASH' overflowed by 17504 bytes`, 128 KB flash is not enough to support a build that includes the Thread Commissioning Joiner capabilities.  You should consider the CC2652 or other supported platforms that have more flash capacity.
