### ISSUE TITLE
strnlen missing in older gcc versions

### ISSUE THREAD

**Issue by mszczodrak** [openthread/openthread#279]
In spinel.c we are using strnlen. This function is not defined in arm-none-eabi-gcc-4.8.3, which is still a common version.

Perhaps we can avoid using this function, or add a local version when it's missing, or we can add configure check AC_FUNC_STRNLEN to catch that situation early.

Some background reading about the problem: http://stackoverflow.com/questions/30203551/undefined-reference-to-strnlen-despite-string-h-include

**Comment by darconeous** [comment]
Note that `spinel.c` isn't the only file in OpenThread that references `strnlen()`. The file [`src/core/mac/mac_frame.hpp`](https://github.com/openthread/openthread/blob/d917618c7b428ee244e6febbdce3c71f5e3c5bbe/src/core/mac/mac_frame.hpp) does as well, on [line 783](https://github.com/openthread/openthread/blob/d917618c7b428ee244e6febbdce3c71f5e3c5bbe/src/core/mac/mac_frame.hpp#L738).
