### ISSUE TITLE
[radio] mIsCcaEnabled flag behaviour is not well defined

### ISSUE THREAD

**Issue by KaSroka** [openthread/openthread#2801]
Expected behaviour for this flag is not well defined.

Current mac (and link raw) behaviour for frames with `mIsCcaEnabled` set to `false` looks like this:
- Start CSMA-CA random backoff
- Send frame without CCA

But most common case for frames with CCA disabled is that we just transmit frame without backoff as well.

We should define common CSMA-CA random backoff behaviour when this flag is set to `false` (as now the description says only about CCA) or introduce additional flag for CSMA-CA.

I have faced this problem when using link raw API as there is no option to send frame without CSMA-CA backoff with `OPENTHREAD_CONFIG_ENABLE_SOFTWARE_RETRANSMIT = 1` and I was expecting that setting this flag to false will do the job.

**Comment by jwhui** [comment]
I think it makes sense to exclude backoff when `mIsCcaEnabled` is set to false.  Maybe we should rename it to `mIsCsmaCaEnabled`.

We can separate the backoff and CCA functionality when there is a clear use case.

Would you like to submit a PR to address this?

**Comment by KaSroka** [comment]
I can submit a PR which will exclude backoff when `mIsCcaEnabled` is set to `false`.
