### ISSUE TITLE
Integrate with Openweave

### ISSUE THREAD

**Issue by raupune** [openthread/openthread#2822]
Dear,
How to integrate Openweave and Openthread? 
Openweave works on Application Layer. While Openthread covers remaining. 
I went through Google codelabs.
But question still pinches my mind How to integrate them here? 
How to build them together? 
I am novice at GNU Build Toolchain.
Thanks.

**Comment by fscii** [comment]
To be perfectly honest, and I really hope people hear this with the open mind its being said with... I prefer that the open community have said thanks for the gift of openthread etc... we'll take it into consideration and may incorporate it or may not.  Basically what they did was give the open community the labor of making everything else on earth Nest compatible.  Imagine apple doing that now. n Yet on the flip side where's 802.11AC open source?   10GB is coming soon AX and opensource at 300mbit?  That's ok cuz the major corporations have figured out ow to hire armies of programmers without a penny except to their shareholders.  E.g. Microsoft wanting to buy Git and do what with licensing in the future and fees?  The most draconian company of all time w/code is going to hold the keys while alternate OS's of Remix and FLINT vanish at midnight (both times)?  Your code is open, your wallet is empty as theirs fills, now its time to open your eyes and your mind. 
Nothing makes me happier than to see open source code... but nothing makes me sicker to see corporations making BILLIONS taking it and programmers saying "hey if you like it drop a nickel in my tin can"  nope not a penny.  And corporations feel the need to OWN something that's free to everyone -- exactly what is the motive for that can anyone tell me?
 /Sorry about soapbox but I've been off the net most part of a few years to the dearest dying relative and come back to this disaster...
