### ISSUE TITLE
Unable to read messages on COAP server running on Raspberry Pi via Nodered

### ISSUE THREAD

**Issue by akansal1** [openthread/openthread#2823]
I am trying to read COAP messages on nodered running on Raspberry Pi, but I am unable to do so directly. The problem I have found is that UDP packets are being directed to NCP  on OTBR that and are not able to routed to localhost server.

![image](https://user-images.githubusercontent.com/8511760/41782932-2cb83202-7659-11e8-9b7b-f862c4c55188.png) 

I am able to read packets, if I forward coming on 5683 port of IPV6 to 5683 port of localhost server. But this is not working for GET requests. Am I missing anything? because, it should not have been this difficult in my opinion as, I am able to get responses if I push everything to COAP server  running on cloud service with any problem.
Is there a different way to generate IPV6 address for coap client running on MCU for the server running on 192.168...,localhost, 127.0.0.1 etc local ip addresses as  normal ipv4 to ipv6 conversions are not able route these requests.

**Comment by jwhui** [comment]
This is issue is related to the border router project.  Let's continue the discussion in: https://github.com/openthread/borderrouter/issues/142
