### ISSUE TITLE
[nrf52840] device hangs when reinitializing cc310

### ISSUE THREAD

**Issue by chshu** [openthread/openthread#2898]
#2878 reinitialize all peripherals except uart for pseudo reset, but it introduced another issue that the device hangs when reinitializing cc310, the issue only exist when OT Dtls related features are enabled (because of #2896).

The way to reproduce:

Build with: ```make -f examples/Makefile-nrf52840 COMMISSIONER=1 USB=1```
Download and perform ```reset``` cli command, the device will hangs in:
```
(gdb) bt
#0  0x00037412 in SaSi_HalWaitInterrupt ()
#1  0x00035bf8 in LLF_RND_WaitRngInterrupt ()
#2  0x00036d6c in LLF_RND_GetTrngSource ()
#3  0x000344c4 in SaSi_RndInstantiateOrReseed.part.0.constprop.4 ()
#4  0x0003461c in CRYS_RndInit ()
#5  0x000333fe in nrf5CryptoInit ()
    at /home/chenshu/code/openthread/examples/../third_party/mbedtls/../../third_party/NordicSemiconductor/libraries/crypto/cc310_mbedtls.c:55
#6  0x0001fe5c in PlatformInit (argc=argc@entry=0, argv=argv@entry=0x0 <__isr_vector>)
    at /home/chenshu/code/openthread/examples/../examples/platforms/nrf52840/platform.c:86
#7  0x000002c6 in main (argc=0, argv=0x0 <__isr_vector>) at /home/chenshu/code/openthread/examples/../examples/apps/cli/main.c:68
```

#2897 avoid the issue by removing the cc310 reinitialization during pseudo reset.

**Comment by jwhui** [comment]
Resolved by #2897.
