### ISSUE TITLE
[windows] fix Warning uninitialized memory '*aJoinerId' in otJoinerGetId()

### ISSUE THREAD

**Issue by rgreenwood60** [openthread/openthread#2916]
In function otJoinerGetId() of otapi.cpp
otExtAddress structure pointed to by aJoinerId potentially is uninitialized
and produces a C6001 compiler warning.

adding
ZeroMemory(aJoinerId, sizeof(otExtAddress));
before calling 
return DwordToThreadError(SetIOCTL(aInstance, IOCTL_OTLWF_OT_JOINER_ID, aJoinerId));

suppresses the warning and initializes the calling routines structure before attempting to use
the IOCTL_OTWLF_OT_JOINER_ID call to get the Joiner Id

In addition it may be good to check for (aJoinerId == nullptr) as well as the (aInstance == nullptr) check

**Comment by jwhui** [comment]
Thanks for raising this issue.  Would you like to submit a PR to address this?
