### ISSUE TITLE
NRF52840 SED Power consumption

### ISSUE THREAD

**Issue by kpyush** [openthread/openthread#2918]
Hi can you give figures for current profile when nrf52840 is configured as Sleepy End Device with following configurations.
 
```
otPlatRadioSetTransmitPower(sInstance, 0);
mRxOnWhenIdle =  false;
mSecureDataRequests = true;
otLinkSetPollPeriod(sInstance, 1000);
otThreadSetChildTimeout(sInstance, 10);
```

**Comment by LuDuda** [comment]
Hello @kpyush,

Could you please raise this question in [Nordic Semiconductor DevZone portal](https://devzone.nordicsemi.com/) where our tech support will help you.

**Comment by kpyush** [comment]
@LuDuda sure..
