### ISSUE TITLE
Keep udp open, ifconfig up and thread

### ISSUE THREAD

**Issue by blaizi** [openthread/openthread#2929]
Hello

I'm currently working on an openthread project, on an EFR32 device, and I have got a question:
After disconnecting a node, is it possible, after reconnecting it, that it stays in the state it was before, like router state for example, and also that the udp connection still activated.

Thank you a lot !

**Comment by blaizi** [comment]
I actually have a SoC communicating with a NCP, and when I disconnect this SoC and then reconnect it, it is still in the network, but the ifconfig is down and the UDP closed. 
I am currently struggling to manage that the UDP still open and the ifconfig still up when I put this node on power again.
If I understand correctly that is not possible because of the NCP ? (which would still on power in my case)

**Comment by jwhui** [comment]
By default, the example applications do not bringup the interface and start Thread protocols after power on.  OpenThread supports changing this default behavior via the [`otThreadSetAutoStart()`](https://github.com/openthread/openthread/blob/f824343f8cac34863c4267ae96a390da48c86ad3/src/core/api/thread_api.cpp#L479) API.  You can also change the value via the [`autostart`](https://github.com/openthread/openthread/blob/f824343f8cac34863c4267ae96a390da48c86ad3/src/cli/README.md#autostart) CLI command.

**Comment by blaizi** [comment]
Oh thanks a lot for your help !
However about the UDP, I suppose that it cannot make the "udp open" and "udp bind" automatically after power on ?

**Comment by jwhui** [comment]
As noted, the example CLI app does not automatically bringup the interface and open the UDP socket at startup time.  However, you could modify the example CLI app to make the appropriate calls to bring up the Thread interface and bind to the UDP socket.
