### ISSUE TITLE
[nrf52840] Uart_cli would be hung after network formation since #2968

### ISSUE THREAD

**Issue by yuzhyang** [openthread/openthread#2977]
**Summary**
UART CLIs would not have response for OT network running around 20 mins; All the Uart CLIs are disabled within the same WPAN.

**To Reproduce**
Information to reproduce the behavior, including:
1. 12 nodes are used with ot-cli-ftd firmware
2. Start OT network ('thread start') and keep interact with nodes through UART CLI (eg: command 'state' via JLink UART)
3. UART CLIs of all the nodes are not assessable after a period of time (around 20 mins for reference)

**Comment by LuDuda** [comment]
Hello, thanks for raising this issue. I'm ooo, @hubertmis will look at it.
