### ISSUE TITLE
[mle] API to provide MLE Parent Response information

### ISSUE THREAD

**Issue by bisdash** [openthread/openthread#2996]
Need to provide a way for clients of openthread(most likely vendor specific upper layers) to get parent request scan response data for SED. The plan is to implement it via a callback which needs to be installed by upper layer. The callback will be used to deliver following stats about a parent when a Parent Response is handled in Mle.
1. RSSI (1 byte)
2. rlock16 (2 byte)
3. extAddr (8 byte)
4. priority
5. Link count - LQ3 (1 byte)
6. Link count - LQ2 (1 byte)
7. Link count - LQ1 (1 byte)

**Comment by jwhui** [comment]
Resolved by #3027.
