### ISSUE TITLE
CLI example does not match README

### ISSUE THREAD

**Issue by cdwilson** [openthread/openthread#3]
This may be obvious, but when starting the example at https://github.com/openthread/openthread/tree/master/examples/cli the README shows:

    $ ./soc --nodeid=1 -S
    $ start
    Done

However, when I actually ran this example, I thought `soc` had hung because there was no `$` prompt printed.  Here's what I actually get when running it:

    $ ./soc --nodeid=1 -S
    start
    start
    Done

Everything works, but just may be a bit confusing for people trying this for the first time.

**Comment by beriberikix** [comment]
Thanks @cdwilson! Good catch. We'll update the README.

**Comment by jwhui** [comment]
Submitted PR #10
