### ISSUE TITLE
platform: add non-volatile, flash, and/or secured memory driver

### ISSUE THREAD

**Issue by turon** [openthread/openthread#30]
The platform api should be extended to provide a platform-specific means to store items that are required to be non-volatile.

**Comment by darconeous** [comment]
This is needed for implementing the [Spinel `CAP_NET_SAVE` capability](https://github.com/openthread/openthread/blob/master/src/ncp/PROTOCOL.md#b-feature-network-save).

**Comment by jwhui** [comment]
Resolved by #775.
