### ISSUE TITLE
[cc2652] does not compile

### ISSUE THREAD

**Issue by ubx-caloca** [openthread/openthread#3144]
Currently (Oct 11), I get an error when trying to compile for cc2652. I tracked the error and it seems that it appears after commit 
[mbedtls] simplify config file (#3126) a5dc13e3be6e478afce64c3dce4ba27136ea709f

Information to reproduce the behavior, including:
1. Git commit id : 
[mesh-forwarder] update indirect message logs (#3135) 467ab24e9baaa805ac98e9f1192a8217f3ca964c
2. IEEE 802.15.4 hardware platform
 cc2652
3. Build steps:
 make -f examples/Makefile-cc2652  JOINER=1
4. Network topology
---

**Console/log output**
In file included from /home/vorke/Openthread2/openthread/examples/../src/core/meshcop/dtls.hpp:41:0,
                 from /home/vorke/Openthread2/openthread/examples/../src/core/coap/coap_secure.hpp:35,
                 from /home/vorke/Openthread2/openthread/examples/../src/core/api/coap_secure_api.cpp:39:
/home/vorke/Openthread2/openthread/third_party/mbedtls/repo/include/mbedtls/entropy.h:129:5: error: 'mbedtls_sha256_context' does not name a type; did you mean 'mbedtls_aes_context'?
     mbedtls_sha256_context  accumulator;
     ^~~~~~~~~~~~~~~~~~~~~~

**Comment by jwhui** [comment]
I am not able to reproduce the issue. Did you try from a clean checkout and running `./bootstrap` again?

**Comment by jwhui** [comment]
Can you try the following steps:

1. `git clean -xfd` # this will blow away any untracked files
2. `./boostrap`
3. `make -f examples/Makefile-cc2652 JOINER=1`

Note that Travis also succeeds in building this configuration:

1. https://github.com/jwhui/openthread/commit/c7512794b250
2. https://travis-ci.org/jwhui/openthread/builds/440336706
3. https://travis-ci.org/jwhui/openthread/jobs/440336720

**Comment by ubx-caloca** [comment]
Doing the previous steps worked !! Thanks Jonathan.

I will make note to do the those steps every time I pull the latest changes.

**Comment by jwhui** [comment]
Great to hear that it works!
