### ISSUE TITLE
Get the hardware MAC

### ISSUE THREAD

**Issue by NOA-Ben** [openthread/openthread#3187]
I can get the unique identifier of the device through the API interface. I need to use 3 or more slave nodes. Each slave node has a temperature sensor and transmits the temperature to the root node. I need to identify which temperature value comes from. node

**Comment by jwhui** [comment]
You could use [`otLinkGetFactoryAssignedIeeeEui64()`](https://github.com/openthread/openthread/blob/71d4ad3e777672a441e238344290df302ad86bb7/include/openthread/link.h#L375) and include that as part of the application payload along with the temperature sensor.

**Comment by NOA-Ben** [comment]
Thank you so fast reply, I will try now

**Comment by jwhui** [comment]
@NOA-Ben, any updates on this issue?
