### ISSUE TITLE
How to save user data in settings area

### ISSUE THREAD

**Issue by kpyush** [openthread/openthread#3198]
Hi there,

I wanted to save some user information in the settings, is there any way to save this information in the settings area.

**Comment by jwhui** [comment]
For testing purposes, you could try using the [`otPlatSettings*`](https://github.com/openthread/openthread/blob/a07751ec0d7b02394670803e40dd080833d94b36/include/openthread/platform/settings.h) API. However, make sure to avoid the [Key IDs used by OpenThread](https://github.com/openthread/openthread/blob/a07751ec0d7b02394670803e40dd080833d94b36/src/core/common/settings.hpp#L123) - I suggest choosing a large value just to be sure.

Note that, in general, the `otPlat*` platform APIs are reserved for use by OpenThread. Unexpected use of the `otPlat*` APIs could lead to unpredictable behavior. In the case of settings, for example, wiping settings would lead to a device losing its network credentials necessary to communicate in a Thread network.
