### ISSUE TITLE
Zolertia Firefly NCP

### ISSUE THREAD

**Issue by nikiizvorski** [openthread/openthread#3213]
Hi the bug that we are facing is with Zolertia Firefly after is being flashed and thats been successful with one of the prebuilt firmwares doesn't seem to work as excepted. Only half functionality works and after it needs to make a connection it doesn't seem to do it.

**To Reproduce**
Just pull the latest bin from the website and flash it.

**Expected behavior**
To work as expected and as shown on the website

**Console/log output**

sudo python ~/cc2538-bsl/cc2538-bsl.py -e -w -v -p /dev/ttyUSB0        -a 0x00200000 ~/otpzor.bin
Opening port /dev/ttyUSB0, baud 500000
Reading data from /home/viblegrid/otpzor.bin
Firmware file: Raw Binary
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:18:E6:9C:39
Erasing 524288 bytes starting at address 0x00200000
    Erase done
Writing 524288 bytes starting at address 0x00200000
Write 16 bytes at 0x0027FFF0F8
    Write done                                
Verifying by comparing CRC32 calculations.
    Verified (match: 0xf8e51be9)

**Additional context**
2018-10-25 13:59:09.813 6188-6188/? D/lowpan-hdlc-adapter: userdriver: open() ok.
2018-10-25 13:59:09.881 6188-6192/? I/lowpan-hdlc-adapter: Device opened
Seems to act as it should but it doesn't proceed and fails to connect to the networks.

Using latest Android Thins and raspberry pi3 b as suggested.

**Comment by nikiizvorski** [comment]
bump

**Comment by jwhui** [comment]
Unfortunately, we do not have anyone actively supporting OpenThread on Android Things at this time - of course, contributions are welcome!

Otherwise, is it possible for you to use Raspbian on RPi 3b with [wpantund](https://github.com/openthread/wpantund)? Alternatively, you could try [OpenThread Border Router](https://openthread.io/guides/border-router).
