### ISSUE TITLE
otLinkActiveScan() returns a non null-terminated network name

### ISSUE THREAD

**Issue by sergeuz** [openthread/openthread#3233]
**Describe the bug**

`otLinkActiveScan()` doesn't null-terminate a network name if it has the maximum length of 16 characters.

**To Reproduce**

Set up a network with a name containing 16 characters and perform an active scan.

**Additional context**

The issue is caused by an incorrect size argument passed to `memcpy()` in the `Mac::ConvertBeaconToActiveScanResult()` method (the source `BeaconPayload::mNetworkName` string is not null-terminated): https://github.com/openthread/openthread/blob/9d585edc46999b82b30b8cf3e88901f8b271ab63/src/core/mac/mac.cpp#L312

**Comment by jwhui** [comment]
@sergeuz, thanks for raising this issue! Are you willing to submit a PR with the fix?

**Comment by sergeuz** [comment]
@jwhui Sure. I won't be able to make it today though, but will definitely submit it tomorrow if that's ok

**Comment by jwhui** [comment]
@sergeuz, of course, no problem!

**Comment by jwhui** [comment]
Resolved by #3246.
