### ISSUE TITLE
How to integrate OpenWeave and OpenThread

### ISSUE THREAD

**Issue by kevin-zhux** [openthread/openthread#3255]
Dear,

How to integrate OpenWeave and OpenThread, could you give me some advice or documentations?

Best Regard,
Kevin Zhu

**Comment by vervaekejonathan** [comment]
I have the same question

**Comment by jwhui** [comment]
See: https://groups.google.com/d/msg/openweave-users/vHuFq9DhP9Y/WaPdssBpEQAJ

**Comment by tehnorm** [comment]
I get "You do not have permission to access this content. (#418)" when trying to access the openweave-users group.

**Comment by jwhui** [comment]
@tehnorm, try signing in and becoming a member of [openweave-users](https://groups.google.com/forum/#!forum/openweave-users) - it is currently configured such that only group members can view posts.
