### ISSUE TITLE
How to get network topology tool of thread?

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/openthread#3311]
I tried to built a tool to evaluate network topology using 'sudo wpanctl getprop'. But in this command, only the nodes which are directly connected to NCP are listed.

Can any help?

**Comment by abtink** [comment]
There are multiple properties provided by OT/`wpantund` related to topology:
- `"Thread:ChildTable"` list of the children attached to the device
- `"Thread:NeighborTable"` list of neighbors (routers and direct chidllren)
- `"Thread:RouterTable"` list of all routers in networks (this list includes both routers that device can directly talk to, and routers that hops aways and the best next hop to reach them).

**Comment by tarunsmalviya** [comment]
Yes. But I cannot create complete graph of network based on these information because this doesn't provide details of child which are not directly connected to NCP.

**Comment by abtink** [comment]
Each router tracks its own children, so need to get the date from each router node separately.

**Comment by jwhui** [comment]
By design, no Thread device needs to maintain state about all other Thread devices in the network - allowing the network to scale while minimizing memory and communication resource utilization.

As @abtink mentioned, the information needs to be aggregated across the nodes in the network.

**Comment by tarunsmalviya** [comment]
Okay. Got it.
Thank you!

**Comment by tarunsmalviya** [comment]
Okay.There are tools provided by Nordic which is for windows and Linux x64, in which a CLI is connected and the tools draws the network topology. Can you elaborate how did they do it.

**Comment by jwhui** [comment]
Nordic implemented an application layer protocol where nodes report topology information to the topolgy visualization service.

**Comment by LuDuda** [comment]
@tarunsmalviya @jwhui Actually, I am the author of nRF Thread Topology Monitor and just to be precise the tool communicates with CLI device which periodically retrieves the current list of routers. Each router is polled by sending the standard Thread diagnostic messages (MGMT_DIAG.req) - [CLI command](https://github.com/openthread/openthread/tree/master/src/cli#networkdiagnostic-get-addr-type-). In response, routers in the network send their current link set (current connected neighbors), child table, and basic network parameters, such as Network Address or Extended MAC Address.

Because of that, no additional application layer protocol is needed - just bare Thread stack.

It would be of course nice to add support for MGMT_DIAG messages to spinel so that apart of CLI, also NCP could be used as a topology monitor device :)

**Comment by jwhui** [comment]
@LuDuda, thanks for clarifying! Adding support to spinel is an interesting thought. It might also be useful to implement a library so that any device that can route to the Thread network can perform these services.

**Comment by LuDuda** [comment]
@jwhui Can you elaborate more on what type of library are you thinking of?

Currently, we use almost unmodified CLI example (we do have some fancy led blinking :)) that is entirely driven from PC side by node.js script (with logic for polling all routers, topology database, visualization etc).

**Comment by jwhui** [comment]
@LuDuda use of TMF messages are limited to mesh-local addressing. It might also be nice to have something that does not require to be on-mesh. One possibility is to have something that operates in commissioner role and uses UDP proxy feature of border router. Anything more involved probably requires additional code on device and is probably best done within application-specific frameworks.

**Comment by tarunsmalviya** [comment]
@LuDuda Can you please share more details regarding [https://github.com/openthread/openthread/tree/master/src/cli#networkdiagnostic-get-addr-type-](CLI) command as I didn't find any proper documentation regarding the CLI command.

Thanks

**Comment by jwhui** [comment]
@tarunsmalviya , the [`networkdiagnostic get`](https://github.com/openthread/openthread/tree/cfc4882c3d7ee9f49ca9169394f61e7b43a56dd6/src/cli#networkdiagnostic-get-addr-type-) CLI command sends a `DIAG_GET.req` message to retrieve Thread state information from another device. You can learn more about available network diagnostics in [Thread 1.1.1 Section 10.11](https://www.threadgroup.org/support#specifications).

In summary, you can try the following steps:
1. Use the [`router table`](https://github.com/openthread/openthread/tree/cfc4882c3d7ee9f49ca9169394f61e7b43a56dd6/src/cli#router-table) CLI command to obtain the list of Thread routers in the network.
1. Use the [`networkdiagnostic get`](https://github.com/openthread/openthread/tree/cfc4882c3d7ee9f49ca9169394f61e7b43a56dd6/src/cli#networkdiagnostic-get-addr-type-) CLI command to retrieve information from a given Thread router.
1. You can see the information available via network diagnostics defined in [`src/core/thread/network_diagnostic_tlvs.hpp`](https://github.com/openthread/openthread/blob/cfc4882c3d7ee9f49ca9169394f61e7b43a56dd6/src/core/thread/network_diagnostic_tlvs.hpp).

Hope that helps.

**Comment by tarunsmalviya** [comment]
@jwhui Thanks for the help :)

**Comment by tarunsmalviya** [comment]
@LuDuda Can you share the complete format of command you mentioned. According to document, the commnd is `networkdiagnostic get <addr> <type>`. But what are values of <type> and what information does this command send. 
Also, please share any document regarding the same.

**Comment by tarunsmalviya** [comment]
@jwhui `router table` command returns the list of router with details like rloc16, etc.

When running `networkdiagnostic get` command which address we have to pass as argument because I tried with passing rloc16, but got parse error.

Also, I am unable to fetch NCP data when I run `networkdiagnostic get` command by passing multicast address.

**Comment by LuDuda** [comment]
@tarunsmalviya as described in the [documentation](https://github.com/openthread/openthread/tree/master/src/cli#networkdiagnostic-get-addr-type-) you need to pass RLOC IPv6 address, which is constructed from Mesh Local Prefix and RLOC16 - `MeshLocalPrefix::ff:fe00:RLOC16` e.g. `networkdiagnostic get fdde:ad00:beef:0:0:ff:fe00:f400 0 1 6`

**Comment by tarunsmalviya** [comment]
@LuDuda How do we calculate connections between router using router table. According to me, links between router can be known using id and next hop field, but in output of router table command, invalid router id is there in next hop, i.e., 63. Does that mean something?

**Comment by LuDuda** [comment]
In the TMM i just query for `Route64 `which helps to determine Routers topology. You can also query for `Child Table` to see attached children.

**Comment by tarunsmalviya** [comment]
@LuDuda Thanks!
Can you please explain how to determine link between routers using Route64?

**Comment by jwhui** [comment]
@tarunsmalviya, see [Thread 1.1.1](https://www.threadgroup.org/support#specifications) Section 5.20.1 for the MLE Route64 TLV Format.

Note that this issue was previously closed. Feel free to submit a new issue for future questions so that we can track them better. Thanks.
