### ISSUE TITLE
No internet connectivity when NCP is a commissioner

### ISSUE THREAD

**Issue by KaSroka** [openthread/openthread#3322]
I've noticed an issue that is caused by #3123. When NCP is a commissioner it would drop packets from other nodes instead of forwarding them to wpantund, blocking any internet traffic.

To reproduce we need one board with CLI and border router with internet connectivity.
CLI board should be able to ping external server:
```bash
ping 2001:4860:4860:0:0:0:0:8888
16 bytes from 2001:4860:4860:0:0:0:0:8888: icmp_seq=10 hlim=57 time=40ms
```
Now start commissioner on border router:
```bash
sudo wpanctl commissioner start
```
Ping from CLI board would fail:
```bash
ping 2001:4860:4860:0:0:0:0:8888
```

**Comment by bukepo** [comment]
Thanks for raising this issue. I have submitted #3328 to fix this issue.
