### ISSUE TITLE
Implement CoAP for openthread for cc2538 or Native PC

### ISSUE THREAD

**Issue by Praveen-Kumar-K** [openthread/openthread#334]
Hi All,

I have tried CLI applictions which is working fine, further i want to test the CoAP on my node (cc2538) with openthread. I am stuck with the procedure to compile coap for thread, integrate coap with CLI, can any one help me in this issue for move further to implement CoAP and Test it. 

Thanks,
Praveen Kumar K

**Comment by jwhui** [comment]
The OpenThread API supports sending and receiving UDP messages.  You can use those APIs to send/receive CoAP messages.  You could also look into [RIOT-OS](https://riot-os.org/), which supports CoAP and has a recent [PR](https://github.com/RIOT-OS/RIOT/pull/5552) to integrate OpenThread.
