### ISSUE TITLE
[netdata] 6LoWPAN Context Identifier reusage

### ISSUE THREAD

**Issue by avtolstoy** [openthread/openthread#3351]
**Describe the bug**

6LoWPAN Context Identifiers are reused on Leaders that received/restored the Network Data from some other node (e.g. after a reset). This of course causes connectivity issues, because an incorrect prefix/CID is assigned during compression/decompression. The main issue is that only a simple call to `SetNetworkData()` is made without synchronizing the received Network Data with the set of variables that track used Context Identifiers and their reusage timeouts: https://github.com/openthread/openthread/blob/master/src/core/thread/network_data_leader_ftd.hpp#L245

Another issue is that `ContextTlv`s and `PrefixTlv`s obtained in such a way will never get evicted from the Network Data and may eventually overflow it.

**To Reproduce**
We are using `1253becb720e0d8afc1cb0f1e39a76225a235e77` on nRF52840.

This issue is sometimes reproducible in a two-node network:

Have the Leader register itself as a Border Router with a certain prefix. The prefix will get CID 1. Reset the Leader node, it will request the Network Data from the other node, have the Leader register a different prefix, both prefixes will have CID set to 1 (one with compressed flag unset, the new one with it set).

**Expected behavior**

The Context Identifiers should be properly synced and their timeouts should be managed.

**Console/log output**
Network Data was received from the second node:
```
0000008318 [ot] INFO: -MLE-----: Receive Advertisement (fe80:0:0:0:a8ef:ec3f:919c:7a41,0xe400)
0000008319 [ot] INFO: -MLE-----: Route table updated
0000008331 [ot] INFO: -MLE-----:        3c00 -> fc00, cost:0 16, lqin:0, lqout:0
0000008332 [ot] INFO: -MLE-----:        e400 -> fc00, cost:0 16, lqin:3, lqout:3
0000008485 [ot] INFO: -MLE-----: Send Advertisement (ff02:0:0:0:0:0:0:1)
0000008675 [ot] INFO: -MLE-----: Send delayed message (fe80:0:0:0:a8ef:ec3f:919c:7a41)
0000008700 [ot] INFO: -MLE-----: Receive Link Accept (fe80:0:0:0:a8ef:ec3f:919c:7a41,0xe400)
0000008702 [ot] INFO: -MLE-----: Send Data Request (fe80:0:0:0:a8ef:ec3f:919c:7a41)
0000008730 [ot] INFO: -MLE-----: Receive Data Response (fe80:0:0:0:a8ef:ec3f:919c:7a41)
0000008731 [ot] TRACE: =======================[set network data len=028]========================
0000008743 [ot] TRACE: | 08 04 0B 02 E8 F5 03 14 | 00 40 FD 82 23 E4 40 16 | ....hu...@}.#d@.
0000008747 [ot] TRACE: | 00 00 07 02 11 40 05 04 | 3C 00 33 00 .. .. .. .. | .....@..<.3.....
0000008754 [ot] TRACE: ------------------------------------------------------------------------
```

Leader registered a different prefix.

Both prefixes are in the Network Data with CID = 1:
```
0000011448 [ot] TRACE: ===========================[netdata len=044]============================
0000011458 [ot] TRACE: | 08 04 0B 02 E8 F5 03 0E | 00 40 FD 82 23 E4 40 16 | ....hu...@}.#d@.
0000011469 [ot] TRACE: | 00 00 07 02 01 40 03 14 | 00 40 FD DB 70 D1 2C D9 | .....@...@}[pQ,Y
0000011480 [ot] TRACE: | 00 00 07 02 11 40 05 04 | 3C 00 33 00 .. .. .. .. | .....@..<.3.....
0000011482 [ot] TRACE: ------------------------------------------------------------------------
```

**Comment by LuDuda** [comment]
Thanks for raising this issue!

@jwhui as a first step I propose just to read out contexts from received Network Data and synchronize it with the internal database. What do you think?

However, I see some challenges with the current approach of accepting network data from some Router by Leader which has been just reset. Thread specification defines CONTEXT_ID_REUSE_DELAY variable that defines the minimum time between disallowing the use of a 6LoWPAN context ID for compression and reusing the ID for a new prefix. Since we don't keep track of contexts in non-volatile memory we simply can't guarantee it after Leader is reset. I think the similar is happening with ID_REUSE_DELAY. Should then Leader create a new partition and clear network data after its reset?

**Comment by LuDuda** [comment]
Although my concerns are probably incorrect for contexts in OpenThread since we don't remove prefixes from Network Data before `CONTEXT_ID_REUSE_DELAY` anyway. I'm not sure if this is correct behaviour and specification does not help a lot here. But worst case we will wait longer than `CONTEXT_ID_REUSE_DELAY` before we reealocate the context, so we are fine here.

**Comment by jwhui** [comment]
@avtolstoy, thanks for reporting this issue with detailed description!

@LuDuda, I agree that we should synchronize internal state with the received Network Data.

Regarding `CONTEXT_ID_REUSE_DELAY`, Thread 1.1.1 Section 5.15.9 states the following:

> In particular, if a prefix no longer appears in the Valid Prefix Set and the External Route Set, that prefix must be retained in the 6LoWPAN Context ID Set with CID_compress set to `false’ for at least CONTEXT_ID_REUSE_DELAY seconds before being removed from that set.

As a result, I believe OpenThread has the correct behavior. Of course, if the Leader resets, it will have to set the reuse delay back to `CONTEXT_ID_REUSE_DELAY` again.

Regarding `ID_REUSE_DELAY`, one option is to simply reset the delay after reattaching as Leader. The downside is that no new routers will be allowed for `ID_REUSE_DELAY` (100 seconds), but that seems better than having to create a new partition.

Thoughts?

**Comment by LuDuda** [comment]
I've created a PR with the proposed fix.

Regarding `CONTEXT_ID_REUSE_DELAY` you are correct, my assumption was that 6LoWPAN Context ID Set is Leader's internal table.

When it comes to `ID_REUSE_DELAY` i agree that creating a new partition is highly undesirable, but in the other hand blocking Router promotion for 100 seconds is also quite bad. Especially if there is some new node that has connection only to REED that can't promote. I guess we can create another GitHub issue where we can try to figure it out.

**Comment by jwhui** [comment]
@LuDuda, thanks for proposing a fix!

In looking at the code, I think we may need another change to ensure the leader retrieves network data from a neighboring device. Something like https://github.com/openthread/openthread/compare/master...jwhui:network-data. Thoughts?

I agree to address the `ID_REUSE_DELAY` as a separate issue.

**Comment by beriberikix** [comment]
Many thanks @LuDuda @jwhui for looking into this and already submitting PRs. We appreciate the fast turnaround 🙇
