### ISSUE TITLE
otInstanceInit struct allocation

### ISSUE THREAD

**Issue by jia200x** [openthread/openthread#3362]
Hello OpenThread developers,

I'm currently improving the RIOT-OS port of OpenThread and came here to describe a problem I'm facing and a possible solution.

## The problem
I'm trying to create an OpenThread container struct like this:
```
typedef struct {
    otInstance instance;
    riot_radio_handler_t radio_handler;
    int foo;
} ot_container_t;

ot_container_t ot_container;
```

Since `&ot_container == &ot_container->instance`, I could access RIOT-OS specific stuff from the instance pointer instead of defining global variables.

E.g:

Now I use global variables:
```
 /* Global radio descriptor */
riot_radio_handler *radio_handler = RADIO_HANDLER;

void otPlatRadioSetPanId(otInstance *aInstance, uint16_t aPanId)
{
    radio_handle->set_panid(aPanid);
}
```

With the container:
```
void otPlatRadioSetPanId(otInstance *aInstance, uint16_t aPanId)
{
    ot_container_t container = (ot_container_t*) aInstance;
    riot_radio_handler_t riot_radio = container->radio_handler
    
    /* radio_handle is not global anymore */
    radio_handle->set_panid(aPanid);
}
```

The OpenThread instances [are currently allocated in the core](https://github.com/openthread/openthread/blob/8d125135914e035eaf25270e5ed1e14061425e89/src/core/common/instance.cpp#L49). So this pattern doesn't seem to be feasible so far.

## Possible solution
Although it requires an API change, I guess this pattern could be done if:
1. There's a helper for allocating the Instance (get size of Instance class)
2. The otInstanceInit function receive one `buffer` argument. If it's NULL, OpenThread allocates the buffer. Otherwise OpenThread uses the user-allocated buffer

Is this feasible? Or do you think there is a better solution?

**Comment by jia200x** [comment]
(sorry, it published before I finished. I'm still writing the description)

**Comment by jia200x** [comment]
(done!)

**Comment by jwhui** [comment]
@jia200x, OpenThread's [multiple instance feature](https://github.com/openthread/openthread/blob/23ff1015d4f68b07c303ab35c9656f43642d2c1d/configure.ac#L386) allows external allocation of OpenThread instance memory. Does that satisfy your use case?

**Comment by jwhui** [comment]
@jia200x, any comments?

**Comment by jia200x** [comment]
@jwhui sorry for the delay.

Yes, I think there could be a workaround with this approach for multiple instance feature. 
It would be direct though, if there's a way to know the size of the `otInstance` object in compile time (instead of calling `otInstanceInit(NULL, &len)`.) 

Do you know if this is possible?

**Comment by jia200x** [comment]
well, I think my second question is unrelated to the original. So I guess the issue could be closed.
Thanks!
