### ISSUE TITLE
MleRouter::HandleStateUpdateTimer can continue to expire indefinitely

### ISSUE THREAD

**Issue by conormoneill** [openthread/openthread#3372]
If the following sequence occurs, the MleRouter::HandleStateUpdate timer can be left expiring indefinitely.

- Configure role as router via spinel interface
- Wait for node to complete MLE attach as a child.  HandleStateUpdateTimer will be started, and mRouterSelectionJitterTimeout will be set to a random number between 1 and 120 seconds.  When the jitter timeout expires the device will transition to router role.
- Before device transitions to router role, use Spinel interface to configure device as a child (no router capabilities)

When this sequence is followed, the HandleStateUpdateTimer will continue to expire indefinitely.  Further, eventually this will result in the device perpetually aggressively attempting to reattach to its current parent by virtue of the mRouterTable.GetLeaderAge() call returning a leader age that is >= mNetworkIdTimeout.

The simple fix is to exit the HandleStateUpdateTimer handler without resetting the timer if the device's mode has changed to something that doesn't support routing capabilities (ie, exit the handler if Mle::IsMinimalEndDevice() == true).

**Comment by jwhui** [comment]
Resolved by #3376.
