### ISSUE TITLE
Radio only not working for nrf52840

### ISSUE THREAD

**Issue by gjc13** [openthread/openthread#3427]
**Describe the bug**
Radio only not working for nrf52840
**To Reproduce**
git commit id
1. git commit id e14d763e2ec301a509fa757890819a8a05e0eeb1
2. nrf52840 dev kit
3. Build radio only ot_cli and nrf52840 ot_ncp_radio and ot_cli_ftd
4. Flash one nrf52840 dev kit with ot_cli_ftd, another with ot_ncp_radio.
5. Run 
```
ot_cli /dev/ttyACM0
screen /dev/ttyACM1
```
5. In both cli, type in
```
panid 0x1234
ifconfig up
thread start
```
Both nodes become leader.
**Expected behavior**
Two nodes should form a network.

**Additional context**
After a simple investigation, the problem is nrf52840 received a wrong spinel frame on first radio send. The spinel frame does not begin with 0x7e. `strace` dump indicates that there is nothing wrong with the frame sent from host. NRF uart, however, just receives the wrong data.
Error output is:
```
 Framing error 6: [
55 53 42 53 6A 02 00 00 EC 34 12 FF FF A4 88 1C 51 8A 0A CB 0E 7F 3B 02 F0 4D 4C 4D 4C AD DD 00 15 AC 0F 00 00 00 00 00 00]
```

**Comment by bukepo** [comment]
It seems the MSD is not disabled. Try disabling as https://github.com/openthread/openthread/blob/master/src/posix/README.md#nrf52840
