### ISSUE TITLE
[efr32] cannot compile with log output OPENTHREAD_CONFIG_LOG_OUTPUT_APP

### ISSUE THREAD

**Issue by josephn123** [openthread/openthread#3615]
**Describe the bug**
Set log output `OPENTHREAD_CONFIG_LOG_OUTPUT` to `OPENTHREAD_CONFIG_LOG_OUTPUT_APP`

**Console/log output**
Linker fails due to missing `efr32LogInit()`.

**Additional context**
This is because of the following in `examples/platforms/efr32/logging.c`:
```
#if (OPENTHREAD_CONFIG_LOG_OUTPUT == OPENTHREAD_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED) || \
    (OPENTHREAD_CONFIG_LOG_OUTPUT == OPENTHREAD_CONFIG_LOG_OUTPUT_NCP_SPINEL)
```
The call to `efr32LogInit()` in `system.c` should not be made if the above is not true (so additional preprocessor check required in `system.c`).

**Comment by jwhui** [comment]
@josephn123, thanks for raising this issue! I agree with the proposed resolution. Would you like to submit a PR?

**Comment by josephn123** [comment]
Will do, please assign to me
