### ISSUE TITLE
[posix-app] enhance reset implementation

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3647]
**Is your feature request related to a problem? Please describe.**
posix/posix-app reset implementation.

**Describe the solution you'd like**
Move call to `otTaskletsProcess()` from main into `otSysMainloopProcess()`, ensure there's no business processing in `otSysMainloopUpdate()` and `otSysMainloopPoll()`, so that we can move `gResetJump` as an internal variable fully owned by platform. This make porting work easier. 

**Describe alternatives you've considered**
Implement reset with pseudo-reset, which used to be buggy on posix-app.

**Additional context**
None

**Comment by jwhui** [comment]
Closing stale issue.
