### ISSUE TITLE
[nrf52840] otPlatRadioDisable() doesn't disable radio

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3656]
**Describe the bug**
From code, disabling nrf52840 doesn't really change the radio state in nordic SDK. If the radio state is in RECEIVE mode, otPlatRadioDisable() may still ACK packets.

**Comment by LuDuda** [comment]
Thanks, @bukepo for reporting this.

According to the [documentation](https://github.com/openthread/openthread/blob/master/include/openthread/platform/radio.h#L215), OT should always call `otPlatRadioSleep()` before invoking `otPlatRadioDisable()`. For complete radio shutdown you can use `nrf5RadioDeinit()` function.

Do you think this behaviour should be modified (as well as OpenThread documentation allows for such transition)? I took a quick look on the first reference hardware platform, which seems to act in the same way.

**Comment by bukepo** [comment]
Yes. Shall we add asserts to prevent illegal usage?

**Comment by LuDuda** [comment]
Can you clarify your reply (I see two contradicted sentences :smile:)?

My understanding is that `otPlatRadioDisable` behaves correctly (according to the documentation). Do you think about adding assert in the platform code or OT?

**Comment by bukepo** [comment]
Yes, I think we should add assert in platform code to prevent we use it in wrong way.

**Comment by LuDuda** [comment]
Thanks, I will look at it and propose PR.
