### ISSUE TITLE
[coap] otCoapMessage type not defined

### ISSUE THREAD

**Issue by ozanoner** [openthread/openthread#3684]
There is a type named otCoapMessage, but I couldn't find its definition. I appreciate if you can help me with it.  
https://github.com/openthread/openthread/blob/master/src/cli/cli_coap_secure.cpp#L589

**Comment by bukepo** [comment]
@ozanoner Thanks for reporting this. I think it's a typo, which should be `otMessage`. Would you like to submit a PR to fix it?

**Comment by jwhui** [comment]
For clarity the `otCoapMessage` argument should be removed. The `otCoapRequestHandler` type changed as part of #3419.

**Comment by bukepo** [comment]
Thanks, and we should also enable this feature in our CI test.

**Comment by jwhui** [comment]
Resolved by #3737.
