### ISSUE TITLE
[posix-app] auto start support with platform netif enabled

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3685]
Auto start is now implemented in ot instance init. Giving no chance init other components including platform netif. We should change the design, possibly trigger auto start in a tasklet.

**Comment by jwhui** [comment]
Do we have a good use case for autostart? If not, maybe we should consider removing this feature?

**Comment by bukepo** [comment]
I think this feature is useful to for ot-br-posix's `--with-ncp=openthread` mode.

**Comment by jwhui** [comment]
In the case of `--with-ncp=openthread`, do we need to have a run-time configuration that is persistently stored?

**Comment by bukepo** [comment]
I agree we could remove this feature.

**Comment by jwhui** [comment]
@bukepo, submitted #3920.
