### ISSUE TITLE
[efr32] efr32 project doesn't build

### ISSUE THREAD

**Issue by josephn123** [openthread/openthread#3703]
**Describe the bug**
Build issue, by default `OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT` is not defined.

**To Reproduce**
Take latest commit `e3d0368070c67c21e998b54c95cbc3c26178a2e1`
```
./bootstrap
make -f examples/Makefile-efr32 BOARD=BRD4304A clean
make -f examples/Makefile-efr32 BOARD=BRD4304A
```

**Console/log output**
Snippet of full output:
```
openthread/examples/../src/core/phy/phy.hpp:84:67: error: 'OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT' was not declared in this scope
 OT_STATIC_ASSERT((OPENTHREAD_CONFIG_RADIO_2P4GHZ_OQPSK_SUPPORT || OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT),
```

**Comment by jwhui** [comment]
@josephn123, thanks for raising this issue! I just submitted #3704. Please review.
