### ISSUE TITLE
Shall we refine returning type of otMessageRead()?

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3706]
**Is your feature request related to a problem? Please describe.**
`otMessageRead()` current returns `int`, which differs from the internal `Message::Read()` returning `uint16_t`.
 https://github.com/openthread/openthread/blob/master/include/openthread/message.h#L275
https://github.com/openthread/openthread/blob/master/src/core/common/message.hpp#L418

From the definition of `otMessageRead()`, it doesn't allow negative returning value. Shall we 
change the returning type to `uint16_t`, `size_t` or `unsigned int`?

**Describe the solution you'd like**
Change returning type to `uint16_t`.

**Describe alternatives you've considered**
Change to `size_t` or `unsigned int`.

**Comment by jwhui** [comment]
I agree on changing to return `uint16_t`.
