### ISSUE TITLE
About Radio caps

### ISSUE THREAD

**Issue by dismirlian** [openthread/openthread#3711]
Hi all,

The following code says that `OT_RADIO_CAPS_TRANSMIT_RETRIES` implies `OT_RADIO_CAPS_CSMA_BACKOFF`:

https://github.com/openthread/openthread/blob/42c46368f191aae9637782943e72c52c4b11824b/src/core/mac/sub_mac.hpp#L434-L441

Shouldn't `OT_RADIO_CAPS_TRANSMIT_RETRIES` also imply `OT_RADIO_CAPS_ACK_TIMEOUT`, given that `OT_RADIO_CAPS_TRANSMIT_RETRIES` means that the radio performs the whole CSMA=>TX=>wait-for-ACK=>Retry-on-failure mechanism automatically?

Thanks,
Diego.

**Comment by jwhui** [comment]
@dismirlian, yes `OT_RADIO_CAPS_TRANSMIT_RETRIES` implies `OT_RADIO_CAPS_ACK_TIMEOUT`. However, `OT_RADIO_CAPS_ACK_TIMEOUT` does not imply `OT_RADIO_CAPS_TRANSMIT_RETRIES`.

At the same time, it is valid for a radio to support `OT_RADIO_CAPS_CSMA_BACKOFF` but not `OT_RADIO_CAPS_CSMA_BACKOFF`.

**Comment by jwhui** [comment]
@dismirlian, do you have further questions on this?

**Comment by dismirlian** [comment]
Hi @jwhui, no, it's clear, thanks!
