### ISSUE TITLE
[travis] Is it possible to use multiple jobs to run toranj tests?

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3719]
**Is your feature request related to a problem? Please describe.**
From `tests/toranj/start.sh`, tests are run one by one. This could use a lot of time. I hope we can use multiple jobs to run these tests.

**Describe the solution you'd like**
For each job, create a net namespace for it so that multiple wpantund can run on a single host. And we can try out how many number of jobs saves most time.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jwhui** [comment]
Closing for now as the transition to GitHub Actions has reduced the severity of this.
