### ISSUE TITLE
[nrf52840] otPlatRadioTransmit() returns errors not defined in API

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3726]
**Describe the bug**
OpenThread only allows returning `OT_ERROR_INVALID_STATE`, but OT_ERROR_FAILED is returned.

https://github.com/openthread/openthread/blob/master/include/openthread/platform/radio.h#L516
https://github.com/openthread/openthread/blob/master/examples/platforms/nrf52840/radio.c#L352

**Comment by bukepo** [comment]
Thoughts?

**Comment by LuDuda** [comment]
Hello @bukepo, sorry, we are busy with release this week, will start working on that next week. But because higher layer asserts on any error, we need to figure out how to handle error internally.
