### ISSUE TITLE
[dtls] on-mesh commissioner collapses if multiple dtls handshake with joiners

### ISSUE THREAD

**Issue by hjian2017** [openthread/openthread#3754]
If you use a joiner to repeatedly handshake with the on-mesh commissioner, join the thread network. When such a process is executed more than 15 times, it will cause a memory problem with the on-mesh commissioner and collapse.

**Comment by sravanti298** [comment]
Trying to reproduce this issue in POSIX platform but, didn't find any memory problem.
When the joiner is successfully completed the commissioning process, it's entry is removing after several seconds.
Could you please provide some other details like which platform you have used?

**Comment by jwhui** [comment]
@sravanti298, I believe @hjian2017 was using the nRF52840 SoC. That said, I'm not sure anyone has reproduced this recently. I will close this issue. We can reopen if it comes up again.
