### ISSUE TITLE
Allow nodes to assume the parent’s Thread operational parameters on attach

### ISSUE THREAD

**Issue by jaylogue** [openthread/openthread#3766]
Add an option to OpenThread such that, when a node attaches to a network, it always accepts the active operational dataset from the parent, even if the parent’s active timestamp is less than or equal to its own.

This supports OOB commissioning scenarios where commissioning is implemented by storing an incomplete operational dataset in the joining node (via the otSetActiveDataset() function).  With this change, a new node will correctly assume the operational parameters of its parent node upon attach, even if the timestamp of its dataset (typically 0) matches that of the parent’s network.

One possible way to add this functionality without requiring a new API would be to allow the active operation dataset to be set without an active timestamp.  This could serve as a signal that  the node’s operational dataset should always considered to be of lower priority than the parent’s.

**Comment by jwhui** [comment]
Submitted #3773 that implements proposal above.
