### ISSUE TITLE
Don't add a new address for a new on-mesh prefix if we already have one

### ISSUE THREAD

**Issue by darconeous** [openthread/openthread#381]
Currently, adding an on-mesh prefix always seems to add a new address to the address list, even if there is already an address in the list with that prefix.

When we add a on-mesh prefix, OpenThread should first check the address list to see if we already have an address for that prefix. If we do, we shouldn't create a new address.

**Comment by jwhui** [comment]
The `mSlaac` field in `otBorderRouterConfig` gives control over whether or not Thread devices should locally autoconfigure an address from the associated IPv6 prefix.  Currently, OpenThread will always autoconfigure an address if the `mSlaac` flag is set.

Question: Should OpenThread make the application/client responsible for configuring IPv6 addresses for prefixes other than the Mesh Local prefix?  The advantage of this approach is that the application/client is responsible for determining what IPv6 prefixes it should configure addresses for.
