### ISSUE TITLE
[nrf52xx] set acknowledged with frame pending flag

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3826]
**Is your feature request related to a problem? Please describe.**
Needs set acked frame pending flag in radio driver

**Describe the solution you'd like**
Implement in radio Nordic SDK.

**Describe alternatives you've considered**
None

**Additional context**
See more in #3785

**Comment by LuDuda** [comment]
Hello @bukepo, it seems that we have sufficient support in our current radio driver for this feature.

We will send PR soon after adding some on-hardware tests, but can you please test if this [commit](https://github.com/LuDuda/openthread/commit/b20b1cd2ac7b140dad433591f59f79cd3641812e) resolves a problem that you found in #3785?
