### ISSUE TITLE
Reference operator in `network_time.h` header file

### ISSUE THREAD

**Issue by szymonnnm** [openthread/openthread#3832]
**Describe the bug**
I'm not sure wether it's desired, but it looks like in the `network_time.h` a reference operator has sneaked in:
```c
otNetworkTimeStatus otNetworkTimeGet(otInstance *aInstance, uint64_t &aNetworkTime);
```
This results in a build error when trying to include this file from some other `.c` file.

**To Reproduce**
Information to reproduce the behavior, including:
1. Git commit id: 0208d10563aa21c518092985c78ecf9cd223ab74
2. IEEE 802.15.4 hardware platform: nRF52840
3. Build steps: 
For the purposes of this example, I simply added `#include <openthread/network_time.h>
` to the `examples/apps/cli/main.c`. Then I executed
```
./bootstrap
make -f ./examples/Makefile-nrf52840
```
4. Network topology - not relevant I think

**Expected behavior**
I would like to use network time synchronization functions from OT API in the `.c` source files. 

**Console/log output**
```
In file included from openthread/examples/../examples/apps/cli/main.c:37:0:
openthread/examples/../include/openthread/network_time.h:87:70: error: expected ';', ',' or ')' before '&' token
 otNetworkTimeStatus otNetworkTimeGet(otInstance *aInstance, uint64_t &aNetworkTime);
                                                                      ^
In file included from openthread/examples/../examples/apps/cli/main.c:37:0:
openthread/examples/../include/openthread/network_time.h:87:70: error: expected ';', ',' or ')' before '&' token
 otNetworkTimeStatus otNetworkTimeGet(otInstance *aInstance, uint64_t &aNetworkTime);
```

**Comment by jwhui** [comment]
@szymonnnm, thank you for raising this issue. I just submitted #3833. Please review.
