### ISSUE TITLE
OT does NOT work properly since 56fa9ac9cdb612895a524f00251135781603d90a

### ISSUE THREAD

**Issue by FiveDimensions** [openthread/openthread#3859]
When doing the certification test on latest code(eb46303ff8318a76d5a9012c389d8b25667c68b8), found OT (on cc2538) does not work, no packet send&recv. After binary searches on OT commit from last success test, locate the issue since 56fa9ac9cdb612895a524f00251135781603d90a

**Comment by KaSroka** [comment]
Please check if #3861 fixed the problem.

**Comment by bukepo** [comment]
@Irving-cl
