### ISSUE TITLE
send sample message to child from Leader/Router

### ISSUE THREAD

**Issue by Praveen-Kumar-K** [openthread/openthread#386]
Hi,
I want to send/receive message to Child from Leader/router, can any one help me in this regard.
here is My Working set-up,
by cli application, configured 1-Leader, 1-Router, 1-Child, where i am able to work with commands listed in CLI- application. Now i want to send sample Hi message to Child to Leader (How can child receive send by leader/Router or How can Leader/Router send message to Child). How i can integrate messages with leader or Child.

Thanks,
Praveen

**Comment by jwhui** [comment]
You can use OpenThread's [UDP APIs](https://openthread.github.io/openthread/d2/d11/group__udp.html) for sending/receiving UDP messages.

BTW, GitHub Issues are generally used for bugs and feature requests.  We prefer the [openthread-users](https://groups.google.com/forum/#!forum/openthread-users) mailing list for general questions.
