### ISSUE TITLE
create a CI check with MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED=1

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#3875]
**Is your feature request related to a problem? Please describe.**
Missing check with MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED=1

**Describe the solution you'd like**
Add a check with MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED=1

**Describe alternatives you've considered**
None

**Additional context**
#3873

**Comment by Moandor-y** [comment]
Fixed by https://github.com/openthread/openthread/pull/4946.
