### ISSUE TITLE
[tests] change string format in travis test scripts

### ISSUE THREAD

**Issue by Irving-cl** [openthread/openthread#3924]
**Make the usage of string concatenation consistent**
Currently at somewhere of our test script, for example, https://github.com/openthread/openthread/blob/master/tests/scripts/thread-cert/node.py#L683, the string format is as: 
`cmd = 'commissioner panid ' + str(panid) + ' ' + str(mask) + ' ' + ipaddr`
we should be consistent and use format at such places, like https://github.com/openthread/openthread/blob/master/tests/scripts/thread-cert/node.py#L738:
`cmd = 'routerselectionjitter %d' % jitter`

**Comment by Irving-cl** [comment]
@bukepo

**Comment by jwhui** [comment]
Resolved by #3929.
