### ISSUE TITLE
nrf52840 radio not working on v0.9.3

### ISSUE THREAD

**Issue by gjc13** [openthread/openthread#3934]
**Describe the bug**
Cannot use any radio functionality on nrf52840 v0.9.3 DK.

**To Reproduce**
Commit: 1b37f64ac3222d9b3c7c246416e25cf996787985
Build command:
```
make -f examples/Makefile-nrf52840
```
Flash the ot-cli-ftd binary into nrf52840 v0.9.3 DK.
Run `scan` on command line.

**Expected behavior**
A list of networks found.

**Console/log output**
No network found and no log on radio inputs/outputs.

**Additional context**
May be caused by recent changes on Nordic radio driver.

**Comment by gjc13** [comment]
@LuDuda friendly reminder

**Comment by LuDuda** [comment]
Hello, @gjc13 we will take a look at this ASAP, however, note that this is engineering version of the silicon. Have you checked the production-ready silicon e.g. on PCA10056 v1.0.0 DK?

**Comment by gjc13** [comment]
It works on v1.0.0 dongle. I don't have a v1.0 DK at my hand.

**Comment by robertcragie** [comment]
I get the same problem on 0.9.0 and 0.9.2 boards using nRF52840 Q1AA:
```
> ipaddr
Done
> 
```
When I run `scan` I see no beacon request.

**Comment by bukepo** [comment]
How about we revert v1.4.0 first? @LuDuda All our dev boards don't work now.

**Comment by krlo** [comment]
nRF52840 Engineering A chip support is end of life.  Nordic has supported this Engineering version of silicon up to, and beyond, the previously communicated period, to support prototype builds with nRF52840.  In [this section](https://infocenter.nordicsemi.com/topic/comp_matrix_nrf52840/COMP/nrf52840/nrf52840_comp_matrix.html) you can find compatibility matrix between the nRF52840 IC revisions and development kits.
