### ISSUE TITLE
Thread 1.2

### ISSUE THREAD

**Issue by seriph** [openthread/openthread#3946]
Is there an estimated eta on the new features from Thread 1.2 being implemented into OpenThread?

**Comment by jwhui** [comment]
@seriph, with the Thread 1.2.0 specification now in final status, we will start contributing new Thread 1.2.0 code in the coming weeks. Stay tuned!

**Comment by Ahmedkalnaggar** [comment]
@jwhui Is there any page or issue to track the status of contributing Thread 1.2 code ?
Features that has been added, other features that still under development  .. etc ?

**Comment by vervaekejonathan** [comment]
Any news on this?

**Comment by jwhui** [comment]
We are starting to introduce Thread 1.2.0 features. See #4327 for status.
