### ISSUE TITLE
[build] new policy proposal for configure/build options

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#3964]
**Is your feature request related to a problem? Please describe.**
The policy for what options are included in `configure.ac` vs. `src/core/openthread-core-default-config.h` is not clear. Some options simply affect C preprocessor defines while others affect what artifacts to build, linker options, etc.

**Describe the solution you'd like**
- `configure.ac` only contains build options that cannot be addressed by a standard C source file.
- All build options that can be addressed by a standard C source file shall be placed in one (i.e. `src/core/openthread-core-default-config.h`)
- As a further optimization, we could consider breaking `src/core/openthread-core-default-config.h` into multiple files that separate build options by features or components. For example, a separate file for MAC-specific options.

Moving build options into standard C source files whenever possible has the benefit of allowing other build systems to utilize those files and any checking logic that may exist (e.g. `src/core/openthread-core-config-check.h`).

Thoughts?

**Comment by bukepo** [comment]
related to #3898 shall we unify `OPENTHREAD_ENABLE_*` and `OPENTHREAD_CONF_ENABLE_*`?
