### ISSUE TITLE
Configurable Number of Supported Children

### ISSUE THREAD

**Issue by jsnayak** [openthread/openthread#3979]
When trying to simulate a POSIX network to hold the upper limit of child nodes, I hit an upper limit of 64 after which I observed an assert as below:
ot-cli-ftd: /home/work/src/openthread_190702/examples/../src/core/common/message.cpp:667: bool ot::Message::GetChildMask(uint8_t) const: Assertion `aChildIndex < sizeof(mBuffer.mHead.mInfo.mChildMask) * 8' failed.

It was clarified that currently the channel mask supports up to 64 children. To increase the limit, it was suggested that I should try to change 8 to a larger number in 
`https://github.com/openthread/openthread/blob/master/src/core/common/message.hpp#L96`

As per the specification the number of the supported end devices should be be up to 511. In order to support this, can the number of supported children be made configurable. 
[Original Discussion](https://groups.google.com/forum/#!topic/openthread-users/wpUPlhCEYlI)

**Comment by jwhui** [comment]
@jsnayak @seungigi, just submitted #4118. Please review.
