### ISSUE TITLE
Random Number Generator Correctness

### ISSUE THREAD

**Issue by jsnayak** [openthread/openthread#3985]
I see that Openthread is now using a pseudo-random generator RandomManager::NonCryptoPrng::GetNext()
The random numbers generated using this (on the CC2538 platform) were tested using the [NIST Statistical Test Suite.](https://csrc.nist.gov/publications/detail/sp/800-22/rev-1a/final) The results have been attached and indicate a rather large % of failure; [finalAnalysisReport.txt](https://github.com/openthread/openthread/files/3381593/finalAnalysisReport.txt) and [freq.txt](https://github.com/openthread/openthread/files/3381596/freq.txt)

Is there any particular reason why this pseudo-random number generator that is currently part of OT has been selected? Is there any particular test criteria that were checked when choosing it?

During our testing, the random generator in Openthread was replaced with the Linear Congruential Generator (LCG) [implementation](https://csrc.nist.gov/Projects/Random-Bit-Generation/Documentation-and-Software) that is part of the NIST Statistical Test Suite. The random numbers generated using the LCG gave a significantly better result set when tested with the NIST test suite. 

Can the LCG random number generator be considered for the stack? What are your test considerations for this?

**Comment by jwhui** [comment]
@jsnayak, thank you for submitting this issue.

Note that [`RandomManager::NonCryptoPrng::GetNext()`](https://github.com/openthread/openthread/blob/a938ee2845df49d6208e3b94a9070025920cc6b3/src/core/common/random_manager.cpp#L122) is not intended for cryptographic applications, as the name suggests. As a result, there was no intention for it to pass the test suite published in [SP 800-22 Rev. 1a](https://csrc.nist.gov/publications/detail/sp/800-22/rev-1a/final).

That said, new contributions are always welcome. If `RandomManager::NonCryptoPrng::GetNext()` can be enhanced while considering the tradeoffs between random number quality, code/memory complexity, etc, that would be interesting to review.
