### ISSUE TITLE
Converting/Clearing queued msgs for sleepy child on child device mode change 

### ISSUE THREAD

**Issue by abtink** [openthread/openthread#3988]
**Describe the bug**
We need to clear or convert the the queued messages (for indirect tx) to a sleepy child, when/if the child switches its device mode and becomes non-sleepy. I think with the current model, the messages would stay in the send queue. We need to also handle the case where we are in middle of an indirect tx of a longer message requiring fragmentation (we need to ensure the indirect msg pointer is cleared in the child entry when it switched from sleepy to non-sleepy).

We can face similar situation if we have messages in the send queue for a currently ED (non-sleepy) which then switches to be an SED (the already queued msg will go out as direct tx and fail and we may kick the child out of table due to those failures).

**Comment by jwhui** [comment]
Resolved by #4001.
