### ISSUE TITLE
Do we need to implement CRC/Checksum ourselves?

### ISSUE THREAD

**Issue by OscarVanL** [openthread/openthread#4009]
Hi,

When implementing openthread, do we need to have CRC or similar checksums included in our UDP packets if we want to ensure message integrity? I'm using OpenThread for a IoT sensor network, so ensuring that the values reported for the sensors are valid and error-free is desirable.

I see on the technical overview that Thread uses CoAP, which already implements ACKs and resends, but I see no details about whether CoAP or thread implements CRC checking at the application layer.

Should we include CRCs in our UDP packets from the nodes to the border router?

**Comment by jwhui** [comment]
@OscarVanL, it depends on what APIs you are using to send messages via OpenThread.

If you are using OpenThread's [CoAP](https://openthread.io/reference/group/api-coap) or [UDP](https://openthread.io/reference/group/api-udp) APIs, OpenThread will handle the UDP checksum calculation. However, if you are using OpenThread's [otIp6Send](https://openthread.io/reference/group/api-ip6#otip6send) API to send raw IPv6 datagrams, then the caller needs to provide a complete IPv6 datagram, including the UDP checksum.

**Comment by OscarVanL** [comment]
Thank you!
