### ISSUE TITLE
How exactly is the SAMR21 only partially supported?

### ISSUE THREAD

**Issue by OscarVanL** [openthread/openthread#4019]
Hi,

I want to use OpenThread on a SAMR21, however, see it is described as 'partially supported', but I can't find any more detail on what features are/are not implemented. Do you know what the limitations may be for the SAMR21? 
So far I've experienced errors related to SSL on the device. Is this working?

Thanks

**Comment by jwhui** [comment]
@OscarVanL, "limited support" indicates that the example platform drivers are contributed by the community and not actively maintained by any particular person or organization.

When you say "SSL", are you referring to Thread Commissioning and DTLS? If so, what kind of errors are you seeing?

Note: I do not have any SAMR21 hardware and do not have any first-hand experience with OpenThread on the SAMR21.
