### ISSUE TITLE
arm-gcc-8 takes much more time to run tests

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4053]
**Describe the bug**
In Travis-CI, it takes more than double time to finish arm-gcc-8 test. Not sure if anyone knows to enhancement that.
see: https://travis-ci.org/openthread/openthread/builds/566705354

**Comment by jwhui** [comment]
It seems other users of arm-gcc-8 are reporting similar concerns in the [Arm Compilers Forum](https://community.arm.com/developer/tools-software/tools/f/arm-compilers-forum/13459/gcc-g-version-8-very-slow-to-compile/36774).

**Comment by bukepo** [comment]
Yes, please feel free to close this issue.
