### ISSUE TITLE
Provide a script to replace all outdated definitions

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4063]
**Is your feature request related to a problem? Please describe.**
A lot of definitions are changed recently. We need to provide a maintained script to replace outdated definitions in a project.

**Describe the solution you'd like**
Provide a script to scan all Makefiles and source files, and replace them all.

**Describe alternatives you've considered**
None.

**Additional context**
It seems some definitions are not just renamed, but also changed the usage. We may need to handle this situation too.

**Comment by jwhui** [comment]
#4080 was closed.
