### ISSUE TITLE
spinel: documentation issue with local routes property

### ISSUE THREAD

**Issue by turon** [openthread/openthread#407]
PROP_THREAD_LOCAL_ROUTES (route add/remove) looks to have the same arguments as PROP_THREAD_ON_MESH_NETS (prefix add/remove), but the stable parameter should probably be               prf instead: Default Router Preference, which may be: 'high', 'med', or 'low'.

Also, for PROP_THREAD_ON_MESH_NETS, the stable flag should probably just be part of the general flags parameter and follow the Thread specification definition, otherwise the API has a  redundant and possibly conflicting way of accessing it.

```
D.4.12. PROP 91: PROP_THREAD_LOCAL_ROUTES

Type: Read-Write
Packed-Encoding: A(T(6CbC))
Data per item is:

6: IPv6 Prefix
C: Prefix length, in bits
b: Stable flag
C: Other flags
```

**Comment by turon** [comment]
per RQ: stable flag is broken out specifically because it is determined by the encapsulating TLV, not the flags.

Documentation should provide more detail or spec reference for the encoding of "Other flags".

**Comment by abtink** [comment]
PR https://github.com/openthread/openthread/pull/1886 addresses this issue.
