### ISSUE TITLE
Retain address cache entries across router link re-establishment

### ISSUE THREAD

**Issue by smides-nest** [openthread/openthread#4077]
**Is your feature request related to a problem? Please describe.**
Mesh-local packets are often dropped for extended periods of time after a router-to-router link goes away. Broadcast Address Queries are often delayed due to previously failed queries and backoff, even once a link is re-established. This scenario is somewhat common in the presence of extended strong interference (enough to result in the link going down).

**Describe the solution you'd like**
Instead of deleting address cache entries associated with a given RLOC16 when the link goes away, mark them as invalid. When a new link is established, look through the cache to see if there are any invalid cache entries associated with the just-connected RLOC16. If so, mark them as active, again. In most scenarios, this will drastically reduce the duration of dropped packets on a temporary link outage.

All pending Address Queries associated with the "new" router's RLOC16 should also be canceled.

Note that there exists a possibility that a different router establishes a link using the previously-used RLOC16. This would have to occur after the RLOC16-to-EUI64 entry timed out, in which case there would be a period of time that the re-attached node is an end device (if it has no children).

**Describe alternatives you've considered**
One alternative is to reset the backoff / delay timer for any/all pending Address Queries when a new router link is established.

**Additional context**
The aforementioned long intervals of dropped packets (no route to host) were observed in a two router setup, sending ICMPv6 Echo packets between the two using mesh-local addresses.

**Comment by jwhui** [comment]
This is addressed by #4753, by not removing the router/neighbor entry when a link failure occurs.
