### ISSUE TITLE
[api] unify enable/disable API style

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4159]
**Is your feature request related to a problem? Please describe.**
Currently we have two styles for enable/disable. Most uses two separate APIs. But `otLinkRawSetEnable(bool)` and `otLinkRawSrcMatchEnable(bool)` accepts a parameter to disable the functionality, shall we unify the style by adding two disable APIs?

**Comment by jwhui** [comment]
The following APIs seems to follow the `SetEnabled(boo)` model:
- otChannelManagerSetAutoChannelSelectionEnabled
- otChannelMonitorSetEnabled
- otIp6SetEnabled
- otIp6SetMulticastPromiscuousEnabled
- otIp6SetReceiveFilterEnabled
- otIp6SetSlaacEnabled
- otLinkSetEnabled
- otLinkRawSetEnable
- otLinkRawSetPromiscuous
- otThreadSetEnabled
- otThreadSetRouterRoleEnabled
- otPlatRadioEnableSrcMatch
- otPlatRadioSetPromiscuous

**Comment by bukepo** [comment]
Thanks! Which style is recommended for new APIs?

**Comment by jwhui** [comment]
I think the preference has been the `SetEnabled(bool)` style, rather than two separate APIs.

**Comment by bukepo** [comment]
Thank you for the confirmation!
