### ISSUE TITLE
Do we allow attached node operate in promiscuous mode?

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4161]
**Is your feature request related to a problem? Please describe.**
From https://github.com/openthread/openthread/blob/master/src/core/api/link_api.cpp#L300, we don't allow.
From https://github.com/openthread/openthread/blob/master/src/ncp/ncp_base.cpp#L1356, no check for this at all.

**Describe the solution you'd like**
I think it makes sense to support this, so that an attached node can still act as sniffer.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bukepo** [comment]
@smides-nest

**Comment by jwhui** [comment]
FWIW, many IEEE 802.15.4 radios do not support both promiscuous mode and auto generation of immediate acks.

**Comment by simonlingoogle** [comment]
> FWIW, many IEEE 802.15.4 radios do not support both promiscuous mode and auto generation of immediate acks.

We actually had a plan to implement this in the future to support functional Thread stack and sniffing at the same time.

**Comment by jwhui** [comment]
> > FWIW, many IEEE 802.15.4 radios do not support both promiscuous mode and auto generation of immediate acks.
> 
> We actually had a plan to implement this in the future to support functional Thread stack and sniffing at the same time.

@simonlingoogle , what was the plan to support radios that do not support promiscuous mode and auto-generation of immediate acks at the same time?

**Comment by simonlingoogle** [comment]
> @simonlingoogle , what was the plan to support radios that do not support promiscuous mode and auto-generation of immediate acks at the same time?

It was actually less of a plan, but more of a thought or idea. 
The intention was to have similar user experience to other networks (e.g. Ethernet) in which developers can use `wireshark` to capture all packets while the network stack is still working. We expected it to be helpful for OT developers to diagnose issues on OTBR.

**Comment by jwhui** [comment]
> It was actually less of a plan, but more of a thought or idea.
> The intention was to have similar user experience to other networks (e.g. Ethernet) in which developers can use `wireshark` to capture all packets in promiscuous mode while the network stack is still working. We expected it to be helpful for OT developers to diagnose issues on OTBR.

@simonlingoogle , I agree it can be useful. However, as mentioned previously, many existing radios do not support promiscuous mode and auto-generation of immediate acks at the same time. It may be that newer radios do support this, however.
