### ISSUE TITLE
Adding support for peripherals like I2C on EFR32MG21 Platform

### ISSUE THREAD

**Issue by binartech** [openthread/openthread#4165]
Is there any instructions on how to add the required files to be able to use GPIO I2C or other peripherals.
I know we have to modify Makefile. But would like to have an instruction on what Makefile to modify and all the required include folders and files.

platform: efr32

**Comment by nigelg-silabs** [comment]
The easiest way to obtain the files is to generate the project within simplicity with the desired peripherals enabled. This will also generate the correct hardware configuration for the project.
Currently we haven't produced any instructions on how to modify the OT makefile to add peripherals
