### ISSUE TITLE
Support for 868MHz band on EFR32MGx platform

### ISSUE THREAD

**Issue by NikhilSarnaik** [openthread/openthread#4172]
I understand that there is support for EFR32MGx to run OT on 915MHz. Are there any plans to add support for EFR32 to run on 868MHz band? Is there a porting guide or some help available to add the support for 868MHz?

**Comment by jwhui** [comment]
@NikhilSarnaik, I am not aware of any current plans to add support for 868 MHz band. To add support for a different band, you'll need to:

1. Add support within OpenThread core for a new IEEE 802.15.4 Channel Page (search for `OPENTHREAD_CONFIG_RADIO_915MHZ_OQPSK_SUPPORT` to see what was done for 915 MHz band).

2. Add support within radio driver for new band. On the EFR32, the Simplicity Studio Radio Configurator for RAIL generates the radio configuration for a given channel plan. See the autogenerated configuration in [third_party/silabs](https://github.com/openthread/openthread/tree/master/third_party/silabs).

Hope that helps.
