### ISSUE TITLE
connecting to more than one thread network at the same time.

### ISSUE THREAD

**Issue by binartech** [openthread/openthread#4203]
Does any one knows if its possible to join one network and than move the node to another network that uses same masterkey and same PANID and connecting to that network without having to rejoin in that network ?

Just to be more clear: I have a threadnetwork in my house and another at the office. I want to move a device from my house to the office without having to rejoin to that network. Both networks has same panid, both commissioners have same masterkey.

**Comment by jwhui** [comment]
Are there other Thread Network parameters that differ between the home and office networks? If the Thread network parameters are the same, then there should be no issue. In fact, from a Thread network perspective, the home and office are simply two different partitions of the same Thread network.

**Comment by binartech** [comment]
@jwhui 
I can build both networks with same `parameters as those networks do not see each other. I'll test and see how it works thanks.
