### ISSUE TITLE
Should we define utils configuration macros in a special file ?

### ISSUE THREAD

**Issue by zhanglongxia** [openthread/openthread#4223]
**Is your feature request related to a problem? Please describe.**

There are several common code files under the `examples/platforms/utils/` directory. The codes in these files are configurable. Currently, we define the utils configuration macros in the file "`openthread-core-xxxx-config.h`". However, the these utils configuration macros don't belong to the **openthread core**. It is better to define utils configuration macros in other place.

**Describe the solution you'd like**

Add a new configuration file "platform-utils-config.h" to configure the examples/platforms/utils/ modules.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jwhui** [comment]
#4333 covers this issue more generally.
