### ISSUE TITLE
How to change USB ATTRS{product}?

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/openthread#4259]
I want to assign NCP `/dev/ttyNCP` and CLI `/dev/ttyCLI` port. I tried this by changing udev.rules. Sometimes usb info command returns **ATTRS{product}=="nRF52 USB Product"** and sometimes **ATTRS{product}=="nRF52840 OpenThread Device"**.

Is there any way we can fix these values in NCP and CLI firmware itself?

**Comment by jwhui** [comment]
GitHub Code Search:

- https://github.com/openthread/openthread/search?q=%22nRF52+USB%22&unscoped_q=%22nRF52+USB%22

- https://github.com/openthread/openthread/search?q=%22nRF52840+OpenThread%22&unscoped_q=%22nRF52840+OpenThread%22

Hope that helps.
