### ISSUE TITLE
[radio] Variable set but never used.

### ISSUE THREAD

**Issue by piotrkoziar** [openthread/openthread#4347]
**Describe the bug**
After this 82c13c25a40f3637da39b7332a203a69002d9df8 commit compiler warns about sExtAddress variable (from openthread\examples\platforms\nrf528xx\src\radio.c) set but never used.

**To Reproduce**
1. OT with commit 82c13c25a40f3637da39b7332a203a69002d9df8
2. Build with OPENTHREAD_CONFIG_MAC_HEADER_IE_SUPPORT=0

**Expected behavior**
Compilation ends without the warning.

**Console/log output**
..\..\..\..\..\openthread\examples\platforms\nrf528xx\src\radio.c(88): warning:  #\550-D: variable "sExtAddress"  was set but never used

  static otExtAddress sExtAddress;

..\..\..\..\..\openthread\examples\platforms\nrf528xx\src\radio.c: 1 warning, 0 errors

**Additional context**
In otPlatRadioSetExtendedAddress() swapped Extended Address is assigned to the sExtAddress, which is used in otMacFrameProcessTransmitAesCcm() to generate nonce for AES CCM computation. However otMacFrameProcessTransmitAesCcm() is included in preprocessor output only if OPENTHREAD_CONFIG_MAC_HEADER_IE_SUPPORT=1 is defined.

sExtAddress could be inside #if block or OT_UNUSED_VARIABLE macro.

**Comment by jwhui** [comment]
Resolved by #4361.
