### ISSUE TITLE
[code] create src/utils for common utilities

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4413]
**Is your feature request related to a problem? Please describe.**
create a folder `src/utils` for utilities that can be used by multiple applications. I think spinel, hdlc, the upcoming performance test utilities are examples of this requirement.

**Additional context**
#4117
https://github.com/openthread/openthread/pull/3975#discussion_r301717735

**Comment by bukepo** [comment]
@jwhui  @abtink @simonlingoogle @zhanglongxia Thoughts?

**Comment by abtink** [comment]
Sounds good to me.

**Comment by jwhui** [comment]
SGTM

**Comment by zhanglongxia** [comment]
SGTM
