### ISSUE TITLE
Update silabs platform support for gecko sdk v2.7

### ISSUE THREAD

**Issue by allexoll** [openthread/openthread#4415]
With the Dec 13 2019 gecko SDK update from Silicon Labs (2.6->2.7) the platform examples are no longer working. 
`v2.6`to `v2.7` in the makefiles fixes most of it, but the RTC driver used is now depreciated.

* temp fix: `#define SL_SUPRESS_DEPRECATION_WARNINGS_SDK_2_7` in `v2.7/platform/emdrv/rtcdrv/inc/rtcdriver.h`
* fix should use sleeptimer instead

**Comment by nigelg-silabs** [comment]
We are currently porting our examples to SDK2.7 to encompass the improvements made in this SDK release. We expect this to be available in the new year

**Comment by jwhui** [comment]
Resolved by #4447
