### ISSUE TITLE
Service ALOC not working properly when Server is a Thread Child

### ISSUE THREAD

**Issue by mwilniewiec** [openthread/openthread#4424]
Hi, we are using Service ALOC in our project to communicate Nodes -> Border Router. 
An NCP registers as a Server in a leader, getting ALOC etc. All nodes receive that ALOC in thread network data and communicates with the NCP over ALOC to get to the Border Router.

This solution looks very nice, no extra effort needed, supports multiple border routers in the same network, thread network forwarding traffic to the nearest NCP etc.

Recently we discovered that when our NCP becomes a child (specially in bigger networks) Service ALOCs stops working and we see that nodes are not talking to our NCP.

Initial code investigation lead us think that Thread Child is not synchronizing it's network data with the leader. Are there any reasons that this feature shouldn't work fine for a Child?

**Comment by jwhui** [comment]
@mwilniewiec, thank you for identifying this issue! I have confirmed that the current implementation does not trigger network data registration when in the child role. I have submitted #4425 to address this issue. Please review.
