### ISSUE TITLE
Non-compiling code when trying to use Service without Border Router

### ISSUE THREAD

**Issue by Nopik** [openthread/openthread#4454]
When using Service API in client (i.e. having `OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE` on node, without `OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE` enabled) following code: https://github.com/openthread/openthread/blob/master/src/core/thread/network_data_local.cpp#L370-L375

is not compiling (`||` expects 2 arguments, but get 1).

**Comment by dismirlian** [comment]
Hi, please see PR #4443

**Comment by Nopik** [comment]
Thanks. The change in #4443 seems to do the trick, thanks!

**Comment by jwhui** [comment]
I think #4443 needs an update - see https://github.com/openthread/openthread/pull/4443#discussion_r363848675.

**Comment by dismirlian** [comment]
I'm sorry, I thought it was the usual Travis timeouts...

**Comment by jwhui** [comment]
Resolved by #4443
