### ISSUE TITLE
Invalid #define name

### ISSUE THREAD

**Issue by Nopik** [openthread/openthread#4455]
Instead of `OPENTHREAD_CONFIG_NCP_SPI_ENABLENEL_ENCRYPTER` there should be `OPENTHREAD_CONFIG_NCP_ENABLE_SPINEL_ENCRYPTER`:
- The extra `NEL` seems like a typo.
- Spinel encrypter is not related to NCP using SPI or not, it can encrypt whole spinel stream, regardless of transport.

**Comment by Nopik** [comment]
Ah, I've just realized that `SPINEL` was just split into `SPI` and `NEL`, with `ENABLE` inside ;)

**Comment by dismirlian** [comment]
Hi, please see #4300

**Comment by Nopik** [comment]
#4300 looks ok for me (at least in the spinel define area). Hopefully it will be merged soon!

**Comment by jwhui** [comment]
Resolved by #4300
