### ISSUE TITLE
MAC counters doesn't count out of band tx frames

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4459]
**Is your feature request related to a problem? Please describe.**
tx out of band frames are also 15.4 frames, no matter how it is secured, the frame type can be retrieved. Shall we count these frames?

**Describe the solution you'd like**
count frames according to the frame type instead of tx operation.

**Describe alternatives you've considered**
count these frames as other frames because there's other rx frame counter.

**Additional context**
This is helpful to analyze power consumption.

**Comment by bukepo** [comment]
@abtink @jwhui do you think out of bound frames should also be counted?

**Comment by abtink** [comment]
Sounds reasonable to me.

**Comment by jwhui** [comment]
Can you define "out-of-bound"? Do you mean "out-of-band"? If the latter, I agree that we should account for them.

**Comment by bukepo** [comment]
sorry for the typo. Yes, it's out of band.

**Comment by FiveDimensions** [comment]
add tx oob counter in PR #4936

**Comment by librasungirl** [comment]
> Is your feature request related to a problem? Please describe.
> tx out of band frames are also 15.4 frames, no matter how it is secured, the frame type can be retrieved. Shall we count these frames?
> 

> Describe the solution you'd like
> count frames according to the frame type instead of tx operation.

The request requires counting OoB frame.
A bit ambiguity on the suggested solution - is it to count Oob by frame type? or redesign the mac counter to count all mac frame by frame type?
@bukepo

**Comment by bukepo** [comment]
My original proposal was count by frame type, i.e. data frame, mac data request frame, etc.
@abtink Did we agree on this?

**Comment by abtink** [comment]
@bukepo , either way (counting all as `mTxOther` or parse and consider per type) sounds ok to me
My suggestion https://github.com/openthread/openthread/pull/4936#discussion_r423917442 is mainly to keep the code simple (since we may remove the whole OOB feature later on).

**Comment by bukepo** [comment]
I also OK to count as mTxOther. Thanks
