### ISSUE TITLE
[coap] Make retransmission parameters dynamically configurable

### ISSUE THREAD

**Issue by dismirlian** [openthread/openthread#4470]
**Is your feature request related to a problem? Please describe.**
For some use cases, the default CoAP Transmission Parameters used by OpenThread (the same specified by RFC7252) are not adequate. Furthermore, for some applications, the Transmission Parameters should be configurable per-message, to accommodate different requirements by different parts of the application.

**Describe the solution you'd like**
Make the Transmission Parameters configurable per-message.

**Describe alternatives you've considered**
Extend the CoAP core and API to allow configurable per-message parameters:
- ACK_TIMEOUT
- ACK_RANDOM_FACTOR
- MAX_RETRANSMIT

The current behavior should be preserved for applications that don't need to specify these parameters dynamically.

**Additional context**
See #4434.

I can start looking into this. @sjlongland, @jwhui, what do you think?

Diego.

**Comment by sjlongland** [comment]
My thinking is, you're not necessarily going to have every message with different timing parameters, in fact I think the vast majority of users of the CoAP library will be using the defaults (from RFC7252).

I think it fair to assume that the application developer would define a few parameters as a `const struct` and pass that in somehow.  Thus we could have a "default" one exported by OpenThread, and if someone wants something different, they declare it and tell the CoAP library what they need for that request.  My thoughts were either an extra parameter to `otCoapSendRequest`, which could be `NULL` to accept defaults.

There's a few derived constants, two approaches could be used here:
- define variables to hold the computed values of these derived constants (chews up maybe a dozen bytes or two per request "slot")
- compute the values on demand (a few more processor cycles consumed… the calculations are not particularly strenuous)

**Comment by dismirlian** [comment]
> My thinking is, you're not necessarily going to have every message with different timing parameters, in fact I think the vast majority of users of the CoAP library will be using the defaults (from RFC7252).
> 
> I think it fair to assume that the application developer would define a few parameters as a `const struct` and pass that in somehow. Thus we could have a "default" one exported by OpenThread, and if someone wants something different, they declare it and tell the CoAP library what they need for that request. My thoughts were either an extra parameter to `otCoapSendRequest`, which could be `NULL` to accept defaults.
> 
Exactly my thoughts


> There's a few derived constants, two approaches could be used here:
> 
> * define variables to hold the computed values of these derived constants (chews up maybe a dozen bytes or two per request "slot")
> * compute the values on demand (a few more processor cycles consumed… the calculations are not particularly strenuous)
Browsing the code, it seems that there are very few calculations to be done, and (maybe almost) all during creation of the new message. I'm thinking that with a few minor modifications, the CoapMetadata class can hold the required status in the existing member variables:
- mRetransmissionTimeout (can be calculated on "transaction" creation from ACK_TIMEOUT and ACK_RANDOM_FACTOR)
- mRetransmissionCount (we could change this to mRemainingRetransmissions to avoid also saving MAX_RETRANSMIT, and compare with 0).

**Comment by jwhui** [comment]
@dismirlian @sjlongland, thank you for looking into this enhancement. The proposed path forward seems reasonable to me.

**Comment by jwhui** [comment]
Resolved by #4481
