### ISSUE TITLE
When does different device state mean in mtd's?

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/openthread#4478]
SED sends one data point every 30 seconds if it is connected and increments the counter, but if it is detached or disabled, it does nothing.
Polling period is of 15 seconds, and child timeout is 30 seconds.
I am facing the issue that SED don't send data for sometime but when it again starts sending data , its counter is continuous.
So what does it mean to be in connected state for a SED?

**Comment by jwhui** [comment]
To attach to a parent, a SED needs to perform an MLE exchange to establish a parent-child relationship. As part of that exchange, the child communicates a "child timeout" value that indicates to the parent how often the SED will check in with the parent. You can learn more about the MLE attach process at https://openthread.io/guides/thread-primer/network-discovery

When attached to a parent, the SED needs to periodically send IEEE 802.15.4 Data Request messages to reset the child timeout on the parent. If the parent does not receive an IEEE 802.15.4 Data Request message for a time duration longer than the child timeout, the parent will remove the SED from its child table.

A child detects connectivity to a parent using IEEE 802.15.4 Acknowledgments sent in response to its IEEE 802.15.4 Data Request messages. If the SED does not receive an Acknowledgment, it will try to retransmit the Data Request message. If no Acknowledgment after several consecutive attempts, the SED will move to the detached state and start looking for a new parent again.

Hope that helps.

**Comment by bhumikaajain** [comment]
@jwhui 
The explanation shared was also my understanding of connectivity, but my issue is SED's counter don't increase unless it is in connected state, but I don't received any data packets on server from SED's for around 2hr but still when I receive the next packet, the counter is continuous on next packet received. 
On the other hand if I power off Border router and FTD's and power on them after 2 hours, SED's resume sending data but counter is resumed from the last value when thread network was up.

So in first case when thread network was up (ftd, border router, ncp powered up), if last counter value received at 12:05 is 1188 and next data point is received at 15:00, then my counter value is 1538.
That shows my SED was connected throughout the time but it was packet loss. Also in the network there are 5 FTD's and 11 SED's, rest 10 SED's were sending data during this duration (without any loss).

In second case when I power off my FTD's and border router, if last data point received is at 12:05, with counter value 1188 and FTD's are powered off at this time, and powered on at 15:00, then when next data point is received its counter value is 1189, which should be as device went in detached state. All 11 SED's resume data with next counter value when FTD's are powered up.

**Comment by jwhui** [comment]
Can you provide more information about your setup, including:

- Git commit id
- Hardware platform
- Commands you used to build your image

One thing you could try is decreasing the polling period and/or increasing the child timeout period to reduce the chance of the parent losing a data request message from the SED.

Some other things you could do to investigate further:

- Inspect the child table on the FTDs to see if the parent believes that the child is still attached.
- Use a [sniffer](https://openthread.io/guides/ncp/sniffer) to capture transmissions to validate whether the child is actually sending data to the parent.
- Use ICMPv6 Echo Request/Reply between the SED and Parent to determine if the SED-Parent link is still working.

As mentioned in the [Child Supervision](https://openthread.io/guides/build/features/child-supervision) guide, the Thread Specification recommends that the SED receive something from its Parent periodically to validate the receive path. This could be application traffic, ICMPv6 Echo Responses, OpenThread's Child Supervision feature, etc.

**Comment by bhumikaajain** [comment]
Git commit is 
https://github.com/openthread/openthread/tree/704511c (with revert of 136a444)
Hardware Platform : nrf52840
I have built my image on  nRF5 SDK for Thread and Zigbee v2.0.0.

Also this issue is random, there is no specific pattern or it is not on any specific SED.

**Comment by bhumikaajain** [comment]
Any update on this what could be causing the issue.
Do you need any other info from my end?

**Comment by jwhui** [comment]
It is possible for the parent to have timed the child out without the child knowing. The only way for the child to check this is by receiving a data message from the parent. Have you tried one of the methods I suggested above?

At the same time, we could root cause this issue by investigating further. Have you tried any of the suggested investigations above?

**Comment by jwhui** [comment]
Closing stale issue.

**Comment by ksathara** [comment]
@bhumikaajain I am also seeing something similar in my system. Have you managed to solve this? 

Thanks,
Kaushalya
