### ISSUE TITLE
[cli] Site survey CLI command

### ISSUE THREAD

**Issue by cfaessler** [openthread/openthread#4512]
For a new home automation product line I am evaluating OpenThread technology. One of the key performance metrics for the evaluation is possible coverage with meshed devices. With the current solution it is hard to evaluate different scenarios in a semi-automated way.

**Solution**
Client side: Add a new CLI command which receives UDP broadcasts and replies to a configured server with link quality, rssi and node name values.
To send broadcasts and log received values I provide a python script (udp server). Mainly intended to run on the border router.

**Alternatives**
- Use ICMP messages received hook to send UDP message with metrics. Allows server to simple send pings
- Alternatively to the python script, one could implement a CLI udp server part
- Future idea could be to integrate this tool in the border router UI, which let's one simple do a node exploration / site survey

Happy to do the implementation and open a PR. But would like to get some thoughts from the community whether it will be something that is appreciated in the official repo

**Comment by cfaessler** [comment]
@jwhui does no labeling and reaction mean there's no interest on this?

**Comment by bukepo** [comment]
@cfaessler Thank you for proposing this feature. We have a new tool in https://github.com/openthread/openthread/pull/4117, which seems to be able to serve as a base of this feature. It's close for now, but we are going to re-open it later.

Could you please help review it and see if it's helpful to your use case?

**Comment by jwhui** [comment]
@cfaessler, any updates you can share?

**Comment by jwhui** [comment]
Closing stale issue.
