### ISSUE TITLE
[tests] thread_cert enhancements

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#4587]
This issue tracks the issues noticed in existing thread_cert to be enhanced

- [ ] mixed style of `cmd` variable and command string when `send_command()` (https://github.com/openthread/openthread/pull/4423#discussion_r382054336)

- [ ] inconsistent attach waiting time in existing tests (https://github.com/openthread/openthread/pull/4423#discussion_r381914918)

- [ ] unnecessary `if i == 0` check for _expect() if there is always return value for `get_xxx()` method (https://github.com/openthread/openthread/pull/4423#discussion_r382060673)

- [ ] add doc in one place (https://openthread.io/testing) regarding 
        a) run single thread_cert test locally
        b) introduce `inspector` which enables node interactive during test

**Comment by jwhui** [comment]
Closing stale issue.
