### ISSUE TITLE
dose this logic is correct in test\scripts\thread-cert\net_crypto.py?

### ISSUE THREAD

**Issue by zlu93311** [openthread/openthread#4668]
It looks not reasonable logic in follow method, when 'self_key_id_mod == 0', it will raise ValueError exception anyway.  

Should this logic be like following??
  if self.key_id_mode == 0:
  .
  .
  elif self.key_id_mode == 1:
  ....
  elif self.key_id_mode == 2:
  else:
  

================================================
@property
    def sequence_counter(self):
        """ Compute or extract sequence counter based on currently set Key Index Mode. """

        if self.key_id_mode == 0:
            key_source = self.key_id[:8]
            format = ">Q" if self._big_endian else "<Q"
        if self.key_id_mode == 1:**
            # Try to guess valid Key Sequence Counter based on Key Index. This
            # one should work for now.
            return self.key_index - 1
        elif self.key_id_mode == 2:
            # In this mode sequence counter is stored on the first four bytes
            # of Key ID.
            key_source = self.key_id[:4]
            format = ">I" if self._big_endian else "<I"
        else:
            raise ValueError("Unsupported Key Index Mode: {}".format(
                self.key_id_mode))

        return struct.unpack(format, key_source)[0]

**Comment by Irving-cl** [comment]
Thanks for pointing out. I added a fix in #4675. Please have a review.
