### ISSUE TITLE
[doc] configuration description missing in openthread.io

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#4684]
**Is your feature request related to a problem? Please describe.**
I couldn't find OpenThread's configurations description in https://openthread.io/reference. I think it helpful to have a centered place to introduce all OpenThread configuration and usage.

**Describe the solution you'd like**
Add a generated configurations page.

**Comment by jwhui** [comment]
Related to #4038

**Comment by Vyrastas** [comment]
If we want to do something like this right, it should be hosted on GitHub (does it need to be per platform?) as a Markdown file, and we can import it into openthread.io.  So the source would be editable by anyone whenever the switches change (how often does that happen?) and I just need to run a quick script to update the website.

**Comment by jwhui** [comment]
> If we want to do something like this right, it should be hosted on GitHub (does it need to be per platform?) as a Markdown file, and we can import it into openthread.io. So the source would be editable by anyone whenever the switches change (how often does that happen?) and I just need to run a quick script to update the website.

We already have doxygen in header files in [src/core/config](https://github.com/openthread/openthread/tree/master/src/core/config). Would it be possible to autogenerate docs using the config header files as source?

**Comment by Vyrastas** [comment]
Yeah that would be easier.  I assume we'd use all the header files in there?

**Comment by jwhui** [comment]
> Yeah that would be easier. I assume we'd use all the header files in there?

Yes, I think so.

**Comment by Vyrastas** [comment]
I'll take a look at this

**Comment by jwhui** [comment]
Configuration variables documentation is available here: https://openthread.io/reference
