### ISSUE TITLE
NRF52840 Flash

### ISSUE THREAD

**Issue by Feng573795502** [openthread/openthread#4738]
Nrf52840 BLE+Thread Encountered Flash error，When using a multi-protocol connection otPlatFlashWrite（）Will cause an exception

commit b64d148b9755347c05c2e06423bc9e4d181fff15
`error = nrf5FlashWrite(mapAddress(aSwapIndex, aOffset), aData, aSize);
    assert(error == OT_ERROR_NONE);`
`    

    // Store the middle block of data.
    remainder = aSize % sizeof(uint32_t);
    blockSize = aSize - remainder;

    error = sdFlashSingleWrite(aAddress, aData, blockSize / sizeof(uint32_t));

    otEXPECT(error == OT_ERROR_NONE);

    aAddress += blockSize;
    aData += blockSize;
    aSize -= blockSize;
    result += blockSize;

    // Store any additional bytes that didn't fit into middle block.
    if (remainder)
    {
        blockValue = 0xffffffff;

        memcpy((uint8_t *)&blockValue, aData, remainder);

        error = sdFlashSingleWrite(aAddress, (uint8_t *)&blockValue, sizeof(blockValue) / sizeof(uint32_t));

        otEXPECT(error == OT_ERROR_NONE);

        result += remainder;
    }
exit:
    return result;
 `

result cannot be 0

**Comment by LuDuda** [comment]
@Feng573795502 thank you for reporting of the issue. The fix is almost ready :)
