### ISSUE TITLE
IAR can't compile two files with the same name (leader.cpp)

### ISSUE THREAD

**Issue by piotrkoziar** [openthread/openthread#4745]
**Describe the bug**
After recent changes (#4430), IAR build of OpenThread libraries fails with error like this:
```
Build error: Multiple tools write to the same file.
  File: foo\iar\_build\leader.o
  Tool 1: C/C++ Compiler, when processing foo\openthread\src\core\backbone_router\leader.cpp
  Tool 2: C/C++ Compiler, when processing foo\openthread\src\core\meshcop\leader.cpp
```
It is caused by two files with the same name (leader.cpp) that are processed during the compilation of SOURCES_COMMON in src/core/Makefile.am.

**To Reproduce**
Information to reproduce the behavior:
1. Git commit: #4430 or later
2. Use IAR toolchain to compile sources

**Solution**
I believe the best solution is to change filename of at least one leader.cpp file, i.e.: 
meshcop/~~leader.cpp~~ -> meshcop/**meshcop_leader.cpp**
meshcop/~~leader.hpp~~ -> meshcop/**meshcop_leader.hpp**

**Comment by jwhui** [comment]
@piotrkoziar, thank you for raising this issue.

I agree that we should avoid having source files with duplicate filenames. Would you like to submit a PR with the proposed fix?

**Comment by piotrkoziar** [comment]
@jwhui Thank you for the answer.

Yes, I will prepare PR with the fix.

**Comment by jwhui** [comment]
> Yes, I will prepare PR with the fix.

@piotrkoziar, thanks!

**Comment by OlivierGre** [comment]
@piotrkoziar How do you proceed to build the project with IAR?

**Comment by piotrkoziar** [comment]
@OlivierGre Sorry but I no longer build OpenThread code with IAR, for more than a year. However, I was able to build the project at the time this issue was fixed. 
For me, a lot of work would be required to proceed with IAR compilation, especially after C++11 features were introduced to the code.

**Comment by OlivierGre** [comment]
Hi Piotr. Ok thank you for your message.
