### ISSUE TITLE
Child Supervision check verification

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/openthread#4801]
I am using openthread commit id: 8a1992e and build the libraries with Child supervision feature enabled.
I just want to know how can I verify that child supervision is actually working in my stack.

**Comment by abtink** [comment]
@bhumikaajain one way would be through logs.  OT logs need to be enabled (at INFO level). 

This log should be seen on parent when the _first_ sleepy child attaches:
https://github.com/openthread/openthread/blob/8a1992e2e42fb707babe9491a6a1456e553490e8/src/core/utils/child_supervision.cpp#L155
This log  "Sending child supervision to xxx" is emitted when there is no tx msg from parent to a sleep child for a while. Supervision msg (which are empty payload frame) are sent from parent to a sleepy child only if there has been no tx traffic to the child within a past interval (supervision interval). The purpose of this is for the child to know that it is still a child of its parent (it is still in parent's child table).
https://github.com/openthread/openthread/blob/8a1992e2e42fb707babe9491a6a1456e553490e8/src/core/utils/child_supervision.cpp#L99

----

(Much) harder way of checking behavior is through emulating the test-case which verifies behavior, i.e. issuing the same set of commands through `wpanctl` on the nodes as the test-case does: [test-018-child-supervision.py](https://github.com/openthread/openthread/blob/8a1992e2e42fb707babe9491a6a1456e553490e8/tests/toranj/test-018-child-supervision.py)

Note that this requires running devices with `wpantund` and having `wpanctl` access and also requires whitelisting feature to be enabled in OT/NCP build.
