### ISSUE TITLE
[config] autogenerated config file by configure.ac has no header guard

### ISSUE THREAD

**Issue by wgtdkp** [openthread/openthread#4816]
**Describe the bug**
The auto-generated header file `openthread-config-generic.h` has no header guard.

**To Reproduce**
1. run `bootstrap && make -f examples/Makefile-simulation`
2. check header `build/x86_64-unknown-linux-gnu/include/openthread-config-generic.h`, it has no header guard.

**Expected behavior**
The auto-generated header file `openthread-config-generic.h` has header guard.

**Console/log output**

**Additional context**

**Comment by jwhui** [comment]
Closing stale issue. Transition to CMake/Ninja should will avoid this issue.
