### ISSUE TITLE
Move utilities headers to public include directory

### ISSUE THREAD

**Issue by gjc13** [openthread/openthread#4828]
**Is your feature request related to a problem? Please describe.**
As we are moving spinel and other common code to `src/lib`, some of the code has dependency on utilities code under `src/core` such as `code_utils.hpp`.

**Describe the solution you'd like**
Add a new directory such as `src/common` or `src/utils` and make it a public include directory.

**Comment by gjc13** [comment]
@wgtdkp Kangping has more to share on what do we need when we use OpenThread as a third party c++ library for Thread related projects (such as porting to a new platform or ot-rtos).

**Comment by jwhui** [comment]
Closing stale issue.
