### ISSUE TITLE
Thread Certification results as hosted HTML

### ISSUE THREAD

**Issue by beriberikix** [openthread/openthread#486]
Currently we host [Thread Certification results](https://github.com/openthread/openthread/wiki/Thread-Certification#results-summary) as PDFs in ZIPs. It would be faster to check results if they were hosted as HTML. We can leverage the [new feature for publishing docs](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages).

**Comment by jwhui** [comment]
I agree it would be nice to have the results in HTML format.  However, the Thread Certification Harness produced by the Thread Group only outputs results in PDF format.

**Comment by beriberikix** [comment]
That's what I figured. Let's put it on the backburner for now (P4? Another label?) Maybe it is something we can ask for in the future.

**Comment by turon** [comment]
Does the publishing docs feature support hosing PDF files via HTTP?

_____________________________
Martin Turon  |  Nest Labs

**Comment by jwhui** [comment]
The GitHub feature will host anything you can commit to git.  However, linking a PDF file is pretty much what we have now on the wiki.

**Comment by darconeous** [comment]
There is always <https://rawgit.com>.

**Comment by jwhui** [comment]
Closing stale issue.
