### ISSUE TITLE
[nrf52811] Can we reduce the value of OPENTHREAD_CONFIG_HEAP_INTERNAL_SIZE_NO_DTLS?

### ISSUE THREAD

**Issue by zhanglongxia** [openthread/openthread#4861]
The ot-cli-mtd image already occupied 19kB of the RAM on platform nrf52811. The RAM size of nrf52811 is 24kB. The stack  size is 2kB. There is not much RAM space available for users. I saw the OPENTHREAD_CONFIG_HEAP_INTERNAL_SIZE_NO_DTLS is set to 2024 on platform nrf52811, can we reduce the heap size to reduce the occupied RAM size?

**Comment by LuDuda** [comment]
Hello @zhanglongxia,

I agree with you. The nRF52811 is designed to work in RCP architecture where DTLS is established on the Host level. We do not support Joiner or Border Agent roles in the nRF52811. So it is okay to set this value to 0 I think. Would you like to create such PR?
