### ISSUE TITLE
Factory Diagnostics module "Diag"

### ISSUE THREAD

**Issue by mamer11** [openthread/openthread#4873]
Hello,

I'm trying to activate Factory Diagnostics module "Diag" in CLI, I'm following the example: openthread/examples/platforms/efr32mg21/, I tried  to call OPENTHREAD_CONFIG_DIAG_ENABLE=1 in this way:
"make -f examples/Makefile-efr32mg21 BOARD=BRD4180A OPENTHREAD_CONFIG_DIAG_ENABLE=1" 
I'm not sure if this correct way, I did not get any error, but the "Diag" still not activated, it's not appear in list of available commands after I flash my board, please your advice.

**To Reproduce**
 efr32mg21 

Thanks

**Comment by bukepo** [comment]
Could you try the following command instead?
```bash
make -f examples/Makefile-efr32mg21 BOARD=BRD4180A DIAGNOSTIC=1
```

**Comment by mamer11** [comment]
Thank you, I tried it but still the same problem. kindly check the attached file, this is part of what I got after I applied the command.
![Captureto](https://user-images.githubusercontent.com/56914634/79978239-e3848200-849f-11ea-91ec-d715cbb5edd9.JPG)

Thanks

**Comment by mamer11** [comment]
Thank you. The problem solved.
