### ISSUE TITLE
The addition of otRadioCoexMetrics

### ISSUE THREAD

**Issue by testter2** [openthread/openthread#4947]
Hello everybody,

I was wondering what is the reason behind adding this new structure otRadioCoexMetrics and what is it used in?
maybe you can support on this @zhanglongxia @jwhui 

Thanks,

**Comment by jwhui** [comment]
@testter2 , `otRadioCoexMetrics` is intended for radio drivers that implement radio coexistence mechanisms - for example, Wi-Fi + Thread coexistence. The metrics help provide visibility into the frequency of various coex events. If the radio driver does not implement radio coexistence, you can ignore this.

Does that help answer your question?

**Comment by testter2** [comment]
Sure, thanks.
