### ISSUE TITLE
Modifying of Platform Abstraction Layer APIs

### ISSUE THREAD

**Issue by testter2** [openthread/openthread#4948]
Hello everybody,

In this link https://openthread.io/guides/porting/implement-platform-abstraction-layer-apis 
Random should be replaced by Entropy as Random has been moved from platform abstraction to become an open thread module. 

Thanks,

**Comment by jwhui** [comment]
@testter2 , thanks for pointing this out. We'll work to update the docs. Thanks.

**Comment by Vyrastas** [comment]
Looks like the Flash one needs to be updated too, I assume we should use /include/openthread/platform/flash.h now?

**Comment by jwhui** [comment]
> Looks like the Flash one needs to be updated too, I assume we should use /include/openthread/platform/flash.h now?

@Vyrastas , platforms need only implement one of:

1. https://github.com/openthread/openthread/blob/master/include/openthread/platform/flash.h

2. https://github.com/openthread/openthread/blob/master/include/openthread/platform/settings.h

The choice is made with:
https://github.com/openthread/openthread/blob/b4a5df49e64c5f13333f5251619d71235a60be38/src/core/config/openthread-core-default-config.h#L344

**Comment by testter2** [comment]
> Looks like the Flash one needs to be updated too, I assume we should use /include/openthread/platform/flash.h now?

I also think so as the current link in the website has the old path for flash.h file before moving it the platform.

**Comment by Vyrastas** [comment]
Thanks, I'll get them updated.

**Comment by Vyrastas** [comment]
This has been fixed.
