### ISSUE TITLE
License for shipping

### ISSUE THREAD

**Issue by vervaekejonathan** [openthread/openthread#4991]
If we are shipping a product containing openthread (one nrf52 device with 'nRF5 SDK for Thread and Zigbee', one nrf52 device as openthread NCP and a (borderrouter) device with wpantund), would this require some certification and would this require us to add a Thread logo on a box or something similair?

**Comment by jwhui** [comment]
Becoming a Thread Certified Component or Built on Thread certified product confers three benefits to those who successfully complete certification:

1. Rights to use word and logo marks.

1. Rights to claim compatibility.

1. Rights to intellectual property held by those organizations contributing to the Thread specification.

By not certifying, your organization is opting out of the benefit of all three of those and in particular, taking on the risk potential associated with (3). As always, the consultation of outside or inside counsel is advised to best assess the risks to your business.

If you are using an existing Thread Certified Component, you may qualify for the inheritance certification program available to both Implementer and Contributor members. The inherited certification and an Implementer membership is the lowest cost way to enjoy the three benefits above.
