### ISSUE TITLE
[cmake]  compile failed when the CMake build type is not set

### ISSUE THREAD

**Issue by zhanglongxia** [openthread/openthread#4998]
**Describe the bug** A clear and concise description of what the bug is.

If we are not specified the build type `CMAKE_BUILD_TYPE` to `Release`, CMake build will be failed on platform `cc1352`, `cc2650`, `cc2652`, `smar21` and `qpg6095`.

**To Reproduce** Information to reproduce the behavior, including:

```
mkdir build
cd build
cmake -GNinja -DOT_PLATFORM=${platform}  -DCMAKE_TOOLCHAIN_FILE=examples/platforms/${platform}/arm-none-eabi.cmake  ..
ninja
```

**Comment by jwhui** [comment]
Closing stale issue. Build scripts in platform-specific repos specify the build type.
