### ISSUE TITLE
Support setting multiple dataset properties at once and changing dataset init default values

### ISSUE THREAD

**Issue by gabekassel** [openthread/openthread#5028]
**Problem Statement**
As of May 2020, initializing an operational dataset uses a pre-made default dataset. Separately, operational datasets can only be updated one property/attribute as a time (e.g. panid, masterkey, etc). 

**Potential Solution**
Support setting multiple dataset properties in one command and potentially tie to dataset init to "seed" the dataset fully upon init.

**Comment by jwhui** [comment]
@gabekassel , I just submitted #5055. Please review.
