### ISSUE TITLE
[doc] chinese translation of Thread Primer

### ISSUE THREAD

**Issue by dsyx** [openthread/openthread#5086]
I have translated `Thread Primer` into **Chinese**.
Request the source files of the following pages so that I can better format the translation:
* [What is Thread?](https://openthread.io/guides/thread-primer)
* [Node Roles and Types](https://openthread.io/guides/thread-primer/node-roles-and-types)
* [IPv6 Addressing](https://openthread.io/guides/thread-primer/ipv6-addressing)
* [Network Discovery and Formation](https://openthread.io/guides/thread-primer/network-discovery)
* [Router Selection](https://openthread.io/guides/thread-primer/router-selection)

Thanks.

**Comment by jwhui** [comment]
@dsyx, see #5088.
