### ISSUE TITLE
Clean up macros in posix/netif.cpp

### ISSUE THREAD

**Issue by gjc13** [openthread/openthread#5096]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.

There are too many `ifdef`s in `netif.cpp`, making this file hard to read and maintain.

**Describe the solution you'd like** 
Refactor this file in a modularized manner, separating different functionalities and platform specific implementations into different files.

**Comment by jwhui** [comment]
Closing stale issue.
