### ISSUE TITLE
We should only have one README file

### ISSUE THREAD

**Issue by darconeous** [openthread/openthread#51]
I noticed that we have both `README` and `README.md` files. We should get rid of one or the other, and I vote for getting rid of `README`.

I would have just filed a pull request for this, except that there is text in `README` that doesn't appear in `README.md`, so I'm not sure if/how the data from `README` should be merged into `README.md`.

This should be resolved before any initial first cut.

**Comment by darconeous** [comment]
This issue is being worked on. Adding to the `0.1.0` milestone so that we remember to resolve this issue one way or the other before then.

**Comment by jwhui** [comment]
Fixed with #124.
