### ISSUE TITLE
DHCP client closes the socket and stops solicitation if two consecutive Data response message are received in a short time

### ISSUE THREAD

**Issue by karsev** [openthread/openthread#5166]
If two messages with the same prefix arrive in a short time ( See void Dhcp6Client::UpdateAddresses(void) in  dhcp6_client.cpp)
The second message closes the socket before the first message (DHCP solicit) is handled. This happens because "newAgent" variable in the function will stay false.

The result is that a Thread device will not do the address solicitation successfully and does not get the global ipv6 address.

**To Reproduce** 

1. Git commit id: c8efee95f3be7aa3f35a6da50bca737d2e53ddc3 (src/core/net/dhcp6_client.cpp)
2. IEEE 802.15.4 hardware platform: Atmel at86rf233
3. Build steps: Reference platform should work fine for testing.
4. Network topology: Not relevant

**Expected behavior** 

If consecutive Data response messages are received with the same prefix, the second one should not close the socket.

**Comment by jwhui** [comment]
@karsev , thanks for raising this issue. I have submitted #5169 that proposes a fix. Please review.
