### ISSUE TITLE
When BR is a REED and its RLOC changes, DHCP client in node does not update RLOC in identity associations.

### ISSUE THREAD

**Issue by karsev** [openthread/openthread#5167]
When BR is REED, it can keep changing its RLOC16 address frequently 
DHCP client in nodes does not detect this change when they get the Data response message.

**To Reproduce** 

1. Git commit id: c8efee9 (src/core/net/dhcp6_client.cpp)
2. IEEE 802.15.4 hardware platform: Atmel at86rf233
3. Build steps: should be reproducible in the reference platform.
4. Network topology: RLOC seems to change more often when there are 23 devices in the network (on the downgrade threshold). 

**Expected behavior** 

DHCP client should update RLOC in the funcion "void Dhcp6Client::UpdateAddresses(void)"
(mIdentityAssociations[i].mPrefixAgentRloc)

**Comment by jwhui** [comment]
@karsev , thanks for raising this issue. I have submitted #5169 that proposes a fix. Please review.
