### ISSUE TITLE
spinel-cli: fix failing tests 

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#517]
spinel-cli was merged in #364, however multiple tests still fail.  This issue tracks the effort to get all tests passing.

**Comment by jwhui** [comment]
I'm seeing spurious pass/fail results on Cert_5_1_07 with ncp-sim ([build example](https://travis-ci.org/openthread/openthread/jobs/157433184)).  I'm going to submit a another PR that moves that test to the SKIP list for now.

**Comment by jwhui** [comment]
I'm still seeing spurious failures ([example](https://travis-ci.org/jwhui/openthread/jobs/159651444)).

**Comment by turon** [comment]
@jwhui @darconeous #585 leverages the new ot-ncp clean exit to hopefully solve the spurious eof failures.

**Comment by jwhui** [comment]
Still seeing spurious failures ([example](https://travis-ci.org/openthread/openthread/jobs/159939839))...

**Comment by turon** [comment]
Thanks for letting me know.  Root cause for that seems to be this:

```
ot-ncp: /home/travis/build/openthread/openthread/examples/../src/core/common/message.cpp:201: ThreadError Thread::Message::MoveOffset(int): Assertion `GetOffset() + aDelta <= GetLength()' failed.
Aborted (core dumped)
```
