### ISSUE TITLE
[github-actions] cli-ftd-otns failing in master

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#5170]
**Describe the bug** A clear and concise description of what the bug is.

cli-ftd-otns GitHub Action is failing in master

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: 5ce4046
2. IEEE 802.15.4 hardware platform: N/A
3. Build steps: N/A
4. Network topology: N/A

**Expected behavior** A clear and concise description of what you expected to happen.

cli-ftd-otns GitHub Action passes.

**Console/log output** If applicable, add console/log output to help explain your problem.

https://github.com/openthread/openthread/runs/824271448

[logs_9382.zip](https://github.com/openthread/openthread/files/4854580/logs_9382.zip)

**Additional context** Add any other context about the problem here.

Started failing after merging #5155

**Comment by ctan-g** [comment]
Looking into this

**Comment by jwhui** [comment]
> Looking into this

Thanks, @ctan-g !

**Comment by ctan-g** [comment]
@jwhui I found that the cause is my `OT_TOOL_WEAK` definition of `otPlatOtnsStatus` in `otns.cpp` isn't properly being overridden by the strong one in `otns.c` during linking when building the simulation images. Do you happen to know why this is happening?

**Comment by simonlingoogle** [comment]
I wonder how did we pass the GitHub action checks.

**Comment by simonlingoogle** [comment]
Turn out `cli-ftd-otns` GitHub action is not using the current openthread commit of the PR, but always using openthread master for checking. This was the reason why `cli-ftd-otns` check passed.
