### ISSUE TITLE
Posix implementation should output meaningful error message upon unexpected exit

### ISSUE THREAD

**Issue by gjc13** [openthread/openthread#5177]
**Is your feature request related to a problem?**

The posix process silently exits with an error code upon unexpected exits. (e.g. Access denied/invalid args etc.)
This makes debugging quite hard, especially for new comers.

**Describe the solution you'd like** 
We should at print the file and the line number upon exit and some meaningful error message at least in debug builds.

**Comment by simonlingoogle** [comment]
I think meaningful error messages will be very helpful.
