### ISSUE TITLE
[cli] add a netstat command

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#5186]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.
I hope to have a command to list all sockets, which can be helpful for debugging issues.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
 provide a simple implementation of netstat-like command, including bound address, port and status.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
simply list all open ports.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by bukepo** [comment]
@jwhui @abtink what do you think?

**Comment by jwhui** [comment]
I assume this is an OpenThread CLI? Sounds like a good idea to me.

**Comment by bukepo** [comment]
Yes, an OpenThread CLI.

**Comment by abtink** [comment]
Sounds great to me.
