### ISSUE TITLE
[cli] use compressed IPv6 addresses

### ISSUE THREAD

**Issue by moandor-y** [openthread/openthread#5209]
**Is your feature request related to a problem? Please describe.**
Current OpenThread CLI has many places displaying IPv6 addresses without compression. E.g. `ipmaddr` gives something like `ff02:0:0:0:0:0:0:1` which is verbose.

**Describe the solution you'd like**
Change these representations to compressed IPv6 addresses. E.g. `ff02:0:0:0:0:0:0:1` -> `ff02::1`.

**Comment by Moandor-y** [comment]
@jwhui @abtink what do you think?

**Comment by bukepo** [comment]
SGTM:+1: If we don't want to increase the overhead to all builds, we may add this function in the cli library only. Thoughts?

**Comment by simonlingoogle** [comment]
Be careful  that it might cause OpenThread THCI or other scripts to fail. @Moandor-y

**Comment by Moandor-y** [comment]
> Be careful that it might cause OpenThread THCI or other scripts to fail. @Moandor-y

Yes. At least all scripts using regex to match IPv6 addresses need to be changed to something like [this](https://stackoverflow.com/questions/53497/regular-expression-that-matches-valid-ipv6-addresses).

**Comment by jwhui** [comment]
Compressed representation sounds good to me.

**Comment by jwhui** [comment]
Closing stale issue.
