### ISSUE TITLE
Enhance size-report to include 1.2 features

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/openthread#5274]
Continuing discussion from https://github.com/openthread/openthread/pull/5248#discussion_r458561842 

> I was hoping to catch situations where adding Thread 1.2 code (intentionally or unintentionally) changes Thread 1.1 code. Should we flag situations where adding a Thread 1.2 feature significantly increases Thread 1.1 code?

Here are some examples by adding more 1.2 columns to `size-report`.  

### Example 1:

|  name  |  branch  | 1.1 text  | 1.1 data  | 1.1 bss  | 1.1 total | 1.2 text  | 1.2 data  | 1.2 bss  | 1.2 total |
| :----: | :------: | -----: | ----: | ---: | ----: |  ----: | ----: | ----: | ----: |
| libopenthread-ncp-ftd.a | master | 396720 | 736 | 72828 | 470284 | 396720 | 736 | 72828 | 470284 |
|  | #5268 | 396720 | 736 | 72828 | 470284 | 396720 | 736 | 72828 | 470284 |
|  | +/- | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| libopenthread-ncp-mtd.a| master | 319360 | 736 | 64180 | 384276 | 319360 | 736 | 64180 | 384276 |
|  | #5268 | 319360 | 736 | 64180 | 384276 | 319360 | 736 | 64180 | 384276 |
|  | +/- | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

### Example 2 (Only add 1.1/1.2 for total column):
|  name  |  branch  | text  | data  | bss  | 1.1 total | text  | data  | bss  | 1.2 total |
| :----: | :------: | -----: | ----: | ---: | ----: |  ----: | ----: | ----: | ----: |
| libopenthread-ncp-ftd.a | master | 396720 | 736 | 72828 | 470284 | 396720 | 736 | 72828 | 470284 |
|  | #5268 | 396720 | 736 | 72828 | 470284 | 396720 | 736 | 72828 | 470284 |
|  | +/- | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| libopenthread-ncp-mtd.a | master | 319360 | 736 | 64180 | 384276 | 319360 | 736 | 64180 | 384276 |
|  | #5268 | 319360 | 736 | 64180 | 384276 | 319360 | 736 | 64180 | 384276 |
|  | +/- | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

### Example 3 (removing `total`) :

|  name  |  branch  | 1.1 text  | 1.1 data  | 1.1 bss  | 1.2 text  | 1.2 data  | 1.2 bss  | 
| :----: | :------: | -----: | ----: | ---: | ----: |  ----: | ----: |
| libopenthread-ncp-ftd.a | master | 396720 | 736 | 72828  | 396720 | 736 | 72828 | 
|  | #5268 | 396720 | 736 | 72828  | 396720 | 736 | 72828 |
|  | +/- | 0 | 0 | 0 | 0 | 0 | 0 | 
| libopenthread-ncp-mtd.a | master | 319360 | 736 | 64180 |  319360 | 736 | 64180 |
|  | #5268 | 319360 | 736 | 64180 | 319360 | 736 | 64180 |
|  | +/- | 0 | 0 | 0 | 0 | 0 | 0 |

_Originally posted by @simonlingoogle in https://github.com/openthread/openthread/pull/5248#discussion_r458561842_

**Comment by jwhui** [comment]
I think Example 3 is sufficient for me. I generally prefer to see the individual breakdown vs the total number.

**Comment by simonlingoogle** [comment]
Hi @bukepo 
Would you give comments on what we need to enhance to achieve 1.2 size-report as in Example 3 ?

**Comment by bukepo** [comment]
I hope we can print size diff of each symbols.

**Comment by simonlingoogle** [comment]
> I hope we can print size diff of each symbols.

Agree that it's useful to have size diff of each symbol. But the result would be very long, so maybe we should have a link in the comment which can guide us to the detailed report? 

I think this is another topic that worth discussing. However it is unrelated to 1.2 features?

**Comment by bukepo** [comment]
> > I hope we can print size diff of each symbols.
> 
> Agree that it's useful to have size diff of each symbol. But the result would be very long, so maybe we should have a link in the comment which can guide us to the detailed report?
> 
> I think this is another topic that worth discussing. However it is unrelated to size report for 1.2 features?

Agree. I think it's better to display the results of 1.1 and 1.2 separately in two sections, which also works for future versions.

**Comment by simonlingoogle** [comment]
Close for now since we already have Thread 1.2 size-report.
