### ISSUE TITLE
[cli] only support a single CLI server?

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#5304]
The current CLI supports multiple servers. And by default, UART and Console servers are built together. This would cause issues because when a server receives data Interpreter::mServer is updated. Then CLI output will go to the last server. This seems reasonable. But there are some async commands such as ping, scan and etc. Then these commands output may went to a wrong server.

How about removing multiple servers support?

**Comment by jwhui** [comment]
I am OK to remove multiple server support if there are no strong use cases for it.
