### ISSUE TITLE
[discriminator] Border Agent support discriminator

### ISSUE THREAD

**Issue by wgtdkp** [openthread/openthread#5314]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.

To support Commissioning on Mobile OS, the Border Agent need to include a discriminator in its mDNS response to help uniquely identify it.

Minimum Requirements:
- the discriminator should persist over reboot.
- the discriminator MUST be changed after factory reset or reprovisioning;
- the discriminator should be randomly generated.

**Describe the solution you'd like** A clear and concise description of what you want to happen.
- Use an unsigned 64 bits integer for discriminator.
- Store the discriminator along with other OpenThread settings.
- Regenerate the discriminator if no existing one or the device is re-commissioned.
- Provide getter APIs for OTBR to retrieve this information.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

Implement the discriminator in OTBR
- Require additional separate settings storage. 

**Additional context** Add any other context or screenshots about the feature request here.

@jwhui @abtink @bukepo @librasungirl Thoughts?

**Comment by jwhui** [comment]
Resolved by https://github.com/openthread/ot-br-posix/pull/701
