### ISSUE TITLE
[continuous-integration] packet-verification keeps failing on 6_1_09 for latest PRs

### ISSUE THREAD

**Issue by Irving-cl** [openthread/openthread#5483]
**Describe the bug**
Latest PRs all failed in packet-verfication at `./tests/scripts/thread-cert/Cert_6_1_09_EDSynchronization.py` or `./tests/scripts/thread-cert/Cert_5_5_02_LeaderReboot.py`. I re-run the jobs for mulpitle times.

affected PRs: #5449 #5479 #5481 #5482

**Comment by FiveDimensions** [comment]
submitted #5486 to fix it
