### ISSUE TITLE
Floating point in EFR32 builds

### ISSUE THREAD

**Issue by theHurc** [openthread/openthread#5492]
Is there a particular reason the EFR32 builds use the `-mfloat-abi=soft` option instead of `-mfloat-abi=softfp`? Isn't the EFR32 capable of hardware floating point?

**Comment by dismirlian** [comment]
Yes, it's possible, in fact we have been runningr our tests with softfp. It would be even better to use the `hard` abi, if Silabs provided compatible versions of RAIL, which weren't available last time I checked.

**Comment by romacdon** [comment]
Thanks for raising the question @theHurc.  You are correct.  For the series1 parts (efr32mg1, efr32mg12, and efrmg13) you can use `-mfloat-abi=softfp` and we will look into changing that in an upcoming PR.  For series2 parts (efr32mg21) we are correctly using `-mfloat-abi=hard`.

Also, thanks @dismirlian for your confirmation.

**Comment by theHurc** [comment]
Thank you.
