### ISSUE TITLE
Question - OpenThread - Send large packet (50KB) over UDP

### ISSUE THREAD

**Issue by limartin1** [openthread/openthread#5498]
Hello,
I need to send a large data buffer (50KB for example) in UDP on an OpenThread network.
By default, UDP sending via otUdpSend is limited to 1232 Bytes of payload. I saw that we could modify certain parameters in the library to reach 1999 bytes. (https://github.com/openthread/openthread/issues/3324) I think this is not necessarily what I need.
Is there a way to send a 50KB buffer over UDP without having to manually split it?

Otherwise do you know what is the most efficient way to slice my buffer? I have not found a similar use case on the internet. Maybe I don't have the right approach?

Thank you,
Lilian

**Comment by jwhui** [comment]
OpenThread itself does not currently provide a way to transfer bulk data.

You could take a look at #4247 , which is looking at implementing CoAP Block-Wise Transfer support ([RFC 7959](https://tools.ietf.org/html/rfc7959)).
