### ISSUE TITLE
Fail to compile, after pull

### ISSUE THREAD

**Issue by L-Belluomini** [openthread/openthread#5506]
Hi to everyone, new developer with little experience, probably my fault.

**Describe the bug** A clear and concise description of what the bug is.
error to compile after pull
**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
    210ff5a13957e1ba605e65bd8d22a05d1209f870
2. IEEE 802.15.4 hardware platform
    efr32mg12 ( BOARD=BRD4166 )
3. Build steps
    git pull origin master
    make -f examples/Makefile-efr32mg12 BOARD=BRD4166 clean
    make -f examples/Makefile-efr32mg12 BOARD=BRD4166

4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

make -f examples/Makefile-efr32mg12 BOARD=BRD4166A 
  BUILD    efr32mg12
make -j10 -C build/efr32mg12 --no-print-directory all
  CHECK         .local-version
  GEN           .local-version
make --no-print-directory all-recursive
Making all in include
make  all-recursive
Making all in openthread
Making all in platform
make[6]: Nothing to be done for 'all'.
make[6]: Nothing to be done for 'all-am'.
Making all in third_party
Making all in silabs
...
...
CXX      radio/libopenthread_radio_a-radio_callbacks.o
  CXX      radio/libopenthread_radio_a-radio_platform.o
make[4]: *** No rule to make target 'thread/thread_uri_paths.hpp', needed by 'all-am'.  Stop.
make[4]: *** Waiting for unfinished jobs....
  CXX      thread/libopenthread_radio_a-link_quality.o
make[3]: *** [Makefile:438: all-recursive] Error 1
make[2]: *** [Makefile:591: all-recursive] Error 1
make[1]: *** [Makefile:517: all] Error 2
make: *** [examples/Makefile-efr32mg12:293: do-build-cortex-m4] Error 2

**Additional context** Add any other context about the problem here.

**Comment by jwhui** [comment]
@L-Belluomini , can you try running `./bootstrap` before the `make` commands?
