### ISSUE TITLE
Support for FEMs

### ISSUE THREAD

**Issue by dismirlian** [openthread/openthread#5561]
**Is your feature request related to a problem? Please describe.**
Currently, OT provides two API functions (and associated CLI commands) to set the TX power and the CCA threshold. As per IEEE802.15.4, those values should be measured at the antenna (or antenna connector). When a FEM is used in front of the radio, the user must correct for the PA and LNA gains by hand. Please see #5532 for background.

**Describe the solution you'd like**
As per the discussion in #5532, an API to set the PA and LNA gains, so that the radio platform driver can account for the FEM, (and maybe also cap the total TX power).

**Describe alternatives you've considered**
Please see #5532.

**Comment by jwhui** [comment]
@dismirlian , we submitted #5563. Please review.
