### ISSUE TITLE
[codecov] coverage check is failing on master

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#5571]
See status checks on: https://github.com/openthread/openthread/commits/master

@Moandor-y , can you help take a look?

**Comment by Moandor-y** [comment]
It seems some commits have wrong coverage displayed in the check status, but after clicking details it shows the correct coverage.
Anyway, I think this check is useful only for PRs, it's not needed on master branch. I'll send a PR to make it only post a status to PRs.
