### ISSUE TITLE
Simulation 1.2 / packet-verification-1-1-on-1-2 (pull_request) keeps failing in many PRs.

### ISSUE THREAD

**Issue by Irving-cl** [openthread/openthread#5576]
**Describe the bug** A clear and concise description of what the bug is.
This item keeps failing:
![Screen Shot 2020-09-25 at 12 27 42 PM](https://user-images.githubusercontent.com/12945188/94226670-c0686d80-ff2a-11ea-9256-48370322aceb.png)

Many PRs are affected now.

**Comment by simonlingoogle** [comment]
it's a duplication of #5572
