### ISSUE TITLE
OpenThread should never create or join a partition with a PANID of 0xFFFF

### ISSUE THREAD

**Issue by darconeous** [openthread/openthread#56]
The current default value of the PANID (as retrieved by `otGetPanId()`) is `0xFFFF`. This itself isn't a bad default—it effectively implies that the PANID is undefined (because it is not a valid PANID for a network).

However, the current OpenThread stack seems to take this value and run with it anyway, happily creating a new partition with the PANID `0xFFFF` instead of doing something more reasonable (like calculating a new PANID).

I propose that the behavior for having a PANID of `0xFFFF` should be to:

* If a suitable already partition exists and has a legal PANID, use the PANID from that partition and join it. (maybe we would want to do this anyway)
* If no suitable partition is found nearby, allocate a new PANID and use that to start a new partition.

Thoughts?

**Comment by jwhui** [comment]
> The current default value of the PANID (as retrieved by otGetPanId()) is 0xFFFF. This itself isn't a bad default—it effectively implies that the PANID is undefined (because it is not a valid PANID for a network).
> 
> However, the current OpenThread stack seems to take this value and run with it anyway, happily creating a new partition with the PANID 0xFFFF instead of doing something more reasonable (like calculating a new PANID).

I agree that OpenThread should not use `0xFFFF` as a valid PANID.

> I propose that the behavior for having a PANID of 0xFFFF should be to:
> 
> If a suitable already partition exists and has a legal PANID, use the PANID from that partition and join it. (maybe we would want to do this anyway)

I agree that if a device is not configured with a valid PANID and a valid partition exists, it should use that partition's PANID and attach.

> If no suitable partition is found nearby, allocate a new PANID and use that to start a new partition.

I am OK with allocating a new PANID, but I don't think that OpenThread should do this autonomously.  In particular, a new PANID should only be created when initially forming the network or when changing the PANID.  I think both scenarios should require explicit action from outside OpenThread.

**Comment by darconeous** [comment]
Looking at the output from the description in [openthread/wpantund/19](https://github.com/openthread/wpantund/issues/19), I believe this is still a problem.

I'm going to bump this to a P1 because I think we should address this before the [0.01.00 milestone](https://github.com/openthread/openthread/milestone/1).
