### ISSUE TITLE
[efr32] wrong reset reason

### ISSUE THREAD

**Issue by dismirlian** [openthread/openthread#5685]
In `otPlatGetResetReason`, the return value implies that the last reset was caussed by an `assert`, when actually it was a brownout or an EM4 reset. I think a better fit would be `OT_PLAT_RESET_REASON_OTHER`.

https://github.com/openthread/openthread/blob/9aa2402753fab14d378d5035748c9c0bfc17173a/examples/platforms/efr32/src/misc.c#L83-L88

https://github.com/openthread/openthread/blob/9aa2402753fab14d378d5035748c9c0bfc17173a/examples/platforms/efr32/src/misc.c#L111-L115

**Comment by romacdon** [comment]
@dismirlian - I agree.  That looks wrong.  @lmnotran can you take a look?
