### ISSUE TITLE
A Number of Build Warnings on Windows

### ISSUE THREAD

**Issue by nibanks** [openthread/openthread#570]
Many of the build warnings have been fixed in the last few months, but a number are still there. I recently got appveyor building on my branches, and you can see the list of warnings from the latest build:

https://ci.appveyor.com/project/nibanks/openthread/build/messages

Most of the build warnings are "conversion from .. to .., possible loss of data"

**Comment by jwhui** [comment]
I agree we should fix these build warnings.  Interesting that gcc and clang do not pick up these warnings.  Are you willing to submit a PR that addresses these warnings?

**Comment by nibanks** [comment]
Sure. I just figured I'd open an issue now that I had something concrete to point it to.

**Comment by jwhui** [comment]
Fixed in #577.
