### ISSUE TITLE
[tests] unstable Cert_5_6_9 

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#5707]
**Describe the bug** 
Cert_5_6_9 fails for https://github.com/openthread/openthread/pull/5690 unexpectedly, rerun could pass.

**Expected behavior** 
Consistently pass if no bugs newly introduced in the PR.

**Console/log output** 
https://github.com/openthread/openthread/pull/5690/checks?check_run_id=1306518328

**Comment by FiveDimensions** [comment]
The pcap files were deleted by the second run, will try to reproduce locally.

**Comment by FiveDimensions** [comment]
It can not be reproduced after running locally for 1500 times, suggest closing the issue first. If found in the future, please upload the packets files and reopen the issue. Thanks!
