### ISSUE TITLE
otOpenUdpSocket Requires Caller to use Internal class Ip6::UdpSocket

### ISSUE THREAD

**Issue by nibanks** [openthread/openthread#571]
Because the `Ip6::UdpSocket` class now takes a parameter in its constructor (`Udp &aUdp`), code external from the main openthread library cannot call `otOpenUdpSocket` with a plain `otUdpSocket` object. `otOpenUdpSocket` immediately casts any `otUdpSocket` passed in to a `Ip6::UdpSocket` which will result in a null pointer read since the constructor was never called to set `mTransport`.

**Comment by jwhui** [comment]
Shall we just have OpenThread maintain a fixed number of sockets for the client (with a compile-time configuration parameter)?

**Comment by jwhui** [comment]
In #614, @wbober proposed to initialize the `mTransport` field as part of `otOpenUdpSocket()`, which could work as well.  Thoughts?

**Comment by nibanks** [comment]
I'm fine with that approach.

**Comment by jwhui** [comment]
Fixed in #623.
