### ISSUE TITLE
CodeLab Formatting Issues: "Simulating a Thread network using OpenThread in Docker"

### ISSUE THREAD

**Issue by wabrams** [openthread/openthread#5726]
On Step 3 (Simulate a Thread network):
![image](https://user-images.githubusercontent.com/29085413/97355574-b2c14300-185c-11eb-946f-ed5352802150.png)
"1**. Start Node 1**" (formatting showing ** instead of bolding)
![image](https://user-images.githubusercontent.com/29085413/97355689-dedcc400-185c-11eb-9acc-b32dae2571db.png)
"If you don't see the &gt; prompt after running this command, press enter**.**" (errors with the &gt character code (should be >) and bolding the period (shouldn't see ** for bolding))

**Comment by wabrams** [comment]
apologies if this isn't the correct place, but the "Report a mistake" widget in the corner directs me here.

**Comment by Vyrastas** [comment]
This is the right place... thanks for letting us know.  They migrated all Codelabs to a new backend recently, I'll have to see why that particular section isn't formatting correctly.

**Comment by wabrams** [comment]
yea no problem. tested it in firefox, edge, and chrome (no extensions) before posting. didn't find the source for that page, otherwise i would've just submitted a pull request.

**Comment by Vyrastas** [comment]
This is updated now!
