### ISSUE TITLE
Leader::Stop() doesn't remove 'a/sd' resource.

### ISSUE THREAD

**Issue by wbober** [openthread/openthread#575]
This is a minor issue. When a leader drops the role (when it changes partition) it doesn't remove the 'a/sd' resource.

**Comment by jwhui** [comment]
OpenThread's minimal coap server implementation does not currently support removing a resource that has already been added.  This is limitation is known, but (as you noted) not critical for Thread and Thread Certification.

**Comment by wbober** [comment]
Agree.

**Comment by jwhui** [comment]
If you haven't noticed, I submitted the PR referenced above to address this issue.  Feel free to review.

**Comment by wbober** [comment]
Reviewed.
