### ISSUE TITLE
A server should delay resending Server Data Notification.

### ISSUE THREAD

**Issue by wbober** [openthread/openthread#576]
According to Thread 1.1 spec, a server must wait at least DATA_RESUBMIT_DELAY seconds before resending its data if an inconsistency is detected.

It looks to me that currently this is done upon receiving any advertisement.

**Comment by jwhui** [comment]
Thanks for pointing this out.  As a side note, we are currently prioritizing functionality required to achieve Thread Certification.  I don't believe this functionality is covered in the Thread Certification Test Plan.  Regardless, I do believe this functionality should be included.

**Comment by wbober** [comment]
Ok I'll have the priority in mind. 

I'm not familiar Thread Certification Test Plan but the Thread spec 1.1 defines this as a MUST. I guess it will get into the test plan at some point but it can wait until then.

**Comment by jwhui** [comment]
While Thread Certification is the current priority, we value any feedback of OpenThread's implementation of the Thread Spec.  Not sure if you noticed, but I did submit the PR referenced above to address this specific issue.

**Comment by wbober** [comment]
OK.

I'll review the PR.
