### ISSUE TITLE
[thread-cert] LowPower_5_3_01 failed when VIRTUAL_TIME=0

### ISSUE THREAD

**Issue by Irving-cl** [openthread/openthread#5783]
**Describe the bug**
When running the case `v1_2_LowPower_5_3_01_SSEDAttachment.py` with `VIRTUAL_TIME=0` it fails. Currently the cases are all run with `VIRTUAL_TIME=0`. Currently our tests are all run with `VIRTUAL_TIME=1`.
 
**To Reproduce** Information to reproduce the behavior, including:
```
THREAD_VERSION=1.2 VIRTUAL_TIME=0 CSL_RECEIVER=1 ./script/test build cert tests/scripts/thread-cert/v1_2_LowPower_5_3_01_SSEDAttachment.py
```

1. Git commit id: f886f34d0
2. IEEE 802.15.4 hardware platform: simulation
3. Build steps: `THREAD_VERSION=1.2 VIRTUAL_TIME=0 CSL_RECEIVER=1 ./script/test build`

**Comment by simonlingoogle** [comment]
Is it a 100% chance fail?

**Comment by Irving-cl** [comment]
> Is it a 100% chance fail?

As I tried, yes.
