### ISSUE TITLE
[efr32] radio: should the capabilities include OT_RADIO_CAPS_SLEEP_TO_TX?

### ISSUE THREAD

**Issue by dismirlian** [openthread/openthread#5819]
Hi, I think the efr32 radio driver is able to transition to TX directly from idle (`OT_RADIO_CAPS_SLEEP_TO_TX`), but this is not declared in `otPlatRadioGetCaps`:

https://github.com/openthread/openthread/blob/515b2bb0671d63f4ca4e2abcd028ccc4c6dc61af/examples/platforms/efr32/src/radio.c#L671-L676

This would help reduce power for SEDs, for instance.

What do you think?

**Comment by jwhui** [comment]
@romacdon , thoughts on this issue?

**Comment by romacdon** [comment]
Thanks for the ping on this @jwhui.

@dismirlian - I checked with a few people here and you are correct.  We support `OT_RADIO_CAPS_SLEEP_TO_TX`.  Have you already tried this?  If so feel free to open a PR.  If not I will get one of the team members here at Silabs to make the change.

**Comment by dismirlian** [comment]
@romacdon I did try it, and I had to make a very small modification (IIRC I removed/changed some `otEXPECT_ACTION` or `assert` to cope with an unexpected sleep->transmit transition). It worked fine, but the radio driver has changed a lot since then; this was some months ago (maybe when I posted the issue?) and I didn't save the modification.

**Comment by romacdon** [comment]
Thanks @dismirlian.  I'll get someone to make the official change.  We definitely appreciate all your help.
