### ISSUE TITLE
Leader should refuse to update network name and extended pan id when pskc is missing

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#5836]
**Describe the bug** A clear and concise description of what the bug is.
Thread spec requires PSKc being updated when either network name or extended pan id is requested to be updated.

**Expected behavior** A clear and concise description of what you expected to happen.
reject MGMT_ACTIVE_SET or MGMT_PENDING_SET if PSKc TLV is missing when changing network name or extended pan id is requested.

**Comment by jwhui** [comment]
@bukepo , this sounds like something that should belong in the Thread Protocol Specification. Should we submit a Thread Group JIRA for this?

**Comment by jwhui** [comment]
Closing stale issue.
