### ISSUE TITLE
[github-actions] Cert_5_3_06_RouterIdMask.py failed intermittently 

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/openthread#5909]
**Describe the bug**
Cert_5_3_06_RouterIdMask.py failed intermittently 

**Console/log output**

[logs_42915.zip](https://github.com/openthread/openthread/files/5634268/logs_42915.zip)

[packet-verification-1.1-on-1.2-pcaps (2).zip](https://github.com/openthread/openthread/files/5634270/packet-verification-1.1-on-1.2-pcaps.2.zip)

**Comment by FiveDimensions** [comment]
From the log, there is another advertisement with router costs set {1,0,1} in Step 5 which causes the sniff time difference value larger than 3 seconds, delete the second trickle time check in PR #5912
