### ISSUE TITLE
v1_2_LowPower_7_2_01_ForwardTrackingSeries.py crashed

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/openthread#5926]
**Describe the bug** 
v1_2_LowPower_7_2_01_ForwardTrackingSeries.py crashed.

**Console/log output** If applicable, add console/log output to help explain your problem.
[core-thread-1-2-clang-m64.zip](https://github.com/openthread/openthread/files/5652482/core-thread-1-2-clang-m64.zip)
[thread-1-2-clang-m64-pcaps.zip](https://github.com/openthread/openthread/files/5652484/thread-1-2-clang-m64-pcaps.zip)

**Comment by Irving-cl** [comment]
@simonlingoogle 

Thanks for providing the artifacts. I'll debug it soon. #5774 already mentioned this case.

**Comment by Irving-cl** [comment]
It's the same problem with #5802, fixed by #5921.
