### ISSUE TITLE
[github-actions] expects RCP mode test fail intermittently

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/openthread#5928]
**Describe the bug** 

expects RCP mode test fail intermittently.

It happens quite often recently.

**Console/log output**

[logs_44259.zip](https://github.com/openthread/openthread/files/5663306/logs_44259.zip)

**Comment by Moandor-y** [comment]
Looks like the node crashed. Do we have core dumps for this?

**Comment by Irving-cl** [comment]
@Moandor-y 
I haven't added dumps for that yet. We can add dump uploading as: https://github.com/openthread/openthread/pull/5861.

**Comment by Irving-cl** [comment]
I'll add dumps uploading for expect tests.

**Comment by Moandor-y** [comment]
Happened again after core dump uploading added: <https://github.com/openthread/openthread/pull/5839/checks?check_run_id=1547881295>, but there are no core dumps in the uploaded artifacts. Maybe this is not a crash?

**Comment by jwhui** [comment]
Here is one recent failure:
- [logs_45459.zip](https://github.com/openthread/openthread/files/5690858/logs_45459.zip)
- [core-expect-rcp.zip](https://github.com/openthread/openthread/files/5690860/core-expect-rcp.zip)
- [core-expect-tun.zip](https://github.com/openthread/openthread/files/5690861/core-expect-tun.zip)

**Comment by jwhui** [comment]
Here is another recent failure:
- [logs_45435.zip](https://github.com/openthread/openthread/files/5690867/logs_45435.zip)
- [core-expect-rcp.zip](https://github.com/openthread/openthread/files/5690868/core-expect-rcp.zip)
- [core-expect-tun.zip](https://github.com/openthread/openthread/files/5690869/core-expect-tun.zip)
