### ISSUE TITLE
Router ID 62 treated as incorrect Router ID

### ISSUE THREAD

**Issue by rlubos** [openthread/openthread#597]
Hi,
I've looked through the OpenThread code, and I've noticed that in OpenThread (mostly in mle_router.cpp, the value kMaxRouterId (62) is treated as incorrect Router ID, while according to the specification this value is still a valid Router ID. I'm affraid that this might generate problems with interoperability with other stacks.

**Comment by jwhui** [comment]
Yes, I agree this is an issue - another one that the Certification Harness does not seem to catch. Please feel free to submit a PR to correct this.

**Comment by rlubos** [comment]
Yes, I'll fix this and submit PR.

**Comment by jwhui** [comment]
Fixed in #625.
