### ISSUE TITLE
[github-actions] tun-realm-local-multicast.exp fails intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#5980]
**Describe the bug**

tun-realm-local-multicast.exp fails intermittently

**Console/log output**

- [logs_46415.zip](https://github.com/openthread/openthread/files/5719877/logs_46415.zip)
- [core-expect-posix.zip](https://github.com/openthread/openthread/files/5719875/core-expect-posix.zip)
- [syslog-expect-posix.zip](https://github.com/openthread/openthread/files/5719876/syslog-expect-posix.zip)

**Comment by bukepo** [comment]
Does this failure still happen?

**Comment by jwhui** [comment]
I haven't seen this in a while. Closing.
