### ISSUE TITLE
Trickle Timer implementation

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#600]
Question: Do you plan to implement stand-alone Trickle Timer module that could be used for MLE Advertisement and in future for MPL retransmissions?

**Comment by jwhui** [comment]
Yes, that would make sense once we have multiple use cases for Trickle implemented.

**Comment by nibanks** [comment]
I had implemented most of the trickle timer logic and multicast forwarding logic in my Thread implementation before moving to use OpenThread instead. If you would like, I could take a stab at it for you.

**Comment by jwhui** [comment]
Resolved by #603.
