### ISSUE TITLE
[random manager] should we check the return value of mbedtls_ctr_drbg_seed?

### ISSUE THREAD

**Issue by dismirlian** [openthread/openthread#6014]
Related to #6013, I experienced a hard-to-debug issue, which was masked by the fact that `RandomManager::CryptoCtrDrbg::Init` doesn't check the return value of `mbedtls_ctr_drbg_seed`, leaving the user unaware that the random hardware generator failed.

https://github.com/openthread/openthread/blob/7fe84c59cdf6ce1070ac2d877d826779a04df140/src/core/common/random_manager.cpp#L191-L195

Is this intended? Should we print an error message? Should we assert?

Thanks.

**Comment by jwhui** [comment]
@dismirlian , thanks for raising this issue.

At a minimum, I think it would be great to emit a critical-level log and assert. Would you be willing to submit a PR for that?

**Comment by dismirlian** [comment]
Hi @jwhui I can submit a PR. Would it be sufficient to assert? Do you think there should be also a critical level message?

**Comment by jwhui** [comment]
Yes, I think we should have both a critical-level log and assert (as mentioned in https://github.com/openthread/openthread/issues/6014#issuecomment-755770014).
