### ISSUE TITLE
[devsite] seeming mistakes in Hardware Codelab

### ISSUE THREAD

**Issue by Irving-cl** [openthread/openthread#6031]
**Describe the bug**
1. `NCP` are still used in some places. [Codelab #Step4](https://openthread.io/codelabs/openthread-hardware#3) says, "**Set up the RCP Joiner**". And `ot-ctl` is used to manage the Thread device. However, the title of **Step8** is "Add the NCP Joiner". And there are many other occurrences of `NCP` and `wpantund`, `wpanctl`. It seems that there's no NCP in this codelab. I guess it's from the last version. Should these be updated? Other occurrences: 
    * **Step7**, in the code block to show `ot-ctl` for RCP Joiner, `wpanctl:utun7> scan`.
    * **Step8**, `NCP` and `wpanctl` command are still used in text, code blocks and topology graph.

Thoughts? @Vyrastas @jwhui

**Comment by Vyrastas** [comment]
Yeah, I have a long-standing task to update this Codelab to remove the references to wpantund and wpanctl, but I haven't had time lately.  I'll try to take a look later this week but if someone else (a Googler) wants to update, the Codelabs are now on openthread.io so they can be edited like any other openthread.io source file.

**Comment by Irving-cl** [comment]
@Vyrastas 

Ok, I think I can do it as I just played with it recently.

**Comment by jwhui** [comment]
Codelab updates have been published.
