### ISSUE TITLE
Transmitting sensor data from thread network to external IPv6 network

### ISSUE THREAD

**Issue by ToMiller** [openthread/openthread#6098]
Hello,

I have just been getting started with openthread and am trying to read sensor data from a EFR32 board, and want to send these data via a borderrouter to an external network.
I have created an ot-cli-ftd example on my EFR32 and can read out sensor data, and I also have a borderrouter working. I have connected them both in one mesh-network and can transmit the data.

However I find it difficult to find the right approach to send the data to an external network. I don't need to send the data to the borderrouter and then from there send it to an IPv6 address, right?
I found several approaches, like CoAP and MQTT, but I can't find no example for my EFR32, so I guess I have to create the script on my own. So, would you suggest going with CoAP or MQTT?
And is there any good tutorial I can follow to solve my problem?

Thank you!

**Comment by maxikrie** [comment]
I am currently trying to achieve something similar and I have decided for DDS employing following open source implementation with support for constrained devices - https://github.com/eProsima/Fast-DDS. So far it looks promising, but I hit an obstacle with the thread - I can let you know more once this is resolved.

An alternative would be MQTT-SN, but I don't like that beyond the embedded devices MQTT is TCP based, which is too much overhead for the data I am interested in. Maybe somebody else with more experience can comment on MQTT(-SN) and ideally also DDS or CoAP.

**Comment by maxikrie** [comment]
https://github.com/openthread/openthread/issues/6053#issue-782606606

**Comment by jwhui** [comment]
> However I find it difficult to find the right approach to send the data to an external network. I don't need to send the data to the borderrouter and then from there send it to an IPv6 address, right?

Yes, given that Thread is an IPv6 network, a packet's destination can be any IPv6 host that is reachable from the Thread device.

> I found several approaches, like CoAP and MQTT, but I can't find no example for my EFR32, so I guess I have to create the script on my own. So, would you suggest going with CoAP or MQTT?

Both CoAP or MQTT are IP-based protocols. Either approach should work, but which is better will depend on your specific use case.

> And is there any good tutorial I can follow to solve my problem?

Unfortunately, we do not have any tutorials specific to CoAP or MQTT. However, I believe some silicon vendors supporting OpenThread have examples and tutorials as part of their SDKs.

**Comment by jwhui** [comment]
Closing stale issue.
