### ISSUE TITLE
[codelab]  typo in codelab3  (Simulate a Thread Network)

### ISSUE THREAD

**Issue by paragdixit-g** [openthread/openthread#6100]
In codelab 3 (Simulate a Thread Network),  under  'Verify the Network', under '1. Check connectivity'
 this line: 
"Node 1's RLOC of 0x5800 is found in the table"
should likely be:
"Node 2's RLOC of 0x5800 is found in the table"

**Comment by jwhui** [comment]
@paragdixit-g , thanks for pointing that out. I agree.

**Comment by Irving-cl** [comment]
Thanks. I've submitted a CL for that.

**Comment by Irving-cl** [comment]
Fixed.

**Comment by Vyrastas** [comment]
Thanks @Irving-cl 👍
