### ISSUE TITLE
mTransport field is not initialized when using otUdpSocket

### ISSUE THREAD

**Issue by wbober** [openthread/openthread#614]
I'm playing around with using ot from plain C code. There is an issue when otUdpSocket is used as below:

    otUdpSocket m_socket;
    if (otOpenUdpSocket(sInstance, &m_socket, udp_receive, NULL) != kThreadError_None)
    {
    	printf("Failed to create socket\r\n");
    	goto exit;
    }

The`otOpenUdpSocket()` function will crash because the `mTransport` is NULL. This is because there is no constructor to initialize this field.

To get my self going I just modified `otOpenUdpSocket()` to init the `mTransport` field of a socket if NULL. 

Should I add PR with this modification or do we add `otInitUdpSocket()` or alike to the API?

**Comment by jwhui** [comment]
This issue is being tracked in #571.  Let's continue the discussion there.
