### ISSUE TITLE
[doc] Links to ot-nrf528xx example have expired.

### ISSUE THREAD

**Issue by Irving-cl** [openthread/openthread#6161]
**Describe the bug**
In ot-nrf528xx [README.md](https://github.com/openthread/ot-nrf528xx/blob/main/README.md), the links to the examples have expired. Clicking them leads to 404 Page not found.
![Screen Shot 2021-02-11 at 10 54 42 AM](https://user-images.githubusercontent.com/12945188/107598037-986a7400-6c57-11eb-9254-11b69b743b2a.png)

**Comment by jwhui** [comment]
See https://github.com/openthread/ot-nrf528xx/pull/2

**Comment by Irving-cl** [comment]
Thanks! Then we can wait for the PR.
