### ISSUE TITLE
NCP set xpanid & masterkey doesn't work

### ISSUE THREAD

**Issue by shahab5** [openthread/openthread#618]
Hi,

I used wpantund to set `Network:XPANID` and `Network:Key` , it reports parse error.

I debugged to find that `spinel_datatype_unpack` uses `SPINEL_DATATYPE_DATA_S` as `pack_format`.
The `ptr` returned points to a string of characters and not integers and as such the length check fails (size of characters is double the expected size).

There should be a conversion from `char` to `int` before proceeding here.

Thanks,
Shahab

**Comment by darconeous** [comment]
When you specify `Network:Key`, you need to use the `--data` argument to indicate that the parameter is hexadecimal-encoded binary data:

    wpanctl set Network:Key --data 00112233445566778899aabbccddeeff

**Comment by shahab5** [comment]
Thanks for the info.
Will try and update.

Regards
Shahab

**Comment by shahab5** [comment]
Verified, its working.
closing this issue.
