### ISSUE TITLE
VIRTUAL_TIME thread-cert test cases get stuck when the frame is incorrect

### ISSUE THREAD

**Issue by Irving-cl** [openthread/openthread#6203]
**Describe the bug** A clear and concise description of what the bug is.
When I run a test case with `VIRTUAL_TIME=1`(there's some errors in my binaries), the case got stuck forever. This causes the workflow on github action always running (not showing that the case fail). If I run it locally, it's like this:
> 3: state
> 1: ipaddr
> 2: ping fe80:0:0:0:146e:a00:0:1
> 3: ping fe80:0:0:0:146e:a00:0:1
> 2: linkmetrics mgmt fe80:0:0:0:146e:a00:0:1 enhanced-ack register m  **#!!! it got stuck here**
> ^CTraceback (most recent call last):
>   File "./tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py", line 390, in <module>
>     unittest.main()
>   File "/usr/lib/python3.6/unittest/main.py", line 95, in \_\_init\_\_
>     self.runTests()
>   File "/usr/lib/python3.6/unittest/main.py", line 256, in runTests
>     self.result = testRunner.run(self.test)
>   File "/usr/lib/python3.6/unittest/runner.py", line 176, in run
>     test(result)
>   File "/usr/lib/python3.6/unittest/suite.py", line 84, in \_\_call\_\_
>     return self.run(*args, \*\*kwds)
>   File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
>     test(result)
>   File "/usr/lib/python3.6/unittest/suite.py", line 84, in \_\_call\_\_
>     return self.run(\*args, \*\*kwds)
>   File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
>     test(result)
>   File "/usr/lib/python3.6/unittest/case.py", line 653, in \_\_call\_\_
>     return self.run(\*args, \*\*kwds)
>   File "/usr/lib/python3.6/unittest/case.py", line 605, in run
>     testMethod()
>   File "./tests/scripts/thread-cert/v1_2_LowPower_7_1_01_SingleProbeLinkMetricsWithEnhancedAcks.py", line 104, in test
>     self.simulator.go(5)
>   File "/home/openthread/tests/scripts/thread-cert/simulator.py", line 513, in go
>     self.receive_events()
>   File "/home/openthread/tests/scripts/thread-cert/simulator.py", line 358, in receive_events
>     self._add_message(addr[1] - self.port, data)
>   File "/home/openthread/tests/scripts/thread-cert/simulator.py", line 201, in _add_message
>     messages = self._message_factory.create(io.BytesIO(message_obj))
>   File "/home/openthread/tests/scripts/thread-cert/message.py", line 598, in create
>     ipv6_packet = self._lowpan_parser.parse(lowpan_payload, message_info)
>   File "/home/openthread/tests/scripts/thread-cert/lowpan.py", line 1131, in parse
>     return self._handle_iphc_header(data, message_info)
>   File "/home/openthread/tests/scripts/thread-cert/lowpan.py", line 1088, in _handle_iphc_header
>     ipv6_header, extension_headers, udp_header = self._decompress_iphc(data, message_info)
>   File "/home/openthread/tests/scripts/thread-cert/lowpan.py", line 1024, in _decompress_iphc
>     return self._lowpan_decompressor.decompress(data, message_info)
>   File "/home/openthread/tests/scripts/thread-cert/lowpan.py", line 811, in decompress
>     header_first_byte = ord(self._peek_n_bytes(data, 1))
>   File "/home/openthread/tests/scripts/thread-cert/lowpan.py", line 791, in _peek_n_bytes
>     data.seek(-n, io.SEEK_CUR)

**Expected behavior** A clear and concise description of what you expected to happen.
So it is actually stuck at `lowpan.py`. We should make it in a way that the script returns an error.

**Comment by simonlingoogle** [comment]
One quick fix is that you can add `USE_MESSAGE_FACTORY = False` to your test case to skip message decoding since we are using `pktverify` for this test case.
