### ISSUE TITLE
Possible vulnerability to replay attack in LinkAccept handler

### ISSUE THREAD

**Issue by hubertmis** [openthread/openthread#624]
LinkAccept handler compares received Response TLV with both mChallenge (generated for multicast LinkRequest) and neighbor->mPending.mChallenge (generated for unicast LinkRequest).  If at least one of challenges matches Response TLV, LinkAccept message is accepted.

IMHO Response TLV should be compared with only one (appropriate) Challenge value and multicast mChallenge value should be invalidated after timeout to make sure replay attack is not possible.

**Comment by jwhui** [comment]
I agree.  Will you submit a PR to address this issue?

**Comment by hubertmis** [comment]
Sure. Will do.
