### ISSUE TITLE
OPENTHREAD WITHOUT RASPBERRY PI

### ISSUE THREAD

**Issue by SriNagaC** [openthread/openthread#6244]
to openthread-users
Dear,

I am using Efr32mg12 2.4ghz BRD4161A Radio broads using simplicity studio V5(silicon labs).

my project Target is i want create mesh network.

I want make LED light ON/OFF in light device(3-4 devices) FROM THE SWITCH device BUTTON.

i am thinking to use you can use a Thread FTD (Full Thread Device) to act as Thread leader to form Thread network. Then, use some other FTD to act as Thread router and MTD (Minimal Thread Device) to act as end device to join the network for testing Thread mesh network. For controlling 3-4 lights from switch device, i am thinking to  implement light functionality on routers and switch on end device to make it.

for the over communicate i am Thinking to use UDP Protocol to make light on/off in light devices from the switch button. 

Can you any help me how can i make this functionality in code.

can you anyone suggest me any example code to achieve this functionality. 

I will wait for your kind response regarding this here.

Thanking you in advance

**Comment by jwhui** [comment]
Our [Developing with OpenThread APIs](https://openthread.io/codelabs/openthread-apis#0) codelab might be helpful.
