### ISSUE TITLE
Error in instructions on https://openthread.io/codelabs/openthread-hardware#3

### ISSUE THREAD

**Issue by squishykid** [openthread/openthread#6254]
**Describe the bug** When running the guide, I had to run `script/build nrf52840 USB_trans` instead of `script/build nrf52840 UART_trans`. Otherwise ot-daemon would exit with `[CRIT]-PLAT----: platformRadioInit() at ../../src/posix/platform/radio.cpp:105: InvalidArgument`

**To Reproduce** Information to reproduce the behavior, including:

1. Follow the guide: https://openthread.io/codelabs/openthread-hardware#3
2. `/dev/acmTTY0` does not show up

**Expected behavior** `/dev/acmTTY0` to show up

**Console/log output**
```
./build/posix/src/posix/ot-daemon -v 'spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200'
./build/posix/src/posix/ot-daemon[206454]: Running OPENTHREAD/20191113-01773-gda1b0ddbe-dirty; POSIX; Mar  9 2021 18:40:08
./build/posix/src/posix/ot-daemon[206454]: Thread version: 2
./build/posix/src/posix/ot-daemon[206454]: [CRIT]-PLAT----: Init() at ../../src/posix/platform/hdlc_interface.cpp:150: InvalidArgument
```

**Additional context** https://groups.google.com/g/openthread-users/c/tGodlrI9H7g?pli=1

**Comment by bukepo** [comment]
Thank you for reporting this issue. We are fixing the guide.

**Comment by jwhui** [comment]
The codelab has been updated. Thanks, @squishykid !
