### ISSUE TITLE
[github-actions] v1_2_test_csl_transmission.py fails intermittently

### ISSUE THREAD

**Issue by brianljt** [openthread/openthread#6256]
@bukepo points out that CI test thread-1-2-posix fails intermittently.

https://github.com/openthread/openthread/runs/2064804931?check_suite_focus=true

**Comment by wgtdkp** [comment]
More failure logs:
[logs-csl-trransmission.txt](https://github.com/openthread/openthread/files/6154883/logs-csl-trransmission.txt)
[thread-1-2-posix-pcaps.zip](https://github.com/openthread/openthread/files/6154884/thread-1-2-posix-pcaps.zip)
