### ISSUE TITLE
CLI: Routers and children list

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#626]
I find it a little bit difficult to debug network topology using OpenThread's CLI.

To list all routers or children, two steps procedure is required:

![router_list_old](https://cloud.githubusercontent.com/assets/5144764/18632995/808a7062-7e7a-11e6-9605-8636fc63332e.png)

What do you think about changing behaviour of "router/child list" to something like below? Alternatively to introduce a new one like "router/child table".

![router_list](https://cloud.githubusercontent.com/assets/5144764/18633068/d2a3404a-7e7a-11e6-9a86-9344f3321847.png)
![child_list](https://cloud.githubusercontent.com/assets/5144764/18633074/d67a7bb6-7e7a-11e6-9736-fbcb948e0b36.png)

If yes i will send a PR. The downside is the limit of kTxBufferSize, that is not a problem with current approach.

**Comment by xiaom-GitHub** [comment]
@LuDuda The new router/child list looks very pretty. However, current THCI implementation parses and abstracts the key network information from previous output format. Maybe introducing a new cli is better, but not sure if it's a little redundancy for memory resources.

**Comment by wbober** [comment]
@xiaom-GitHub 
Maybe a parameter to router/child list command would be an option? For example:
`router pretty-list` or simply `router table`

**Comment by xiaom-GitHub** [comment]
@wbober Yes, definitely, that would be a feasible option with a different argument.

**Comment by jwhui** [comment]
The list format looks great - feel free to submit a PR that supports the new format with a command-line option.

**Comment by jwhui** [comment]
Addressed in #662.
