### ISSUE TITLE
[github-actions] v1_2_test_csl_transmission.py fails

### ISSUE THREAD

**Issue by wgtdkp** [openthread/openthread#6267]
Describe the bug

./tests/scripts/thread-cert/border_router/v1_2_test_csl_transmission.py fails intermittently.

Console/log output

- https://github.com/openthread/openthread/pull/6237/checks?check_run_id=2082343326
- [thread-1-2-posix-pcaps.zip](https://github.com/openthread/openthread/files/6120272/thread-1-2-posix-pcaps.zip)

**Comment by brianljt** [comment]
Dup of #6256
