### ISSUE TITLE
Openthread video guide or tutorial?

### ISSUE THREAD

**Issue by Hard1kPrajapat1** [openthread/openthread#6269]
Hello Team,

I am new to this technology, and I want to adopt the tutorial or any video lecture for the Openthread to learn. I have searched the same on Udemy google but could not found. Is there any link or websites where we can have and learn?

Thanks,
Hardik

**Comment by jwhui** [comment]
There are a number of guides and tutorials linked on https://openthread.io/

**Comment by Hard1kPrajapat1** [comment]
Thanks for sharing the link, there are a lot of guides available which will be useful. But I am looking for the Video tutorial which explains the openthread from scratch, its connectivity, and working.

**Comment by jwhui** [comment]
> Thanks for sharing the link, there are a lot of guides available which will be useful. But I am looking for the Video tutorial which explains the openthread from scratch, its connectivity, and working.

There is a video from Google I/O 2018 on the front page of https://openthread.io/ that provides an overview of Thread and OpenThread.

**Comment by Hard1kPrajapat1** [comment]
Okay, thank you so much.
