### ISSUE TITLE
[github-actions] v1_2_LowPower_5_3_01_SSEDAttachment.py fails intermittently.

### ISSUE THREAD

**Issue by wgtdkp** [openthread/openthread#6272]
**Console/log output**
[ packet-verification-low-power.log](https://github.com/openthread/openthread/files/6127431/packet-verification-low-power.txt)
[packet-verification-low-power-pcaps.zip](https://github.com/openthread/openthread/files/6127451/packet-verification-low-power-pcaps.zip)

**Comment by jwhui** [comment]
Dup of #6401
