### ISSUE TITLE
[github-actions] v1_2_test_csl_transmission.py fails intermittently.

### ISSUE THREAD

**Issue by wgtdkp** [openthread/openthread#6273]
**Console/log output**

[thread-1.2-posix.log](https://github.com/openthread/openthread/files/6127500/thread-1.2-posix.log)

[thread-1-2-posix-pcaps (1).zip](https://github.com/openthread/openthread/files/6127540/thread-1-2-posix-pcaps.1.zip)

**Comment by jwhui** [comment]
Dup of #6267
