### ISSUE TITLE
[github-actions] Cert_9_2_02_MGMTCommissionerSet fails intermittently

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/openthread#6296]
Cert_9_2_02_MGMTCommissionerSet fails intermittently

[packet-verification-pcaps.zip](https://github.com/openthread/openthread/files/6154355/packet-verification-pcaps.zip)

[logs_61308.zip](https://github.com/openthread/openthread/files/6154354/logs_61308.zip)

**Comment by jwhui** [comment]
Have not seen this failure for a while. Closing.
