### ISSUE TITLE
API Code lab typo on step 6

### ISSUE THREAD

**Issue by HannanSolo** [openthread/openthread#6366]
**Describe the bug** A clear and concise description of what the bug is.
On step 6 on the api code lab it instructs to add this line of code.
```
/* Register Thread state change handler */
otSetStateChangedCallback(instance, handleNetifStateChanged, instance);
```
after the `otCliUartInit` call, but in reality the `otCliUartInit` has been changed to `otAppCliInit(instance)`

**Comment by jwhui** [comment]
@HannanSolo , thanks for raising this issue. We'll update the codelab accordingly.

**Comment by Vyrastas** [comment]
This is fixed.
