### ISSUE TITLE
Brew not installed

### ISSUE THREAD

**Issue by thcu-gp** [openthread/openthread#6367]
This line assumes the `brew` command is available.
On my freshly installed Ubuntu 18.04 it isn't.
There seems to be code to select a package manager (which is `apt` on Ubuntu), but still uses `brew` for this one step.
https://github.com/openthread/openthread/blob/d0bbfe6e4c0d173bd41423842dbb2f9bad6a2137/script/bootstrap#L50

**Comment by bukepo** [comment]
unfortunately,  `apt` doesn't provide this package. This line tries its best to install shfmt if `brew` is available.

**Comment by thcu-gp** [comment]
The script failed ungracefully once (that's  why I opened the issue)
But on the last try it showed the warning properly.
Closing the issue
