### ISSUE TITLE
[github-actions] v1_2_test_csl_transmission fails intermittently

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#6449]
The job:
https://github.com/openthread/openthread/pull/6428/checks?check_run_id=2348812753
The pcap:
[thread-1-2-gcc-m32-pcaps.zip](https://github.com/openthread/openthread/files/6314848/thread-1-2-gcc-m32-pcaps.zip)

**Comment by brianljt** [comment]
Hi @bukepo, would you please also upload the artifacts like pcap and log? Thank you!

**Comment by bukepo** [comment]
another failure:
https://github.com/openthread/openthread/pull/6450/checks?check_run_id=2358701469
artifacts:
[thread-1-2-clang-m64-pcaps.zip](https://github.com/openthread/openthread/files/6322243/thread-1-2-clang-m64-pcaps.zip)
