### ISSUE TITLE
[github-actions] v1_2_LowPower_5_3_01_SSEDAttachment.py fails intermittently

### ISSUE THREAD

**Issue by bukepo** [openthread/openthread#6455]
Job:
https://github.com/openthread/openthread/pull/6451/checks?check_run_id=2350287690

Pcap:
[packet-verification-low-power-pcaps.zip](https://github.com/openthread/openthread/files/6318477/packet-verification-low-power-pcaps.zip)

**Comment by jwhui** [comment]
Dup of #6041
