### ISSUE TITLE
Issue on commissionig EFR32mg12 device into network

### ISSUE THREAD

**Issue by 99002507** [openthread/openthread#6486]
I have followed  instructions from [https://www.silabs.com/documents/public/quick-start-guides/qsg170-openthread-sdk-quick-start-guide.pdf](url) to act as thread end device.

I have only one device, followed the instructions and made it as a leader.

My problem here is, As I have only one EFR32 device and made it as Leader and I can see from BorderRouters wpanctl status that BorderRouter is acting as Leader, but there can be only one leader in a thread network right?

By that assumption I've followed the steps to make EFR32 device as child this time and at masterkey step, I've used Network key mentioned in FORM section in web GUI[10.42.0.1] and at end when I check for the end device state as mentioned in instructions, it is showing as detached.
Need help to check whether I'm following correct steps or missing something here, If I'm missing something need to know how to make the EFR32 device as child and work with it.

**Comment by jwhui** [comment]
See response at https://groups.google.com/g/openthread-users/c/jDNeiIqsFzc/m/WVstLRjoCgAJ
