### ISSUE TITLE
[github-actions] frequent failures of `cli-ftd-otns`

### ISSUE THREAD

**Issue by abtink** [openthread/openthread#6520]
Noticed that `cli-ftd-otns` seems to be failing more frequently (than before): 
- https://github.com/openthread/openthread/actions/workflows/simulation-1.1.yml
- Example: https://github.com/openthread/openthread/runs/2448314372?check_suite_focus=true
(Seems to be related to "Generate coverage" step).

@simonlingoogle can you please help take a look. Thanks.

**Comment by jwhui** [comment]
See https://github.com/openthread/ot-ns/pull/123
