### ISSUE TITLE
send message 

### ISSUE THREAD

**Issue by anying11** [openthread/openthread#6594]
What should I do if I want to send a string from a end device to a border router through cli?

**Comment by jwhui** [comment]
See [src/cli/README_UDP.md](https://github.com/openthread/openthread/blob/main/src/cli/README_UDP.md).

**Comment by anying11** [comment]
Can  the ipv6 address be found  through cli ,or I have to  make up it ?

**Comment by jwhui** [comment]
> Can the ipv6 address be found through cli ,or I have to make up it ?

See [src/cli/README.md#ipaddr](https://github.com/openthread/openthread/blob/main/src/cli/README.md#ipaddr)

**Comment by anying11** [comment]
In the "udp send <ip> <port> <message>" partition,what does port mean?Does this mean that the port it already use or a brand new port?

**Comment by simonlingoogle** [comment]
The port of `udp send` command is the destination port.

**Comment by anying11** [comment]
May I ask what does the "eventTypeAlarmFired" mean?

**Comment by anying11** [comment]
How can I get all the information in all of the border routers,even without the connection to Wifi?Is this possible?

**Comment by jwhui** [comment]
Closing stale issue.
