### ISSUE TITLE
End-devices do not seem to send user added on-mesh-prefix to leader

### ISSUE THREAD

**Issue by anthonykustasamberbox** [openthread/openthread#6633]
I am having an issue where I am trying to add an on-mesh-prefix using wpantund to a device on the edge of a 19 device setup and the on-mesh-prefix fails to make it to the leader and propagate through the network. The device I am setting up the prefix on is an end-device in this situation.
When I tried running some tests on a smaller network of 4 devices, I see that the on-mesh-prefix only propitiates through the network when the device that I configured gets promoted from an end-device to a router.

It seems like the on-mesh-prefix does not propagate from an end-device. Any assistance in getting the on-mesh-prefix to propagate through the network from an end device would be appreciated!

Setup:
Radio - SiLabs ERF32 MGM12P32GE
Openthread Git commit - 394739f3d840ab0b43b99226e08af18368fb892d
_^ I have had this issue with multiple git commits. This is the most recent one I have tried_
Wpantund commit - 523bdab12ee0a0450450423fc39e66970b6774b8

I am running the following command when adding the prefix on the end-device
`wpanctl -I tun0 add-prefix fdd1:2780:66a7:150b:: -o -a -f`

**Comment by jwhui** [comment]
@anthonykustasamberbox , is your end device a router-eligible end device (REED)? If so, I believe #6613 will address your issue.

Prior to #6613, we had logic to delay registering network data if the device is waiting to become a router. The Thread Specification requires a random delay of up to 2 minutes, which can be a long time when waiting for network data to appear.
