### ISSUE TITLE
Why use IEEE 802.15.4-2006?

### ISSUE THREAD

**Issue by purvisb** [openthread/openthread#6648]
[This page](https://openthread.io/guides/porting) says openthread requires a [IEEE 802.15.4-2006](https://standards.ieee.org/standard/802_15_4-2006.html) 2.4 GHz radio. 

Why not use a newer version of 802.15.4 like [IEEE 802.15.4-2011](https://standards.ieee.org/standard/802_15_4-2011.html) or [IEEE 802.15.4z-2020](https://standards.ieee.org/standard/802_15_4z-2020.html)?

I am naïve on this subject. Please bear that in mind when responding.

**Comment by jwhui** [comment]
IEEE 802.15.4-2006 provides the broadest silicon availability and compatibility with existing product designs. Thread was designed with the goal of leveraging proven technologies, economies of scale, and fast time to market.

**Comment by purvisb** [comment]
@jwhui Thank you for the prompt response. That makes sense.

Any initial thoughts on the challenges that would be encountered with modifying OpenThread to use 802.15.4z-2020? Or are there no obvious obstacles (besides development time)?

**Comment by jwhui** [comment]
I haven't looked into it much myself.

You may find this effort interesting: https://github.com/Decawave/mynewt-dw1000-core

**Comment by purvisb** [comment]
Thank you for sharing.

**Comment by markus-becker-tridonic-com** [comment]
@jwhui are you sure that IEEE 802.15.4-2006 is enough? Especially OT_RADIO_CAPS_TRANSMIT_TIMING and OT_RADIO_CAPS_TRANSMIT_SEC might require a newer version of the standard, or?

**Comment by jwhui** [comment]
> @jwhui are you sure that IEEE 802.15.4-2006 is enough? Especially OT_RADIO_CAPS_TRANSMIT_TIMING and OT_RADIO_CAPS_TRANSMIT_SEC might require a newer version of the standard, or?

@markus-becker-tridonic-com , it depends on the Thread version and the features within. IIEEE 802.15.4-2015 is only required when implementing Enh-Ack or CSL as a part of Thread 1.2. Thread 1.2 routers are required to support IEEE 802.15.4-2015, but not Thread 1.2 end devices. Also Thread 1.1 devices are not required to support IEEE 802.15.4-2015.
