### ISSUE TITLE
GRL 1.1 TH reports "Contract class not implemented -OpenThreadNo module named commissioner" using current THCI and DeviceInputFields.xml

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/openthread#6738]
**Describe the bug** A clear and concise description of what the bug is.
**Console/log output** If applicable, add console/log output to help explain your problem.

```
Thread V1.1 Test Harness Release 2.2.2
Python Version:  2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
ARM True
Kirale True
NXP True
OTFF True
OTN True
OTS True
Error: THCI cannot be included OpenThread has error or Does not implement Contract class(iThci)
Log -->   [Contract class not implemented -OpenThreadNo module named commissioner]

Error: THCI cannot be included OpenThread_BR has error or Does not implement Contract class(iThci)
Log -->   [Contract class not implemented -OpenThread_BRNo module named commissioner]
```

1. Git commit id - `95c5cb793`
4. Network topology - `GRL 1.1`

**Expected behavior** A clear and concise description of what you expected to happen.

> I expected the THCI to load into GRL without error but it cannot locate this commissioner module.  I attempted to follow the steps in the readme, however it looks like that file is not updated since it contains no references to OpenThread_BR.py.  It would be nice to have up to date instructions for this installation if possible!

**Comment by simonlingoogle** [comment]
Thanks for reporting this bug. `commissioner` library exists only in Thread Dev Harness 1.2. 

Will file a PR to fix.

**Comment by JaneFromSilabs** [comment]
Thank you for the fix!  This new THCI is loading up just fine in the 1.1 TH.
