### ISSUE TITLE
Missing duration update in wait() method in otci.py

### ISSUE THREAD

**Issue by qilinkang** [openthread/openthread#6755]
**Describe the bug** A clear and concise description of what the bug is.

https://github.com/openthread/openthread/blob/main/tools/otci/otci/otci.py

For wait() in otci.py duration variable in while loop has not been updated:

while duration > 0:
                output = self.__otcmd.wait(1)
                if match_line(expect_line, output):
                    success = True
                    break

if not success:
                raise ExpectLineTimeoutError(expect_line)

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by simonlingoogle** [comment]
Good catch. Thanks @qilinkang . 
I will file a fix ASAP.

**Comment by simonlingoogle** [comment]
@qilinkang I have sent https://github.com/openthread/openthread/pull/6759 to fix this bug. PTAL.
