### ISSUE TITLE
[github-actions] Cert_9_2_16_ActivePendingPartition fails intermittently 

### ISSUE THREAD

**Issue by librasungirl** [openthread/openthread#6793]
[logs_84486.zip](https://github.com/openthread/openthread/files/6766494/logs_84486.zip)
[packet-verification-1.1-on-1.2-pcaps.zip](https://github.com/openthread/openthread/files/6766498/packet-verification-1.1-on-1.2-pcaps.zip)

**Comment by jwhui** [comment]
[logs_95452.zip](https://github.com/openthread/openthread/files/7164668/logs_95452.zip)
[packet-verification-1.1-on-1.2-pcaps.zip](https://github.com/openthread/openthread/files/7164669/packet-verification-1.1-on-1.2-pcaps.zip)

**Comment by jwhui** [comment]
[logs_102697.zip](https://github.com/openthread/openthread/files/7530517/logs_102697.zip)
[packet-verification-pcaps.zip](https://github.com/openthread/openthread/files/7530518/packet-verification-pcaps.zip)

**Comment by jwhui** [comment]
[logs_111185.zip](https://github.com/openthread/openthread/files/7902938/logs_111185.zip)
[packet-verification-1.1-on-1.2-pcaps.zip](https://github.com/openthread/openthread/files/7902942/packet-verification-1.1-on-1.2-pcaps.zip)

**Comment by jwhui** [comment]
Closing stale issue.
