### ISSUE TITLE
Thread sniffer to catch the traffic for ongoing openthread connection

### ISSUE THREAD

**Issue by Hard1kPrajapat1** [openthread/openthread#6794]
Hello Team,

I have created an Openthread network where border routers, other routers, and end devices(nRF52840) are there. I just want to sniff the IPv6 packets on this Openthread network. Can anyone guide or send a link?

I have also checked that the nRf52840 USB dongle can be used for sniffing but I think it will work on the BLE protocol and in my case, I am only going to use thread, not BLE.

Thanks in advance,
Hardik

**Comment by jwhui** [comment]
See:
- https://openthread.io/guides/pyspinel/sniffer
- https://openthread.io/guides/pyspinel/sniffer-extcap

**Comment by Hard1kPrajapat1** [comment]
Thanks @jwhui, I will check those links. Also, can you please confirm the below statement?

The nrf52840 USB dongle is used as a sniffer only in the case of BLE, is it correct? What If I flash it with thread only binary, so will I be able to sniff the thread packets?

**Comment by simonlingoogle** [comment]
> The nrf52840 USB dongle is used as a sniffer only in the case of BLE, is it correct? What If I flash it with thread only binary, so will I be able to sniff the thread packets?

Yes. Both nRF52840 DK and USB Dongle can be used as a Thread sniffer. 

BTW, Make sure to use `USB_trans -DOT_BOOTLOADER=USB` when building firmware for USB Dongle. Please check https://github.com/openthread/ot-nrf528xx/blob/main/src/nrf52840/README.md#nrf52840-dongle-support-pca10059 for more details.

**Comment by jwhui** [comment]
Closing stale issue.
