### ISSUE TITLE
 [GRL Test 9.2.7] Operational Dataset synchronization issue

### ISSUE THREAD

**Issue by schinchani** [openthread/openthread#6804]
Certification Test 9.2.7 fails if the Router node in the topology is running the OpenThread stack.

As per Thread 1.1.1 spec section 8.4.3.5.1  and 8.4.3.5.2,  when attaching to a Thread Network Partition, if the newly received Active/Pending Timestamp is older than what the Thread Device had before attaching, the Thread Device MUST attempt to update the Leader with its newer Active/Pending Operational Dataset. This behavior is not observed on the Router node. The Router (testbed) node fails to synchronize its (newer) active and pending operational datasets, in turn, causing the test case to fail.

It appears that there may also be a potential test plan bug, as the test plan (version R68) steps 5 and 11 instruct the harness to initiate this synchronization for the Router, which should not be the case, as per spec section 8.7.4.2 and  8.7.5.2 which states that:
A Thread Device that has a newer Active/Pending Operational Dataset, as determined by the Active/Pending Timestamp included in Thread Network Data, MUST provide its newer Active/Pending Operational Dataset to the Leader by sending a MGMT_ACTIVE/PENDING_SET.req to the Leader

Although the attached traces are for an older version of OpenThread, I have also observed this issue on a relatively newer version of the OpenThread stack

**Comment by jwhui** [comment]
@schinchani , thanks for raising this issue. I have submitted a proposed fix with #6813. Please review.
