### ISSUE TITLE
[cbor] is CBOR support suggested for the future

### ISSUE THREAD

**Issue by AuSchell** [openthread/openthread#6836]
CBOR is widely accepted as the JSON alternative for constrained devices. Are there any intentions to include a CBOR module to OpenThread?

**Comment by jwhui** [comment]
@AuSchell , currently, only the Thread Commercial Commissioning extensions make use of CBOR. I expect CBOR to be included when Thread Commercial Commissioning extensions are contributed.

**Comment by AuSchell** [comment]
@jwhui, ok, thank you for your answer.
