### ISSUE TITLE
Appveyor account & badge

### ISSUE THREAD

**Issue by beriberikix** [openthread/openthread#684]
Do we have an OpenThread account on Appveyor? I found @nibanks but none for the OT org. When we're ready, we should create one and add a status page to the top-level readme.

**Comment by jwhui** [comment]
We already have one - that's how we get the build status reports for each PR.  I delayed putting it on the README to give appveyor some soak time...

**Comment by beriberikix** [comment]
Duh, I didn't think to look at the PR checks. We can keep this as a tracking bug until appveyor is soaked and the badge is up _or_ close since you're all over it.

**Comment by beriberikix** [comment]
And to save a search, here's the [instructions for Github](https://www.appveyor.com/docs/status-badges/#badges-for-projects-with-public-repositories-on-github-and-bitbucket).

**Comment by nibanks** [comment]
I had already added it to one of my branches to test it out:
https://github.com/nibanks/openthread/tree/windows

**Comment by jwhui** [comment]
@nibanks, feel free to submit a PR that adds the appveyor badge.

**Comment by jwhui** [comment]
Resolved by #741.
