### ISSUE TITLE
no module found crypto

### ISSUE THREAD

**Issue by syrine-design** [openthread/openthread#6866]
![Capture](https://user-images.githubusercontent.com/63754152/127315327-05af424f-f324-4d59-8191-87091b05edf7.PNG)
I have done everything but still i get no module found what can i do ?

**Comment by jwhui** [comment]
There's a number of comments in openthread/openthread#1137
<https://github.com/openthread/openthread/issues/1137> that describe how to
address this issue.

--
Jonathan Hui

**Comment by jwhui** [comment]
Closing stale issue.
