### ISSUE TITLE
Link Quality Indicator (LQI) stale

### ISSUE THREAD

**Issue by farhangj** [openthread/openthread#6874]
Experimenting with nRF52840dks and NRF NCS 1.6.x.

In the OpenThread stack, in the router when I query child info using otThreadGetChildInfoByIndex(), the Link Quality in parameter seems to be stale.
How often does it update and is the scale 0 to 255? I notice Nordic's radio reports LQI divided by a factor of 4 compared to the IEEE 802.15.4 apparently, hence the register value needs to be multiplied by 4. Is this done in the Thread stack? ([https://infocenter.nordicsemi.com/topic/ps_nrf52840/radio.html#ieee802154_ed__fig_sample_ed]

Regardless I am noticing very low LQI values (typically 3) while the RSSI is very healthy, -28dBm (derived from the same func above)
LQI is stuck at 3 and I played with setting txpower on the child node, and that didn't change LQI.

I am sending CoAP messages router -> child with reply back frequently (every 20s) and there's no message losses.
Why is the LQI so low? How do I interpret the values?

**Comment by jwhui** [comment]
Thread does not make use of LQI reported by IEEE 802.15.4 radios. The challenge is that IEEE 802.15.4 does not define LQI sufficiently enough for it to be comparable between different radios.

If you are referring to the link quality values reported in the neighbor tables - for example, as visible in [router table](https://github.com/openthread/openthread/blob/main/src/cli/README.md#router-table) CLI command, that is Thread's definition of link quality. [Thread 1.1.1 Section 5.9.4](https://www.threadgroup.org/support#specifications) defines link quality, with 3 indicating the highest link quality.
