### ISSUE TITLE
Change packet type during Transmission

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/openthread#6898]
Hi, 
In my open thread network, there are 3 types of nodes:
1. SED (Sleepy end devices): They are battery powered and the polling period is 30 seconds.
2. FTD (Full thread devices): They act as routers for SEDs. They have no power consumption restriction.
3. NCP: Which is attached to RPi based Border router. It receives all data packets from SEDs and FTDs.

Following are some additional details:
Git Commit ID: 8a1992e
IEEE 802.15.4 hardware platform : Nordic's nrf52840
SDK: NRF_SDK_for_thread_and_zigbee_4.0

Since SEDs are battery-powered, they send non-confirmable data packets every minute and sleep.

Is it possible that the non-confirmable packet sent by SEDs be converted to the confirmable packet by FTDs, and FTDs do multiple attempts if the packet is not reached to border router?

**Comment by jwhui** [comment]
> Is it possible that the non-confirmable packet sent by SEDs be converted to the confirmable packet by FTDs, and FTDs do multiple attempts if the packet is not reached to border router?

No, Thread does not provide this capability. Thread is an application-layer agnostic networking protocol. A Thread FTD forwards packet at the IPv6 layer and does not perform any application-layer proxying.
