### ISSUE TITLE
[csl] Issues/inconsistencies from otPlatRadioGetNow() and mInfo.mRxInfo.mTimestamp as uint64_t

### ISSUE THREAD

**Issue by George-Stefan** [openthread/openthread#7054]
The value of otPlatRadioGetNow() is uint64_t but it's always downcasted/truncated to uint32_t when converted to a `Time` object (since `uint32_t mValue`).
The same goes for mInfo.mRxInfo.mTimestamp.

Because of this, the code for wraparound check in `GetCslWindowEdges()` is wrong.

```
void SubMac::GetCslWindowEdges(uint32_t &ahead, uint32_t &after)
{
    uint32_t semiPeriod = mCslPeriod * kUsPerTenSymbols / 2;
    uint64_t curTime    = otPlatRadioGetNow(&GetInstance());
    uint64_t elapsed;
    uint32_t semiWindow;

    if (mCslLastSync.GetValue() > curTime)
    {
        elapsed = UINT64_MAX - mCslLastSync.GetValue() + curTime;
    }
    else
    {
        elapsed = curTime - mCslLastSync.GetValue();
    }
```

On top of this, otPlatRadioGetNow() value is not truly an uint64_t on most platforms (36 or 48 bit) so the radio timer/counter doesn't wrap at UINT64_MAX but at a lower value.

We should convert everything to uint32_t before doing any kind of comparison involving the radio timer or Rx timestamp.

**Comment by George-Stefan** [comment]
^^ @doru91, @marius-preda, @mihai-ignat

**Comment by abtink** [comment]
I don't recall/remember  the reason for why `uint64_t` was used for `otPlatRadioGetNow()`.I think practically `uint32_t` should work fine (2^32 usec is about 1 hour). I think we can consider chaging it to `uint32_t` but it may impact existing platform implementations (and also RCP APIs). So it will be a bigger change to the code.

In general I suggest we don't use `otPlatRadioGetNow()` values along with `TimeMilli` and `TimeMicro` (or `Time`) definitions (they are intended for `otPlatAlaramMilli` and `otPlatAlaramMicro` which are `uint32_t`). 
-  I agree the current of `TimeMicro` object to store the CSL last sync `mLastCslSync` in the code is not good  and would be better to change it (since the underlying value is `uint64_t`)

**Comment by jwhui** [comment]
@Irving-cl , can you provide any thoughts on the above?

**Comment by Irving-cl** [comment]
I think it would be big change to the code if we update `otPlatRadioGetNow()` to use `uint32_t`. What about we add another version of `otPlatRadioGetNow()` which returns `uint32_t` and update all Timer to use that new one? And for Timer value comparison, we always wrap at UINT32_MAX. Thoughts? @abtink @George-Stefan

**Comment by simonlingoogle** [comment]
I don't think we should change `otPlatRadioGetNow` to return `uint32` (or anything in general) if there is no obvious benefit. 
`uint32_t`'s range is apparently too small so that there will be wrappings, meanwhile using `uint64_t` may have potential future benefits.

**Comment by George-Stefan** [comment]
The max value for CSL period/phase is on 20bit

**Comment by Irving-cl** [comment]
So the proposal would be: we add a new version of `otPlatRadioGetNow` and use it for Timer (since the field in `Timer` class is just 32bits. And of course, we keep the original version as it is. We can always explicitly cast the 64 bit to 32 bit. But it's troublesome. Adding a new version of `otPlatRadioGetNow` makes things easier. Thoughts? @simonlingoogle

**Comment by simonlingoogle** [comment]
Can we simply use TimeMicro::GetNow() to get the current time, and then the code will be just like:

```
void SubMac::GetCslWindowEdges(uint32_t &ahead, uint32_t &after)
{
    uint32_t semiPeriod = mCslPeriod * kUsPerTenSymbols / 2;
    TimeMicro curTime    = TimeMicro::GetNow();
    uint32_t elapsed;
    uint32_t semiWindow;

    elapsed = curTime - mCslLastSync;
```

**Comment by George-Stefan** [comment]
Let's do all the operation on uint32_t, using the natural wraparound of unsigned values.
Everything will work fine as long as otPlatRadioGetNow() is used as reference everywhere even if it's downcasted to uint32_t

```
void SubMac::GetCslWindowEdges(uint32_t &ahead, uint32_t &after)
{
    uint32_t semiPeriod = mCslPeriod * kUsPerTenSymbols / 2;
    uint32_t curTime    = otPlatRadioGetNow(&GetInstance());
    uint32_t elapsed;
    uint32_t semiWindow;

    elapsed = curTime - mCslLastSync.GetValue();
```

I can do a PR if you agree with my proposal

**Comment by jwhui** [comment]
> Let's do all the operations on uint32_t, using the natural wraparound of unsigned values. Everything will work fine as long as otPlatRadioGetNow() is used as reference everywhere even if it's downcasted to uint32_t
> 
> ```
> void SubMac::GetCslWindowEdges(uint32_t &ahead, uint32_t &after)
> {
>     uint32_t semiPeriod = mCslPeriod * kUsPerTenSymbols / 2;
>     uint32_t curTime    = otPlatRadioGetNow(&GetInstance());
>     uint32_t elapsed;
>     uint32_t semiWindow;
> 
>     elapsed = curTime - mCslLastSync.GetValue();
> ```
> 
> I can do a PR if you agree with my proposal

I think this should work. Please submit a PR. Thanks.

**Comment by simonlingoogle** [comment]
> > Let's do all the operations on uint32_t, using the natural wraparound of unsigned values. Everything will work fine as long as otPlatRadioGetNow() is used as reference everywhere even if it's downcasted to uint32_t
> > ```
> > void SubMac::GetCslWindowEdges(uint32_t &ahead, uint32_t &after)
> > {
> >     uint32_t semiPeriod = mCslPeriod * kUsPerTenSymbols / 2;
> >     uint32_t curTime    = otPlatRadioGetNow(&GetInstance());
> >     uint32_t elapsed;
> >     uint32_t semiWindow;
> > 
> >     elapsed = curTime - mCslLastSync.GetValue();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can do a PR if you agree with my proposal
> 
> I think this should work. Please submit a PR. Thanks.

Just to make it clear. Are we changing `otPlatRadioGetNow` to return uint32_t or not?

BTW, I think we should use `TimeMicro` if possible. `TimeMicro` is introduced for this very purpose. Thoughts? @abtink

**Comment by jwhui** [comment]
> BTW, I think we should use `TimeMicro` if possible. `TimeMicro` is introduced for this very purpose. Thoughts? @abtink

I believe `otPlatRadioGetNow()` was introduced to support RCP, where the time on RCP is what's important. However, given that sub-mac executes on RCP, I think it makes sense to use `otPlatAlarmMicroGetNow()` if possible.

**Comment by jwhui** [comment]
@George-Stefan , can you help clarify your proposal and the question in https://github.com/openthread/openthread/issues/7054#issuecomment-975030778? Feel free to submit a PR directly with a concrete proposal. Thanks!
