### ISSUE TITLE
Request to a new repository to support Infineon platform

### ISSUE THREAD

**Issue by ItoddchouFX** [openthread/openthread#7102]
Hi,
Can you create a new repository to host the support of Infineon 802.15.4 Thread platforms?
The repo name will be "ot-ifx".

Thanks,
Todd

**Comment by jwhui** [comment]
@ItoddchouFX, do you have any updates on the Infineon platform contribution?

**Comment by ItoddchouFX** [comment]
@jwhui I will push Infineon platform support once the CLA review is completed.

**Comment by ItoddchouFX** [comment]
@jwhui Can you enable the "Action" of openthread/ot-ifx?

**Comment by jwhui** [comment]
> @jwhui Can you enable the "Action" of openthread/ot-ifx?

@ItoddchouFX , you should be able to enable GitHub Actions in your own fork.

**Comment by ItoddchouFX** [comment]
@jwhui  https://github.com/openthread/ot-ifx/workflows/Build/badge.svg?branch=main&event=push cannot be found. Can you help?

**Comment by jwhui** [comment]
> @jwhui  https://github.com/openthread/ot-ifx/workflows/Build/badge.svg?branch=main&event=push cannot be found. Can you help?
Here the error is.
https://github.com/ItoddchouFX/ot-ifx/runs/4733964202?check_suite_focus=true

@ItoddchouFX , that error is expected. The link points to the main branch result, for which there are none yet.

**Comment by ItoddchouFX** [comment]
@jwhui  Please help review https://github.com/openthread/ot-ifx/pull/4

**Comment by ItoddchouFX** [comment]
@jwhui Please help review openthread/ot-ifx#4 again.

**Comment by jwhui** [comment]
Resolved by https://github.com/openthread/ot-ifx/pull/4.
