### ISSUE TITLE
How to retrieve the IP Address of a Thread device commissioned onto a network?

### ISSUE THREAD

**Issue by Olivier-STMicroelectronics** [openthread/openthread#7115]
After the commissioning of a Thread device, is there a way to retrieve the IP address of this device?

Thank you

**Comment by Olivier-STMicroelectronics** [comment]
Thank you for your advices.

If I use DNS-SD on the Thread device, this service will be visible from any device of the Thread network but will it be visible from a smartphone connected to the WIFI? (the border router doing the "link" between the wifi network and the thread network).

I want to retrieve the IP address of a Thread device that just been commissioned on the Thread network. The goal is to send it some commands from the smartphone. For the moment, I have the feeling that I should follow the suggestions from Jonathan done in https://github.com/openthread/openthread/issues/7114. It would allow to pass the IP address of the device during the Commissioning itself.

**Comment by jwhui** [comment]
> If I use DNS-SD on the Thread device, this service will be visible from any device of the Thread network but will it be visible from a smartphone connected to the WIFI? (the border router doing the "link" between the wifi network and the thread network).

The service is also discoverable on Wi-Fi. See Step 6 of [Thread Border Router - Bidirectional IPv6 Connectivity and DNS-Based Service Discovery](https://openthread.io/codelabs/openthread-border-router#5).

**Comment by Olivier-STMicroelectronics** [comment]
In the example given, this is the Border Router that advertises the service. 
If the advertising of the service is done by the Thread device, it was not clear to me if it would be visible from devices connected to the WIFI network.

**Comment by wgtdkp** [comment]
> If the advertising of the service is done by the Thread device, it was not clear to me if it would be visible from devices connected to the WIFI network.

The service is registered by the Thread end device to the Border Router and Border Router help advertise the service on WiFi network. So, yes your iPhone can discover the service registered by your end device.

**Comment by Olivier-STMicroelectronics** [comment]
Ok thank you for the clarification!

**Comment by firehills** [comment]
Sorry, late to the discussion but Check the Diag option OT_NETWORK_DIAGNOSTIC_TLV_IP6_ADDR_LIST - issue this to a mesh local scope and you'll get all the addresses of the nodes it can see. Fully supported in the CLI, example issued from a border router output below.

```
pi@rpi4ThreadBROffice:~ $ sudo ot-ctl  networkdiagnostic get ff02::1 8
DIAG_GET.rsp/ans from fe80:0:0:0:e4eb:241:3229:a692: 0880fdde56a3571f9c80000000fffe00fc11fd2a902c8e3800018358118cdb3b9caffdde56a3571f9c80000000fffe00fc10fdde56a3571f9c80000000fffe00fc38fdde56a3571f9c80000000fffe00fc00fdde56a3571f9c80000000fffe003800fdde56a3571f9c803578a87b19ca8e05fe80000000000000e4eb02413229a692
IP6 Address List:
    - fdde:56a3:571f:9c80:0:ff:fe00:fc11
    - fd2a:902c:8e38:1:8358:118c:db3b:9caf
    - fdde:56a3:571f:9c80:0:ff:fe00:fc10
    - fdde:56a3:571f:9c80:0:ff:fe00:fc38
    - fdde:56a3:571f:9c80:0:ff:fe00:fc00
    - fdde:56a3:571f:9c80:0:ff:fe00:3800
    - fdde:56a3:571f:9c80:3578:a87b:19ca:8e05
    - fe80:0:0:0:e4eb:241:3229:a692
DIAG_GET.rsp/ans from fe80:0:0:0:1ca2:783e:cc4e:2b5f: 0840fdde56a3571f9c80000000fffe006800fdde56a3571f9c802fcc0e4d408d0caffe800000000000001ca2783ecc4e2b5ffd2a902c8e3800015f2ea78a2dd23221
IP6 Address List:
    - fdde:56a3:571f:9c80:0:ff:fe00:6800
    - fdde:56a3:571f:9c80:2fcc:e4d:408d:caf
    - fe80:0:0:0:1ca2:783e:cc4e:2b5f
    - fd2a:902c:8e38:1:5f2e:a78a:2dd2:3221
DIAG_GET.rsp/ans from fe80:0:0:0:f0c2:2c97:127a:92f4: 0840fdde56a3571f9c80000000fffe00b000fd2a902c8e380001e069960f28500497fdde56a3571f9c8032ea9ab6595ef07bfe80000000000000f0c22c97127a92f4
IP6 Address List:
    - fdde:56a3:571f:9c80:0:ff:fe00:b000
    - fd2a:902c:8e38:1:e069:960f:2850:497
    - fdde:56a3:571f:9c80:32ea:9ab6:595e:f07b
    - fe80:0:0:0:f0c2:2c97:127a:92f4
Done
pi@rpi4ThreadBROffice:~ $
```
