### ISSUE TITLE
Implement MPL delayed retransmissions.

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#713]
The current MPL implementation retransmits MPL messages only once and without delay.  The implementation needs to be enhanced such that a router retransmits each MPL message multiple times with a randomized delay.

**Comment by LuDuda** [comment]
I am willing to take this task. And if i have a green light i can start to work on it from the next week.

**Comment by jwhui** [comment]
@LuDuda, thanks for picking up this task.

**Comment by LuDuda** [comment]
Just one question. As we agreed here #608 in the first iteration we will do a copy in the application layer (CoAP/MPL) for any retransmission mechanisms. Should we use IP message pool (Ip6::mMessagePool) for this purpose or create a separate configurable message pool in both CoAP and MPL. Personally i believe that eventually in the future we should optimize it in the way that message will not be freed by lower layers when its somehow marked by application, so, for simplicity using IP message pool looks like a good idea for now.

**Comment by jwhui** [comment]
@LuDuda, I agree with your thoughts.  Using the IP message pool seems like the right long-term direction.

**Comment by LuDuda** [comment]
I think this can be closed.

**Comment by jwhui** [comment]
Resolved by #827, #887, and #893.
