### ISSUE TITLE
MbedTls sets Global Allocation Buffers

### ISSUE THREAD

**Issue by nibanks** [openthread/openthread#714]
In the pursuit of getting OpenThread running multiple instances in parallel, I have found a fairly big issue with mbedtls. Take this code for example:

```
MbedTls::MbedTls(void)
{
    mbedtls_memory_buffer_alloc_init(mMemory, sizeof(mMemory));
}
```

That sets some global variables to use this class's private memory buffer. When you have multiple instances, they all end up calling this same code. If you happen to bring up a new instance in the middle of the previous one's operation, you completely reset that instance's buffer. Best case, if you bring up all instances at the same time and shut them down at the same time (which is what we do for python cert tests) you now only have 1 buffer's worth of memory to use for all instances, not to mention that you now have two separate threads accessing the same buffer, with no locks. At the current size of `2048 * sizeof(void*)` that isn't enough to pass the basic commissioning tests (though upping it to `2500` seems to fix it).

I have looked at mbedtls's code and it is infeasible to change it to support instancing. The only other option I could think of would be somehow correct OpenThread's usage of mbedtls use one global, static buffer or implement the alloc/free functions themselves.

Any thoughts?

**Comment by jwhui** [comment]
I think it makes sense for OpenThread to offer a build option that allows the platform to provide its own implementations of `calloc()` and `free()` to mbedtls.  I don't think OpenThread should provide its own alternative implementation of `calloc()` and `free()`, unless we can do much better (i.e. significantly reduce memory overhead) than the mbedtls allocator in the single-instance case.
