### ISSUE TITLE
OTBR: Amount of RAM on Raspberry PI

### ISSUE THREAD

**Issue by OlivierGre** [openthread/openthread#7185]
Hi,
When using a Raspberry Pi for the OpenThread Border Router (ex: a Raspberry Pi 4 Model B), is there a minimal amount of RAM?
This board exists with 4 or 8 GB of memory so I'm wondering if 4GB is enough.
Thank you

**Comment by wgtdkp** [comment]
There is no such requirement, you are free to choose 4 GB to save money :)

**Comment by OlivierGre** [comment]
Good. Thank you
