### ISSUE TITLE
Spinel: How to use functions like spinel_prop_key_to_cstr() ?

### ISSUE THREAD

**Issue by OlivierGre** [openthread/openthread#7206]
In Spinel.c, there are: 
```c++
spinel_prop_key_to_cstr(spinel_prop_key_t prop_key)
spinel_capability_to_cstr(spinel_capability_t capability)
```
(and some others)

How are they intended to be used? They seem not used.

I'm wondering if there is a trace to enable to see a trace (in the UART) for every spinel frame sent or receive.

Thank you

**Comment by abtink** [comment]
These are intended for logging (debugging) and often used by the host side driver (which also uses the `spinel` lib).
(`spinel` is the interface between NCP/RCP and a host).

As an example, these functions are used by [`wpantund`](https://github.com/openthread/wpantund) to log all sent and received spinel messages exchanged between host and NCP (e.g. from [SpinelNCPInstance::log_spinel_frame()](https://github.com/openthread/wpantund/blob/a8f3f761f6753b567d1e5ad22cbe6b0ceb6f2649/src/ncp-spinel/SpinelNCPInstance.cpp#L7000)).

**Comment by OlivierGre** [comment]
Thanks.
in the meantime, I have added my own traces in NcpBase class and I have used them.
