### ISSUE TITLE
are wpantund and OpenThread NCP live again ?

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/openthread#7256]
As per this [https://stackoverflow.com/questions/64311666/replacement-for-wpantund-deprecated/66463966#66463966](link) wpantund and OpenThread NCP are live again and not marked as deprecated anymore. Nordic Semiconductor is committed to develop and maintain them for the OpenThread community for Thread 1.1 and Thread 1.2. 

Is it true?

**Comment by jwhui** [comment]
OpenThread is a community-based, open-source project. The [wpantund](https://github.com/openthread/wpantund/) repo is still active but has not received very many contributions lately. That said, contributions are always welcome!
