### ISSUE TITLE
rcp MLE Announce format error.

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/openthread#7282]
There are two format error in the Announce message.
1 The Fragmentation Header in 6LoWPAN layer is not need.
2 The Channel Page in MLE layer is error.

![image](https://user-images.githubusercontent.com/97089879/148034320-6eadbf54-a691-4166-a6d0-5456cc7d3f0f.png)

**Comment by jwhui** [comment]
@jinpeng1989 , thanks for raising this issue.

> 1. The Fragmentation Header in 6LoWPAN layer is not need.

If you have `OPENTHREAD_CONFIG_MULTI_RADIO` enabled, this is intended behavior. Note that `OPENTHREAD_CONFIG_MULTI_RADIO` is currently enabled by default on OTBR.

https://github.com/openthread/openthread/blob/cbd8512f47043466d0d71f5246f33058bcc1e500/src/core/thread/mesh_forwarder.cpp#L479-L483

> 2. The Channel Page in MLE layer is error.

I have confirmed this is a bug. I have submitted a proposed fix in #7285. Please review. Thanks for catching this!
