### ISSUE TITLE
Consolide codelab_sim Dockerfile into environment Dockerfile

### ISSUE THREAD

**Issue by Vyrastas** [openthread/openthread#7314]
To take advantage of CMake/Ninja and avoid maintaining two different Dockerfiles, let's move any needed functionality from the `codelab_sim` Dockerfile into the `environment` Dockerfile, and use `environment` for the simulation codelab going forward.

I believe it would just mean making sure in `environment` that ping6 works and that OpenThread Daemon / ot-ctl is built (instructions: https://github.com/openthread/openthread/tree/main/src/posix).  Then we can remove `codelab_sim` and update the simulation codelab for the new Dockerfile.

**Comment by jwhui** [comment]
Resolved by #7368

**Comment by j-noel-longhand** [comment]
Hi Jonathan -
I still intend to update the Codelab to reference the
openthread/environment Docker image (will submit pull request once the new
Docker image is available from Dockerhub).

And at some point, we should pull the codelab-otsim Dockerfile from the
repo, if it has no further use.

Thanks,

Jonathan
[image: Google Logo]
Jonathan Donald
Technical Writer (provided by Bárd na nGleann Teoranta)
Nest Smart Home Ecosystem TechPubs
***@***.***

**Comment by jwhui** [comment]
> I still intend to update the Codelab to reference the openthread/environment Docker image (will submit pull request once the new Docker image is available from Dockerhub). And at some point, we should pull the codelab-otsim Dockerfile from the repo, if it has no further use.

Sounds good. Thanks @j-noel-longhand .
