### ISSUE TITLE
Ubuntu does not have ``brew'' as package manager

### ISSUE THREAD

**Issue by zhanghan177** [openthread/openthread#7327]
https://github.com/openthread/openthread/blob/395d502576025f432e37da5538abf53ed4615700/script/bootstrap#L50

This bootstrap script uses `brew` to install shfmt. However, the OS is supposed to use apt-get as package manager (`install_packages_apt()`). This line is ineffective since we will always run into the error:
```
+ brew install shfmt
./script/bootstrap: line 50: brew: command not found
```

**Comment by jwhui** [comment]
The same question was raised in #6367 and a response was provided in https://github.com/openthread/openthread/issues/6367#issuecomment-828116186.

AFAIK, apt does not provide `shfmt` and `snap` has its own problems as mentioned in https://github.com/openthread/openthread/blob/871a7125c9988d042b27c6f24cc6bf44fce90a9c/script/bootstrap#L49.

You can try using `snap` as follows:
```
sudo snap install shfmt
```
