### ISSUE TITLE
When using "simulation" to simulate in Linux, you cannot continuously simulate, and keep prompting "program received signal sig34, real time event 34" information

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7375]
**Additional context** Add any other context about the problem here.

When simulating with Linux, use the CLI mode. When you enter "thread start", the system prompts "program received signal sig34, real time event 34

In __ GI___ select (nfds=7, readfds=0x7fffffffe370, writefds=0x7fffffffe3f0, exceptfds=0x7fffffffe470, timeout=0x7fffffffe360) at ../ sysdeps/unix/sysv/linux/select. c: 69 () ", and then run for 1-2 seconds, constantly prompt the above information, and the simulation can no longer be carried out.

**Comment by jwhui** [comment]
Can you provide more detail about your setup? Are you trying to use GDB?

Note that simulation makes use of linux timers: https://github.com/openthread/openthread/blob/ce77ab3c1d7ad91b284615112ae38c08527bf73e/examples/platforms/simulation/alarm.c#L130

**Comment by tuopu** [comment]
Yes, I use GDB emulation, and Linux uses the latest distribution Ubuntu 21.0,


use&nbsp; “cmake -G"CodeBlocks - Ninja" -DOT_PLATFORM=simulation ..”
The command generates a simulation project in the build directory and uses CodeBlocks software for simulation. GDB can be used for normal simulation in the past, but the latest thread version will get the above information and cannot be simulated normally.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openthread/openthread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月30日(星期天) 凌晨3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openthread/openthread] When using "simulation" to simulate in Linux, you cannot continuously simulate, and keep prompting "program received signal sig34, real time event 34" information (Issue #7375)





 
Can you provide more detail about your setup? Are you trying to use GDB?
 
Note that simulation makes use of linux timers: https://github.com/openthread/openthread/blob/ce77ab3c1d7ad91b284615112ae38c08527bf73e/examples/platforms/simulation/alarm.c#L130
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jwhui** [comment]
Have you tried configuring GDB with the following?
```
handle SIG34 pass nostop noprint
```

**Comment by tuopu** [comment]
After testing, it can run normally. Can you help point out the reason for this message.

**Comment by jwhui** [comment]
As mentioned in https://github.com/openthread/openthread/issues/7375#issuecomment-1024973316, it is caused by a timer that generates a signal and interrupts the process.
