### ISSUE TITLE
Will modifying or renaming a file cause an error

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7377]
In the project, these files have the same name, heap cpp、link_ metrics. cpp、mac_ frame. cpp、radio.c、flash.c, if you modify the file name, whether it will cause an error.

**Comment by jwhui** [comment]
Without knowing details of your project, you should be able to rename files as long as those files are properly included in your build system and any preprocessor references to those files are updated accordingly.

**Comment by tuopu** [comment]
thank you，I see。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openthread/openthread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月1日(星期二) 凌晨2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openthread/openthread] Will modifying or renaming a file cause an error (Issue #7377)





 
Without knowing details of your project, you should be able to rename files as long as those files are properly included in your build system and any preprocessor references to those files are updated accordingly.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
