### ISSUE TITLE
For more information about multiple handles

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7383]
Thread supports multiple handles. For advice, declare multiple handles. Can they be regarded as multiple devices in the network? Each handle has its own network address, or do multiple handles share one address.

**Comment by jwhui** [comment]
If you are referring to an [`otInstance`](https://openthread.io/reference/group/api-instance#otinstance), then they are separate, independent Thread instances. Different instances will appear as separate network interfaces.

**Comment by tuopu** [comment]
I see. Thank you.
