### ISSUE TITLE
how can  set and adjust thread to make it suitable for PHY chip

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7387]
Because the chip I use is 433-868 / 915MHz phys and supports air speed of 20KB / s-1000kb / s, what parameters do I need to set and adjust thread to make it suitable for PHY chip,thank you.

**Comment by jwhui** [comment]
Note that the Thread Specification currently only specifies operation over IEEE 802.15.4 2.4 GHz O-QPSK PHY. While it may be possible to adapt OpenThread to a different PHY, it would not be conformant to the current Thread Specification.

If you want to adapt OpenThread to support a different PHY that has longer communication delays, you may need to adjust various protocol timeouts. The most important ones are likely in MLE (see [src/core/thread/mle_types.hpp](https://github.com/openthread/openthread/blob/main/src/core/thread/mle_types.hpp)) and the MAC (see [src/core/mac/sub_mac.hpp](https://github.com/openthread/openthread/blob/main/src/core/mac/sub_mac.hpp)).

**Comment by tuopu** [comment]
Thank you very much for your reply. I understand and will study further.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openthread/openthread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月3日(星期四) 凌晨2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openthread/openthread] how can  set and adjust thread to make it suitable for PHY chip (Issue #7387)





 
Note that the Thread Specification currently only specifies operation over IEEE 802.15.4 2.4 GHz O-QPSK PHY. While it may be possible to adapt OpenThread to a different PHY, it would not be conformant to the current Thread Specification.
 
If you want to adapt OpenThread to support a different PHY that has longer communication delays, you may need to adjust various protocol timeouts. The most important ones are likely in MLE (see src/core/thread/mle_types.hpp) and the MAC (see src/core/mac/sub_mac.hpp).
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
