### ISSUE TITLE
How to update remote resources with put and post commands  with the coap api

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7388]
I can use the command "coap resource test resource" to create resources, use "coap set testing123" to change resources, and use "coap get FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource" to obtain resources, but I can't update resource values with put and post. The commands are "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource con payload" and "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource block-1024 10", and I don't understand the role of "payload" in "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource con payload", Is it the content of the "test resource" resource?

**Comment by jwhui** [comment]
> I can use the command "coap resource test resource" to create resources, use "coap set testing123" to change resources, and use "coap get FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource" to obtain resources, but I can't update resource values with put and post. The commands are "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource con payload" and "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource block-1024 10", and

The OpenThread CLI is intended to serve as an example of how to use the OpenThread APIs. The current CoAP CLI implementation does not handle the CoAP put and post primitives - see implementation of `Coap::HandleRequest()`: https://github.com/openthread/openthread/blob/3b79cb0d084edc00c7ec8a29f97b0e8a40bbe18c/src/cli/cli_coap.cpp#L603

> I don't understand the role of "payload" in "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource con payload", Is it the content of the "test resource" resource?

"payload" specifies the CoAP message payload.

**Comment by tuopu** [comment]
Thank you very much for your reply. I understand and will study further.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openthread/openthread"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月3日(星期四) 凌晨1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openthread/openthread] How to update remote resources with put and post commands  with the coap api (Issue #7388)





  
I can use the command "coap resource test resource" to create resources, use "coap set testing123" to change resources, and use "coap get FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource" to obtain resources, but I can't update resource values with put and post. The commands are "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource con payload" and "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource block-1024 10", and
  
The OpenThread CLI is intended to serve as an example of how to use the OpenThread APIs. The current CoAP CLI implementation does not handle the CoAP put and post primitives - see implementation of Coap::HandleRequest(): https://github.com/openthread/openthread/blob/3b79cb0d084edc00c7ec8a29f97b0e8a40bbe18c/src/cli/cli_coap.cpp#L603
  
I don't understand the role of "payload" in "coap post FDDE: ad00: beef: 0:2780:9423:166c: 1aac test resource con payload", Is it the content of the "test resource" resource?
  
"payload" specifies the CoAP message payload.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
