### ISSUE TITLE
Ram occupation size if the influence caused by ram is set and reduced

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7408]
Hello, in the current example of thread, the ram of cc2538 is only 32K, while the memory occupation of nrf52840 after compilation is 80K. expert，how can i  set the memory occupation . What is the impact of small setting on thread.

**Comment by jwhui** [comment]
Default build configurations are in [src/core/config](https://github.com/openthread/openthread/tree/main/src/core/config).

Examples for overriding the default configurations:
- https://github.com/openthread/ot-cc2538/blob/main/src/openthread-core-cc2538-config.h
- https://github.com/openthread/ot-nrf528xx/blob/main/src/nrf52840/openthread-core-nrf52840-config.h
