### ISSUE TITLE
Can thread be compiled and run under win10 without using docker

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7424]
Hello, expert. Without docker, using cmake and MinGW environment, can I  compile and run threads under win10？

**Comment by jwhui** [comment]
I don't develop on Windows, but I've heard good things about [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/about).

**Comment by tuopu** [comment]
Thank you very much for your reply.
