### ISSUE TITLE
RCP timeout and SPI interface implementation issue

### ISSUE THREAD

**Issue by abtink** [openthread/openthread#7429]
The PR https://github.com/openthread/openthread/pull/7427 has triggered me to take a look at `radio_spinel` and its SPI interface implementation.

**I think I may have an issue with the current code which may explain some the RCP response timout failures.**

In short: `RadioSpinel` can call `SendFrame()` on the interface assuming that then frame is send AND received by the RCP (which is not necessarily the case), and then it can call `WaitForFrame()` waiting for the RCP  to signal that it has a response frame (which RCP will not signal if it has not yet received the original frame).

Here are the details:
- The current `SpiInterface::SendFrame()` implementation
   - Copies the frame into the local buffers
   - Marks `mSpiTxIsReady` boolean to indicate we have something to send
   - And then call `PushPullSpi()` once
- The `PushPullSpi()` will trigger central (master) to do one SPI transaction
- The Spinel SPI protocol defines header where both sides indicates how many bytes they could receive (in a transaction)
- This is then used to determine whether a sent frame was received by other side or not
   - In the case central having something to send, it can follow up with another SPI transaction
   - In case of peripheral, it still keeps the GPIO active indicating it still has a pending frame to send
- The key point is that the call to `PushPullSpi()` from `SpiInterface::SendFrame()` does not necessarily mean that that frame is received by the RCP.
- The issue is then in `RadioSpinel` code we can call `WaitForFrame()` 
  - Which in the current `SpiInterface` implementation waits for the GPIO interrupt pin to be asserted by the peripheral/RCP
  - But in the case that RCP could not receive the frame in the previous transaction, it would not assert the pin
  - Which then triggers an RCP timeout

The current `SpiInterface` implementation for `RadioSpinel` was adopted from `spi-hdlc-adapter` code.
- In the `spi-hdlc-adapter` we have a run loop and a single `select()` call
- And there is a single "push-pull-spi" call which exchanges one SPI transaction based on the current state (i.e., whether we have some pending frame to send, or the peripheral has indicated that it has something to send to us).
- So if peripheral is not ready to accept/receive our frame in a first transaction, we go through the loop again and follow with another transaction.

The key difference in `SpiInterface` is that there are multiple places where `select()` is called where we can block and wait
- It is called in `WaitForFrame()` where we can block and wait for GPIO pin from the RCP.
- And we can also block from the main run loop which then calls `SpiInterface::Process()`  
  - Note that `Process()` does correctly check `mSpiTxIsReady` and does `PushPullSpi()` if it set, but we don't get to this code when we are waiting in `WaitForFrame()`.

I personally do not like the fact that we need multiple `select()` calls (multiple blocking points) in the code, but I think this model was basically required by `radio_spinel` design choices since its initial implementation (how it managed to bridge between synchronous API calls and async exchanges with an RCP). It is going to be a tough thing to update now, but I do wish/hope that we can change this model in future.

_The fix from PR https://github.com/openthread/openthread/pull/7427 reduces the likelihood of the issue by simply invoking `PushPullSpi()` 5 times in `SendFrame()` but it is not addressing the root cause._

I think the proper fix for this should be in `WaitForFrame()`:
- If we see `mSpiTxIsReady` is true (meaning we have a pending tx frame), we need to do `PushPullSpi()` immediately
- And keep doing it while `mSpiTxIsReady` is still true while waiting to a frame.

I will try to submit a fix for this later.

FYI: @zhanglongxia , @bukepo @librasungirl

**Comment by bukepo** [comment]
Thanks for the analysis. I agree fix in WaitForFrame() is better.

**Comment by simonlingoogle** [comment]
> I personally do not like the fact that we need multiple `select()` calls (multiple blocking points) in the code, but I think this model was basically required by `radio_spinel` design choices since its initial implementation (how it managed to bridge between synchronous API calls and async exchanges with an RCP). It is going to be a tough thing to update now, but I do wish/hope that we can change this model in future.

I would agree with the spirit here. 

IIUC, `WaitForFrame` blocks the main loop, but any operation that is blocking is harmful to OpenThread performance because ideally the main loop select should be the only blocking operation.

**Comment by zhanglongxia** [comment]
Thanks for the great analysis. The root cause of the issue is that the RCP failed to receive the SPI frame from the host. What we can do is re-transmiting the SPI frame to the RCP again.
Yous suggestion is putting the re-transmission logic to the `WaitForFrame`. The problem is that not all Spinel command will call the `WaitForFrame` after they call the `SendFrame`. So if the radio_spinel_impl doesn't call the `WaitForFrame`, this issue still exist.

**Comment by abtink** [comment]
> The root cause of the issue is that the RCP failed to receive the SPI frame from the host

The fact that RCP at some instances may not be able to accept/receive a SPI from from the host is expected and normal. It is not  a bug or issue on RCP.  In general, it is just how SPI central and peripheral model works:
- Since central controls the clock and can basically start a transaction whenever it wants, it is perfectly fine for peripheral to not be ready to accept a transaction 
  - An example can be that peripheral is out of buffer, since rx buffer already used for a previous frame and it still being processed.

---------

> Your suggestion is putting the re-transmission logic to the WaitForFrame. The problem is that not all Spinel commands will call the WaitForFrame after they call the SendFrame. So if the radio_spinel_impl doesn't call the WaitForFrame, this issue still exist.

We already have the mechanism for the follow-up transaction or we can call it re-transmission in `Process()` and `UpdateFdSet()` methods. There is also logic that handles the rate-limiting (if the peripheral cannot accept and refuses transactions back-to-back):
https://github.com/openthread/openthread/blob/ff848e7a2068f25c8415c5086149921f45ca4099/src/posix/platform/spi_interface.cpp#L679-L685

These are all called from the main run loop along with all other platform/system drivers. This is a clean and nice model and ensures that all platform drivers are serviced from same run loop

One way we can think about it is that `SendFrame()`'s  job is to pass/give the frame to `SpiInterface` for it to process and send later (ideally from main run loop) - same way that `otPlatRadioTransmit()` passes the frame to radio driver.

The complexity with `RadioSpinel` is that we need to have an extra `select()` and blocking point in `WaitForResponse()` and therefore it needs to do the same logic as what we do in the main run loop.  I submitted the PR with the proposed change, and in it we call `UpdateFdSet()` and `Process()` in `WaitForFrame()` basically creating a similar mini run loop in this method.

**Comment by abtink** [comment]
> We Call PushPullSpi once in SendFrame. If we are to call PushPullSpi more in WaitForFrame(), can we remove PushPullSpi call in SendFrame?

I agree. This may be a good idea.  It may be good to do `PushPullSPi` from only once place in the code in `Process()` which is then called from main run loop or from `WaitForResponse()` which has its own mini run loop 😄

**Comment by abtink** [comment]
This PR should help address this (already merged, so we can close this).
- https://github.com/openthread/openthread/pull/7431
