### ISSUE TITLE
kChildIdMask maybe error

### ISSUE THREAD

**Issue by nykh2010** [openthread/openthread#7530]
https://github.com/openthread/openthread/blob/c9f23ccddaaa08f4c5cc2b8a9160eac1e2b4a2e9/src/core/thread/network_diagnostic_tlvs.hpp#L1036
is kChildIdMask 0x1ff ?

**Comment by wgtdkp** [comment]
@nykh2010 Thanks for catching this issue, I just created https://github.com/openthread/openthread/pull/7531 to fix it.
