### ISSUE TITLE
The thread command was entered but could not be executed

### ISSUE THREAD

**Issue by tuopu** [openthread/openthread#7551]
Hello, expert, when I transplant thread to a new platform, when I transplant the serial port command function, when I input the command, I can only output "done". Is there a debugging command switch macro?

**Comment by jwhui** [comment]
Many commands (especially those that are setting values) will only output `Done` to indicate that the command completed successfully.

OpenThread logs will provide much more visibility into the internal operation - see this [OpenThread Logs guide](https://openthread.io/guides/build/logs) to learn more .
