### ISSUE TITLE
Is the routerCount definition out of loop body?

### ISSUE THREAD

**Issue by nykh2010** [openthread/openthread#7612]
https://github.com/openthread/openthread/blob/5c8a9cb5bc28ce6f794c0d8db7189b1f2dd586ba/src/core/thread/mle_router.cpp#L4307
The routerCount is always set to 0. The peerLinkQuality always get from the first one of Route64 TLV.

**Comment by jwhui** [comment]
@nykh2010 , thank you for raising this issue!

I believe this is a bug. I'll submit a PR with a proposed fix soon.

**Comment by jwhui** [comment]
Just submitted #7617. Please review.
