### ISSUE TITLE
Respond many beacon frames to a beacon request.

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/openthread#7621]
The otbr respond many beacon frames to a beacon request. Is this as expected? The KNBA7DF5D72A is otbr.

ot-br-posix commid id: a965a7535dad33303585d2080437f3d796e54a81
openthread commid id: e736d2488d9d4f787650d81f2b84f59a194f2b41

![image](https://user-images.githubusercontent.com/97089879/164461810-afa91eff-b117-4d52-ad3b-e69e9633e6a6.png)

**Comment by jwhui** [comment]
@jinpeng1989 , can you attach the actual pcap file?

Couple observations:
1. The beacons you highlighted are about 2 seconds apart.
2. There are other devices sending multiple beacons as well.

Is it possible that there are Beacon Request messages being sent but not captured by the sniffer?

Note that OTBR does [log when it receives a Beacon Request](https://github.com/openthread/openthread/blob/b5a347a3f95059fe0b2fa7ebe0054edbff90d37e/src/core/mac/mac.cpp#L2055). You could enable logging to see if OTBR is actually responding to multiple Beacon Request messages.

**Comment by jinpeng1989** [comment]
[many_beacon_respond.zip](https://github.com/openthread/openthread/files/8536082/many_beacon_respond.zip)

**Comment by jinpeng1989** [comment]
Networkkey: 237a5a5fba31c6ea2e6ea2c717047248

**Comment by jwhui** [comment]
@jinpeng1989 , can you also provide the OTBR logs, which would indicate if OTBR is receiving more Beacon Request messages than might appear in the sniffer trace?

In the pcap file you provided, I'm also seeing cases where it appears a Zigbee device is sending multiple Beacons in response to a Beacon Request.

**Comment by jinpeng1989** [comment]
Sorry, forgot to reply. You are right. There are many zigbee devices far away from my sniffer.  So my sniffer didn't pick up all of them. The otbr only reply one beacon frame to one beacon request.
