### ISSUE TITLE
Test harnes Leader 9.2.6 fail

### ISSUE THREAD

**Issue by GabrielCouturier** [openthread/openthread#7701]
Problem
Running on NXP K32W061 board.
Test harness Leader 9.2.6 fail at step :
Check if Data Response packet has Security
Policy TLV in Active Operational Dataset : Security
Policy sub TLV not present

See attached logs
[Fail_OT_NXP_9_2_6_Leader_v54.4_2022_05_06-10_51_02.zip](https://github.com/openthread/openthread/files/8700518/Fail_OT_NXP_9_2_6_Leader_v54.4_2022_05_06-10_51_02.zip)

After doing the bisection :
It starts failing with :
https://github.com/openthread/ot-nxp/commit/f68cedc102

This open thread submodule update correspond to one change in the open thread stack :
https://github.com/openthread/openthread/commit/a8b4fbb1893823e1c247ee1cc

**Comment by jwhui** [comment]
Closing as duplicate of https://github.com/openthread/ot-nxp/issues/264
