### ISSUE TITLE
`RoutingManager` learning RA header from host

### ISSUE THREAD

**Issue by abtink** [openthread/openthread#7815]
I noticed a potential situation in `RoutingManager` with how we update stale timer and how the RA header discovered from Host daemons. Here is an overview:
- When we receive an RA msg, we check if the source IP address matches the `InfraIf` itself 
(`if (mInfraIf.HasAddress(aSrcAddress))`)
- If it is we call `UpdateRouterAdvertHeader()`
   - which then updates `mTimeRouterAdvMessageLastUpdate` time and sets `mLearntRouterAdvMessageFromHost`.
- From `ResetDiscoveredPrefixStaleTimer()` one of the conditions is related to this
  - if we learnt the RA msg header from host, we then use `mTimeRouterAdvMessageLastUpdate` to check if discovered RA header may be stale or not
- When stale timer expires, we send a sequence of RS msgs (to check if we see again the same RA msg with RA header)

The situation is that I think it is possible that we receive the RA message that we sent out ourself which would then reset the RA header back and reset the `mTimeRouterAdvMessageLastUpdate`
- If the host daemon stopped sending RA, we may not notice it and keep using the saved RA header.

One solution is to try to somehow determine if the received RA is the one generated by `RoutingManager` or host (from options included in it).

Thoughts?

**Comment by simonlingoogle** [comment]
Can we really receive RA/RS from Thread BR self? @wgtdkp 

If so, we may need to configure `IPV6_MULTICAST_LOOP` to zero to avoid the issue.

**Comment by abtink** [comment]
> Can we really receive RA/RS from Thread BR self?

The mechanism in `RoutingManager` to discover the host RA header is assuming that we would receive RA message that is sent by the host (on the BR itself). So I expect it can be possible that we also receive the RA message that we (from `RoutingManager`) prepare and give to platform/host to be sent out.

**Comment by wgtdkp** [comment]
> If the host daemon stopped sending RA, we may not notice it and keep using the saved RA header.

Typically, the host daemon will send a RA message with zero Router Lifetime and we will reset the learnt RA header in this case. But in case we missed that RA or the host daemon crashes before sending out the RA, I agree there will be a problem that we will keep using the old RA header.

Comparing the entire RA message to determine who sent the RA should work with most cases, but we can't guarantee that host daemon won't sent the same options.

I think below idea should work:
If we are using the RA learnt from host daemon (`mLearntRouterAdvMessageFromHost` is true), we keep decreasing the Router Lifetime when sending out RA messages. For example, if we received a RA from host daemon at 00:00:00 with Router Lifetime of 30 minutes, we use Router Lifetime of 20 minutes when sending our RA messages 10 minutes after learning the RA (just kind of tracking the Router Lifetime of the initial learnt RA header).  So if the host daemon crashes and we do't get a refresh of the Router Lifetime from the host daemon anymore, we will decrease to zero Router Lifetime and then we can reset to our default RA header.


@abtink @simonlingoogle @jwhui Thoughts?

// @librasungirl FYI

**Comment by simonlingoogle** [comment]
> For example, if we received a RA from host daemon at 00:00:00 with Router Lifetime of 30 minutes, we use Router Lifetime of 20 minutes when sending our RA messages 10 minutes after learning the RA (just kind of tracking the Router Lifetime of the initially learnt RA header).

I think it's a good idea to timeout the RA header, but sending RA with decreasing `Router Lifetime` might not be a good idea because it brings extra unexpected changes to the networking environment. 

I think comparing the whole RA message is a better idea.

**Comment by abtink** [comment]
- Submitted https://github.com/openthread/openthread/pull/7846

**Comment by abtink** [comment]
We can close this.
