### ISSUE TITLE
Commissioning Dataset MUST be included while sending stable Network Data to SED

### ISSUE THREAD

**Issue by lluwang** [openthread/openthread#801]
This is to pass 9.2.6 (DUT as Router) to be compliant with 8.4.3.2 of spec.

**Comment by jwhui** [comment]
Is this to satisfy Step 15 of 9.2.6?  I actually think the specs are wrong in this case.  The SED is configured to only receive stable network data.  Step 15 indicates that the Commissioning Data TLV is not marked as stable.  That information is not useful to the SED and should not be provided.

**Comment by jwhui** [comment]
FYI, I found [TESTPLAN-272](https://threadgroup.atlassian.net/browse/TESTPLAN-272) which already discusses this issue.

**Comment by lluwang** [comment]
Yes. And also file JIRA DEV-1016 for this.
But I also found that 8.4.3.2 said that "When transmitting stable thread network data, Thread Network Data MUST include a Commissioning Data TLV with the Stable flag set to one."
How do I understand this? Set stable to 1 even commissioning data stable flag is zero. Or do you think that this is wrong?

**Comment by jwhui** [comment]
I do not agree with that spec text.  There are actually a number of items incorrect.  For example, what exactly is the Operational Dataset TLV?  The Active or Pending version?
