### ISSUE TITLE
[Link Metrics Report] OTA Endian changed from Big Endian to Little Endian in Little Endian System

### ISSUE THREAD

**Issue by HuangCC-IFX** [openthread/openthread#8038]
**Describe the bug** In https://github.com/openthread/openthread/pull/7046, the value stored in the RAM is changed from little endian to big endian in a little endian system. However, with https://github.com/openthread/openthread/pull/8006, the outgoing data is swapped again (from Big Endian to Little Endian in a Little Endian system). This leads to actual data order in the Link Metrics Report TLV in a little endian format. May I know why @abtink need to change this format? Actually, Test Harness test tool identify this change for Low Power Test Case 7.2.1 and 7.2.2 as failure.

**To Reproduce** Information to reproduce the behavior, including: Execute GRL Test Harness (v56) for Low Power Test Case 7.2.1 and 7.2.2.

1. Git commit id: 967d89cd1aaa3ee1c16931dcbfe62e06278b119c
2. IEEE 802.15.4 hardware platform: Infineon CYW30739
3. Build steps: Refer to https://github.com/openthread/ot-ifx
4. Network topology: Refer to Low Power Test Case 7.2.1 and 7.2.2

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.
![without_967d89c](https://user-images.githubusercontent.com/83624568/185100475-6f6e1280-631f-4eff-8e39-a203d9aa5594.png)
![with_967d89c](https://user-images.githubusercontent.com/83624568/185100491-d2b67ad7-4f74-4b2e-bb2e-4eb2c46c5968.png)

**Comment by abtink** [comment]
Submitted https://github.com/openthread/openthread/pull/8039
