### ISSUE TITLE
Compile error (warning) on Linux

### ISSUE THREAD

**Issue by dtodor** [openthread/openthread#8066]
The compiler (GCC 11.2.0) complains that `hints` might not have been:

https://github.com/openthread/openthread/blame/main/src/posix/platform/infra_if.cpp#L647

```
third_party/openthread/repo/src/posix/platform/infra_if.cpp
third_party/openthread/repo/src/posix/platform/infra_if.cpp: In member function ‘otError ot::Posix::InfraNetif::DiscoverNat64Prefix(uint32_t)’:
third_party/openthread/repo/src/posix/platform/infra_if.cpp:647:21: error: ‘hints’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  647 |         freeaddrinfo(hints);
      |         ~~~~~~~~~~~~^~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```

This will be the case if this check fails: https://github.com/openthread/openthread/blame/main/src/posix/platform/infra_if.cpp#L616.

**Comment by jwhui** [comment]
I just submitted #8070 to fix the issue.

**Comment by dtodor** [comment]
OK, but now you are freeing an `nullptr`. Is this safe?
