### ISSUE TITLE
Crash when IPv6 interface is disabled in the otThreadDiscover() callback

### ISSUE THREAD

**Issue by selissia** [openthread/openthread#8110]
**Describe the bug**
If otIp6SetEnabled(sInstance, false) is called from the callback supplied to otThreadDiscover() the device crashes. More info below. 

**To Reproduce** 
1. Git commit id: 2ce3d3bf0
2. IEEE 802.15.4 hardware platform: Silicon Labs BRD4186C
3. Build steps: Regular build steps in Silicon Labs Studio Thread project
4. Network topology: Single device

Add the following code to the application triggered by some user action such as button press or a CLI command:
```
{
 otIp6SetEnabled(sInstance, true);
 otThreadDiscover(sInstance, 0, OT_PANID_BROADCAST, false, false,  scanResult, 0);
}

void scanResult(otActiveScanResult *aResult, void *aContext)
{
    if (aResult == NULL) {
        otIp6SetEnabled(sInstance, false);
    }
}
```
Triggering the action results in a crash in MeshForwarder::UpdateSendMessage()

**Expected behavior**
Device should not crash

**Console/log output**
N/A

**Additional context** 
When Thread scan completes  the following calls happen 
`MeshForwarder::UpdateSendMessage() -->Get<Mle::DiscoverScanner>().HandleDiscoveryRequestFrameTxDone() --> DiscoverScanner::HandleDiscoverComplete()->mHandler(nullptr, mHandlerContext);`

The `mHandler()` points to the discovery  callback. If the callback calls
`otIp6SetEnabled(mOTInst, false)`
then it in turn calls `MeshForwarder::Stop()` which sets mSendMessage to nullptr

When the call stack returns to `MeshForwarder::UpdateSendMessage()` it tries to access mSendMessage in `RemoveMessageIfNoPendingTx(*mSendMessage)` resulting in a hard fault.

**Comment by abtink** [comment]
Thanks @selissia.  Submitted https://github.com/openthread/openthread/pull/8111 which should help resolve this.
