### ISSUE TITLE
missing leader node info in diagnostics restful api

### ISSUE THREAD

**Issue by lancersky** [openthread/openthread#8256]
**Describe the bug** A clear and concise description of what the bug is.
![1665216236011](https://user-images.githubusercontent.com/11283852/194697622-cef5bfcb-9653-4cd7-a3c0-000b43056a84.png)
![image](https://user-images.githubusercontent.com/11283852/194697707-e53fd411-914e-4ac1-9809-06e657a1fb1d.png)

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id https://github.com/openthread/ot-br-posix/commit/3a98779dc9f0875af9c7b137e764c9663bfdc9c3
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by lancersky** [comment]
There are 16 router devices and 65 child devices in the Thread network.

**Comment by lancersky** [comment]
Hi @jwhui 
Is it related to the number of TlvTypes? More TlvTypes take more time to collect?
![image](https://user-images.githubusercontent.com/11283852/198186631-7ba89b65-1897-4471-8443-9252d106775b.png)

**Comment by martinzi** [comment]
thanks for raising this discussion.

For further tracing down your issue, I propose comparing wireshark captures. Typically, collect timeout of two seconds is sufficient for multicast responses from routers. However I suspect you may occasionally see packet collissions, in particular related to spacially dispersed Thread routers. Currently, OT lacks randomly delayed answers for multicast management queries. This is addressed in [SPEC-1061](https://threadgroup.atlassian.net/browse/SPEC-1061)

**Comment by jwhui** [comment]
Closing stale issue.
