### ISSUE TITLE
THCI: Enhance commissioning session id

### ISSUE THREAD

**Issue by lluwang** [openthread/openthread#835]
Harness would send MGMT_COMM_SET that includes commissioning session id.

None means that would use device's original session id.
!= None means that would use the session id from Harness.

Harness JIRA for more information:
https://threadgroup.atlassian.net/browse/DEV-1004

THCI are not fully supported this so far. We need to enhance it.

**Comment by xiaom-GitHub** [comment]
closed via #986 .
