### ISSUE TITLE
Conflicting diagnostics commands for GPIO

### ISSUE THREAD

**Issue by maciejbaczmanski** [openthread/openthread#8362]
After merge of https://github.com/openthread/openthread/pull/8316 "gpio" diag command has been added. 
The same diag command is implemented on ot-nrf528xx platform:
https://github.com/openthread/ot-nrf528xx/blob/main/src/DIAG.md#diag-gpio
Commands are overlapping now, so any attempt to use platform's specific command raises `kErrorInvalidArgs` error:
![image](https://user-images.githubusercontent.com/115064000/199939897-9f79c6f2-4184-4b63-b7fa-7e2671db35e4.png)

@zhanglongxia  Should one of commands' name be changed to avoid conflicts?

**Comment by zhanglongxia** [comment]
I will rename the command `gpio` to `pin`.

**Comment by maciejbaczmanski** [comment]
@zhanglongxia Seems good. Thanks.

**Comment by zhanglongxia** [comment]
@maciejbaczmanski The OpenThread diag commands already support setting the GPIO's direction. I think you can update the Nordic's repo to support the new GPIO diag commands now.

**Comment by maciejbaczmanski** [comment]
Fixed by https://github.com/openthread/openthread/pull/8391
Updated ot-nrf528xx platform implementation: https://github.com/openthread/ot-nrf528xx/pull/456
