### ISSUE TITLE
[continuous-integration] build-pretty fails intermittently 

### ISSUE THREAD

**Issue by superwhd** [openthread/openthread#8382]
It seems that the tool was not found after being installed. 

```
========================================
     check markdown
========================================
npm WARN exec The following package was not found and will be installed: prettier@2.0.4
npm WARN exec The following package was not found and will be installed: prettier@2.0.4
sh: 1: prettier: not found
```

Example: https://github.com/openthread/openthread/actions/runs/3424574325/jobs/5704405512

**Comment by abtink** [comment]
The failure seems to happen due to package being installed when we first run it.

- Submitted https://github.com/openthread/openthread/pull/9279 which may  help address this (in the PR we install the package in Bootstrap step).
