### ISSUE TITLE
problem with commissioning end devices

### ISSUE THREAD

**Issue by sohaibbinaltaf** [openthread/openthread#8409]
I have developed a thread network with three devices, raspberry pi with nRF52 dongles. I can ping each node and the network is working fine. All the three nodes are REED (router enabled end devices) with ot-rcp.hex file flashed in the dongles. These devices can turn into routers, but i want to have a device which is dedicatedly an end device. I have a few questions:

1) Do I need to have a ot-cli-ftd.hex file for this end device? I can see in codelabs that ot-cli-ftd.hex is also used as commissioner (which i guess also works as a router). 

2) I am trying in-band commissioning process, but my joiner returns this answer after the following command:

joiner start J01NMEME
Error 13: InvalidState

is this because of the rcp.hex file or some other reason?

3) I am trying to do the same using ot-ftd-cli.hex, but it doesn't respond to the ot-ctl commands. Can you please comment if there is something missing?

$ sudo ot-ctl
**connect session failed: Connection refused**

$ dataset set active 0e080000000000010000000300000d35060004001fffe002081fde57d326d560770708fdbc68a740973ee50510c047914315e34bc9848c27c8e4874e75030f4f70656e5468726561642d653464380102e4d804108aad4605fef84ece5b3e97c6b6cae0990c0402a0f7f8
**bash: dataset: command not found**

4) What would be the difference between rcp.hex and  ot-ftd-cli.hex files if both of these can be used to build a router ? 

Most importantly, as i want a device (raspberry pi with nRF52 dongle) which can only stay as end device and not function or change into a router, is it possible to build it with the rcp.hex  file .

**Comment by bukepo** [comment]
1. You may try disabling router eligible of the dedicatedly end device:

```bash
routereligible disable
```
2. Try bring up the interface before issuing `joiner start`:
```bash
ifconfig up
```
3. If you are using raspberry pi, you should stick to ot-rcp.hex as the firmware of nRF52. Please check the platform designs: https://openthread.io/platforms#platform_designs
4. You may check the platform designs: https://openthread.io/platforms#platform_designs. There are discussions of single-chip and co-processor designs.
