### ISSUE TITLE
[Thread 1.3.x] related OT PRs and Thread JIRAs.

### ISSUE THREAD

**Issue by abtink** [openthread/openthread#8461]
Created this issue to track OT PRs and related Thread Technical Committee JIRAs.
- [x] [SPEC-1136](https://threadgroup.atlassian.net/browse/SPEC-1136) Context ID Reuse Delay
  - https://github.com/openthread/openthread/pull/8876
  - https://github.com/openthread/openthread/pull/8870
  - https://github.com/openthread/openthread/pull/8896
- [x] [SPEC-983](https://threadgroup.atlassian.net/browse/SPEC-983) leader weight based on device config
  - https://github.com/openthread/openthread/pull/8670
- [x] [SPEC-1046](https://threadgroup.atlassian.net/browse/SPEC-1046) Child supervision 
  - https://github.com/openthread/openthread/pull/7993
- [x] ~[SPEC-1061](https://threadgroup.atlassian.net/browse/SPEC-1061) Delay TLV for query (pending)~
- [x] [SPEC-1002](https://threadgroup.atlassian.net/browse/SPEC-1002) Mode change FTD/MTD
  - https://github.com/openthread/openthread/pull/8484
  - https://github.com/openthread/openthread/pull/8498
- [x] [SPEC-1131](https://threadgroup.atlassian.net/browse/SPEC-1131) Child to router upgrade
   -  https://github.com/openthread/openthread/pull/8307
   - https://github.com/openthread/openthread/pull/9154
- [x] [SPEC-1120](https://threadgroup.atlassian.net/browse/SPEC-1120) and [SPEC-1130](https://threadgroup.atlassian.net/browse/SPEC-1130) 
  - https://github.com/openthread/openthread/pull/9042
  - https://github.com/openthread/openthread/pull/8986
  - https://github.com/openthread/openthread/pull/8381 
  - https://github.com/openthread/openthread/pull/8395
  - https://github.com/openthread/openthread/pull/8827
  - https://github.com/openthread/openthread/pull/8901
- [x] [SPEC-1128](https://threadgroup.atlassian.net/browse/SPEC-1128)
  - https://github.com/openthread/openthread/pull/8398
- [x] [SPEC-1136](https://threadgroup.atlassian.net/browse/SPEC-1136)
  - https://github.com/openthread/openthread/pull/7869
- [x] [SPEC-1126](https://threadgroup.atlassian.net/browse/SPEC-1126) (RIO preference based on BR role in mesh)
  - https://github.com/openthread/openthread/pull/8574
- [x] [SPEC-1145](https://threadgroup.atlassian.net/browse/SPEC-1145) - REED/FED to track cost towards all routers using parent's cost
  - https://github.com/openthread/openthread/pull/8956
 - [x] [SPEC-1190](https://threadgroup.atlassian.net/browse/SPEC-1190) 
  - https://github.com/openthread/openthread/pull/9080
- [x] [SPEC-1140](https://threadgroup.atlassian.net/browse/SPEC-1140) - leader override
 - https://github.com/openthread/openthread/pull/9073
 - https://github.com/openthread/openthread/pull/9106
 - https://github.com/openthread/openthread/pull/9186
- [x] [SPEC-1195](https://threadgroup.atlassian.net/browse/SPEC-1195) - delay security policy TLV
  - https://github.com/openthread/openthread/pull/9187
- [x] [SPEC-1180](https://threadgroup.atlassian.net/browse/SPEC-1180) - AP flag 
  - https://github.com/openthread/openthread/pull/9274
- [x] [SPEC-1181](https://threadgroup.atlassian.net/browse/SPEC-1181) - DNS resolver PTR include additional data only if one match. (optional enhc)
  - https://github.com/openthread/openthread/pull/9281
- [x] [SPEC-1167](https://threadgroup.atlassian.net/browse/SPEC-1167)
  - https://github.com/openthread/openthread/pull/9307
- [IETF SRP Replication](https://datatracker.ietf.org/doc/draft-lemon-srp-replication)
   - https://github.com/openthread/openthread/pull/8403
- [x] [SPEC-1222](https://threadgroup.atlassian.net/browse/SPEC-1222) - deprecate on-mesh prefix
   - https://github.com/openthread/openthread/pull/9579
   - https://github.com/openthread/openthread/pull/9585
   - https://github.com/openthread/openthread/pull/9599
- [x] [SPEC-1217](https://threadgroup.atlassian.net/browse/SPEC-1217) - BR to learn and replicate flags from other routers 
  - https://github.com/openthread/openthread/pull/9448
  -  https://github.com/openthread/openthread/pull/9486
   - https://github.com/openthread/openthread/pull/9601
   - https://github.com/openthread/openthread/pull/9607
- [x] [SPEC-1239](https://threadgroup.atlassian.net/browse/SPEC-1239)
  - https://github.com/openthread/openthread/pull/9682
  - https://github.com/openthread/openthread/pull/9684
- [x] [SPEC-1216](https://threadgroup.atlassian.net/browse/SPEC-1216) - ephemeral PSKc
  - https://github.com/openthread/openthread/pull/9435
  - https://github.com/openthread/openthread/pull/9803
  - https://github.com/openthread/openthread/pull/9694
  - https://github.com/openthread/openthread/pull/9966
  - https://github.com/openthread/openthread/pull/10524
- [x] [SPEC-1262](https://threadgroup.atlassian.net/browse/SPEC-1262) key guard time factor or rotation time
  - https://github.com/openthread/openthread/pull/9871
- [ ] ~[SPEC-1243](https://threadgroup.atlassian.net/browse/SPEC-1243) OMR prefix from partition ID~ (not yet approved or added in spec).
  
_Note: Access to the Thread JIRA links requires Thread membership and Thread group login/account._

This is follow-up to https://github.com/openthread/openthread/issues/7460 for new changes after 1.3.0 (for 1.3.x)

**Comment by suveshpratapa** [comment]
@abtink Does this represent the latest remaining work for 1.3.1 on GitHub? Or are there any items missing?

**Comment by abtink** [comment]
> Does this represent the latest remaining work for 1.3.1 on GitHub? Or are there any items missing?

That's the intention behind this.

**Comment by suveshpratapa** [comment]
Thank you @abtink ! I was going to ask you about the network diagnostics work item so thank you for pointing me to that. Also I know the TCAT/BBTC PR is currently open and yet to be merged so will that count as another 1.3.x item to be added to this list?

**Comment by abtink** [comment]
This tracks everything for 1.3.x (not just 1.3.1). I created and use this issue to track stuff that I did or plan to work on myself (to have a place with all the links to SPEC JIRAs and PRs). 

Feel free to create a new issues to track other items if you want (or you can add them here)

BTW, SRP replication is not part of 1.3.1 and DNS Push is not supported in OT(can be supported by platform if desired).

**Comment by EskoDijk** [comment]
@abtink Seeing that all issues we wanted to do, that were listed here, are addressed, we can probably close this issue? See #9930 for the open issue on remaining items for 1.4.

**Comment by abtink** [comment]
SGTM.
