### ISSUE TITLE
The Child failed send MAC Data Frames to its Parent when its Parent send announce message to another channel.

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/openthread#8519]
The Child failed send MAC Data Frames to its Parent when its Parent leaves the current channel  to send announce message to another channel.
The rloc16 of this Child is 0x2805， it consecutive unicast MAC Data Frames sent to 0x2800， but there is no Mac layer Ack.
![image](https://user-images.githubusercontent.com/97089879/206972350-5d89ab82-2a6f-4139-adfb-3d94dd64ddcf.png)
Checked the log, the Parent is sending announce on other channels at this time. What is the maximum time when Parent leaves the current channel to send announce message to another channel? Is there a definition in the standard? 
Is this kind of packet loss as expected?
![image](https://user-images.githubusercontent.com/97089879/206975330-9c8868fa-a4aa-45a3-a114-84c3f9c2aad7.png)

**Comment by jinpeng1989** [comment]
Add log and wireshark packets, Network Key: 5d7838199c00a8dd596dd687ecb1b84e
[5d7838199c00a8dd596dd687ecb1b84e.zip](https://github.com/openthread/openthread/files/10205225/5d7838199c00a8dd596dd687ecb1b84e.zip)
[send_failed_when_announce.log](https://github.com/openthread/openthread/files/10205226/send_failed_when_announce.log)

**Comment by jwhui** [comment]
The MLE Announce message should take on the order of tens of milliseconds - basically the time it takes for the radio to switch to a different channel, transmit a broadcast message, and return back to the main channel.

It appears that your device is only attempting to transmit a unicast message a total of 4 times (unless the ack message is getting dropped from the sniffer capture). Thread Specification requires 15 retransmissions when no ack is received and OpenThread implements that requirement.

**Comment by jinpeng1989** [comment]
The sleep end device in our system base on the Thread Specification 1.1.1, the macMaxFrameRetries is 3.
![image](https://user-images.githubusercontent.com/97089879/207215936-bf9b784a-de9a-4cb9-9c4e-9108a7e3d1f8.png)

**Comment by jwhui** [comment]
In OpenThread, the number of retries is controled via the build config [`OPENTHREAD_CONFIG_MAC_DEFAULT_MAX_FRAME_RETRIES_DIRECT`](https://github.com/openthread/openthread/blob/b02bdb9e3bfc0207737bebb94824713f61f5352c/src/core/config/mac.h#L73). I would encourage you to increase the number of retries to 15. Even better if you can upgrade your device to Thread 1.3, which includes many other enhancements such as this.

**Comment by jwhui** [comment]
Closing stale issue.
