### ISSUE TITLE
Log line separators

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#852]
#810 removes `\r` from log lines.  More generally, line separators should be platform/use-case specific.

How about we simplify `otPlatLog()` to always assume a single log line at a time?  In other words, format strings passed to `otLog*()` no longer end with `\n`.  Instead, `otPlatLog()` will be responsible for appending the appropriate line separators if necessary.  This would be consistent with other logging infrastructure such as syslog.  If people agree, I'll go ahead and work on an update.

**Comment by nibanks** [comment]
That sounds great to me. The Windows WPP equivalent of these already makes the assumption the log is a single line.
