### ISSUE TITLE
Ensure route priority for a BR is set differently depending if its a router vs. an end device.

### ISSUE THREAD

**Issue by ndyck14** [openthread/openthread#8539]
We need to ensure BRs in Router roles are more likely to be selected from the route table compared to devices operating as end-devices.

From [SPEC-1126](https://threadgroup.atlassian.net/browse/SPEC-1126):

> If the Border Router is currently in a Thread End Device (REED) role, the Route Preference in a RIO SHOULD be set to ‘Low’ (11) because this Border Router is less preferable than other Border Routers that are operating in a Thread Router role.

**Comment by jwhui** [comment]
@ndyck14 , thanks for submitting this! I updated your description to include a link to the Thread Group JIRA.

**Comment by jwhui** [comment]
Resolved by #8574
