### ISSUE TITLE
Orphan children can cause MLE Announce flooding

### ISSUE THREAD

**Issue by ADEscobar** [openthread/openthread#8542]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.

Hi, I see that recently the handling of MLE announcements was changed so that every orphan announcement generates an announcement by every node receiving it:

```
 if (timestamp.IsOrphanTimestamp() || MeshCoP::Timestamp::Compare(&timestamp, localTimestamp) < 0)
    {
        SendAnnounce(channel);

#if OPENTHREAD_CONFIG_MLE_SEND_UNICAST_ANNOUNCE_RESPONSE
        SendAnnounce(channel, aRxInfo.mMessageInfo.GetPeerAddr());
#endif
    }
```

If the network is quite congested, a child can take several reattachment attempts before the attach is successful, and every reattach causes an Orphan announcement, triggering an announcement reply (multicast and unicast if enabled) from every node in range, heavily increasing the traffic.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

Is it really needed to reply every single orphan announcement? As I see it, the orphan child will just try the attachment again as usual with or without this reply, so maybe it is better to answer only if there is a relevant change in the dataset that should be reported to the orphan child (new channel or panid?).

**Comment by jwhui** [comment]
@ADEscobar , thanks for raising this issue. Because this requires a change to the Thread Specification, we discussed this within the Thread Group  -  [SPEC-1165](https://threadgroup.atlassian.net/browse/SPEC-1165).

Resolved by #9388
