### ISSUE TITLE
If a Child that has attached to the Parent indicating it is an rx-on-when-idle Device try to use Child Update Request to modify its mode to rx-off-when-idle, should the parent reject it?

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/openthread#8557]
As stated in the Specification that A Child that has attached to the Parent indicating it is an rx-on-when-idle Device MUST NOT use Child Update Request to modify its mode to rx-off-when-idle. During the actual testing, there is a Child attempt to do this.
![image](https://user-images.githubusercontent.com/97089879/208583148-df6eb5d1-de45-4b01-8de2-a5c36a6c61b8.png)

Packet 98: The Child Device initially attached to the Parent indicating it is an rx-on-when-idle Device.
Packet 128: The Child Device use Child Update Request to modify its mode to rx-off-when-idle. 
Packet 140: The Parent Device reply Child Update Respond without 'error'. 

Is there a consequence to that? Will it affect the rest of the communication? If the answer is yes, I think the Parent should reject the attempting from the Child Device.
![image](https://user-images.githubusercontent.com/97089879/208584484-f6a177b1-7d63-423b-9bde-ef14cf07b13c.png)
![image](https://user-images.githubusercontent.com/97089879/208586322-af4aa2a4-970b-49bb-a87a-12379fe0ea32.png)
![image](https://user-images.githubusercontent.com/97089879/208586522-32e2d286-3f5e-4a1b-a7e1-6dd0a0be8652.png)

More details, please see attachment, Network Key: f7f05cdd3cda3c5d3c983d2f597b177e
[rxon_to_rxoff.zip](https://github.com/openthread/openthread/files/10265424/rxon_to_rxoff.zip)

**Comment by jinpeng1989** [comment]
This change applies to the Child side, right?

**Comment by jinpeng1989** [comment]
This change applies to the Child side, right?

**Comment by jwhui** [comment]
> This change applies to the Child side, right?

Yes, correct.

**Comment by jinpeng1989** [comment]
The Child Device cannot be updated to the new version of the stack due to memory resource constraints. I wonder if this fix can be applied to the lower version stack?
Is it possible that the Parent reject the Child's attempting? Then the Child will try to re-attach.

**Comment by jwhui** [comment]
Closing stale issue.
