### ISSUE TITLE
channel manager command doesn't output favored channels

### ISSUE THREAD

**Issue by mmb-davidsmith** [openthread/openthread#8570]
In reviewing the CLI code, I found that there's an issue with the output of the "channel manager" command where it will output the supported channels for both the supported and favored lines.

https://github.com/openthread/openthread/blob/e167a1f07168cfb1a7f32129b6c4b30b588a3725/src/cli/cli.cpp#L1855-L1865

The "favored" output should use `favoredMask`.

**Comment by jwhui** [comment]
@mmb-davidsmith , thanks for raising this issue!
