### ISSUE TITLE
CoAP block2 responses are missing the token after first block response

### ISSUE THREAD

**Issue by tbitcs** [openthread/openthread#8641]
CoAP Block2 requests are not working after the first block response is sent. This issue is similar to #7976, only that the token is missing on Block2 responses, therefore the fix from #7980 does not apply to block2 requests. 

To reproduce, create any block2 request greater than the block size (e.g. set block size to 1024 bytes and send 1500 bytes). The first Block2 ACK response (Block #0) is good. However, the second Block2 ACK response (Block # 1) will have a missing token (Token Length = 0).

![image](https://user-images.githubusercontent.com/98970594/211648118-92c9ee0a-8715-4c93-8214-323e195bde55.png)

[Wireshark Capture](https://github.com/openthread/openthread/files/10386387/coap-block2-issue.zip)

I propose the following fix:

[coap.zip](https://github.com/openthread/openthread/files/10386327/coap.zip)
File name: src\core\coap.cpp
method name: CoapBase::ProcessBlock2Request
```
response->SetMessageId(aMessage.GetMessageId());

++ SuccessOrExit(error = response->SetTokenFromMessage(aMessage));

VerifyOrExit((bufLen = otCoapBlockSizeFromExponent(aMessage.GetBlockWiseBlockSize())) <= kMaxBlockLength,
                 error = kErrorNoBufs);
```

**Comment by jwhui** [comment]
@tbitcs , thanks for raising this issue. Would you like to submit a PR?

**Comment by tbitcs** [comment]
@jwhui, PR #8699 submitted.

**Comment by tbitcs** [comment]
@jwhui I had to create a new fork and PR due to cla issues. Please see #8700.
