### ISSUE TITLE
Network name for new/random dataset

### ISSUE THREAD

**Issue by dtodor** [openthread/openthread#8765]
Wouldn't it be better to use the `NetworkNameManager::sNetworkNameInit` as a prefix when initialising a new/random dataset?

https://github.com/openthread/openthread/blob/99a615bec2eeccad9ff03d6c5581c1fd51becf68/src/core/meshcop/dataset.cpp#L86

**Comment by jwhui** [comment]
@dtodor , I think that sounds reasonable. Would you like to submit a PR with the proposed fix?
