### ISSUE TITLE
The Heap::String implementation fails to provide a sanity check prior to freeing member memory.

### ISSUE THREAD

**Issue by adabreuti** [openthread/openthread#8798]
**Describe the bug**

When calling Heap::String::Set() it is possible to free a NULL pointer if the member buffer, mStringBuffer, is set to NULL.

There is an assumption that all heap free API's handle NULL pointers gracefully when using OPENTHREAD_CONFIG_HEAP_EXTERNAL_ENABLE. 

In the case of the opensource BGET implementation for instance, the brel API does not check for pointer validity prior to freeing the input memory, which can cause application crashes. This could be the case for other opensource/third party heap implementations and as such, precautions should be taken to filter the inputs to be released.

BGET Reference: https://www.fourmilab.ch/bget/

**Expected behavior**

When running an application which calls Heap::String::Set() without first setting the member buffer mStringBuffer to a known value, the application should continue to run.

**Comment by abtink** [comment]
Thanks @adabreuti .

We do have a requirement for `otPlatFree()` implementations to support `NULL` as input. 

https://github.com/openthread/openthread/blob/57ed65edf479344a2c1bffca3a643da6d7f494f9/include/openthread/platform/memory.h#L76-L83

The platform layer providing the implementation of `otPltFree()` should ensure and handle this (e.g. if the underlying heap library does not directly support it, then `otPlatFree()` function should check for this).
