### ISSUE TITLE
MAC: Frame Counter on retransmissions

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#881]
Currently OpenThread's MAC implementation retransmits MAC Frames using the same sequence (DSN) but different Frame Counter (in Auxilary header). However my understanding is that Frame Counter has to be the same for subsequent retransmissions.

The 802.15.4 specification is not so clear about it, but i believe it is possible to make a deduction that current behavior is not correct (Transmission and Retransmission chapters). Also all implementations that I know retransmit frames using the same Frame Counter which looks logical for me.

The one obvious problem was when i have tested OpenThread nodes in dense network and i often received 2 ICMP Echo Reply (on one Echo Request) instead of one, whenever ACK for first Echo Reply hasn't been detected on other side. Normaly Frame Counter guarantees that this situation will not occur, and second Echo Reply will be simply discarded on MAC Layer (due to reply attack protection).

**Comment by jwhui** [comment]
Good catch!  I just submitted #883 to address this issue.
