### ISSUE TITLE
When netdata registrations fail due to netdata being full, it can take an unnecessarily long time to re-attempt once netdata space is available

### ISSUE THREAD

**Issue by ndyck14** [openthread/openthread#8843]
When netdata is full, it seems there is a delay before re-attempting to register the failed item. This can happen for crucial service items like prefixes or SRP services, without which a mesh cannot function for application layers like Matter.

It seems to me, there is no reason to delay (outside of perhaps a random jitter) to re-register netdata items once netdata becomes sufficiently empty. This should be observable from netdata update events. Discussions with @abtink show this may not be trivial, but I did want to log this as a possible improvement.

A fix to this may benefit from [PR 8381](https://github.com/openthread/openthread/pull/8381)

**Comment by jwhui** [comment]
Closing stale issue.
