### ISSUE TITLE
Stale prefix contexts will not get cleared if leader goes into a crashloop /rebooted frequently

### ISSUE THREAD

**Issue by sarveshkumarv3** [openthread/openthread#8854]
Currently if there are stale prefix contexts in the network data (with only the 6LoWPAN context ID) and leader goes into a crashloop or rebooted frequently, the stale contexts would not get cleared

Specifically  Leader::HandleNetworkDataRestoredAfterReset method would invoke StartContextReuseTimer for stale prefix on every crash which would reset the mContextLastUsed timer value. 

Thinking about potential solutions, one of the approaches to handle this could be to persist how long the entry has remained stale and restore the timer to run only for the remaining time?

**Comment by ndyck14** [comment]
This is related to discussion around the length of this timer: https://threadgroup.atlassian.net/browse/SPEC-1163

Leader weight is also relevant (intermittent powered devices should become less likely to to become leader).

**Comment by jwhui** [comment]
Resolved by #8859.
