### ISSUE TITLE
API: Multicast address subscribe/unsubscribe

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#891]
Currently OpenThread API does not allow to add / remove IPv6 address of multicast type. Do we want to have such possibility for example to be able to add such address in the CLI example? If yes, should we reuse ipaddr command and detect whether address is of multicast type, or we want to have separate commands for it?

**Comment by nibanks** [comment]
For Windows, I'd prefer to add the option to get forwarded all multicast messages, since the Windows networking stack will take care of the rest.

**Comment by jwhui** [comment]
I agree that the API should include multicast address subscribe/unsubscribe.  I also agree that the API should allow passing all received IPv6 multicast messages to the host without explicitly subscribing.  @LuDuda, are you willing to submit a PR for these enhancements?

**Comment by LuDuda** [comment]
Yes, you can assign me for that.
