### ISSUE TITLE
When leader promotes a node to router, it should also invalidate the eid-rloc cache for the previous child

### ISSUE THREAD

**Issue by ndyck14** [openthread/openthread#8974]
For scenarios when a child upgrades to router, we want to ensure routability is re-established as quickly as possible.

First step is to invalidate the cache, which ensures address query can happen on next packet coming through.

Although we could also consider directly migrating the previous map from previous child ID to new router ID, which could obviate the lookup. Taking this one step further, any node receiving a new router ID could consider migrating an old child eid-rloc cache if the extaddr of the new router and old child rloc are both known.

Other considerations: if routing is not established yet to new router, its possible next lookup may still go to old parent.

**Comment by abtink** [comment]
Submitted https://github.com/openthread/openthread/pull/8987 related to this

**Comment by jwhui** [comment]
Resolved by #8987
