### ISSUE TITLE
Don't print network key or other sensitive information to logs

### ISSUE THREAD

**Issue by gabekassel** [openthread/openthread#8993]
**Is your feature request related to a problem? Please describe.**
Logging is hugely useful for debug, however logs today can leak sensitive customer data such as network key. Filtering this data from hitting logs improves security posture. See below example when writing network key through CLI

`otbr-agent[11526]: 00:00:01.006 [I] Platform------: > dataset networkkey 309d2c6af200e6b6354d57227ed0804b` 

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Apply a filter to specific pieces of data so they're excluded from logs

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by gabekassel** [comment]
Thanks @abtink! That should unblock me temporarily.

**Comment by abtink** [comment]
Related to this submitted 
- https://github.com/openthread/openthread/pull/8994.

**Comment by jwhui** [comment]
Resolved by #8994
