### ISSUE TITLE
Discovery request always uses the same extended address instead of a random address 

### ISSUE THREAD

**Issue by sarveshkumarv3** [openthread/openthread#9019]
**Describe the bug** 

Discovery request always uses the same extended address instead of a random address 

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id - latest openthread commit from main 
2. IEEE 802.15.4 hardware platform - nrf52840
3. Build steps - built as FTD following steps here - https://openthread.io/codelabs/openthread-hardware#4
4. Network topology - node triggering a discovery request using the cli command (https://github.com/openthread/openthread/blob/main/src/cli/README.md#discover-channel)

**Expected behavior** A clear and concise description of what you expected to happen.

As per the specification, the source address should be randomized for every discovery request 

8.4.4.1.1.1

Discovery Request messages MUST have the Source Address in the IEEE 802.15.4 header set to
an extended (64-bit) new randomly generated value.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by jwhui** [comment]
@sarveshkumarv3 , thanks for submitting this issue.

I believe this is a specification issue. The intent behind the referenced spec text was to prohibit tracking a device as it is trying to join a network. Note that Section 8.4.4 is titled "Joiner Protocol". We should update the specification to indicate that source address randomization is only required when a device is not already commissioned.
