### ISSUE TITLE
Shouldn't `ifconfig down` disable the radio?

### ISSUE THREAD

**Issue by edmont** [openthread/openthread#9141]
I would expect that `otIp6SetEnabled(false)` effectively disables the radio, but this doesn't seem to be the case. Actually it seems `Links::Disable` is never used in the code. Is there any reason for that?

**Comment by abtink** [comment]
I cannot recall any specific reason for this. 
I noticed this (that we never call `Disable()`) in past. To me it is reasonable to add this but may be careful if there happens to be any side-effects
