### ISSUE TITLE
Test Cert_8_2_01_JoinerRouter.py seems Unreliable

### ISSUE THREAD

**Issue by nibanks** [openthread/openthread#933]
I have had several failures that required a rerun to resolve, failing because of `Cert_8_2_01_JoinerRouter.py`, [for example](https://travis-ci.org/nibanks/openthread/jobs/173293903).

I see the following error in the console output:

```
2016-11-04 16:19:19.413854 CRIT MCOP mbedtls_ssl_read_record() returned -30848 (-0x7880)
```

This seems to map to:

```
/**< The peer notified us that the connection is going to be closed. */
#define MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY                 -0x7880 
```

**Comment by jwhui** [comment]
I've seen this too.  I haven't had a chance to root cause this yet.

**Comment by nibanks** [comment]
As far as I can tell, this will only happen if the other side calls `mbedtls_ssl_close_notify`. That seems to be called in two places:

- `Dtls::Process` in response to receiving a result of `MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY`, obviously not the culprit here.
- `Dtls::Stop` which must be the issue here. That is called from `Dtls::HandleMbedtlsSetTimer` if `aFinish == 0`. I'm not exactly sure what that means. Did something timeout?

**Comment by chshu** [comment]
The CLOSE_NOTIFY is expected steps by the end of DTLS handshake which is also called by `Joiner::Close()` in `joiner.cpp`, so it maybe not the root cause, I will take a look at this issue.

**Comment by nibanks** [comment]
Now I just hit a similar error on `Cert_8_1_01_Commissioning' ([build link](https://travis-ci.org/nibanks/openthread/jobs/176504186)):

```
2016-11-16 21:16:56.211905 CRIT MCOP is a fatal alert message (msg 40)
2016-11-16 21:16:56.212013 CRIT MCOP mbedtls_ssl_read_record() returned -30592 (-0x7780)
```

**Comment by chshu** [comment]
I tried but failed to reproduce the failure locally with many runs, may need more efforts to locate the root cause.
