### ISSUE TITLE
[posix] fixed uninitialized pointer read

### ISSUE THREAD

**Issue by hastigondaliya** [openthread/openthread#9552]
Coverity checks report uninitialized pointer read for reqs if this check fails,
https://github.com/openthread/openthread/blob/837c7fd357d3546f96b9b1433d8f1348371b242e/src/posix/platform/infra_if.cpp#L672
reqs[0] remains uninitialized when calling free in the exit
https://github.com/openthread/openthread/blob/837c7fd357d3546f96b9b1433d8f1348371b242e/src/posix/platform/infra_if.cpp#L698-L706

Here, reqs pointer is declared but not initialized. So pointer can be declared or initialized nullptr. Additionally, when calling free validation can be added to ensure that the pointer being freed is not nullptr.

Can you please suggest which one should be applied to fix this issue,

> 1. Initialized with nullptr

`struct gaicb    *reqs[1] = {nullptr};`
```
if(reqs[0])
{
    free(reqs[0]);
}
```

> 2. Update pointer name as it single req ptr and update the function accordingly 

`struct gaicb    *req = nullptr;`
```
if(req)
{
    free(req);
}
```

**Comment by jwhui** [comment]
It appears [`getaddrinfo_a`](https://man7.org/linux/man-pages/man3/getaddrinfo_a.3.html) takes a list of `struct gaicb *`. So I think option 1 would make sense.

BTW, the `reqs` list has length 1.
