### ISSUE TITLE
Mesh: Deep Hops Left field

### ISSUE THREAD

**Issue by LuDuda** [openthread/openthread#956]
Currently OT supports Mesh Header with Hops Left field set to 14 or less. However this is not always true, and we need to support Deep Hops Left field. 

Also the algorithm of choosing Hops Left is described in 5.10.1.1 however it is also a little implementation dependent.

I think this field may be set to 14 if calculated (predicted) hop number is less that 14, and set to calculated hop number + X (1-2?) if it's higher than 14. Anyway we should use value 14 or less as much as possible to save extra byte.

Side note: Unfortunately Mesh Header is constructed in a way that Deep Hops Left is injected in the middle of the header, so when we forward a frame and the Hops Left is 15, then we can do memmove of payload to save one byte or just use Deep Hops Left until end (thoughts?)

**Comment by jwhui** [comment]
Agree that we should support larger hop counts.

> Side note: Unfortunately Mesh Header is constructed in a way that Deep Hops Left is injected in the middle of the header, so when we forward a frame and the Hops Left is 15, then we can do memmove of payload to save one byte or just use Deep Hops Left until end (thoughts?)

In addition to not requiring `memmove`, keeping the Deep Hops Left field can help give some indication that the packet may have started with a large Hops Left value.  I'm not sure saving 1 byte on the air will make much practical difference.  But I don't have a strong opinion either way.
