### ISSUE TITLE
[core][crypto] No checks for NULL pointer in aes_ccm.cpp

### ISSUE THREAD

**Issue by George-Stefan** [openthread/openthread#9564]
There are no checks for NULL pointer in aes_ccm.cpp
https://github.com/openthread/openthread/blob/main/src/core/crypto/aes_ccm.cpp#L195

When a malformed Enh-ACK is received, the stack crashes with NULL pointer.

![image](https://github.com/openthread/openthread/assets/51751981/f49fd2ca-6765-4e0f-bcc0-2bc759d8d675)

**Comment by abtink** [comment]
Thanks @George-Stefan .

This seems to be an incorrect behavior by the radio platform implementation which seems to pass a non-`null` pointer to an instance of `otRadioFrame *aAckFrame` in `TxDone()` callback  with a `nullptr` as `mPsdu`.

- If no ack is received, the `TxDone` should be called with a `null` for `aAckFrame` instance itself
- The `ProcessEnhAckSecurity()` won't be called if `aAckFrame` is null (checked in `Mac::HandleTransmitDone()`).
- A `otRadioFrame` instance is  always expcted to have a non-null `mPsdu`.

**Comment by George-Stefan** [comment]
@abtink, the malformed Enh-ACK has FCS valid but could have the ASH or the HIE corrupted making Payload() to return NULL

**Comment by abtink** [comment]
I see.  We should add a check to validate PSDU of an ehc ack frame.

I can add it or do you want to submit a PR?

**Comment by abtink** [comment]
Just submitted https://github.com/openthread/openthread/pull/9565

**Comment by George-Stefan** [comment]
> Just submitted #9565

Isn't a problem that the Enh-ACK is processed in Mac::RecordFrameTransmitStatus() => ProcessCsl() before ProcessEnhAckSecurity() called from Mac::HandleTransmitDone() ?

An attacker could just disrupt the CSL Tx by sending forged Enh-ACKs with CSL IE

**Comment by abtink** [comment]
> Isn't a problem that the Enh-ACK is processed in Mac::RecordFrameTransmitStatus() => ProcessCsl() before ProcessEnhAckSecurity() called from Mac::HandleTransmitDone() ?

From what I recall, the `RecordFrameTransmitStatus()` is mainly intended for updating counters.  I don't think it is calling `ProcessCsl()` (I could not find it in the code?).

**Comment by George-Stefan** [comment]
Yes, on latest stack code, I don't see any of the above problems for CSL
