### ISSUE TITLE
Gcc version detection

### ISSUE THREAD

**Issue by blauret** [openthread/openthread#977]
My experience is openThread does not compile with Gcc 4.x.

If this is assumed, would it be possible to to implement a check which verify the gcc is 5.x or greater or exit with a nice message. 

Maybe it's my limited knowledge of gcc, but when you try to compile OT with gcc 4.x, the build fails with a rather cryptic message. This would be a nice improvement

**Comment by blauret** [comment]
My experience is Thread does not compile with gcc version 4.x. 

I saw somewhere in the build tools some checks about presence of gcc in the path. If OpenThread supports only gcc 5.x or greated, would it be possible to implement a check the version of gcc and display a nice message if it's too old?

**Comment by jwhui** [comment]
OpenThread supports gcc 4, 5, and 6 and you can see the build results [here](https://travis-ci.org/openthread/openthread).

Can you provide your console output that includes the command line and error?

**Comment by blauret** [comment]
Bens-mbpr:openthread ben$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.7.4 20130913 (release) [ARM/embedded-4_7-branch revision 202601]
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Bens-mbpr:openthread ben$ make -f examples/Makefile-cc2538 
  MKDIR    output
  MKDIR    build/cortex-m3-arm-none-eabi
  CONFIG   cortex-m3-arm-none-eabi...
(cd build/cortex-m3-arm-none-eabi && /Users/ben/git/openthread/examples/../configure INSTALL="/usr/bin/install -p" CPP="arm-none-eabi-cpp" CC="arm-none-eabi-gcc" CXX="arm-none-eabi-g++" OBJC="" OBJCXX="" AR="arm-none-eabi-ar" RANLIB="arm-none-eabi-ranlib" NM="arm-none-eabi-nm" STRIP="arm-none-eabi-strip" CPPFLAGS="-fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb " CFLAGS="-fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb " CXXFLAGS="-fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb -fno-exceptions -fno-rtti " LDFLAGS="-fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb -nostartfiles -specs=nano.specs -specs=nosys.specs -Wl,--gc-sections -Wl,-Map=map.map " --host=arm-none-eabi --target=arm-none-eabi --prefix=/ --enable-cli --enable-diag --with-examples=cc2538 --with-platform-info=CC2538 )
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking build system type... i386-apple-darwin15.6.0
checking host system type... arm-none-eabi
checking target system type... arm-none-eabi
checking filtered build system type... i386-apple-darwin
checking filtered host system type... arm-none-eabi
checking filtered target system type... arm-none-eabi
checking for a BSD-compatible install... /usr/bin/install -p
checking whether build environment is sane... yes
checking for arm-none-eabi-strip... arm-none-eabi-strip
checking for a thread-safe mkdir -p... /Users/ben/git/openthread/examples/../third_party/nlbuild-autotools/repo/autoconf/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether to disable executable checking... no
checking for style of include used by make... GNU
checking for arm-none-eabi-gcc... arm-none-eabi-gcc
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-none-eabi-gcc accepts -g... yes
checking for arm-none-eabi-gcc option to accept ISO C89... none needed
checking whether arm-none-eabi-gcc understands -c and -o together... yes
checking dependency style of arm-none-eabi-gcc... gcc3
checking how to run the C preprocessor... arm-none-eabi-cpp
checking for arm-none-eabi-gcc... (cached) arm-none-eabi-gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether arm-none-eabi-gcc accepts -g... (cached) yes
checking for arm-none-eabi-gcc option to accept ISO C89... (cached) none needed
checking whether arm-none-eabi-gcc understands -c and -o together... (cached) yes
checking dependency style of arm-none-eabi-gcc... (cached) gcc3
checking whether arm-none-eabi-gcc and cc understand -c and -o together... yes
checking whether we are using the GNU C++ compiler... yes
checking whether arm-none-eabi-g++ accepts -g... yes
checking dependency style of arm-none-eabi-g++... gcc3
checking how to run the C++ preprocessor... arm-none-eabi-g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether arm-none-eabi-g++ accepts -g... (cached) yes
checking dependency style of arm-none-eabi-g++... (cached) gcc3
checking whether arm-none-eabi-g++ understands -c and -o together... yes
checking for arm-none-eabi-ar... arm-none-eabi-ar
checking for arm-none-eabi-ranlib... arm-none-eabi-ranlib
checking for arm-none-eabi-objcopy... arm-none-eabi-objcopy
checking for arm-none-eabi-strip... (cached) arm-none-eabi-strip
checking whether ln -s works... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether arm-none-eabi-gcc is Clang... no
checking whether the C compiler understands -Wall... yes
checking whether the C compiler understands -Wextra... yes
checking whether the C compiler understands -Wshadow... yes
checking whether the C compiler understands -Werror... yes
checking whether the C compiler understands -std=c99... yes
checking whether the C compiler understands -pedantic-errors... yes
checking whether the C++ compiler understands -Wall... yes
checking whether the C++ compiler understands -Wextra... yes
checking whether the C++ compiler understands -Wshadow... yes
checking whether the C++ compiler understands -Werror... yes
checking whether the C++ compiler understands -std=gnu++98... yes
checking whether the C++ compiler understands -Wno-c++14-compat... yes
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by arm-none-eabi-gcc... /Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld
checking if the linker (/Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... arm-none-eabi-nm
checking the name lister (arm-none-eabi-nm) interface... BSD nm
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i386-apple-darwin15.6.0 file names to arm-none-eabi format... func_convert_file_noop
checking how to convert i386-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld option to reload object files... -r
checking for arm-none-eabi-objdump... arm-none-eabi-objdump
checking how to recognize dependent libraries... unknown
checking for arm-none-eabi-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for arm-none-eabi-ar... (cached) arm-none-eabi-ar
checking for archiver @FILE support... @
checking for arm-none-eabi-strip... (cached) arm-none-eabi-strip
checking for arm-none-eabi-ranlib... (cached) arm-none-eabi-ranlib
checking command to parse arm-none-eabi-nm output from arm-none-eabi-gcc object... failed
checking for sysroot... no
checking for arm-none-eabi-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... no
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... no
checking for objdir... .libs
checking if arm-none-eabi-gcc supports -fno-rtti -fno-exceptions... no
checking for arm-none-eabi-gcc option to produce PIC... -fPIC -DPIC
checking if arm-none-eabi-gcc PIC flag -fPIC -DPIC works... yes
checking if arm-none-eabi-gcc static flag -static works... no
checking if arm-none-eabi-gcc supports -c -o file.o... yes
checking if arm-none-eabi-gcc supports -c -o file.o... (cached) yes
checking whether the arm-none-eabi-gcc linker (/Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... no
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... arm-none-eabi-g++ -E
checking for ld used by arm-none-eabi-g++... /Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld
checking if the linker (/Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld) is GNU ld... yes
checking whether the arm-none-eabi-g++ linker (/Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld) supports shared libraries... no
checking for arm-none-eabi-g++ option to produce PIC... -fPIC -DPIC
checking if arm-none-eabi-g++ PIC flag -fPIC -DPIC works... yes
checking if arm-none-eabi-g++ static flag -static works... no
checking if arm-none-eabi-g++ supports -c -o file.o... yes
checking if arm-none-eabi-g++ supports -c -o file.o... (cached) yes
checking whether the arm-none-eabi-g++ linker (/Users/ben/dev/gcc-arm-none-eabi-4_7-2013q3/arm-none-eabi/bin/ld) supports shared libraries... no
checking dynamic linker characteristics... no
checking how to hardcode library paths into programs... immediate
configure: checking whether to build debug instances
checking whether to build debug instances of programs and libraries... no
checking whether to build code-coverage instances of programs and libraries... no
checking for lcov... no
checking for genhtml... no
checking whether to build graphical code coverage reports... no
checking whether to build code-optimized instances of programs and libraries... yes
configure: checking whether to build tests
checking whether to build tests... yes
checking checking for Python and Python libraries used in tests.... ok
yes
no
yes
no
no
no
yes
cc2538
CC2538
checking whether to build tools... yes
checking for doxygen... /Users/ben/Applications/DiaSemi/SmartSnippetsStudio/Tools/doxygen/Doxygen/Contents/Resources/doxygen
checking for dot... no
checking whether to build documentation... yes
configure: checking required package dependencies
checking for stdbool.h that conforms to C99... no
checking for _Bool... yes
checking for ANSI C header files... (cached) yes
checking for stdint.h... (cached) yes
checking for string.h... (cached) yes
checking for int8_t... no
checking for int16_t... no
checking for int32_t... no
checking for int64_t... no
checking for uint8_t... no
checking for uint16_t... no
checking for uint32_t... no
checking for uint64_t... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/cli/Makefile
config.status: creating include/commissioning/Makefile
config.status: creating include/dhcp6/Makefile
config.status: creating include/ncp/Makefile
config.status: creating include/platform/Makefile
config.status: creating src/Makefile
config.status: creating src/cli/Makefile
config.status: creating src/ncp/Makefile
config.status: creating src/core/Makefile
config.status: creating src/diag/Makefile
config.status: creating third_party/Makefile
config.status: creating third_party/mbedtls/Makefile
config.status: creating examples/Makefile
config.status: creating examples/apps/Makefile
config.status: creating examples/apps/cli/Makefile
config.status: creating examples/apps/ncp/Makefile
config.status: creating examples/platforms/Makefile
config.status: creating examples/platforms/cc2538/Makefile
config.status: creating examples/platforms/da15000/Makefile
config.status: creating examples/platforms/posix/Makefile
config.status: creating tools/Makefile
config.status: creating tools/harness-automation/Makefile
config.status: creating tools/harness-thci/Makefile
config.status: creating tools/spi-hdlc-adapter/Makefile
config.status: creating tools/spinel-cli/Makefile
config.status: creating tools/spinel-cli/spinel/Makefile
config.status: creating tests/Makefile
config.status: creating tests/scripts/Makefile
config.status: creating tests/unit/Makefile
config.status: creating doc/Makefile
config.status: creating include/openthread-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure:

  Configuration Summary
  ---------------------
  Package                                   : OPENTHREAD
  Version                                   : g7b376b4-dirty
  Interface                                 : 0.0.5
  Build system                              : i386-apple-darwin15.6.0
  Host system                               : arm-none-eabi
  Target system                             : arm-none-eabi
  Target architecture                       : arm
  Target OS                                 : eabi
  Cross compiling                           : yes
  Build shared libraries                    : no
  Build static libraries                    : yes
  Build debug libraries                     : no
  Build optimized libraries                 : yes
  Build coverage libraries                  : no
  Build coverage reports                    : no
  Lcov                                      : -
  Genhtml                                   : -
  Build tests                               : yes
  Build tools                               : yes
  OpenThread tests                          : all
  Prefix                                    : /
  Documentation support                     : yes
  Doxygen                                   : /Users/ben/Applications/DiaSemi/SmartSnippetsStudio/Tools/doxygen/Doxygen/Contents/Resources/doxygen
  GraphViz dot                              : -
  C Preprocessor                            : arm-none-eabi-cpp
  C Compiler                                : arm-none-eabi-gcc
  C++ Preprocessor                          : arm-none-eabi-g++ -E
  C++ Compiler                              : arm-none-eabi-g++
  Archiver                                  : arm-none-eabi-ar
  Archive Indexer                           : arm-none-eabi-ranlib
  Symbol Stripper                           : arm-none-eabi-strip
  Object Copier                             : arm-none-eabi-objcopy
  C Preprocessor flags                      : -fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb  -I${abs_top_srcdir}/third_party/mbedtls -I${abs_top_srcdir}/third_party/mbedtls/repo/include -I${abs_top_srcdir}/third_party/mbedtls/repo/include/mbedtls -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\" 
  C Compile flags                           : -fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb  -Wall -Wextra -Wshadow -Werror -std=c99 -pedantic-errors
  C++ Compile flags                         : -fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb -fno-exceptions -fno-rtti  -Wall -Wextra -Wshadow -Werror -std=gnu++98 -Wno-c++14-compat
  Link flags                                : -fdata-sections -ffunction-sections -Os -g  -mcpu=cortex-m3 -mfloat-abi=soft -mthumb -nostartfiles -specs=nano.specs -specs=nosys.specs -Wl,--gc-sections -Wl,-Map=map.map  
  Link libraries                            : 
  Pretty                                    : ${abs_top_srcdir}/.astyle/astyle-wrap.sh
  Pretty args                               : astyle --options=${abs_top_builddir}/.astyle/astyle-opts
  Pretty check                              : ${abs_top_srcdir}/.astyle/astyle-wrap.sh
  Pretty check args                         : astyle --options=${abs_top_builddir}/.astyle/astyle-opts --dry-run
  OpenThread CLI support                    : yes
  OpenThread NCP support                    : no
  OpenThread builtin mbedtls support        : yes
  OpenThread Commissioner support           : no
  OpenThread Joiner support                 : no
  OpenThread DTLS support                   : no
  OpenThread Diagnostics support            : yes
  OpenThread Cli logging support            : no
  OpenThread Certification log support      : no
  OpenThread DHCPv6 Server support          : no
  OpenThread DHCPv6 Client support          : no
  OpenThread examples                       : cc2538
  OpenThread platform information           : CC2538


  BUILD    cortex-m3-arm-none-eabi
make -j99 -C build/cortex-m3-arm-none-eabi --no-print-directory all
  CHECK    .local-version
  GEN      .local-version
/Applications/Xcode.app/Contents/Developer/usr/bin/make --no-print-directory all-recursive
Making all in include
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in cli
make[5]: Nothing to be done for `all'.
Making all in commissioning
make[5]: Nothing to be done for `all'.
Making all in dhcp6
make[5]: Nothing to be done for `all'.
Making all in ncp
make[5]: Nothing to be done for `all'.
Making all in platform
make[5]: Nothing to be done for `all'.
make[5]: Nothing to be done for `all-am'.
Making all in src
Making all in core
  CXX      libopenthread_a-openthread.o
  CXX      coap/libopenthread_a-coap_client.o
  CXX      coap/libopenthread_a-coap_server.o
  CXX      coap/libopenthread_a-coap_header.o
  CXX      common/libopenthread_a-crc16.o
  CXX      common/libopenthread_a-logging.o
  CXX      common/libopenthread_a-message.o
  CXX      common/libopenthread_a-tasklet.o
  CXX      common/libopenthread_a-timer.o
  CXX      common/libopenthread_a-trickle_timer.o
  CXX      crypto/libopenthread_a-aes_ccm.o
  CXX      crypto/libopenthread_a-aes_ecb.o
  CXX      crypto/libopenthread_a-hmac_sha256.o
  CXX      crypto/libopenthread_a-openthread-crypto.o
  CXX      crypto/libopenthread_a-mbedtls.o
  CXX      crypto/libopenthread_a-sha256.o
  CXX      mac/libopenthread_a-mac.o
  CXX      mac/libopenthread_a-mac_frame.o
  CXX      mac/libopenthread_a-mac_whitelist.o
  CXX      mac/libopenthread_a-mac_blacklist.o
  CXX      meshcop/libopenthread_a-joiner_router.o
  CXX      meshcop/libopenthread_a-leader.o
  CXX      net/libopenthread_a-icmp6.o
  CXX      net/libopenthread_a-ip6.o
  CXX      net/libopenthread_a-ip6_address.o
  CXX      net/libopenthread_a-ip6_filter.o
  CXX      net/libopenthread_a-ip6_mpl.o
  CXX      net/libopenthread_a-ip6_routes.o
  CXX      net/libopenthread_a-netif.o
  CXX      net/libopenthread_a-udp6.o
  CXX      thread/libopenthread_a-address_resolver.o
  CXX      thread/libopenthread_a-announce_begin_server.o
  CXX      thread/libopenthread_a-energy_scan_server.o
  CXX      thread/libopenthread_a-key_manager.o
  CXX      thread/libopenthread_a-link_quality.o
  CXX      thread/libopenthread_a-lowpan.o
  CXX      thread/libopenthread_a-meshcop_dataset.o
  CXX      thread/libopenthread_a-meshcop_dataset_manager.o
  CXX      thread/libopenthread_a-meshcop_tlvs.o
  CXX      thread/libopenthread_a-mesh_forwarder.o
  CXX      thread/libopenthread_a-mle.o
  CXX      thread/libopenthread_a-mle_router.o
  CXX      thread/libopenthread_a-mle_tlvs.o
  CXX      thread/libopenthread_a-network_data.o
  CXX      thread/libopenthread_a-network_data_local.o
  CXX      thread/libopenthread_a-network_data_leader.o
  CXX      thread/libopenthread_a-panid_query_server.o
  CXX      thread/libopenthread_a-network_diag.o
  CXX      thread/libopenthread_a-network_diag_tlvs.o
  CXX      thread/libopenthread_a-thread_netif.o
  CXX      thread/libopenthread_a-thread_tlvs.o
  CXX      utils/libopenthread_a-slaac_address.o
  AR       libopenthread.a
Making all in cli
  CXX      libopenthread_cli_a-cli_console.o
  CXX      libopenthread_cli_a-cli.o
  CXX      libopenthread_cli_a-cli_dataset.o
  CXX      libopenthread_cli_a-cli_uart.o
  CXX      libopenthread_cli_a-cli_udp.o
/Users/ben/git/openthread/examples/../src/cli/cli_uart.cpp: In member function 'int Thread::Cli::Uart::OutputFormatV(const char*, va_list)':
/Users/ben/git/openthread/examples/../src/cli/cli_uart.cpp:186:5: note: the mangling of 'va_list' has changed in GCC 4.4
  AR       libopenthread-cli.a
Making all in diag
  CXX      libopenthread_diag_a-openthread-diag.o
  CXX      libopenthread_diag_a-diag_process.o
  AR       libopenthread-diag.a
make[4]: Nothing to be done for `all-am'.
Making all in third_party
Making all in mbedtls
  CC       libmbedcrypto_a-hardware_entropy.o
  CC       repo/library/libmbedcrypto_a-aes.o
  CC       repo/library/libmbedcrypto_a-md.o
  CC       repo/library/libmbedcrypto_a-md_wrap.o
  CC       repo/library/libmbedcrypto_a-memory_buffer_alloc.o
  CC       repo/library/libmbedcrypto_a-platform.o
  CC       repo/library/libmbedcrypto_a-sha256.o
  AR       libmbedcrypto.a
make[4]: Nothing to be done for `all-am'.
Making all in examples
Making all in platforms
Making all in cc2538
  CC       libopenthread_cc2538_a-flash.o
  CC       libopenthread_cc2538_a-alarm.o
  CC       libopenthread_cc2538_a-logging.o
  CC       libopenthread_cc2538_a-misc.o
  CC       libopenthread_cc2538_a-platform.o
  CC       libopenthread_cc2538_a-radio.o
  CC       libopenthread_cc2538_a-random.o
  CC       libopenthread_cc2538_a-startup-gcc.o
cp /Users/ben/git/openthread/examples/../examples/platforms/cc2538/../utils/settings.cpp libopenthread_cc2538_settings.cpp
  CC       libopenthread_cc2538_a-uart.o
  CC       libopenthread_cc2538_a-diag.o
  CXX      libopenthread_cc2538_a-libopenthread_cc2538_settings.o
  AR       libopenthread-cc2538.a
make[5]: Nothing to be done for `all-am'.
Making all in apps
Making all in cli
  CC       ot_cli-main.o
  CCLD     ot-cli
arm-none-eabi-gcc: error: nosys.specs: No such file or directory
make[5]: *** [ot-cli] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [do-build-cortex-m3] Error 2

**Comment by jwhui** [comment]
This does not seem to be a problem with the compiler, but a problem with the lib included with the compiler itself.  The distribution of arm-none-eabi-gcc that you are using does not include the nosys .specs file in its lib.

For example, from gcc-arm-none-eabi-4_9-2015q3:

```bash
$ find . -name "*nosys*"
./arm-none-eabi/lib/armv6-m/libnosys.a
./arm-none-eabi/lib/armv6-m/nosys.specs
./arm-none-eabi/lib/armv7-ar/thumb/fpu/libnosys.a
./arm-none-eabi/lib/armv7-ar/thumb/fpu/nosys.specs
./arm-none-eabi/lib/armv7-ar/thumb/libnosys.a
./arm-none-eabi/lib/armv7-ar/thumb/nosys.specs
./arm-none-eabi/lib/armv7-ar/thumb/softfp/libnosys.a
./arm-none-eabi/lib/armv7-ar/thumb/softfp/nosys.specs
./arm-none-eabi/lib/armv7-m/libnosys.a
./arm-none-eabi/lib/armv7-m/nosys.specs
./arm-none-eabi/lib/armv7e-m/fpu/libnosys.a
./arm-none-eabi/lib/armv7e-m/fpu/nosys.specs
./arm-none-eabi/lib/armv7e-m/libnosys.a
./arm-none-eabi/lib/armv7e-m/nosys.specs
./arm-none-eabi/lib/armv7e-m/softfp/libnosys.a
./arm-none-eabi/lib/armv7e-m/softfp/nosys.specs
./arm-none-eabi/lib/cortex-m7/fpu/fpv5-d16/libnosys.a
./arm-none-eabi/lib/cortex-m7/fpu/fpv5-d16/nosys.specs
./arm-none-eabi/lib/cortex-m7/fpu/fpv5-sp-d16/libnosys.a
./arm-none-eabi/lib/cortex-m7/fpu/fpv5-sp-d16/nosys.specs
./arm-none-eabi/lib/cortex-m7/libnosys.a
./arm-none-eabi/lib/cortex-m7/nosys.specs
./arm-none-eabi/lib/cortex-m7/softfp/fpv5-d16/libnosys.a
./arm-none-eabi/lib/cortex-m7/softfp/fpv5-d16/nosys.specs
./arm-none-eabi/lib/cortex-m7/softfp/fpv5-sp-d16/libnosys.a
./arm-none-eabi/lib/cortex-m7/softfp/fpv5-sp-d16/nosys.specs
./arm-none-eabi/lib/fpu/libnosys.a
./arm-none-eabi/lib/fpu/nosys.specs
./arm-none-eabi/lib/libnosys.a
./arm-none-eabi/lib/nosys.specs
./arm-none-eabi/lib/thumb/libnosys.a
./arm-none-eabi/lib/thumb/nosys.specs
```

**Comment by blauret** [comment]
Hi Jonathan,

Thanks for the tip. I'll look closer into my toolchain
