### ISSUE TITLE
HardFault during otInstance initialization

### ISSUE THREAD

**Issue by Cristib05** [openthread/openthread#9841]
**Describe the bug** A clear and concise description of what the bug is.

During the ot instance initialization, if ```OPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE``` flag is enabled, a hard fault occurs when ``` Get<BackboneRouter::Local>().ApplyNewMeshLocalPrefix()``` method is called. 

![image](https://github.com/openthread/openthread/assets/127317648/d2e1c431-ec57-4cf6-b571-36a4bc166bea)
![image](https://github.com/openthread/openthread/assets/127317648/f4123172-abfe-4c50-ab7f-06f00d380dff)

In ```bbr_local.cpp``` file, in method ```void Local::ApplyNewMeshLocalPrefix(void)``` there is a ```VerifyOrExit``` statement called on ```IsEnabled``` which returns the value of ```mState```, private member of ```Local``` class.

In ```Instance::Instance(void)``` constructor, ```mMleRouter(*this)``` is called before ```mBackboneRouterLocal(*this)```. In this case, ```mState``` from ```Local``` class will have a random value, non-deterministic, making that previously mentioned ```VerifyOrExit``` statement to return an incorrect value, most likely, ```mState``` will be different from ```kStateDisabled``` with which is compared, so the execution will be most likely to continue.

As ```mBackboneRouterLocal(*this)``` has not yet been called, ```Get<Mle::MleRouter>()``` will not return what is expected, thus the argument of ```SetMulticastNetworkPrefix``` method will eventually lead to a hardfault in the ```memcpy``` call from ```Ip6::Address::CopyBits()``` method.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id : ffe2f525.
2. IEEE 802.15.4 hardware platform: nxp rw612.
3. Build steps : build with ```OPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE``` flag enabled.
4. Network topology: no network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

**Comment by abtink** [comment]
@Cristib05 Thanks for finding and debugging this. Submitted https://github.com/openthread/openthread/pull/9843 which should help address this

I think zero-initialization of `gInstanceRaw` may (indirectly) help avoid this situation (when `Instance::InitSingle()` is used) by having `BackboneRouter::Local::mState` be zero by default. Though zero-init may be disabled in a project (or toolchain).
