### ISSUE TITLE
Segmentation fault occurs in CLI - CoAP Example when using block-wise.

### ISSUE THREAD

**Issue by eeumay** [openthread/openthread#9884]
**Describe the bug** A clear and concise description of what the bug is.
Segmentation fault occurs when using [CLI Example](https://github.com/openthread/openthread/tree/37fef5ed547421e627b69193798d2556b3cebe19/examples/apps/cli). I followed the [readme](https://github.com/openthread/openthread/blob/37fef5ed547421e627b69193798d2556b3cebe19/examples/apps/cli/README.md) to build and execute the axample and everything was well. And then I continued to run coap following another [readme](https://github.com/openthread/openthread/blob/37fef5ed547421e627b69193798d2556b3cebe19/src/cli/README_COAP.md). Coap worked well untill get with "block-" crashed the program.
Crash log is in the end of **Console/log output**.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id
8bc25042ba5cde20605eec2a329c0dff575303f4 (thread-reference-20230706)
2. IEEE 802.15.4 hardware platform
simulation 
OS: Linux version 5.15.0-92-generic (buildd@lcy02-amd64-005) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024.
3. Build steps
[readme](https://github.com/openthread/openthread/blob/37fef5ed547421e627b69193798d2556b3cebe19/examples/apps/cli/README.md)
4. Network topology
2 devices build as FTD. One is leader and another is child.
 [CLI Example](https://github.com/openthread/openthread/tree/37fef5ed547421e627b69193798d2556b3cebe19/examples/apps/cli)

**Expected behavior** A clear and concise description of what you expected to happen.
Execute coap get with "block-" correctly or report a error.

**Console/log output** If applicable, add console/log output to help explain your problem.
Build:
ubuntu@xxxxx:~/workspace/openSource/openthread$ git status
HEAD detached at thread-reference-20230706
nothing to commit, working tree clean
ubuntu@xxxxx:~/workspace/openSource/openthread$ ./script/cmake-build simulation
+ OT_CMAKE_NINJA_TARGET=
+++ dirname ./script/cmake-build
++ cd ./script/..
++ pwd
+ OT_SRCDIR=/home/ubuntu/workspace/openSource/openthread
+ readonly OT_SRCDIR
+ OT_PLATFORMS=(simulation posix android-ndk)
+ readonly OT_PLATFORMS
+ OT_POSIX_SIM_COMMON_OPTIONS=("-DOT_ANYCAST_LOCATOR=ON" "-DOT_BORDER_AGENT=ON" "-DOT_BORDER_AGENT_ID=ON" "-DOT_BORDER_ROUTER=ON" "-DOT_CHANNEL_MANAGER=ON" "-DOT_CHANNEL_MONITOR=ON" "-DOT_COAP=ON" "-DOT_COAPS=ON" "-DOT_COAP_BLOCK=ON" "-DOT_COAP_OBSERVE=ON" "-DOT_COMMISSIONER=ON" "-DOT_COMPILE_WARNING_AS_ERROR=ON" "-DOT_COVERAGE=ON" "-DOT_DATASET_UPDATER=ON" "-DOT_DHCP6_CLIENT=ON" "-DOT_DHCP6_SERVER=ON" "-DOT_DIAGNOSTIC=ON" "-DOT_DNSSD_SERVER=ON" "-DOT_DNS_CLIENT=ON" "-DOT_ECDSA=ON" "-DOT_HISTORY_TRACKER=ON" "-DOT_IP6_FRAGM=ON" "-DOT_JAM_DETECTION=ON" "-DOT_JOINER=ON" "-DOT_LOG_LEVEL_DYNAMIC=ON" "-DOT_MAC_FILTER=ON" "-DOT_NEIGHBOR_DISCOVERY_AGENT=ON" "-DOT_NETDATA_PUBLISHER=ON" "-DOT_NETDIAG_CLIENT=ON" "-DOT_PING_SENDER=ON" "-DOT_RCP_RESTORATION_MAX_COUNT=2" "-DOT_REFERENCE_DEVICE=ON" "-DOT_SERVICE=ON" "-DOT_SNTP_CLIENT=ON" "-DOT_SRP_CLIENT=ON" "-DOT_SRP_SERVER=ON" "-DOT_UPTIME=ON")
+ readonly OT_POSIX_SIM_COMMON_OPTIONS
+ main simulation
+ [[ 1 == 0 ]]
+ local platform=simulation
+ echo simulation posix android-ndk
+ grep -wq simulation
+ shift
+ local_options=()
+ local local_options
+ options=('-DOT_SLAAC=ON')
+ local options
+ case "${platform}" in
+ local_options+=("-DOT_LINK_RAW=ON" "-DOT_DNS_DSO=ON" "-DOT_DNS_CLIENT_OVER_TCP=ON" "-DOT_UDP_FORWARD=ON")
+ options+=("${OT_POSIX_SIM_COMMON_OPTIONS[@]}" "${local_options[@]}")
+ options+=("-DOT_PLATFORM=${platform}")
+ options+=("$@")
+ build simulation -DOT_SLAAC=ON -DOT_ANYCAST_LOCATOR=ON -DOT_BORDER_AGENT=ON -DOT_BORDER_AGENT_ID=ON -DOT_BORDER_ROUTER=ON -DOT_CHANNEL_MANAGER=ON -DOT_CHANNEL_MONITOR=ON -DOT_COAP=ON -DOT_COAPS=ON -DOT_COAP_BLOCK=ON -DOT_COAP_OBSERVE=ON -DOT_COMMISSIONER=ON -DOT_COMPILE_WARNING_AS_ERROR=ON -DOT_COVERAGE=ON -DOT_DATASET_UPDATER=ON -DOT_DHCP6_CLIENT=ON -DOT_DHCP6_SERVER=ON -DOT_DIAGNOSTIC=ON -DOT_DNSSD_SERVER=ON -DOT_DNS_CLIENT=ON -DOT_ECDSA=ON -DOT_HISTORY_TRACKER=ON -DOT_IP6_FRAGM=ON -DOT_JAM_DETECTION=ON -DOT_JOINER=ON -DOT_LOG_LEVEL_DYNAMIC=ON -DOT_MAC_FILTER=ON -DOT_NEIGHBOR_DISCOVERY_AGENT=ON -DOT_NETDATA_PUBLISHER=ON -DOT_NETDIAG_CLIENT=ON -DOT_PING_SENDER=ON -DOT_RCP_RESTORATION_MAX_COUNT=2 -DOT_REFERENCE_DEVICE=ON -DOT_SERVICE=ON -DOT_SNTP_CLIENT=ON -DOT_SRP_CLIENT=ON -DOT_SRP_SERVER=ON -DOT_UPTIME=ON -DOT_LINK_RAW=ON -DOT_DNS_DSO=ON -DOT_DNS_CLIENT_OVER_TCP=ON -DOT_UDP_FORWARD=ON -DOT_PLATFORM=simulation
+ local platform=simulation
+ local builddir=build/simulation
+ shift
+ mkdir -p build/simulation
+ cd build/simulation
+ cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DOT_COMPILE_WARNING_AS_ERROR=ON -DOT_SLAAC=ON -DOT_ANYCAST_LOCATOR=ON -DOT_BORDER_AGENT=ON -DOT_BORDER_AGENT_ID=ON -DOT_BORDER_ROUTER=ON -DOT_CHANNEL_MANAGER=ON -DOT_CHANNEL_MONITOR=ON -DOT_COAP=ON -DOT_COAPS=ON -DOT_COAP_BLOCK=ON -DOT_COAP_OBSERVE=ON -DOT_COMMISSIONER=ON -DOT_COMPILE_WARNING_AS_ERROR=ON -DOT_COVERAGE=ON -DOT_DATASET_UPDATER=ON -DOT_DHCP6_CLIENT=ON -DOT_DHCP6_SERVER=ON -DOT_DIAGNOSTIC=ON -DOT_DNSSD_SERVER=ON -DOT_DNS_CLIENT=ON -DOT_ECDSA=ON -DOT_HISTORY_TRACKER=ON -DOT_IP6_FRAGM=ON -DOT_JAM_DETECTION=ON -DOT_JOINER=ON -DOT_LOG_LEVEL_DYNAMIC=ON -DOT_MAC_FILTER=ON -DOT_NEIGHBOR_DISCOVERY_AGENT=ON -DOT_NETDATA_PUBLISHER=ON -DOT_NETDIAG_CLIENT=ON -DOT_PING_SENDER=ON -DOT_RCP_RESTORATION_MAX_COUNT=2 -DOT_REFERENCE_DEVICE=ON -DOT_SERVICE=ON -DOT_SNTP_CLIENT=ON -DOT_SRP_CLIENT=ON -DOT_SRP_SERVER=ON -DOT_UPTIME=ON -DOT_LINK_RAW=ON -DOT_DNS_DSO=ON -DOT_DNS_CLIENT_OVER_TCP=ON -DOT_UDP_FORWARD=ON -DOT_PLATFORM=simulation /home/ubuntu/workspace/openSource/openthread
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenThread Source Directory: /home/ubuntu/workspace/openSource/openthread
-- OT_APP_CLI=ON
-- OT_APP_NCP=ON
-- OT_APP_RCP=ON
-- OT_FTD=ON
-- OT_MTD=ON
-- OT_RCP=ON
-- OT_THREAD_VERSION=
-- OT_15_4=""
-- OT_ANDROID_NDK=""
-- OT_ANYCAST_LOCATOR=ON --> OPENTHREAD_CONFIG_TMF_ANYCAST_LOCATOR_ENABLE=1
-- OT_ASSERT=""
-- OT_BACKBONE_ROUTER=""
-- OT_BACKBONE_ROUTER_DUA_NDPROXYING=""
-- OT_BACKBONE_ROUTER_MULTICAST_ROUTING=""
-- OT_BORDER_AGENT=ON --> OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE=1
-- OT_BORDER_AGENT_ID=ON --> OPENTHREAD_CONFIG_BORDER_AGENT_ID_ENABLE=1
-- OT_BORDER_ROUTER=ON --> OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE=1
-- OT_BORDER_ROUTING=""
-- OT_BORDER_ROUTING_DHCP6_PD=""
-- OT_BORDER_ROUTING_COUNTERS=""
-- OT_CHANNEL_MANAGER=ON --> OPENTHREAD_CONFIG_CHANNEL_MANAGER_ENABLE=1
-- OT_CHANNEL_MONITOR=ON --> OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE=1
-- OT_COAP=ON --> OPENTHREAD_CONFIG_COAP_API_ENABLE=1
-- OT_COAP_BLOCK=ON --> OPENTHREAD_CONFIG_COAP_BLOCKWISE_TRANSFER_ENABLE=1
-- OT_COAP_OBSERVE=ON --> OPENTHREAD_CONFIG_COAP_OBSERVE_API_ENABLE=1
-- OT_COAPS=ON --> OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE=1
-- OT_COMMISSIONER=ON --> OPENTHREAD_CONFIG_COMMISSIONER_ENABLE=1
-- OT_CSL_AUTO_SYNC=""
-- OT_CSL_DEBUG=""
-- OT_CSL_RECEIVER=""
-- OT_DATASET_UPDATER=ON --> OPENTHREAD_CONFIG_DATASET_UPDATER_ENABLE=1
-- OT_DHCP6_CLIENT=ON --> OPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE=1
-- OT_DHCP6_SERVER=ON --> OPENTHREAD_CONFIG_DHCP6_SERVER_ENABLE=1
-- OT_DIAGNOSTIC=ON --> OPENTHREAD_CONFIG_DIAG_ENABLE=1
-- OT_DNS_CLIENT=ON --> OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE=1
-- OT_DNS_CLIENT_OVER_TCP=ON --> OPENTHREAD_CONFIG_DNS_CLIENT_OVER_TCP_ENABLE=1
-- OT_DNS_DSO=ON --> OPENTHREAD_CONFIG_DNS_DSO_ENABLE=1
-- OT_DNS_UPSTREAM_QUERY=""
-- OT_DNSSD_SERVER=ON --> OPENTHREAD_CONFIG_DNSSD_SERVER_ENABLE=1
-- OT_DUA=""
-- OT_ECDSA=ON --> OPENTHREAD_CONFIG_ECDSA_ENABLE=1
-- OT_EXTERNAL_HEAP=""
-- OT_FIREWALL=""
-- OT_HISTORY_TRACKER=ON --> OPENTHREAD_CONFIG_HISTORY_TRACKER_ENABLE=1
-- OT_IP6_FRAGM=ON --> OPENTHREAD_CONFIG_IP6_FRAGMENTATION_ENABLE=1
-- OT_JAM_DETECTION=ON --> OPENTHREAD_CONFIG_JAM_DETECTION_ENABLE=1
-- OT_JOINER=ON --> OPENTHREAD_CONFIG_JOINER_ENABLE=1
-- OT_LINK_METRICS_INITIATOR=""
-- OT_LINK_METRICS_SUBJECT=""
-- OT_LINK_RAW=ON --> OPENTHREAD_CONFIG_LINK_RAW_ENABLE=1
-- OT_LOG_LEVEL_DYNAMIC=ON --> OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE=1
-- OT_MAC_FILTER=ON --> OPENTHREAD_CONFIG_MAC_FILTER_ENABLE=1
-- OT_MESH_DIAG=""
-- OT_MESSAGE_USE_HEAP=""
-- OT_MLE_LONG_ROUTES=""
-- OT_MLR=""
-- OT_MULTIPLE_INSTANCE=""
-- OT_NAT64_BORDER_ROUTING=""
-- OT_NAT64_TRANSLATOR=""
-- OT_NEIGHBOR_DISCOVERY_AGENT=ON --> OPENTHREAD_CONFIG_NEIGHBOR_DISCOVERY_AGENT_ENABLE=1
-- OT_NETDATA_PUBLISHER=ON --> OPENTHREAD_CONFIG_NETDATA_PUBLISHER_ENABLE=1
-- OT_NETDIAG_CLIENT=ON --> OPENTHREAD_CONFIG_TMF_NETDIAG_CLIENT_ENABLE=1
-- OT_OPERATIONAL_DATASET_AUTO_INIT=""
-- OT_OTNS=""
-- OT_PING_SENDER=ON --> OPENTHREAD_CONFIG_PING_SENDER_ENABLE=1
-- OT_PLATFORM_NETIF=""
-- OT_PLATFORM_UDP=""
-- OT_REFERENCE_DEVICE=ON --> OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE=1
-- OT_SERVICE=ON --> OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE=1
-- OT_SETTINGS_RAM=""
-- OT_SLAAC=ON --> OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1
-- OT_SNTP_CLIENT=ON --> OPENTHREAD_CONFIG_SNTP_CLIENT_ENABLE=1
-- OT_SRP_CLIENT=ON --> OPENTHREAD_CONFIG_SRP_CLIENT_ENABLE=1
-- OT_SRP_SERVER=ON --> OPENTHREAD_CONFIG_SRP_SERVER_ENABLE=1
-- OT_TCP=""
-- OT_TIME_SYNC=""
-- OT_TREL=""
-- OT_TX_BEACON_PAYLOAD=""
-- OT_UDP_FORWARD=ON --> OPENTHREAD_CONFIG_UDP_FORWARD_ENABLE=1
-- OT_UPTIME=ON --> OPENTHREAD_CONFIG_UPTIME_ENABLE=1
-- OT_VENDOR_NAME=""
-- OT_VENDOR_MODEL=""
-- OT_VENDOR_SW_VERSION=""
-- OT_POWER_SUPPLY=""
-- OT_RCP_RESTORATION_MAX_COUNT=2
-- OpenThread CMake build type: Debug
-- Package Name: OPENTHREAD
-- Setting default package version: thread-reference-20230706
-- Package Version: thread-reference-20230706
-- Thread Version: 1.3 (OPENTHREAD_CONFIG_THREAD_VERSION=OT_THREAD_VERSION_1_3)
-- Log output: APP
-- OpenThread Config File: "openthread-core-simulation-config.h"
CMake Warning (dev) at third_party/mbedtls/repo/CMakeLists.txt:39 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS
-- Performing Test C_COMPILER_SUPPORTS_WFORMAT_SIGNEDNESS - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/workspace/openSource/openthread/build/simulation
+ [[ -z '' ]]
+ ninja
[59/867] cd /home/ubuntu/workspace/openSource/openthread/build/simulation...=1" -P /home/ubuntu/workspace/openSource/openthread/etc/cmake/print.cmake
OPENTHREAD_CONFIG_TMF_ANYCAST_LOCATOR_ENABLE=1
OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE=1
OPENTHREAD_CONFIG_BORDER_AGENT_ID_ENABLE=1
OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE=1
OPENTHREAD_CONFIG_CHANNEL_MANAGER_ENABLE=1
OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE=1
OPENTHREAD_CONFIG_COAP_API_ENABLE=1
OPENTHREAD_CONFIG_COAP_BLOCKWISE_TRANSFER_ENABLE=1
OPENTHREAD_CONFIG_COAP_OBSERVE_API_ENABLE=1
OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE=1
OPENTHREAD_CONFIG_COMMISSIONER_ENABLE=1
OPENTHREAD_CONFIG_DATASET_UPDATER_ENABLE=1
OPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE=1
OPENTHREAD_CONFIG_DHCP6_SERVER_ENABLE=1
OPENTHREAD_CONFIG_DIAG_ENABLE=1
OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE=1
OPENTHREAD_CONFIG_DNS_CLIENT_OVER_TCP_ENABLE=1
OPENTHREAD_CONFIG_DNS_DSO_ENABLE=1
OPENTHREAD_CONFIG_DNSSD_SERVER_ENABLE=1
OPENTHREAD_CONFIG_ECDSA_ENABLE=1
OPENTHREAD_CONFIG_HISTORY_TRACKER_ENABLE=1
OPENTHREAD_CONFIG_IP6_FRAGMENTATION_ENABLE=1
OPENTHREAD_CONFIG_JAM_DETECTION_ENABLE=1
OPENTHREAD_CONFIG_JOINER_ENABLE=1
OPENTHREAD_CONFIG_LINK_RAW_ENABLE=1
OPENTHREAD_CONFIG_LOG_LEVEL_DYNAMIC_ENABLE=1
OPENTHREAD_CONFIG_MAC_FILTER_ENABLE=1
OPENTHREAD_CONFIG_NEIGHBOR_DISCOVERY_AGENT_ENABLE=1
OPENTHREAD_CONFIG_NETDATA_PUBLISHER_ENABLE=1
OPENTHREAD_CONFIG_TMF_NETDIAG_CLIENT_ENABLE=1
OPENTHREAD_CONFIG_PING_SENDER_ENABLE=1
OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE=1
OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE=1
OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE=1
OPENTHREAD_CONFIG_SNTP_CLIENT_ENABLE=1
OPENTHREAD_CONFIG_SRP_CLIENT_ENABLE=1
OPENTHREAD_CONFIG_SRP_SERVER_ENABLE=1
OPENTHREAD_CONFIG_UDP_FORWARD_ENABLE=1
OPENTHREAD_CONFIG_UPTIME_ENABLE=1
OPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT=2
OPENTHREAD_CONFIG_ENABLE_BUILTIN_MBEDTLS=1
OPENTHREAD_CONFIG_ENABLE_BUILTIN_MBEDTLS_MANAGEMENT=1
OPENTHREAD_ENABLE_COVERAGE=1
PACKAGE_NAME=OPENTHREAD
OPENTHREAD_CONFIG_THREAD_VERSION=OT_THREAD_VERSION_1_3
OPENTHREAD_CONFIG_LOG_OUTPUT=OPENTHREAD_CONFIG_LOG_OUTPUT_APP
OPENTHREAD_CONFIG_FILE=openthread-core-simulation-config.h
_BSD_SOURCE=1
_DEFAULT_SOURCE=1
OPENTHREAD_EXAMPLES_SIMULATION=1
OPENTHREAD_CONFIG_NCP_HDLC_ENABLE=1
OPENTHREAD_CONFIG_NCP_HDLC_ENABLE=1
[867/867] Linking CXX executable tests/unit/ot-test-spinel-buffer
+ cd /home/ubuntu/workspace/openSource/openthread

FTD1:
ubuntu@xxxxx:~/workspace/openSource/openthread/build/simulation/examples/apps/cli$ ./ot-cli-ftd 1
> dataset init new
Done
> dataset
Active Timestamp: 1
Channel: 25
Channel Mask: 0x07fff800
Ext PAN ID: 099d2351a13f458f
Mesh Local Prefix: fd2e:cd75:5b68:ea59::/64
Network Key: 8c21b47de6b1859e8ea4e5cba3172c74
Network Name: OpenThread-96bb
PAN ID: 0x96bb
PSKc: 2c4af64133f7dfa92521e4806922a650
Security Policy: 672 onrc 0
Done
> dataset commit active
Done
> ifconfig up
Done
> thread start
Done
> state
leader
Done
> ipaddr
fd2e:cd75:5b68:ea59:0:ff:fe00:fc00
fd2e:cd75:5b68:ea59:0:ff:fe00:3400
fd2e:cd75:5b68:ea59:b1d3:90e6:c853:a687
fe80:0:0:0:10bf:768e:ecd2:607e
Done
> coap start
Done
> coap resource test-resource
Done
> coap request from fd2e:cd75:5b68:ea59:167d:bac1:fdc7:77b9 GET
coap response sent

> coap request from fd2e:cd75:5b68:ea59:167d:bac1:fdc7:77b9 GET
send block: Num 0 Len 1024
aa13d8f2387312026b497922e4e25257
227e3b1c6905988151e3171c171f689e
2c9db52dbbdecc7072544191b5ae8d36
68a0a57e2bf3827d7ee5481e16e778bc
f3a712124b0f4804b6f702f3f8af991a
f1b16f4a68e57fb1ca6800fa59f2f5dd
12564514a0171cd3881488387883f141
831034521351dc54b15ebefd8d3615a6
6765510adf361f1e4e653d4edffb5b81
8b1d4ec2e3178791a6adb837f49bd496
75a535a55dfd0a3a8da4de12c1dfa619
2a139c66c1755231a3f7e9134b4de114
3f730f560a17a40a6980515b5a4b0324
fa106a1abdc931cd4e0b07be569fd831
b20526066f69a3fd0fc8633ab651fadc
b9fbe85ed4471a98eb8929f00ef0657c
4c405bbf776ead7e30512f5b2337d463
d24a063faec30a0e828082958e962b0e
760089378ae4e024115ae1cb1f8ffdaa
4948fa22963b83ce68a3cba011fb2fe5
0878510a759aef623c35fb346e3be75a
20f5445a18ed8039b57ac28c013a9f59
d418001f13fe7ac9771e13faac04acea
d66ae237ec132f898f09cd3a63432d37
e7e34ed2bea49fbac2a795fa4a1c3821
f078cd97e6f5ad066fc1c5aa1c2de186
3544a53791765c764451e7bddc0cb57b
158f89dc204479d91dfdd9d89e15d9ac
63bdd5dee71d13797470a3a5107a40ba
29eda9bc6f73554ce60e57dd6a36e42f
4c6ab47a1402a83377b6173d6b487674
a7987e333df9e7722c6388c51cb24224
4a1c709c24d6d0a669f91cd152e919e4
a1c53a2f51e0f0422b9d5e2506fbc15c
dfcdc0062dccb3c1658791d72e7b4e3a
682d20f9252d2b97c41f567eba27a2b0
8c4e05bd85aebad39e9f7ee911d5a4b9
f977b894abbc51b4fb2b40ebbea4fd8c
85a27ed979449641df72115c63d6d6e3
0b29fa1c1e1a8a8c9be5f7a5fedc2ac3
ce250a2631871a983c97700aa8a2ea90
ab758c82db876ffac1bd0355ddb08722
e98daf45edb58467748dcdea69d557fc
22ca22842a92c388b70c154ee946a868
71fcff87619e59eacd9db58579a3e046
bc590e540a889eebdc0792c78ed3caf5
8b1cd80666dceaf1431766a661fa52c4
2aac0808dd2c9a7d6361bdb93ad695fb
69a32146fedc42d1953cf20dc0fed836
95899d43d5ec7ec26a59f4365c8f0748
884a17466e0df73e1ba901342702e278
899b261524e9346b9242b6134a98dd75
8512b1464248f3045374e893f4e7eed3
10c17e63c710e8fabb452402e17192da
2c7bae2279567ef5ee5e6190eb520879
ffe28c2a5e959f83e1b99597b427cfd3
29e9b93f47e1074e2dacc8a5b5587838
1f9d6577ff55d1fae91227ea1e608feb
0c26057477bbb9b95efaf0954c1ea145
ce940a3af2e90e4de9a06cc05a24d89b
812f9a207026d8ffdcdf4921783d4cf6
dbe3331c38b81957c80edb87cbe3b8af
76aa721cec60fca266eb1b63766bf8a7
65431152a84001fa64c5a87967742e47
coap response sent

FTD2:
ubuntu@xxxxx:~/workspace/openSource/openthread/build/simulation/examples/apps/cli$ ./ot-cli-ftd 2
> dataset networkkey 8c21b47de6b1859e8ea4e5cba3172c74
Done
> dataset commit active
Done
> ifconfig up
Done
> thread start
Done
> state
child
Done
> ping fd2e:cd75:5b68:ea59:b1d3:90e6:c853:a687
16 bytes from fd2e:cd75:5b68:ea59:b1d3:90e6:c853:a687: icmp_seq=1 hlim=64 time=3ms
1 packets transmitted, 1 packets received. Packet loss = 0.0%. Round-trip min/avg/max = 3/3.0/3 ms.
Done
> coap start
Done
> coap get fd2e:cd75:5b68:ea59:b1d3:90e6:c853:a687 test-resource
Done
> coap response from fd2e:cd75:5b68:ea59:b1d3:90e6:c853:a687 with payload: 30

> coap put fd2e:cd75:5b68:ea59:b1d3:90e6:c853:a687 con payload
Done
> coap get fd2e:cd75:5b68:ea59:b1d3:90e6:c853:a687 test-resource block-1024
Done
> received block: Num 0 Len 1024
aa13d8f2387312026b497922e4e25257
227e3b1c6905988151e3171c171f689e
2c9db52dbbdecc7072544191b5ae8d36
68a0a57e2bf3827d7ee5481e16e778bc
f3a712124b0f4804b6f702f3f8af991a
f1b16f4a68e57fb1ca6800fa59f2f5dd
12564514a0171cd3881488387883f141
831034521351dc54b15ebefd8d3615a6
6765510adf361f1e4e653d4edffb5b81
8b1d4ec2e3178791a6adb837f49bd496
75a535a55dfd0a3a8da4de12c1dfa619
2a139c66c1755231a3f7e9134b4de114
3f730f560a17a40a6980515b5a4b0324
fa106a1abdc931cd4e0b07be569fd831
b20526066f69a3fd0fc8633ab651fadc
b9fbe85ed4471a98eb8929f00ef0657c
4c405bbf776ead7e30512f5b2337d463
d24a063faec30a0e828082958e962b0e
760089378ae4e024115ae1cb1f8ffdaa
4948fa22963b83ce68a3cba011fb2fe5
0878510a759aef623c35fb346e3be75a
20f5445a18ed8039b57ac28c013a9f59
d418001f13fe7ac9771e13faac04acea
d66ae237ec132f898f09cd3a63432d37
e7e34ed2bea49fbac2a795fa4a1c3821
f078cd97e6f5ad066fc1c5aa1c2de186
3544a53791765c764451e7bddc0cb57b
158f89dc204479d91dfdd9d89e15d9ac
63bdd5dee71d13797470a3a5107a40ba
29eda9bc6f73554ce60e57dd6a36e42f
4c6ab47a1402a83377b6173d6b487674
a7987e333df9e7722c6388c51cb24224
4a1c709c24d6d0a669f91cd152e919e4
a1c53a2f51e0f0422b9d5e2506fbc15c
dfcdc0062dccb3c1658791d72e7b4e3a
682d20f9252d2b97c41f567eba27a2b0
8c4e05bd85aebad39e9f7ee911d5a4b9
f977b894abbc51b4fb2b40ebbea4fd8c
85a27ed979449641df72115c63d6d6e3
0b29fa1c1e1a8a8c9be5f7a5fedc2ac3
ce250a2631871a983c97700aa8a2ea90
ab758c82db876ffac1bd0355ddb08722
e98daf45edb58467748dcdea69d557fc
22ca22842a92c388b70c154ee946a868
71fcff87619e59eacd9db58579a3e046
bc590e540a889eebdc0792c78ed3caf5
8b1cd80666dceaf1431766a661fa52c4
2aac0808dd2c9a7d6361bdb93ad695fb
69a32146fedc42d1953cf20dc0fed836
95899d43d5ec7ec26a59f4365c8f0748
884a17466e0df73e1ba901342702e278
899b261524e9346b9242b6134a98dd75
8512b1464248f3045374e893f4e7eed3
10c17e63c710e8fabb452402e17192da
2c7bae2279567ef5ee5e6190eb520879
ffe28c2a5e959f83e1b99597b427cfd3
29e9b93f47e1074e2dacc8a5b5587838
1f9d6577ff55d1fae91227ea1e608feb
0c26057477bbb9b95efaf0954c1ea145
ce940aSegmentation fault (core dumped)

**Additional context** Add any other context about the problem here.
I'm having trouble using coap block-wise in [gecko_sdk](https://github.com/SiliconLabs/gecko_sdk) with Silicon Labs EFR32 boards. And I tried the Example ot-cli-ftd in Simplicity Studio v5 and found block-wise work not correctly and break down before some intermediate request. Next, I tried simulate cli example. Finally, I found this.

**Comment by eeumay** [comment]
I may have fixed this issue.
Here is diff:
```
ubuntu@xxxxx:~/workspace/openSource/openthread$ git diff
diff --git a/src/core/coap/coap.cpp b/src/core/coap/coap.cpp
index 696d0fc83..64e148792 100644
--- a/src/core/coap/coap.cpp
+++ b/src/core/coap/coap.cpp
@@ -655,7 +655,7 @@ Error CoapBase::PrepareNextBlockRequest(Message::BlockType aType,
         }
 
         // Copy option
-        SuccessOrExit(error = iterator.ReadOptionValue(&optionBuf));
+        SuccessOrExit(error = iterator.ReadOptionValue(optionBuf));
         SuccessOrExit(error = aRequest.AppendOption(optionNumber, iterator.GetOption()->GetLength(), &optionBuf));
     }
```
ReadOptionValue accepts a void* or &uint64_t type，and optionBuf is a uint64_t type. Obviously, this is a typo.

**Comment by jwhui** [comment]
@eeumay , thanks for raising this issue and working to resolve it. Would you like to submit a PR with the fix?

**Comment by eeumay** [comment]
> @eeumay , thanks for raising this issue and working to resolve it. Would you like to submit a PR with the fix?

I'm on it. I will submit a PR and I'm waiting for GitHub Actions. But for copying option correctly, optionBuf should be uint8_t array. I'm not sure how to define a fixed langth adapting to an uncertain length due to the theoretical max is too big, and I decide to use the max length of the uri path which is necessary. Do you have any advice?

**Comment by jwhui** [comment]
> I'm on it. I will submit a PR and I'm waiting for GitHub Actions. But for copying option correctly, optionBuf should be uint8_t array. I'm not sure how to define a fixed langth adapting to an uncertain length due to the theoretical max is too big, and I decide to use the max length of the uri path which is necessary. Do you have any advice?

@eeumay , good observation. I believe the length issue was present in the original contribution:
- #4247 

@abtink , who last updated the `ReadOptionValue()` method, any thoughts on how to address?

**Comment by abtink** [comment]
Using a fixed (max size) array can work but would be limited.

A more flexible (but more complex) approach can be to add a new `AppendOption()` flavor that directly copies the option value from a passed `Option::Iterator`. It can then copy the bytes from one message to another using `AppendBytesFromMessage()`, eliminating the need for an intermediate buffer.

**Comment by eeumay** [comment]
@jwhui @abtink  Thanks for your advice. 
I submit a PR to fix copying option.[#9894](https://github.com/openthread/openthread/pull/9894)
But it still failed that Coap parsed the previous old request (in `CoapBase::PrepareNextBlockRequest()`), because `CoapBase::FindRelatedRequest()` did return a Message appending metaData, which cannot be directly iterated. In this case, `Option::Iterator::Read()` would reach metaData and probably return `kErrorParse`. 
I will open another issue to talk about it.
